### ISSUE TITLE
Support custom DKIM selector

### ISSUE THREAD

**Issue by erik-wramner** [docker-mailserver/docker-mailserver#1304]
The current version of docker-mailserver always uses the value "mail" as DKIM selector. That works and (despite some confusion) is independent of host name. However, at least two users would like to make the DKIM selector configurable.

To do that:
- Add a DKIM_SELECTOR option with mail as the default value
- Modify the setup script to use the selector
- Modify the startup script to patch the configuration to use the selector
- Update the instructions
- Write some kind of test that proves it works

**Comment by bastard640** [comment]
Привяу.

Английский у меня не на высоте и мне лень писать перевод, но у меня есть решение для кастомного dkim. Если кому-то будет не впадлу, переведите его)

Для начала, нам нужно получить доступ к сгенерированным DKIM ключам внутри контейнера, можете пробросить их через volumes, можете хоть зайти внутрь контейнера, не имеет значения.

Далее, находим в директории _/etc/opendkim/KeyTable_ и открываем его на редактирование.

В нем мы имеем примерно следующее:

**mail._domainkey.example.com example.com:mail:/etc/opendkim/keys/example.com/mail.private**

Разобьем запись по ":"

1. mail._domainkey.example.com example.com тоже разбиваем по пробелу
    -  mail._domainkey.example.com - имя ключа, которое у нас задано в файле в той же директории SigningTable

    - example.com - имя хоста

2. **mail** - сам селектор, который будет вставлен в заголовке письма

3. /etc/opendkim/keys/example.com/mail.private - путь до приватного ключика, которым мы подписываем письма

Собственно, чтобы поменять селектор с mail вы просто меняете его в файле KeyTable, отмечен он П.2, сохраняете, перезагружаете контейнер и все у вас работает.

**Comment by erik-wramner** [comment]
Please use English here. It is not my native language either, but it tends to work best.

**Comment by bastard640** [comment]
Hi
 
Sory, i wrote it for russian language speakers and asked them to translate it)

Briefly, it says there, to replace the selector in the current image, you just need to fix  /etc/opendkim/KeyTable
 
mail._domainkey.example.com example.com: mail :/etc/opendkim/keys/example.com/mail.private
 
Bold it is selector.
 
This is information so useful for developers who want use a custom DKIM selector
  
>Суббота, 20 июня 2020, 20:39 +03:00 от Erik Wramner <notifications@github.com>:
> 
> 
>Please use English here. It is not my native language either, but it tends to work best.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Задрот Lineage

**Comment by aendeavor** [comment]
What's the status here?

**Comment by wernerfred** [comment]
Just out of curiosity: what is your reason for switching the selector?
Don't get me wrong - I'm not against it - I just want to understand the motivation behind it.

**Comment by BaileyJM02** [comment]
For me, it would allow me to correctly set a TXT record of `default._domainkey` instead of `mail._domainkey` when using the domain `domain.tld` instead of `mail.domain.tld`. There seems to be a check within the DKIM records, that I don't fully understand, that actually checks against the value of the selector and fails if I place it at `default._domainkey` instead of `mail._domainkey`.

**Comment by shodanx2** [comment]
@wernerfred 
Please explain how this issue is completed ?

I checked the documentation 
https://docker-mailserver.github.io/docker-mailserver/edge/config/best-practices/dkim/
And only mail. selector is mentionned

I am here because I changed my server setup from 
hostname=mail
domain=example.com

to, as the docker-compose.yml comment claim is the appropriate way 

hostname=example.com
#domain=

However, it seems .mail is still the selector and I am also getting a looping dkim error in the logs
Not sure if this is the cause of my error, but there is ambiguity in the documentation as to how custom selectors are entered

**Comment by josephdpurcell** [comment]
Perhaps https://github.com/docker-mailserver/docker-mailserver/issues/1191 is related.

The use case I understand is when you introduce a new DKIM record is added you may not want to immediately expire the old DKIM record in case anyone re-validates the DKIM signature. Hence, the need for customizing the DKIM selector. For example, you may have a selector `dkim2022` and a `dkim2023`, but you don't want to remove `dkim2022` until 2024.

**Comment by nzedler** [comment]
> Perhaps #1191 is related.
> 
> The use case I understand is when you introduce a new DKIM record is added you may not want to immediately expire the old DKIM record in case anyone re-validates the DKIM signature. Hence, the need for customizing the DKIM selector. For example, you may have a selector `dkim2022` and a `dkim2023`, but you don't want to remove `dkim2022` until 2024.

I have an urgent different use case. I'm using SendInBlue for my Email Marketing, which requires setting their DKIM entry in my DNS. Unfortunately, they are using `mail` for the DKIM selector - using two records with the same selector results in a `DKIM failed`. Either I manage to get to use a different selector or I have to use a different email marketing service provider :/

Any way to set a different DKIM selector?

**Comment by georglauterbach** [comment]
Have you read `docker exec <CONTAINER> setup dkim help`??

**Comment by polarathene** [comment]
> Please explain how this issue is completed ?

> Any way to set a different DKIM selector?

The docs don't seem like they got updated (_technically [they didn't even exist back then](https://github.com/docker-mailserver/docker-mailserver/pull/1827)_), but as the PR linked that closed this issue; the feature to support custom selectors was added and the CLI tool provides more info on using that:

https://github.com/docker-mailserver/docker-mailserver/blob/dab70709d90df1d83b920eccc6c0386b283d677e/target/bin/open-dkim#L24-L45

The default is `mail` otherwise.

---

The docs probably could be updated (contributions welcome), but otherwise are showing how to configure with the default `mail` selector, just substitute that for your own custom one.

As the start of this issue notes, the DKIM selector is not tied to the hostname. It can remain as `mail`, or you can use something else and still have `mail.example.com`.

`docker-compose.yml` example suggests using `hostname` for your mail-server FQDN, be that `mail.example.com` or `example.com`, etc, but to completely avoid `domainname` (_misunderstood config advice from past maintainers)_.

**Comment by nzedler** [comment]
> Have you read `docker exec <CONTAINER> setup dkim help`??

I didn't try it because of the `NOT IMPLEMENTED YET!`. Worked however flawlessly. 
Thanks @georglauterbach @polarathene for the quick help.
