### ISSUE TITLE
[BEGINNER] ./setup.sh config dkim not creating file

### ISSUE THREAD

**Issue by Tzzui** [docker-mailserver/docker-mailserver#1773]
I am following this guide: https://github.com/docker-mailserver/docker-mailserver/wiki/Installation-examples

Using the "./setup.sh config dkim" command does nothing for me. The config folder stays empty. There also is no error displayed.

I have no idea how to proceed since I'm rather new to Linux and not familiar with docker at all.

**Comment by wernerfred** [comment]
You will receive further help if you use the Issue template as prompted during creation.

As this is your first issue ever I will give you the advice to read the docs and wiki first before opening an issue. In 2 secs you would have found this wiki page: https://github.com/docker-mailserver/docker-mailserver/wiki/Configure-DKIM which tells you that you need to add an account first before you can generate dkim keys

**Comment by aendeavor** [comment]
I 100% agree with @wernerfred, use the issue template and read the wiki. 

---

But you also mentioned

> I have no idea how to proceed since I'm rather new to Linux and not familiar with docker at all.

I will be honest here, this is not the right project to start with when you're new to Linux and / or Docker. Something like [ownCloud for Docker](https://doc.owncloud.com/server/admin_manual/installation/docker/) is more suited, since a mail server is complex and requires some knowledge about networking, Linux in general and definitely Docker.

**Comment by Tzzui** [comment]
Thanks, creating an account was the solution.

@aendeavor I recently started an apprenticeship and was told to just try this out. So far I've only installed and worked with Zabbix and Joomla/LAMP, but I feel like I'm making good progress. 

Anyway thanks for the help.

**Comment by aendeavor** [comment]
You're welcome.
