### ISSUE TITLE
 SSL_accept error -> I cannot Receive E-Mails from a specific domain

### ISSUE THREAD

**Issue by theoneandonly-vector** [docker-mailserver/docker-mailserver#1784]
# Subject
I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description
I cannot receive E-Mails from a specific domain

```
[36mmail_1              |[0m Jan 30 16:41:30 mail postfix/smtpd[140171]: connect from mailout33.domain.tld[IP.address.is.here]
[36mmail_1              |[0m Jan 30 16:41:30 mail postfix/smtpd[140171]: SSL_accept error from mailout33.domain.tld[IP.address.is.here]: -1
[36mmail_1              |[0m Jan 30 16:41:30 mail postfix/smtpd[140171]: warning: TLS library problem: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:../ssl/statem/statem_srvr.c:2259:
[36mmail_1              |[0m Jan 30 16:41:30 mail postfix/smtpd[140171]: lost connection after STARTTLS from mailout33.domain.tld[IP.address.is.here]
[36mmail_1              |[0m Jan 30 16:41:30 mail postfix/smtpd[140171]: disconnect from mailout33.domain.tld[IP.address.is.here] ehlo=1 starttls=0/1 commands=1/2
```

https://www.checktls.com/TestReceiver for my domain (receiver and logs):
```
  | SSLVersion in use: TLSv1_3
-- | --
  |   | Cipher in use: TLS_AES_256_GCM_SHA384
  |   | Perfect Forward Secrecy: yes
  |   | Certificate #1 of 3 (sent by MX):
  |   | Cert VALIDATED: ok
```

https://www.checktls.com/TestReceiver for sending domain:
```
SSLVersion in use: TLSv1_2
--
  |   | Cipher in use: ECDHE-RSA-AES256-GCM-SHA384
  |   | Perfect Forward Secrecy: yes
  |   | Certificate #1 of 3 (sent by MX):
  |   | Cert VALIDATED: ok
```

additional info:
I use let's encrypt-certificate created on another docker.
I use the latest - branch, updated @29.01.2021

**Comment by aendeavor** [comment]
Having a hard time using the issue templates? Have a look at the descriptions for the two labels.

**Comment by theoneandonly-vector** [comment]
> Having a hard time using the issue templates? Have a look at the descriptions for the two labels.

I just updated the issue (adding Subject and Description as titles..)

I'm no table to change the category (label) as it seems.
Most likely it's a "Question", maybe it's a bug.

**Comment by aendeavor** [comment]
The issue is here and pretty clear: `no shared cipher`. This means the TLS handshake was unable to make out a cipher suite. This is most likely the case because you are enforcing a modern version of TLS (most likely 1.3) but the other party does not support these ciphers.

Either lower try lowering your TLS level (not recommended) or make the other party use other cipher suites.

**Comment by aendeavor** [comment]
Watch this, and the recommended videos, and you'll understand:

<https://youtu.be/86cQJ0MMses>

**Comment by theoneandonly-vector** [comment]
I set this variable:
```
   - TLS_LEVEL=intermediate
```

But it won't fix the issue

**Comment by aendeavor** [comment]
> I set this variable:
> 
> ```
> 
>    - TLS_LEVEL=intermediate
> 
> ```
> 
> 
> 
> But it won't fix the issue
> 
> 

Try `modern`. Ig that doesn't work, these is not much you can do:)

**Comment by theoneandonly-vector** [comment]
I also tried with "modern" which won't fix it.
either this didn't work (how to check?)

or it is a bug/missing feature
here the cipher listed and "TLS_LEVEL=intermediate" should allow tls 1.2, and even 1.1..:
https://github.com/docker-mailserver/docker-mailserver/pull/1475

**Comment by aendeavor** [comment]
This is not a "bug", and I don't know whether you can call it a "missing feature". This PR needs to be re-opened, but it hasn't been yet. @polarathene is working on it, and he/she will be reaching back to when the PR is ready. In the meantime, there is nothing that can be done. You may assist him/her with the PR, that would speed things up.

**Comment by polarathene** [comment]
> I use let's encrypt-certificate created on another docker.

This shouldn't affect the error related to shared cipher suites. It will be an issue with some e-mail communications if the certificate is rejected by older servers once LetsEncrypt is issuing certificates with their new root CA that the old servers may not have. I'm not sure if that's happened just yet. For MTA exchanges they don't tend to verify certs, but MUA(mail clients) might, so it may be an issue on old client devices.

> `ECDHE-RSA-AES256-GCM-SHA384`

This cipher suite is already in the existing support and not requiring my PR from what I can see.

> here the cipher listed and "TLS_LEVEL=intermediate" should allow tls 1.2, and even 1.1..:

TLS version support does not mean all cipher suite are supported, this can be for various reasons beyond the control of this project alone.

You should verify that your changes are in fact making the other cipher suites and TLS versions available, not that you just saved a config file. [testssl.sh](https://testssl.sh/) is a project which can help check your server, or you can try some other service online that may reveal what ciphers are supported. Try get a proper list of supported cipher suites, not just the first one that is negotiated by the tool.

---

> @polarathene is working on it, and he/she will be reaching back to when the PR is ready.

I've been quite busy with other commitments unfortunately. I could allocate some time to get the improved cipher list pushed through and follow up with any other details at a later date I think.

Without more information, I can't say that it'd make much of a difference for resolving this issue. Especially since the cipher suite in question is already supported by the current releases. Please confirm that your server actually does list `ECDHE-RSA-AES256-GCM-SHA384` as a ciphersuite (or any ciphersuites below TLS 1.3).

**Comment by aendeavor** [comment]
@polarathene I understand. We'd be glad to even merge only a small portion of the original PR - after all, every improvement is worthwhile;) So if you think you can create a new PR which can be merged, even if it's small, I'd encourage you to do it:)

**Comment by polarathene** [comment]
Sure. IIRC most of what I had in the PR was fine, I was just being OCD about completing a large supporting document that justifies the decisions made and a valuable resource to anyone maintaining the TLS config in future.

I will try to have a PR by the next weekend after reviewing the changes and a quck review over my research notes to confirm. I'll follow-up with the document and any other additions at a later date.

**Comment by aendeavor** [comment]
> Sure. IIRC most of what I had in the PR was fine, I was just being OCD about completing a large supporting document that justifies the decisions made and a valuable resource to anyone maintaining the TLS config in future.
> 
> I will try to have a PR by the next weekend after reviewing the changes and a quck review over my research notes to confirm. I'll follow-up with the document and any other additions at a later date.

SGTM!

**Comment by theoneandonly-vector** [comment]
I checked my server with "testssl.sh" which results in "Has server cipher order?  ->  yes (TLS 1.3 only)"

since I used    
```
environment:
   - TLS_LEVEL=modern
```

inside my docker-compose.override.yml and all the other environment-variables which reside in this document are working as intended.
I would like to know how to debug this any further.

I also checked for other config-files using:
```
rg 'TLS_LEVEL='
```
which only finds my entry inside my override-file.

**Comment by aendeavor** [comment]
> yes (TLS 1.3 only)"

Means, _exactly like I said_, that you only accept TLSv1.3. This is however not the mail server's fault, as the TLS level `modern` complies with TLSv1.2 too.

This happens when you play with proxy settings, for example. Using Cloudflare? Check it. You just don't accept versions of TLS below 1.3 because you configured it somewhere else, this has nothing to do with this project.

I'd check my other setup if I were you.

**Comment by polarathene** [comment]
@theoneandonly-vector  I would assume the problem is because you've changed the config from the original setting you created the container with. Docker is generally immutable and that's how we know it as, that if we restart it, the state is reset.

This isn't happening with your docker-compose setup though. You need to properly take the container down IIRC with a `docker-compose down`, then bring it back up with the new env var / config. I forget the specifics. The current code will see the new env var, but also read the modified config from initial setup. Even if this internal config is not mounted locally and resides in the container it's not reset to the image state until the container is properly brought down.

My PR did catch that and has fixed it accordingly, I just need to review it this coming weekend and get that merged for everyone elses benefit. In the meantime, try the workaround I mentioned above.

@aendeavor does have a point though, both our `TLS_LEVEL` should support more than TLS v1.3. That does suggest something else is interfering. Can you describe your setup a bit more? If there are middleboxes involved, these can act as TLS proxies that are enforcing TLS v1.3 due to some security policy if at an enterprise company?

---

> Using Cloudflare? Check it.

I don't think Cloudflare proxies SMTP?

**Comment by theoneandonly-vector** [comment]
Hi @polarathene 

I don't have a reverse-proxy setup. I also just checked on the server itself using:
```./testssl.sh -t smtp localhost:25```
which gives me the exact same result (besides "Domain name mismatch" of course).

After every change in the config I already always use ```docker-compose down``` and then start it up again with ```docker-compose up``` afterwards.

is there a way to get these settings logged? / debug what should happen manually inside the docker?

**Comment by polarathene** [comment]
You may need to wait until I tackle my referenced PR this weekend and when that gets merged with a new dockerhub update.

I have a test project that uses docker and custom DNS + custom Root CA for issuing the TLS certificates and supporting TLS on a local domain name all offline. It's probably a good way to approach a reproducible environment if the problem really was related to the current docker image for the project somehow. I need to allocate my time for the PR, but should be able to make that setup available on Github sometime after if it'd be helpful.

> After every change in the config I already always use `docker-compose down` and then start it up again with `docker-compose up` afterwards

Only having TLS v1.3 support does seem very odd.

You could maybe try with `nmap` (package), eg `nmap --script ssl-enum-ciphers -p 25 0.0.0.0`.

> is there a way to get these settings logged? / debug what should happen manually inside the docker?

I'm not a regular contributor to the project and my recall of things is a bit foggy.

**Comment by theoneandonly-vector** [comment]
```
nmap --script ssl-enum-ciphers -p 25 0.0.0.0
on the server itself
```
tells me only this:
```
nmap --script ssl-enum-ciphers -p 25 0.0.0.0
Starting Nmap 7.80 ( https://nmap.org ) at 2021-02-02 23:32 CET
Nmap scan report for 0.0.0.0
Host is up (0.000096s latency).

PORT   STATE SERVICE
25/tcp open  smtp

Nmap done: 1 IP address (1 host up) scanned in 0.52 seconds
```

**Comment by aendeavor** [comment]
> I don't think Cloudflare proxies SMTP?

You're right, just HTTP(S) (and related dev) ports. I bet Traefik could allow a construct similar with the new proxy protocol. But this is not the case here, interesting. I'll re-open.

But I still think this not the mailserver's doing.

@theoneandonly-vector whats you whole setup? Host, everything that could be related.

**Comment by theoneandonly-vector** [comment]
this is all the ssl/tls related config from ```cat main.cf``` from inside the docker:
```
# TLS parameters
smtpd_tls_cert_file=/etc/postfix/ssl/cert
smtpd_tls_key_file=/etc/postfix/ssl/key
#smtpd_tls_CAfile=
#smtp_tls_CAfile=
smtpd_tls_security_level = may
smtpd_tls_loglevel = 1
smtp_tls_security_level = may
smtp_tls_loglevel = 1

tls_ssl_options = NO_COMPRESSION, NO_RENEGOTIATION

tls_high_cipherlist = ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
tls_preempt_cipherlist = yes
smtpd_tls_protocols = !SSLv2,!SSLv3,!TLSv1,!TLSv1.1
smtp_tls_protocols = !SSLv2,!SSLv3,!TLSv1,!TLSv1.1
smtpd_tls_mandatory_ciphers = high
smtpd_tls_mandatory_protocols = !SSLv2,!SSLv3,!TLSv1,!TLSv1.1
smtpd_tls_exclude_ciphers = aNULL, LOW, EXP, MEDIUM, ADH, AECDH, MD5, DSS, ECDSA, CAMELLIA128, 3DES, CAMELLIA256, RSA+AES, eNULL
smtpd_tls_dh1024_param_file = /etc/postfix/dhparams.pem
smtpd_tls_CApath = /etc/ssl/certs
smtp_tls_CApath = /etc/ssl/certs
```

**Comment by theoneandonly-vector** [comment]
I use:
Ubuntu 20.04 (mini) (All packages are up to date.)
docker-compose version 1.27.4 (installed/updated using pip3)

**Comment by polarathene** [comment]
> tells me only this

Ok, I think that'd happen if there was only TLS 1.3, it should list earlier TLS version cipher suites if they were available.

> this is all the ssl/tls related config from `cat main.cf` (postfix) from inside the docker:

This looks all fine to me. TLS 1.2 should be supported along with the cipher the other MTA was wanting to negotiate.

The Ubuntu server it's running on is with a cloud provider VPS? Or is this running in a different environment like an enterprise infrastructure locally?

Nothing is coming to mind that would be causing this, especially with this project. I will assist you further once we've got my PR updated and merged/published. The best way for us to go forward is probably if I give you a copy of my test environment to bring up (it's docker-compose based), and verify that works correctly and go from there.

**Comment by theoneandonly-vector** [comment]
Just a quick update.. I now ran:
```
./testssl.sh -t smtp localhost:25
```
inside the host and again the same output.

The Ubuntu Server is running as a VM on a standalone ESXi.

I would love to try the test-environment.

**Comment by polarathene** [comment]
> I would love to try the test-environment.

I will try to put it up on Github after getting my PR sorted :+1:

I need to write some instructions into a README as there are some manual setup steps I didn't find time to automate.

**Comment by theoneandonly-vector** [comment]
As my correct Certificate is diplayed when I use ssltest.s I think it might "just work", but it still bothers me that this value hasn't changed to my custom path:
```
smtpd_tls_cert_file=/etc/postfix/ssl/cert
```
https://github.com/docker-mailserver/docker-mailserver/search?q=smtpd_tls_cert_file

I remmeber that I used to replace this certififcate some time ago using crontab but then had issues after my certififcate was replaced the 2nd time.

**Comment by theoneandonly-vector** [comment]
I just replaced the files and restarted postfix which doesn't fix the issue.

**Comment by aendeavor** [comment]
> I just replaced the files and restarted postfix which doesn't fix the issue.

Obviously. As I said, likely not a cert issue, but a TLS configuration problem.

**Comment by polarathene** [comment]
> but it still bothers me that this value hasn't changed to my custom path

The startup script copies over your custom certificate path to the fixed path you've mentioned, the path in config doesn't update. Shouldn't be an issue.

MTA's rarely enforce validating the certificate unlike web browsers and I think MUAs (mail clients). Certs issues shouldn't affect the supported cipher suites. You'll either have the RSA or ECDSA digital signature based cipher suites, the project doesn't presently support ECDSA IIRC... it may be possible that you're using ECDSA? That's explicitly excluded at present (ignore RSA+AES, that's about RSA for key exchange which is different):

```
smtpd_tls_exclude_ciphers = aNULL, LOW, EXP, MEDIUM, ADH, AECDH, MD5, DSS, ECDSA, CAMELLIA128, 3DES, CAMELLIA256, RSA+AES, eNULL
```

**Comment by theoneandonly-vector** [comment]
my cert is RSA

**Comment by aendeavor** [comment]
Some PRs were merged. Please try again tomorrow with the `:edge` tag.
