### ISSUE TITLE
postfix/dnsblog module

### ISSUE THREAD

**Issue by mrniko** [docker-mailserver/docker-mailserver#1788]
Hi Team,

How to turn off postfix/dnsblog module? Because it blocks IPs listed in bl.spamcop.net and other spam servers

**Comment by aendeavor** [comment]
Let me recap. You used the BUG template, removed everything and then asked this question instead of reading the documentation and / or using the internet, and then expect an answer.

Here is the first step in finding it: <https://www.google.com/search?channel=fs&client=ubuntu&q=postfix+disable+dnsblog>

**Comment by mrniko** [comment]
Thank you for your answer! I'm sorry for the issue with description.
