### ISSUE TITLE
Dual Factor

### ISSUE THREAD

**Issue by luc3004** [docker-mailserver/docker-mailserver#1797]
Hi, - has anybody implemented MFA (e.g. google authenticator) integrated with the server ?  thanks

**Comment by wernerfred** [comment]
I think you misunderstood how MFA is implemented and how it works. Imho you cannot use MFA with an Mailserver (think about other public email providers - as soon as you have MFA enabled on your account you will need to use an app-passwortd (without MFA) to login with an email client)

What can be protected with MFA is your Webmail for example. Then you need 2 factors to access the webmailer which then uses the provided password (without MFA) to connect to the mailserver.

If you think I'm wrong or have a specific setup in mind then _please_ provide more information and use the issue templates otherwise you wont receive valuable help (not bc we do not want to help you but because it is impossible to guess what you want/what the problem/cause is).

**Comment by luc3004** [comment]
Werner, - postix & dovecot can integrate witn pam,  and e.g. google authenticator works with pam.  So this was something i wanted to know if somebody has tried out. 

Any thoughts ? thansk, 
(sorry for not being more detailed on this )
