### ISSUE TITLE
[BUG] dovecot gets killed after server startup

### ISSUE THREAD

**Issue by SebastianMuskalla** [docker-mailserver/docker-mailserver#1837]
As briefly discussed in issue #1834, I have a problem with dovecot being killed by the supervisor.
The server works again (Thanks for the quick fix, by the way 👍), but this issue persists.
As also suggested in #1834, I am creating a new report to discuss the problem.

Every time I start the server, dovecot gets killed by the supervisor after a few seconds.
It then restarts and operation proceeds normally.

Excerpt from `mail.warn`:
```Feb 25 02:25:37 mail dovecot: master: Warning: Killed with signal 15 (by pid=10 uid=0 code=kill)```

Here is the full log of STDOUT (with `DMS_DEBUG` set to `1` and `SUPERVISOR_LOGLEVEL` set to `debug`) from the moment the server starts to the occurrence of the problem:
https://pastebin.com/AiJMbCFq

Here is the `docker-compose.yml` that is used to run the server:
https://pastebin.com/i7eYT1Xq

(By the way, should I still be getting DNS errors like `Feb 25 02:40:11 mail postfix/dnsblog[6054]: warning: dnsblog_query: lookup error for DNS query 133.12.169.134.list.dnswl.org: Host or domain name not found. Name service error for name=133.12.169.134.list.dnswl.org type=A: Host not found, try again` after setting `dns: 1.1.1.1`?)

**Comment by aendeavor** [comment]
First of all, thanks for reporting a bug. I can't help but notice that you **_deleted_** the content of the issue template for bugs. This is **a big problem**, as this template incorporates the necessary information for us maintainers to work out whether it's a misconfiguration or a real bug. Therefore, this is labelled as template not used, a warning _for now_. Please use the template in your issues appropriately.

---

The DNS issue should actually be solved with `1.1.1.1`, but I'm seeing the same "issue". Please see #948 for more information. This is actually not an issue inherent to `docker-mailserver`.

---

To the actual problem at hand: I was actually experiencing the very same behavior. I didn't think about it, but when I discovered that `hostname` was an option for Docker Swarm as well, and I set it, this issue disappeared. I would start there - a hostname-related issue.

I set my hostname to `mail.domain.tld` instead of `mail`, but only because I also use `OVERRIDE_HOSTNAME=mail.domain.tld`. What I would like you to do is this:

1. Run `hostname` **and** `hostname -f` in your container first: `docker exec <CONTAINER> hostname [-f]`. I understand you want to protect your domain from being shown. Therefore, just replace your domain name with `domain` and your top level domain ending with `.tld`.
2. Please show us your `/etc/hosts` file. This should in theory not leak anything.
3. Please try using `OVERRIDE_HOSTNAME` and see if this problem persists. If this is the case, we will somehow need to see whether a script on our side does not what it is supposed to do.

**Comment by SebastianMuskalla** [comment]
> This is most-likely done by Supervisor

Indeed, the PID that issues the signal belongs to a python process that seems to run the supervisor script.

**Comment by casperklein** [comment]
I think, Changedetector (`check-for-changes.sh`) detected a change and restarted dovecot afterwards:

```
2021-02-25T01:25:38.295169232Z 2021-02-25 02:25:38,294 DEBG 'changedetector' stdout output:
2021-02-25T01:25:38.295195151Z dovecot: stopped
2021-02-25T01:25:38.295198561Z dovecot: started
```

**Comment by aendeavor** [comment]
> I think, Changedetector (`check-for-changes.sh`) detected a change and restarted dovecot afterwards:
> 
> 
> 
> ```
> 
> 2021-02-25T01:25:38.295169232Z 2021-02-25 02:25:38,294 DEBG 'changedetector' stdout output:
> 
> 2021-02-25T01:25:38.295195151Z dovecot: stopped
> 
> 2021-02-25T01:25:38.295198561Z dovecot: started
> 
> ```

My fist instinct as well. I was just curious because this message stopped for me seemingly out of nowhere after a hostname update. But I guess we can call this a day - `check-for-changes.sh` is most likely just doing it's job :)
