### ISSUE TITLE
[FR] Can you provide a key only dump in folder /config/opendkim/keys/mydomain.com/ ? 

### ISSUE THREAD

**Issue by tdeseez** [docker-mailserver/docker-mailserver#1876]
# Feature Request
Can you provide a key only dump in folder /config/opendkim/keys/mydomain.com/ ? 

## Context
When adding a dkim key in domain provider web front-end, it may be just easier to copy/paste the key if it is displayed one line.

### Is your Feature Request related to a Problem?
My domain provider is ovh.com, and the dkim dialog looks like this in my web browser : 

![image](https://user-images.githubusercontent.com/81270993/113072423-4f4e8f00-91c7-11eb-95ae-0955715b6cd6.png)

Retrieving the key from already existing files 'mail.private' and 'mail.txt' (with the line breaks and the double quotes) can be painful in order to paste in the key field.

### Describe the Solution you'd like
For instance, an extra file called _mail-key-only-dump.txt_ could enclose the key presented on a single line like this : 

`MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAthaGIMZtlUjoi2leVQWvTbPDFmlCkz2ZGJqRSMErPC7F1U1/likG4JYzC6LRQ85fIirN1NcjiKJR296VUoKTImxRoGMNDO9TiqOdUMStEr9QuQo3NZxI93Qm5+8ukyEqXt1D5cvfNc9TtdCvC5GZrlFBPsKXc7BsHY+2yueCKTpwANQxKDdX3yTLL5H9ABaSuNV4m9Hj2x4ZVnpZTmQYUnQlu7jDK11riGhtTYe/1Y/4NeuXCyCtQ7vzw/O5g88nF1DofuGUOZ6p853eSWLLLAF4QooYB2Rh+aOXglE2oIKlGUZK/zy47kaQLw0dur2GtzVwCaUi7zJxCCVAMJBiDwIDAQAB`

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

**Comment by aendeavor** [comment]
Well, yes (we could in theory somehow enable this in the scripts), but actually no (because it's just not worth it).

Don't get me wrong, I understand where you're coming from. But it's just part of your job to paste a correct version of the key in your DNS provider's table :)

If you provide a PR which enables exactly this, the maintainers will have a look. I would, however, not bet on this being merged.

**Comment by tdeseez** [comment]
Hi,
Thanks for your answer.

I already tried _mailu_, _mailcow_, _yunohost_ (which are all very good) and i must say i really appreciate the efficiency and minimalist approach of _docker-mailserver_. So I only intend to add a very humble contribution to the project. But this may be very subjective I guess. I thought this kind of feature could be appreciated by other users.

>  If you provide a PR which enables exactly this, the maintainers will have a look.

I don't know what's a PR, but I can provide you with this bash script I made today (must point to _mail.txt_ as argument) :
```
#!/bin/bash

if [ ! -f "$1" ]; then
        echo "File '$1' does not exist. You must provide a valid filename as an argument."
        echo "Exiting."
        exit
fi

file_name="$1"
ptn_start="p=MII"
ptn_end=" )"
set keytmp

while read line; do
        line="${line//\"}" # remove quotes from line
        keytmp="$keytmp$line"
done < $file_name

pos1=`echo $keytmp | grep -b -o "$ptn_start"`
pos2=`echo $keytmp | grep -b -o "$ptn_end"`

pos1=$((${pos1//:$ptn_start}+3))
pos2=$((${pos2//:$ptn_end}))

echo $keytmp | cut -c$pos1-$pos2
```
I thought this could be also part of _./setup.sh config dkim_ as an option. For instance : 

`./setup.sh config dkim show_key`

Regards/

**Comment by aendeavor** [comment]
> I don't know what's a PR

A PR is a pull request. An example is #1879, in which a maintainer added color variables to the `setup.sh` script.

> but I can provide you with this bash script I made today (must point to mail.txt as argument)

If you'd like to contribute, you'd need to follow the guide in [`CONTRIBUTING.md`](https://github.com/docker-mailserver/docker-mailserver/blob/master/CONTRIBUTING.md#pull-requests). This guide explains how to submit a "PR". The script you'd need to touch would be `target/bin/open-dkim`.

Please be aware of the fact that this project uses a very rigorous style policy. This can also be seen in [`CONTRIBUTING.md`](https://github.com/docker-mailserver/docker-mailserver/blob/master/CONTRIBUTING.md#coding-style). Make sure you adhere to the styling rules - otherwise contributions cannot be merged. This is done in order to enable high code-quality standards.
