### ISSUE TITLE
[BUG] readlink does not support param -f on macos systems

### ISSUE THREAD

**Issue by mommel** [docker-mailserver/docker-mailserver#1884]
### What is affected by this bug?
Only the  setup.sh on mac

### When does this occur?
when useing ./setup.sh 

### How do we replicate the issue?

1. run  ./setup.sh with any param on macos 

## Behavior
Will fail because of the wrong readlink version

### Actual Behavior
Fails with : illegal option -- f

### Expected Behavior
Does not fail with : option -- f

## Your Environment

Macos

### Environment Variables

not relevant

### Relevant Stack Traces
-

**Comment by aendeavor** [comment]
I'd like to see what happens on your system when you run `setup.sh`. Please show the full output when running it.

I'm curious because the `if ... else ...` should catch your issue just fine. It's not clear to me why this does not work (anymore), since I fixed this issue myself for macOS users.

Can you show the output of your shells version and which shell you're using?

**Comment by reneploetz** [comment]
Note that readlink is an external utility which exists in different implementations for GNU and BSD-based systems. BSD-based systems (such as FreeBSD, MacOSX, ...) provide readlink with a different "-f" option. 

See manpages:
GNU: https://linux.die.net/man/1/readlink
MacOS: https://www.unix.com/man-page/osx/1/readlink/

If one decides not to support MacOS X, we do not need to change any code in the project itself as one can either use a bash alias for readlink binary or modify the path like so: https://apple.stackexchange.com/a/69332

**Comment by wernerfred** [comment]
So after #1886 getting merged and the discussion in #1885 together with the answer of @reneploetz can we close #1884 and #1885 @mommel?
