### ISSUE TITLE
docker-compose v3.x file and memory limits

### ISSUE THREAD

**Issue by Larpon** [docker-mailserver/docker-mailserver#2005]
# Subject

I would like to configure a not documented mail server use case

## Description

I'm using docker-mailserver to run my personal mail on my Raspberry Pi 4 - and everything works as expected. To be on the safe side I searched for how to limit memory usage with docker-compose since I don't want the whole machine to freeze if the mailserver is attacked or similar and [found this issue](https://github.com/docker/compose/issues/4513) which basically says you should use version >= 2.1 of the format. Now I don't know enough of docker to really be able to see how I should apply this to this project.

How can a novice set a limit to how much memory the mailserver setup will use?

Do I simply change the version of the compose file or do I have to setup some (overkill) swarm on my raspberry pi? 🤔

Thanks for a great project!

**Comment by aendeavor** [comment]
Have a look here: <https://stackoverflow.com/questions/42345235/how-to-specify-memory-cpu-limit-in-docker-compose-version-3>. Note the detail: "The conversion is a "best effort" attempt and shouldn't be relied on for production deployments."

**Comment by Larpon** [comment]
@aendeavor - thanks. Yes, that's a very... _interesting_ note.

I still don't know where it leaves the small setups that don't need a swarm :man_shrugging:.
I'll see for how long I can run it in compatibility mode then.

**Comment by aendeavor** [comment]
I am in the process of reverting back to Compose because I dislike certain Swarm _features_. But Compose is not the ultimate solution as well (no proper secrets, etc.). I like that it is easy, to be fair.

But you may want to have a look at <https://k3s.io/>. I have not yet decided whether I want to go Kubernetes. I dislike the added complexity. But I get away from Docker (to CRI-O and crun) this way :D You might be interested.

**Comment by Larpon** [comment]
Thanks for the hint!
