### ISSUE TITLE
Message has a DKIM or DK signature, not necessarily valid

### ISSUE THREAD

**Issue by waterdrop01** [docker-mailserver/docker-mailserver#2022]
Hello Everyone,

I decided to check the trust score of my docker-mailserver using https://www.mail-tester.com and https://dkimvalidator.com/ and both reported the error "**Message has a DKIM or DK signature, not necessarily valid"** (see below):

```
 0.0 SPF_HELO_NONE          SPF: HELO does not publish an SPF Record
 0.1 DKIM_SIGNED            Message has a DKIM or DK signature, not necessarily valid
 0.1 DKIM_INVALID           DKIM or DK signature exists, but is not valid
```
Do you have the same issue, and if not, any idea on how to fix it?

Thanks a lot for any advice!

**Comment by reneploetz** [comment]
If you are not using SPF or DKIM the scores are correct.

This is also not a bug but exactly how spamassassin is operating. Each rule that has a score attached to it, usually the existence of a signature is increasing the score and the validity of the signature is decreasing the score afterwards again. So the DKIM_SIGNED=0.1 is negated by DKIM_VALID=-0.1 if the DKIM signature is valid, but as your domain does not use DKIM you get an additional penalty of DKIM_INVALID=0.1. 
Note that for SPF and DKIM the scores for missing signatures/settings are deliberatly low to discourage spammers from defaulting to use SPF and DKIM to get past the default settings.

**Comment by waterdrop01** [comment]
Thanks a lot @reneploetz for your feedback.

I thought that having a DKIM and/or SPF record could only improve the scoring (your message seem to say otherwise?).

Anyway, even though I don't understand how it works, I'd just like to improve the score if it's not too complicated to do.

I followed the [docker-mailserver documentation](https://docker-mailserver.github.io/docker-mailserver/edge/config/best-practices/dkim/) to setup SPF, DKIM and DMARC records. 

Currently, here is what these records look like:

1. **SPF** TXT record for `my.domain.` domain:
```
"v=spf1 mx ~all"
```
2. **DMARC** TXT record, for `_dmarc.my.domain.` domain:
```
"v=DMARC1; p=none; rua=mailto:postmaster@my.domain; ruf=mailto:postmaster@my.domain; sp=none; ri=86400; rf=afrf; pct=100"
```
3. DKIM TXT record, for `mail._domainkey.my.domain.` domain:
```
v=DKIM1;h=sha256;k=rsa;s=email;p=MIICIjANBgk [...] AwEAAQ==;t=s;
```

Do you have an idea of which DNS setting I could change to make the DKIM "**valid**"? 

Many thanks for your precious help!

**Comment by reneploetz** [comment]
Using SPF on your side will likely improve the scoring for other servers. It's just that the server that is checking your score has opted to score SPF and DKIM rather low as they are using the default settings.
The 0.1 increase for the existance of a DKIM signature will be negated if the signature is valid (=> -0.1 for DKIM_VALID), so having a valid DKIM and having no DKIM result in the same score per default. An existing invalid DKIM header will increase your score by 0.2 - same for an invalid existing SPF header in your mail.

I'm unsure as to why the mail check states that your domain does not have SPF and a valid DKIM. You can try to use https://mxtoolbox.com/ to check the DNS settings for your mail domain. Select the check you want to run after clicking on MX lookup.

**Comment by hnws** [comment]
If you are using DNS provider such as nsone, your DNS record, mail._domainkey.example.tld, should have no space, quotes after the "p=".
It should look like v=DKIM1; h=sha256; k=rsa; p=xxxxxxxxxxxxxxxxxxxxxxxxxxx_long_string_without_space_and_quote_xxxxxxx

**Comment by josephdpurcell** [comment]
It looks like this older thread might be related: https://github.com/docker-mailserver/docker-mailserver/issues/1035.

I ran into this same issue. I don't know the exact resolution, so I'll share what I did.

* I used setup.sh to generate DKIM with a custom selector and after a while figured out that isn't supported, see https://github.com/docker-mailserver/docker-mailserver/issues/1304. So I went back to using the "mail" selector.
* I realized the setup.sh doesn't re-generate the DKIM each time you run it.
* I realized the setup.sh generated TWO DKIM keys, one at docker-mailserver/opendkim/keys/example.com/mail.private and one at docker-mailserver/opendkim/keys/mail.example.com/mail.private. I didn't dig to understand why; my docker-compose has hostname=mail and domainname=example.com, and the email accounts I'm using are like user@example.com. The key that worked is keys/example.com/mail.private (specifically the related .txt file which has the pub key).
* I initially used a 2048 key then saw the comment https://github.com/docker-mailserver/docker-mailserver/issues/1035 and switched to a 1024 key.
* I was copying the p= value into my old DKIM record because I thought I had a well curated record. I was wrong. I replaced my entire record value with the one provided by docker-mailserver (opendkim). The only difference was my old one had `t=s; s=email`. I didn't dig into the RFC but I suspect `t=s` is a problem for my setup.

This thread and issue #1035 have both been helpful, thank you.
