### ISSUE TITLE
THANK YOU 

### ISSUE THREAD

**Issue by michabbb** [docker-mailserver/docker-mailserver#2065]
i remember the days (many years ago, where i didn´t even know that something like docker exists) - where it took me days to setup a simple mailserver with all the usual tools and features. i followed the README here and was able to setup the server in 5 minutes....

HOLY SHIT !!!!!!

!!!! THANK YOU TO ALL CONTRIBUTORS HERE !!!!!

![](https://media.giphy.com/media/M9NbzZjAcxq9jS9LZJ/giphy.gif)

**Comment by maietta** [comment]
I concur. Way back in early 1998, I was wrote a web front-end for an email system for a local ISP. In 2001, I spent several WEEKS setting up and configuring an email server for my customers of my own ISP. It was absolute hell. Along came QmailRocks which was a step by step guide for setup and configuring email systems on Linux. It was rock solid, but we now have Docker containers to help us along.

I just discovered this project a couple of days ago (on accident) and whoah, this is what I wanted to do. I wanted to build an entire email system from scratch, built around docker containers. This project is dead simple and a great start. So instead of working on my own, I'll be contributing anywhere I can to help the project along!

Kudo's to the developer(s) for such an awesome and badly needed project. I'm tired of so called "free" or "open source" projects that have pretty hard limits on usage.

**Comment by georglauterbach** [comment]
@maietta Thank’s for showing interest and offering help. And indeed, there is something that could be done to improve the project:

https://github.com/docker-mailserver/docker-mailserver/pull/2080#issuecomment-878283353

 I’m just connecting the dots here, the PR itself is not important to the issue at hand. `check-for-changes.sh` constantly, as the name suggests, checks for state changes and restarts services (like Postfix) to pick them up. The comment I linked to makes one aware of a “flaw” that could be fixed :)

**Comment by maietta** [comment]
> @maietta Thank’s for showing interest and offering help. And indeed, there is something that could be done to improve the project:
> 
> [#2080 (comment)](https://github.com/docker-mailserver/docker-mailserver/pull/2080#issuecomment-878283353)
> 
> I’m just connecting the dots here, the PR itself is not important to the issue at hand. `check-for-changes.sh` constantly, as the name suggests, checks for state changes and restarts services (like Postfix) to pick them up. The comment I linked to makes one aware of a “flaw” that could be fixed :)

Thanks for the suggested for where I can first start to get my hands dirty. First things first, I've got to get a working instance of this system where I can also configure my POP3 or IMAP clients (I have a suspicion as to why it's not working for me, but haven't yet dug into it). Once that's out of the way, I'll see what I can do to get this project moving a little faster. I'll be glad to devote a lot of my time each week to focus on helping improve this system and setting up things like one-click app deployments on Digital Ocean and Vultr but also for PaaS solutions like Caprover.

For the record, I am building a WHM cPanel hosting alternative under the brand PremoWeb. The idea is to give people a GPLv3 option of a DIY hosting solution that is easy to deploy and low cost, built around the open source projected called Caprover. I'm looking squarely at this Docker Mailserver project as the email system of choice for the back-end of the DIY hosting solution I'm working on.

Again, first things first. I need to get an instance of this system operational where I can also access via POP3 and IMAP. I'll start working on it this morning here in California.

**Comment by colindawson** [comment]
I'd like to add my thanks to this as well.   I tried several years ago to setup a mail server and completely failed.   Even with all the heavy lifting done here it's still taken me a while to get my email server up and fully functional.   (I'm deploying in Kubernetes)
Also the process of getting this setup and running properly has been a great education as well.

Thank you for making a great email server, something which I've found to be the single hardest thing to get setup and running.
