### ISSUE TITLE
[FR] document how to run in rootless Podman

### ISSUE THREAD

**Issue by alexanderadam** [docker-mailserver/docker-mailserver#2178]
# Feature Request

This is more or less a follow-up of @OrvilleQ's [PR that brought general Podman support](https://github.com/docker-mailserver/docker-mailserver/pull/1327).
[As OrvilleQ mentioned earlier](https://github.com/docker-mailserver/docker-mailserver/pull/1327#issuecomment-557875369), another PR should fix this.

## Context

Currently [the script will complain](https://github.com/docker-mailserver/docker-mailserver/blob/0da66ccb34dcaf0663b6b5635ba97f990b761881/setup.sh#L73) with the message `Curently docker-mailserver doesn't support podman's rootless mode` if it is running rootless.

### Is your Feature Request related to a Problem?

docker-mailserver cannot be run in rootless mode.

### Describe the Solution you'd like

It should be running in rootless mode.

I'm new to podman, so I don't know exactly how a proper solution should look like.
To be honest, I'm not even sure what it needs root for.
As far as I understood, the port within the container image shouldn't matter (since it can be mapped at the host), right?
And on the outside only the `CAP_NET_BIND_SERVICE` capability should be needed for privileged ports, right?

### Are you going to implement it?

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

### Alternatives you've considered

Not using `docker-mailserver` for projects that require rootless mode, I guess? :shrug: 

### Who will that Feature be useful to?

For people using rootless services as it is commonly suggested.

### What have you done already?

Nothing except writing this issue.

**Comment by casperklein** [comment]
Disclaimer: I've never used podman.

In a default setup, opening ports <1024 requires root access. So I am not sure, if it's possible to expose port 25, while running rootless.

See also: [Shortcomings of Rootless Podman](https://github.com/containers/podman/blob/main/rootless.md)

**Comment by OrvilleQ** [comment]
@alexanderadam If you look deep into Podman's document, in the [Rootless Network](https://podman.io/getting-started/network#rootless-networking) section you'll find this:

>## Rootless Networking
>When using Podman as a rootless user, the network is setup automatically. The container itself does not have an IP Address, because without root privileges, network association is not allowed. You will also see some other limitations.
>### Publishing Ports
>Port publishing as rootless containers can be done for “high ports” only. All ports below 1024 are privileged and cannot be used for publishing.

Rootless Podman running in the user namespace, binding port under 1024 is impossible even with `CAP_NET_BIND_SERVICE`. You can change the lowest port normal user can binding to like the issue @casperklein mentioned, but the risk caused by this change is even worse than using podman's root mode. The safest way I can imagine now is using iptable in order to forward regular port to privilege port.

But on the other respect, I don't think setup.sh should interactive with things other than docker and podman. And that's the main reason why I didn't open another PR years ago.

**Comment by alexanderadam** [comment]
> Rootless Podman running in the user namespace, binding port under 1024 is impossible even with `CAP_NET_BIND_SERVICE`.

Why is that? I thought this capability is used for exactly that?
As far as I understood, it works on other tools by giving that capability with [`setcap`](https://man7.org/linux/man-pages/man8/setcap.8.html).

Is Podman broken in this regards?

**Comment by alexanderadam** [comment]
Ah, I see. [Podman really is broken in this regards](https://github.com/containers/podman/issues/7866#issuecomment-713475392).

**Comment by OrvilleQ** [comment]
> Ah, I see. [Podman really is broken in this regards](https://github.com/containers/podman/issues/7866#issuecomment-713475392).

Will you can still make rootless docker-mailserver possible but I don't think that's something setup.sh should do.

Maybe I'll write a rootless guide if I have time tomorrow. But it's really busy lately, so don't have hope.

**Comment by alexanderadam** [comment]
> > Ah, I see. [Podman really is broken in this regards](https://github.com/containers/podman/issues/7866#issuecomment-713475392).
> 
> Will you can still make rootless docker-mailserver possible but I don't think that's something setup.sh should do.
> 
> Maybe I'll write a rootless guide if I have time tomorrow. But it's really busy lately, so don't have hope.

What way would you solve this?

I'm definitely against lowering `ip_unprivileged_port_start` but maybe a 'dumb' reverse proxy that just redirects traffic from privileged ports to unprivileged ones would do as well. Or a firewall rule that does this.
This way even exploiting a mail server process wouldn't do any further harm.

**Comment by alexanderadam** [comment]
@OrvilleQ I changed the issue title so that it is about _documenting_ how to run in rootless Podman. :wink:

**Comment by OrvilleQ** [comment]
Pull request has opend. #2179 

Please review this PR when you feel appropriate.

**Comment by georglauterbach** [comment]
I'll chime in here as I provided the most recent [Kubernetes documentation](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/kubernetes/). Have a look at [the deployment's security context under `spec.template.spec.containers.securityContext`](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/kubernetes/#deployments). One can see that `runAsNonRoot: false` was chosen, and DMS is therefore running as a root user. 

Why am I pointing this out? I tested DMS when running non-root and encountered numerous problems, ports being only one. There were so many problems, as seen [in this discussion](https://github.com/docker-mailserver/docker-mailserver/issues/2094#issuecomment-890792244), that I felt like running as root is theoretically possible, but **practically infeasible**.

Looking at the linked PR and this issue's discussion, I feel like you guys are using Podman with DMS in rootless mode without any problems. But I do not understand how this is possible? The container won't even start in rootless mode when I tested it:

``` BASH
$ docker run --user 1000 --rm mailserver-testing:ci
Error: Can't drop privilege as nonroot user
For help, use /usr/bin/supervisord -h
```

Podman should yield the same result. There are countless file permission issues when you tackled the `supervisor` problem, and solving the `supervisord` root problem is non-trivial. Adding all this together, I actually feel like we should do the following:

``` DIFF
- echo "Curently docker-mailserver doesn't support podman's rootless mode, please run this script as root user."
+ echo "Docker Mailserver does not support rootless mode. Please run this script as a root user."
```

because unless someone comes along and changes at least a few thousand lines of code and tests, DMS won't run rootless anytime soon - at least that's what my experience tells me.

**Comment by OrvilleQ** [comment]
> One should also note somewhere that Podman's rootless mode is not about running as a non-root user inside the container, but about the mapping of (normal, non-root) host users to root inside the container :D I got confused for a second here.

Make sense.

:-)

**Comment by alexanderadam** [comment]
I like the firewall solution. Nice and easy.
Thank you! :+1: It looks fine to me.

**Comment by OrvilleQ** [comment]
By default, podman rootless mode us Rootlesskit as the default port forwarder, and we can't get real client IP with it.

In order to get real client IP address, `podman run --network slirp4netns:port_handler=slirp4netns ...` will change port forwarder to slirp4netns.

See [here](https://rootlesscontaine.rs/getting-started/podman/#changing-the-port-forwarder) for more information.

But I'm not sure how to achieve this with `docker-compose.yml`. I mainly use Kubernetes and Podman and I'm not very familiar with writing docker-compose file. Could you guys help me with that?
