### ISSUE TITLE
Letsencrypt subdomain error

### ISSUE THREAD

**Issue by jessec** [docker-mailserver/docker-mailserver#2293]
# Subject

Hi I'm getting the error below everything seems to be working OK but, I was wondering if I should fix this.

I never seen this before and it just happened on a new install with a subdomain. Is this a subdomain issue?

Again everything does seems to work correctly.

Thanks

I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description

	Error: sed -i -r s|^(smtpd_tls_chain_files =).*|\1 /etc/letsencrypt/live/sub.domain.co/privkey.pem /etc/letsencrypt/live/sub.domain.co/fullchain.pem| /etc/postfix/main.cf
	Error: sed -i -r -e s|^(ssl_key =).*|\1 </etc/letsencrypt/live/sub.domain.co/privkey.pem| -e s|^(ssl_cert =).*|\1 </etc/letsencrypt/live/sub.domain.co/fullchain.pem| /etc/dovecot/conf.d/10-ssl.conf

```

**Comment by casperklein** [comment]
On container start, some files are altered. If you restart your container (`docker-compose stop/start`), you will see these errors, because the files have already already been altered.
It's better to fully destroy the container instead: `docker-compose down && docker-compose up -d`

**Comment by jessec** [comment]
OK thanks I will close this.

**Comment by casperklein** [comment]
@docker-mailserver/maintainers I am thinking about a way, to mark, if the container is started for the first time or not. Then we could make some (sed) actions conditional and reduce (non critical) error messages.

**Comment by georglauterbach** [comment]
> @docker-mailserver/maintainers I am thinking about a way, to mark, if the container is started for the first time or not. Then we could make some (sed) actions conditional and reduce (non critical) error messages.

Good idea. I don't know the semantics of `stop / start`. Maybe create a file `/STARTED` that will be created during startup and the checked?

**Comment by NorseGaud** [comment]
> Good idea. I don't know the semantics of `stop / start`. Maybe create a file `/STARTED` that will be created during startup and the checked?

I was just going to say that 😆

**Comment by casperklein** [comment]
Yes, that's what I have in mind: `date > /CONTAINER_STARTED`

**Comment by polarathene** [comment]
In this case it's just regarding TLS configuration. If it's already configured properly due to a container restart instead, it'd probably make sense to check if the change is already applied?

That's the only reason `sedfile` would fail incorrectly right? (_which IIRC was intended to let sed fail if no change occurred, but in this case would be valid and should only fail if not already the expected output value_)

**Comment by casperklein** [comment]
These commands need to be adjusted to something like:

`[ ! -f /CONTAINER_STARTED ] && sedfile ..`

Or the file check, is put in the sedfile wrapper..

**Comment by polarathene** [comment]
> Or the file check, is put in the sedfile wrapper..

That doesn't seem like a good idea. The issue is the expected result here is already the output so sedfile fails. But that may not be the case during a restart, especially elsewhere where sedfile should still apply?

Presently the only usage of `sedfile` is in `Dockerfile`, `setup-stack.sh`(TLS section only), `delmailuser`. I don't know what impact that'd have on `delmailuser` usage.

In this case, I think it's better to probably switch back from `sedfile` to `sed` in the TLS usage. The tests should ensure that the config manipulation works correctly, my usage there only expects that sed was successful at applying a change from default configs at container startup, it should always apply though.

**Comment by casperklein** [comment]
You are right, putting it in the wrapper may not be a good idea. Especially in regards of delmailuser usage. It was just an idea not yet thought through.
