### ISSUE TITLE
554 Blacklisted [10.0.0.2]; please try again later or contact administrator

### ISSUE THREAD

**Issue by maietta** [docker-mailserver/docker-mailserver#2296]
# Subject

554 Blacklisted [10.0.0.2]; please try again later or contact administrator"

## Description

- Fresh Debian install on a VPS with a static, non-blacklisted public facing IP.
- Fresh Docker and Docker-compose 

However, sending an email from GMail to my new mail server I am getting:

554 Blacklisted [10.0.0.2]; please try again later or contact administrator

I know this is running in a containerized environment but not sure how to set this up correctly.

**Comment by casperklein** [comment]
Check your setup. There seems to be some kind of NAT in place, when the google MTA appears with that IP address.

**Comment by polarathene** [comment]
Are you running a rootless container?

**Comment by maietta** [comment]
> Are you running a rootless container?

I used root account to perform the install.

**Comment by polarathene** [comment]
You should fill out a proper bug report.

You should also try to make the issue as reproducible as possible if you want someone to invest time into troubleshooting. Ideally setup two instances of docker-mailserver and with the 2nd replacing gmail, if that still reproduces the problem it would be helpful.

**Comment by maietta** [comment]
> You should fill out a proper bug report.
> 
> You should also try to make the issue as reproducible as possible if you want someone to invest time into troubleshooting. Ideally setup two instances of docker-mailserver and with the 2nd replacing gmail, if that still reproduces the problem it would be helpful.

That's the thing-- I am using fresh install of this system on a fresh install of Debian on a standard VPS with Vultr with UFW firewall and cloud firewalls disabled.

I was looking around for a "recommended" operating system to use this with. At this point, I don't think it's a bug. Perhaps this is an edge case scenario but I get the feeling there is something I am missing in either my config but I tried my best to follow the directions.

For the record, I've been doing Linux administration since 1999 and built many email systems prior and have pretty extensive knowledge of how Docker works. It just surprised me this doesn't seem to work out of the box for me. I will eventually figure it out but I would rather make sure this is noted in the Issues in case anyone else is having the same or similar issue and perhaps someone has already ran into this before.

I am hesitant on filing a bug report just yet.

**Comment by maietta** [comment]
Hey @polarathene,

What operating systems is known to work with docker-mailserver? If I found a bug, it'd have to be with Debian if the install seems to work for everyone else.

**Comment by polarathene** [comment]
> That's the thing-- I am using fresh install of this system on a fresh install of Debian on a standard VPS with Vultr with UFW firewall and cloud firewalls disabled.

That is not reproducible, nor clear what config you're using.

We find users stating similar but often they've got different ideas of what that means. One case is ENV config, some use the example `.env` file we mention in the `docker-compose.yml` some don't use docker-compose, or deviate elsewhere, some distros have other quirks (_eg IIRC on newer Ubuntu releases the Dockerfile won't build without modifying the default systemd resolver config, due to a Debian package patch on Postfix when it installs that_).

I don't mean to question your experience, it's just usually helpful to be more explicit, especially to get further assistance when the issue is more difficult to troubleshoot.

> I was looking around for a "recommended" operating system to use this with.

I ironically am yet to properly deploy the image myself. I often contribute features and troubleshoot user issues through Vultr with the latest Ubuntu or Fedora releases on a 2GB RAM VPS if that's helpful.

I have thus far only done internal testing against the container locally on the host system, for anything requiring DNS or TLS I use CoreDNS (container) and StepCA (also container) to use a custom ACME provisioner instead of LetsEncrypt or external DNS, I test against `mail.example.test` which uses a TLD that public DNS resolvers will refuse, but my local CoreDNS resolver will handle fine.

That enables me to setup an isolated reproduction so that I don't have to deal with any external vendors that may not have relevance to the problem.

> I am hesitant on filing a bug report just yet.

That's fine, it just means there may be reluctance for others to invest time trying to investigate and reproduce.

> I will eventually figure it out but I would rather make sure this is noted in the Issues in case anyone else is having the same or similar issue and perhaps someone has already ran into this before.

If you do troubleshoot this yourself and resolve it, please do share here for others. Or if worthwhile, contribute to our docs :+1: 

---

By all means if you're able to reproduce it locally in a reliable manner, and can provide a series of steps/commands to run feel free to share them here and I can spin up a VPS instance on Vultr myself to verify.

Even if that's just the current setup where you're testing with sending an email from gmail, it'd still be helpful.

You could also run `DMS_DEBUG=1` and then look up the container logs when reproducing the problem, that should provide additional context, but you've provided us with no log output.

**Comment by maietta** [comment]
Thank you, @polarathene. I've been seeing a lot of activity over the last few weeks on this project so I'm hesitant on throwing more at y'all when the problem is likely on my end. I'm currently setting up another instance using a Ubuntu 20.10 with Docker already installed (Vultr template) and we'll see if I get anywhere more with that.

Of course, if I can contribute some good information, I will. If there is something worthy to note if I find, I'll be sure to document this.

**Comment by maietta** [comment]
Update:

After deploying another fresh instance and using the exact same config, this time switching from Debian to Ubuntu, I had no issues at all. It worked. I was able to send email from Gmail to my newly created email.

Seems that out of the box, a Debian 11 x64 system running Docker 20.10.10 is not compatible.

Ubuntu 20.10 with Docker 20.10.10 is fully functional.

**Comment by polarathene** [comment]
Thanks for sharing that finding :heart:

**Comment by maietta** [comment]
This has me thinking:

It'd be a fair bit of work, but perhaps a matrix in the docs is something we can be doing to help identify areas that might need work. At minimum, a list of distributions and docker versions known to work would suffice. As if I had enough projects already but that could be one of my first contributions to this project.

**Comment by polarathene** [comment]
> At minimum, a list of distributions and docker versions known to work would suffice.

I think that may require waiting on the test overhaul I'm slowly chipping away at. At least for a more thorough verification.

It likely would work fine on Debian, but the distro may have some quirk to be aware of. Often it's due to certain choices like the contents of `/etc/hostname` and how `/etc/hosts` should be, or differing UID and GID defaults, or `/etc/services`, etc. Sometimes it can be outdated packages or patches, or alternative OS packages. One example of the latter as mentioned before is newer versions of systemd cause build failures of the Dockerfile due to our Debian base image Postfix package patch that is affected by host network config. Older versions of Docker/docker-compose or kernels also have some compatibility issues IIRC, but these are for versions about 2 years or so ago.

When tests are overhauled, I will be doing a test matrix run with a variety of configs to help support making an internal change with more confidence.

> As if I had enough projects already but that could be one of my first contributions to this project.

You're welcome to. I think it's more valuable though to know that Debian 11 didn't work, but for the docs it'd be more helpful if it identified why and if possible how to resolve that.

Generally I don't think we get that many users running into such an issue to warrant a docs entry, other than perhaps SELinux getting in the way. And we know that Ubuntu should be fine for the most-part due to our CI running all tests on it successfully.

**Comment by casperklein** [comment]
My mail host is still on Debian 10, but my dev workstation is on Debian 11. On both, I've no problems running DMS.

Do you use a "plain" installation or a customized image from your hoster?

**Comment by maietta** [comment]
> My mail host is still on Debian 10, but my dev workstation is on Debian 11. On both, I've no problems running DMS.
> 
> Do you use a "plain" installation or a customized image from your hoster?

I used a Debian 11 pre-installed template. I did have to remove Exim which was pre-installed with the image. I then performed a Docker install per the official Linux instructions for Debian. I disabled UFW, the in-built firewall. Those were the only things I did.

So I will re-investigate this when I am back from my trip.
