### ISSUE TITLE
Some questions about tests

### ISSUE THREAD

**Issue by casperklein** [docker-mailserver/docker-mailserver#2350]
1. I see a lot of these lines `ok 240 first # skip This version natively supports setup/teardown_file`. Does this mean, the dummy tests can be removed?

2. When running the tests locally, some of them are always failing:
<details>
<summary>Details</summary>

```
 ✗ checking tls: cipher list - rsa intermediate [25151]
   (from function `assert_success' in file test/test_helper/bats-assert/src/assert.bash, line 114,
    from function `compare_cipherlist' in file test/security_tls_cipherlists.bats, line 164,
    from function `check_cipherlists' in file test/security_tls_cipherlists.bats, line 176,
    from function `check_ports' in file test/security_tls_cipherlists.bats, line 90,
    in test file test/security_tls_cipherlists.bats, line 47)
     `check_ports 'rsa' 'intermediate'' failed with status 5
   [ TASKLOG ]  mail.example.test is up and running

   -- command failed --
   status : 5
   output : jq: error (at /tmp/results/rsa/intermediate/port_25.json:14): Cannot iterate over null (null)
   --

   tls_test_cipherlists
 ✗ checking tls: cipher list - rsa modern [22107]
   (from function `assert_success' in file test/test_helper/bats-assert/src/assert.bash, line 114,
    from function `compare_cipherlist' in file test/security_tls_cipherlists.bats, line 164,
    from function `check_cipherlists' in file test/security_tls_cipherlists.bats, line 179,
    from function `check_ports' in file test/security_tls_cipherlists.bats, line 90,
    in test file test/security_tls_cipherlists.bats, line 51)
     `check_ports 'rsa' 'modern'' failed with status 5
   [ TASKLOG ]  mail.example.test is up and running

   -- command failed --
   status : 5
   output : jq: error (at /tmp/results/rsa/modern/port_25.json:14): Cannot iterate over null (null)
   --

   tls_test_cipherlists
 ✗ checking tls: cipher list - ecdsa intermediate [22167]
   (from function `assert_success' in file test/test_helper/bats-assert/src/assert.bash, line 114,
    from function `compare_cipherlist' in file test/security_tls_cipherlists.bats, line 164,
    from function `check_cipherlists' in file test/security_tls_cipherlists.bats, line 176,
    from function `check_ports' in file test/security_tls_cipherlists.bats, line 90,
    in test file test/security_tls_cipherlists.bats, line 55)
     `check_ports 'ecdsa' 'intermediate'' failed with status 5
   [ TASKLOG ]  mail.example.test is up and running

   -- command failed --
   status : 5
   output : jq: error (at /tmp/results/ecdsa/intermediate/port_25.json:14): Cannot iterate over null (null)
   --

   tls_test_cipherlists
 ✓ checking tls: cipher list - ecdsa modern [24607]
 ✗ checking tls: cipher list - ecdsa intermediate, with rsa fallback [29217]
   (from function `assert_success' in file test/test_helper/bats-assert/src/assert.bash, line 114,
    from function `compare_cipherlist' in file test/security_tls_cipherlists.bats, line 164,
    from function `check_cipherlists' in file test/security_tls_cipherlists.bats, line 176,
    from function `check_ports' in file test/security_tls_cipherlists.bats, line 90,
    in test file test/security_tls_cipherlists.bats, line 66)
     `check_ports 'ecdsa' 'intermediate' 'rsa'' failed with status 5
   [ TASKLOG ]  mail.example.test is up and running

   -- command failed --
   status : 5
   output : jq: error (at /tmp/results/ecdsa_rsa/intermediate/port_25.json:14): Cannot iterate over null (null)
   --

   tls_test_cipherlists
```

</details>

I use this to run the tests on my debian 11 host:

```bash
git clone --recurse-submodules https://github.com/docker-mailserver/docker-mailserver dms
cd dms
make all
```

Any idea, why these tests fail locally?

3. I noticed, that this tests can take some seconds to gracefully stop the containers. But if they are not being reused, it should be safe to stop them "faster" by using `docker stop -t 0` or `docker rm -f`:

https://github.com/docker-mailserver/docker-mailserver/blob/f7465a50888eef909dbfc01aff4202b9c7d8bc00/test/mail_hostname.bats#L180-L198

**Comment by polarathene** [comment]
> 1. I see a lot of these lines `ok 240 first # skip This version natively supports setup/teardown_file`. Does this mean, the dummy tests can be removed?

This was before I joined, and I think part of or before the major bats refactor into multiple test files by another contributor?

I think it's safe for us to remove them, but no immediate need right now.

> When running the tests locally, some of them are always failing

Presumably the JSON file doesn't have values for fields that `jq` attempts to check, but the JSON file itself was written... Maybe upstream `testssl` has changed something (I wish they'd release a stable version we could pin :sweat_smile: )

> Any idea, why these tests fail locally?

Not really, although Debian as a host has been the source of problems for several user issues as of late..

For those tests with `jq` the JSON files are stored in a non-standard location vs other tests, in `/tmp` I think, you should be able to review those file contents afterwards from there in case of failures. I assume the contents would make it more clear what is going wrong, and if it's an issue with upstream.

Alternatively, the location itself could be an issue if the actual JSON field wasn't possible to load. @NorseGaud had this issue I believe a while back, but running macOS. IIRC it was because it turns out I was using an internal bats var/env for the temporary location, and a newer version of bats didn't play well with that or something..

---

> I noticed, that this tests can take some seconds to gracefully stop the containers.

There was a refactor of this test in a closed PR by @NorseGaud , I reviewed it but didn't get around to extracting it to another PR. I don't think it dropped those particular tests (_of which I'm not sure what their relevance is to the hostname support_). I think they're just meant to test the 60 second timeout that the `docker-compose` example config ships with.

**Comment by casperklein** [comment]
Thank you. I had a look at `/tmp/results/rsa/intermediate/port_25.json`:

```
{
          "Invocation"  : "testssl.sh --quiet --warnings=batch --mode parallel --overwrite --preference --jsonfile-pretty port_25.json --starttls smtp example.test:25",
          "at"          : "b9aba4dd4e0c:/home/testssl/bin/openssl.Linux.x86_64",
          "version"     : "3.1dev ",
          "openssl"     : "OpenSSL 1.0.2-chacha from Jan 18 17:12:17 2019",
          "startTime"   : "1640945987",
          "scanResult"  : [
                            {
                                "id"           : "scanProblem",
                                "severity"     : "FATAL",
                                "finding"      : "Can't connect to '172.21.0.2:25' Make sure a firewall is not between you and your scanning target!"
                           }          ],
                    "scanTime"  : "Scan interrupted"
}
```

There is no firewall in place. I will investigate further next year.

**Comment by casperklein** [comment]
It's a timing issue. If I add "sleep 10" after `wait_for_finished_setup_in_container`, the tests pass.

I think, `wait_for_finished_setup_in_container` does not work properly. It checks for the string `is up and running`. However, this does not guarantee, that postfix is fully started yet.
