### ISSUE TITLE
Dovecot Errors in Logwatch

### ISSUE THREAD

**Issue by mindrunner** [docker-mailserver/docker-mailserver#2355]
I am seeing the following errors on one of my instances. Is that something to worry about?

``` BASH
 --------------------- Dovecot Begin ------------------------ 

 
 Dovecot Errors:
    auth: Error: passwd-file /etc/dovecot/userdb: User xxx@yyy.de exists more than once: 58 Time(s)
    auth: Error: passwd-file /etc/dovecot/userdb: User aaa@zzz.de exists more than once: 58 Time(s)
    auth: Error: passwd-file /etc/dovecot/userdb: User ggg@zzz.de exists more than once: 58 Time(s)
    auth: Error: passwd-file /etc/dovecot/userdb: User hhh@yyy.de exists more than once: 58 Time(s)
    auth: Error: passwd-file /etc/dovecot/userdb: User hhh@yyy.de exists more than once: 58 Time(s)
    auth: Error: passwd-file /etc/dovecot/userdb: User hhh@zzz.de exists more than once: 58 Time(s)
    auth: Error: passwd-file /etc/dovecot/userdb: User hhh@ddd.de exists more than once: 58 Time(s)

```

**Comment by georglauterbach** [comment]
This does not look right. What are the contents of the file? Aliases come to mind first to me, as I wrote a PR that "injects" aliases into the file, but injecting more than once should not be happening... especially not 58 times.

**Comment by mindrunner** [comment]
I do have double entries there. same addresses pointing to different maildirs. Not 58 items, though. 

postfix-aliases is empty, but postfix-virtual has a catch-all setup on multiple domains into one single mailbox. not sure if that needs some rework.

Is the userdb file created from scratch on every restart?

**Comment by polarathene** [comment]
> Is the userdb file created from scratch on every restart?

Yes:

https://github.com/docker-mailserver/docker-mailserver/blob/9bcc3df74ab3d9a459707301bb1532da0a061be7/target/scripts/helpers/accounts.sh#L8-L11

>  but postfix-virtual has a catch-all setup on multiple domains into one single mailbox. not sure if that needs some rework.

That is the file that creates dummy accounts for Dovecot as a semi-workaround to spammer abuse of backscatter. Although this is only a concern when Dovecot quotas are used/configured AFAIK.

Added here:

https://github.com/docker-mailserver/docker-mailserver/blob/9bcc3df74ab3d9a459707301bb1532da0a061be7/target/scripts/helpers/accounts.sh#L141-L143

**Comment by mindrunner** [comment]
Alright. I suspect `ENABLE_QUOTAS` to be a fairly new parameter. It was unset in my case. Setting it to `0` and restarting the mailserver makes the `userdb` file looking way cleaner. 

Do we want to investigate further? For me personally, this is fine. However, the behavior might not be expected.

**Comment by polarathene** [comment]
> I suspect `ENABLE_QUOTAS` to be a fairly new parameter.

No, [it's been around since May 2020](https://github.com/docker-mailserver/docker-mailserver/commit/0c838706d0b472a94493986616ab9018e6fc8daa) (_full history [detailed here](https://github.com/docker-mailserver/docker-mailserver/pull/2248#issuecomment-954274526)_). Always been defaulted to `1` / enabled internally, and in the [example `mailserver.env` file since April 2021](https://github.com/docker-mailserver/docker-mailserver/pull/1931).

---

> Do we want to investigate further? For me personally, this is fine. However, the behavior might not be expected.

Without more information from you to reproduce the issue, it's difficult for us to troubleshoot.

I thought we had this documented better, but it seems the only mention about `ENABLE_QUOTAS` and the dummy account generation for aliases is in the [`10.3.0` release notes](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v10.3.0)..

It's likely that you have a config that doesn't play around with the workaround. If you don't need to use quotas, it's fine to disable. There was some talk I think about changing the default to disabled.
