### ISSUE TITLE
LDAP - mail pulled from user folder but mail delivered to domain/user folder

### ISSUE THREAD

**Issue by nathanielread** [docker-mailserver/docker-mailserver#2371]
I have LDAP setup with osixia/openldap. Users are authenticated correctly to imap and smtp using the username. But, when I send mail within the domain, the mail is delivered to the /var/mail/domain/user folder while mail is checked at the /var/mail/user folder. 
When I delete the folders, the user folder is created when checking mail and the domain/user folder is created when I send a mail.

I tried to set the mail_location by doing:
- $DOCKERDIR/appdata/mailserver/docker-data/dms/dovecot/10-mail.conf:/etc/dovecot/10-mail.conf

I have it set in:
mail_location = maildir:/var/mail/%n

But, that doesn't work, so I'm confused as to what I need to override either in environment variables or some config to get mail picked up and delivered to the same location.

Hopefully I'm missing something easy in my ignorance and I appreciate any help. I've sent a decent amount of time getting this all working and really don't want to give up.

Please let me know what else is needed.

relevant docker-compose.yml section (I could get SASLAUTHD to work, so I disabled it):

``` BASH
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    networks:
      mail_proxy:
        ipv4_address: $MAILSERVER_IP
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    domainname: $DOMAINNAME
    hostname: mail
    # env_file: $DOCKERDIR/appdata/mailserver/mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - $DOCKERDIR/appdata/mailserver/docker-data/dms/mail-data/:/var/mail/
      - $DOCKERDIR/appdata/mailserver/docker-data/dms/mail-state/:/var/mail-state/
      - $DOCKERDIR/appdata/mailserver/docker-data/dms/mail-logs/:/var/log/mail/
      - $DOCKERDIR/appdata/mailserver/docker-data/dms/config/:/tmp/docker-mailserver/
      - $DOCKERDIR/appdata/mailserver/docker-data/dms/etc/fail2ban/:/etc/fail2ban/
      - $DOCKERDIR/appdata/mailserver/docker-data/dms/dovecot/10-mail.conf:/etc/dovecot/10-mail.conf
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/traefik2/acme/acme.json:/etc/letsencrypt/acme.json:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ONE_DIR=1
      - DMS_DEBUG=1
      - ENABLE_LDAP=1
      - LDAP_START_TLS=no
      - LDAP_SERVER_HOST=192.168.92.55
      - LDAP_SEARCH_BASE=$LDAP_SEARCH_BASE
      - LDAP_BIND_DN=$LDAP_BIND_DN
      - LDAP_BIND_PW=$LDAP_ADMIN_PASSWORD
      - LDAP_QUERY_FILTER_USER=(&(mail=%s)(mailEnabled=TRUE))
      - LDAP_QUERY_FILTER_GROUP=(&(mailGroupMember=%s)(mailEnabled=TRUE))
      - LDAP_QUERY_FILTER_ALIAS=(|(&(mailAlias=%s)(objectClass=PostfixBookMailForward))(&(mailAlias=%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE)))
      - LDAP_QUERY_FILTER_DOMAIN=(|(&(mail=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailGroupMember=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailalias=*@%s)(objectClass=PostfixBookMailForward)))
      - DOVECOT_PASS_FILTER=(&(objectClass=PostfixBookMailAccount)(uid=%n))
      - DOVECOT_USER_FILTER=(&(objectClass=PostfixBookMailAccount)(uid=%n))
      # - DOVECOT_PASS_FILTER=(&(objectClass=inetOrgPerson)(uid=%n))
      # - DOVECOT_USER_FILTER=(&(objectClass=inetOrgPerson)(uid=%n))
      - DOVECOT_TLS=no
      - DOVECOT_AUTH_BIND=yes
      - DOVECOT_USER_ATTRS=homeDirectory=home,=uid=5000,=gid=5000,mailStorageDirectory=mail/%n
      - ENABLE_SASLAUTHD=0
      # - SASLAUTHD_MECHANISMS=ldap
      # - SASLAUTHD_LDAP_SERVER=ldap
      # - SASLAUTHD_LDAP_START_TLS=no
      # - SASLAUTHD_LDAP_BIND_DN=$LDAP_BIND_DN
      # - SASLAUTHD_LDAP_PASSWORD=$LDAP_ADMIN_PASSWORD
      # - SASLAUTHD_LDAP_SEARCH_BASE=$LDAP_SEARCH_BASE
      # - SASLAUTHD_LDAP_FILTER=(&(objectClass=PostfixBookMailAccount)(uid=%n))
      # - SASLAUTHD_LDAP_PASSWORD_ATTR=userPassword
      # - SASLAUTHD_LDAP_AUTH_METHOD=fastbind
      # - SASLAUTHD_LDAP_MECH=DIGEST_MD5
      # - SASLAUTHD_LDAP_FILTER=(&(uid=%U)(objectClass=inetOrgPerson))
      # - SASLAUTHD_LDAP_FILTER=(&(objectClass=inetOrgPerson)(mail=%u)
      - POSTMASTER_ADDRESS=$POSTMASTER_ADDRESS
      - POSTFIX_MESSAGE_SIZE_LIMIT=100000000
      - SSL_TYPE=letsencrypt
      - LOGROTATE_INTERVAL=daily
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

```

Non-comment sections of 10-mail.conf:

```
mail_location = maildir:/var/mail/%n
namespace inbox {
  inbox = yes
}

mail_privileged_group = docker
mail_plugins = $mail_plugins
maildir_stat_dirs = yes
```

**Comment by polarathene** [comment]
Just chiming in since you haven't received a response for a while.

None of the maintainers here use LDAP afaik, so our ability to support that is low. Those with LDAP knowledge sometimes contribute when they run into problems like this to try fix them, but that's sometimes difficult (as one of the open PRs related to LDAP is stalled by).

Regarding `mail_location` adjustment, often config files for services are modified by the setup scripts at container startup. A quick search for `mail_location` reveals that too is configured [here](https://github.com/docker-mailserver/docker-mailserver/blob/da17e8bf0bd68531f7b14602a7792e8477813f6f/target/scripts/startup/setup-stack.sh#L197-L213). So that's probably overriding what change you tried to make on the config file directly.

It is by default ignoring whatever value is already there and applying: `mail_location = maildir:\/var\/mail\/%d\/%n` (`maildir:/var/mail/%d/%n` after escaping). So you'd need to make a change after this.

Using `user-patches.sh` (see [our docs page](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/user-patches/) and related [FAQ entry](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script)) is the usual advice for these sorts of workarounds without someone contributing a fix/improvement. You should be able to re-use that same line to make the change you want (just removing the `%d` directory):

```bash
#! /bin/bash

# Some comment about what you're wanting to achieve, eg: Workaround for LDAP mail location
sed -i -e 's|^mail_location = .*$|mail_location = maildir:\/var\/mail\/%n|g' /etc/dovecot/conf.d/10-mail.conf

# That's it, nothing else needed in this file! :)
```

Hope that helps!

**Comment by nathanielread** [comment]
@polarathene Thank you. I'll take a look at all of this in the next few days and see what I can come up with! 
If I figure something out, I'll post my solution.

**Comment by freundTech** [comment]
I've just run into the same problem and noticed that it doesn't occur if you log into dovecot using your full email instead of just username.

Change 
`DOVECOT_PASS_FILTER` and `DOVECOT_USER_FILTER` to `(&(objectClass=PostfixBookMailAccount)(mail=%n))`, then change your email client to use your email address as IMAP login name.

This makes dovecot pull mail from the correct folder.


I'm still looking into finding a solution that let's users login using their username.
