### ISSUE TITLE
Nextcloud AIO - Built-in Mail Server

### ISSUE THREAD

**Issue by R7JANV1** [docker-mailserver/docker-mailserver#2480]
# Feature Request

### Is your Feature Request related to a Problem?
no

### Describe the Solution you'd like
Help with programming for the extension of the docker-mailserver for Nextcloud AIO.

### What are you going to contribute??
With everything I can help.

### Context and discussion at Nextcloud AIO
[Built-in Mail Server #68 ](https://github.com/nextcloud/all-in-one/issues/68)

### Alternatives you've considered
Setting up the mail server manually, but this is not very user-friendly and will not find so many users, as the concept of Nextcloud AIO is also to be: user-friendly and simple.

### Who will that Feature be useful to?
For all Nextcloud users but also for all docker mailserver users to set up a mailserver in an easy and userfriendly way.

### What have you done already?
helped to find a solution for the implementation of this extension, because there is a large range of interested parties.

**Comment by polarathene** [comment]
Have you tried setting up `docker-mailserver` yourself yet?

There is only so much you can assist with to make it easier. The user will still need to configure their DNS with the appropriate records, their server needs to not have the mail ports blocked, etc.

There is LDAP support that you could leverage (but is not in as good shape as no maintainer uses LDAP, there is some issues with it), provided your service manages users with LDAP.

Otherwise, there is a separate API project in our organization focused on creating a web API to manage some parts such as user passwords, I'm not sure if they've added user account management on top of that, so you may need to contribute there if that's what you want instead of managing the shell commands our main project uses.

If you only need to send e-mail and not receive it, that should be lighter-weight and you may be better suited with other projects rather than a full-fledged mail-server. Often you can leverage a mail relay service like SendGrid, which offers APIs you could integrate, and free tiers if mail sent out each month is low, integrating with that would probably be easier?
