### ISSUE TITLE
Please Reopen Issue 1138

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [docker-mailserver/docker-mailserver#2514]
> Closing due to no response, please reopen or resubmit if the problem persists.

Please reopen. I was able to fix it with manual change of the main.cf to:

![image](https://user-images.githubusercontent.com/17781278/160349417-534d1479-729f-49c6-933e-368263ad92cf.png)

If that would be fixable in within the compose.yaml or the .env it would be nice.

_Originally posted by @MrLoverLoverMMMM in https://github.com/docker-mailserver/docker-mailserver/issues/1138#issuecomment-1080300494_

**Comment by polarathene** [comment]
You were not involved in the original issue there. A lot has changed since 2019.

For your `compose.yaml` file, remove any `domainname` field, only use `hostname` field with full FQDN.

---

Please file a new bug report if you believe there is a bug to fix (_referencing the old one is fine, but you need provide more info about your setup and problem_), without context it's possible that it's a misconfiguration / misunderstanding on your end.
