### ISSUE TITLE
[FR] setting fetchmail --daemon parameter separately

### ISSUE THREAD

**Issue by tinkernels** [docker-mailserver/docker-mailserver#2567]
# Feature Request

## Context

When `FETCHMAIL_PARALLEL=1`, fetchmailrc will be split and multiple instances will be run. If we want to pass different `--daemon` parameter to fetchmail instances, we should make some change.

### Is your Feature Request related to a Problem?

No.

### Describe the Solution you'd like

With a minimal change to achive.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute?

Code and docs updating.

### Alternatives you've considered

None.

### Who will that Feature be useful to?

Who has `FETCHMAIL_PARALLEL=1` in env.

### What have you done already?

Obtain the `--daemon` parameter from comment lines in fetchmailrc.

**Comment by reneploetz** [comment]
I don't mind the change, but I wonder whether there is a specific reason that you cannot use the "interval" configuration setting for fetchmail and have each configuration use multiples of the same fetch interval?

**Comment by tinkernels** [comment]
> I don't mind the change, but I wonder whether there is a specific reason that you cannot use the "interval" configuration setting for fetchmail and have each configuration use multiples of the same fetch interval?
> 
> For example you could set the poll interval to "60" and use e.g. "interval 2" and "interval 3" to fetch individual configurations every 120 or 180 seconds.

@reneploetz , I don't have a such reason to use the present implement, but just the idea of replacing the value came up firstly.

I'm using `1` as `--daemon` parameter when configuring imap section. If I want to pass the value of `120`, `1`, `120` separately, refer to your example, the setting of `FETCHMAIL_POLL` would become useless.

**Comment by reneploetz** [comment]
Yeah I think I understand - you probably want to reconnect to use IMAP idle immediately after disconnect, hence the "1" as FETCHMAIL_POLL. This setting specifically determines the amount of waiting time between connections to the mail server.

In IMAP idle cases the FETCHMAIL_POLL setting does not influence the waiting time between idle loops if there is no termination of the underlying server connection. It affects only the time to wait for the reconnect of the server connection. Which usually means you can get multiple idle loops per connect loop. Depending on your mail provider server disconnects should happen infrequently every XX hours or days, but who knows :)

Anyway, the problem I can see with this specific setting of "1" for FETCHMAIL_POLL and e.g. "interval 120" for some non-idle accounts (to fetch every 2 minutes) is that fetchmail would wake up every second and write to log that it would wait until those 120 seconds passed. Which then would be rather spammy / unnecessary.

I would probably suggest against using "1" as the setting even for IMAP idle due to the fact that you would try to connect every second even if that try fails, thus potentially hammering the server. But I can see the usecase now, thanks.

**Comment by tinkernels** [comment]
Since it seems a very rare usage, close now.
