### ISSUE TITLE
DKIM and mail with empty body

### ISSUE THREAD

**Issue by mholti** [docker-mailserver/docker-mailserver#2585]
# Subject
I would like some feedback concerning a use case

## Description
Hi all,
I just setup DKIM for my server and it's working fine.
One thing i saw during tests:
I send a test-mail with no/empty body, just a subject and DKIM-check failed on the receivers side.
Is this expected or shall i fill a bugreport?

Thanks for the good work!!!
Michael

**Comment by georglauterbach** [comment]
> Is this expected

No, DKIM should pass.

> shall i fill a bugreport?

No, because this is most likely not a bug on our side but a misconfiguration somewhere in your infrastructure or the infrastructure you're using. **If** you are really certain this is a bug in DMS (which is highly doubt), then open another issue, but I highly recommend double and triple checking your setup.

**Comment by mholti** [comment]
It's a problem on receiver-side. When i send a mail with empty body to my gmail-account all is OK. When i send it to my work-adr., the mail-gateway complains about DKIM not to be OK.
Thanks for the fast answer, i'll close this
