### ISSUE TITLE
Postfix and dovecot killed by supervisor on each mail creation

### ISSUE THREAD

**Issue by abstract-entity** [docker-mailserver/docker-mailserver#2613]
# Postfix and dovecot killed by supervisor on each mail creation

I would like some feedback concerning a use case

## Description

Hello,

Each time i create an user, i can see in logs postfix and dovecot restarting ! 

``` BASH
addmailuser -y toto@toto.com password
```

Containers logs:
``` BASH
Jun  1 08:40:31 feature-mail postfix/master[29611]: terminating on signal 15
Jun  1 08:40:33 feature-mail dovecot: master: Warning: Killed with signal 15 (by pid=7 uid=0 code=kill)
Jun  1 08:40:34 feature-mail dovecot: master: Dovecot v2.3.13 (89f716dc2) starting up for imap, lmtp
Jun  1 08:40:37 feature-mail postfix/master[2385]: daemon started -- version 3.5.6, configuration /etc/postfix
```

changedetector logs: 
``` BASH
[   INF   ]  2022-06-01 08:40:21  Change detected
postfix: stopped
postfix: started
dovecot: stopped
dovecot: started
```

Is this normal? is there an impact on the reception of emails?

**Comment by polarathene** [comment]
Do you plan on adding accounts frequently? (eg: more than once every minute?)

Otherwise there shouldn't be anything to worry about. Change detection support watches config and certificate files for changes in content. If it notices a change, it reprocesses them and restarts Postfix and Dovecot to apply the changes.

In some cases they could probably just use their reload commands. I am working on improving the change detection support, but it might be a while before it's much smarter.

---

> Is this normal?

Yes it's normal. Adding an account updates the config file `postfix-accounts.cf` which is where each account is stored. During startup of the container or when processing changes, that file is read and accounts regenerated (the mail storage is left as-is).

> is there an impact on the reception of emails?

Potentially an issue I think if receiving or sending an email that's being worked on to arrive in the users mail account or send out, sometime there's a bit of a delay from completing those actions (eg sitting in a queue). In a spam test we have I noticed it took around 30 seconds to store after receiving it (it was queued and Amavis didn't process it until about 30 seconds later).

Outside of that window, when Postfix is down and starting back up, an e-mail could arrive and not be delivered, but the service sending the mail is likely to try again not too long afterwards, so it should arrive again. Postfix also is aware of mail it has not successfully sent AFAIK, and will attempt again.

So I think it's unlikely from what I know and understand :sweat_smile: the downtime with change detection shouldn't be too long :)

---

For context this is what is happening, it does log a message for context, but it currently only shows with a more verbose `LOG_LEVEL` set:

https://github.com/docker-mailserver/docker-mailserver/blob/3b4f44e8377598eaa03b88c907dbb9e2f70332ac/target/scripts/check-for-changes.sh#L125-L130

**Comment by polarathene** [comment]
I don't know if our change detection service would cause problems if it's frequently activated, you'd need to investigate that and try identify a reproduction of the issue for one of the volunteers here to be able to try fix it.

For your use-case, I guess you would add the email and then maybe wait on your end for a duration before sending, so that you know the change detection has restarted Postfix to receive a new email to send out.

However since you could have some overlap there with multiple emails being added in a burst, you'd probably want to have your own little service that you route such activity through to manage the interaction with adding email accounts and keeping track when it's ok to send mail (or have the service send the mail itself). This way it could queue up accounts to add, sort of like a buffer and hold off while waiting on Postfix to restart, send some mail, wait a bit, then add the new accounts and repeat?

That should allow it to be more reliable if it is indeed causing an issue for your delivery reliability. When I can investigate what (if anything) requires restarting the services instead of reloading for config changes, if nothing actually requires that, then we can switch to reloading instead which would be much faster and should have no downtime AFAIK.

**Comment by georglauterbach** [comment]
This really isn't something we can easily solve right now; I am very sorry. I will remove the milestone because I am preparing the release of v12.0.0, and this is not relevant to the release.

**Comment by polarathene** [comment]
> This really isn't something we can easily solve right now

This was some of the first changes I brought in for v12. We use `reload` now.

The issue of Postfix and Dovecot being killed to restart during the change detection should no longer be an issue.

There will still be some downtime involved AFAIK, and each change event to the user accounts file will cause Dovecot to rebuild it's own user DBs. So it's not a perfect fix, but the problem experienced should be reduced.

Future steps would involve:
- Smarter change detection trigger by debouncing (_waiting for change activity to settle_) + throttle (_to ensure changes are processed within a certain window, not delayed forever_).
- Smarter handling of user account changes, so that Dovecot doesn't take a brute force approach of recreating it's own user DBs for a single user change.

**Comment by polarathene** [comment]
Closing as v12 released. Issue should be less severe, but it would be good to know if anyone finds it problematic still.
