### ISSUE TITLE
E-mails via STMP server are marked as spam.

### ISSUE THREAD

**Issue by Skyfay** [docker-mailserver/docker-mailserver#2614]
Hello, everyone. I configured the mail server and everything worked as it should.
Now the problem I have is that the e-mails end up in spam via the SMTP server.
I've tried Google and Microsoft.
https://www.mail-tester.com/ tells me i got a 10/10.
Do you have any tips on how I could solve this?
Domain is a .ch domain.
Google:
This message seems dangerous
The sender's email address contains unusual characters that may have been used to spoof the real address. Try not to click links, download attachments, or reply to this message.

**Comment by georglauterbach** [comment]
I think Google serves you better in this case. This is the issue section, where problems or enhancements for DMS are discussed.

I‘d encourage you to search the this repository‘s discussions or try to find the answer in the depths of the web, this is not quite the right place :)

**Comment by Skyfay** [comment]
> I‘d encourage you to search this repository‘s discussions or try to find the answer in the depths of the web, this is not quite the right place :)

If I hadn't already done that, I wouldn't be here ;)

**Comment by polarathene** [comment]
Some TLD are apparently less trustworthy.

You have not shared what the sender address was, but a message from Google that says it contained "unusual" characters. You might want to consider what that may be, perhaps you have characters that are not `a-z`, `A-Z`, `0-9`? Whatever that is, that's not something we control, it's something you do for a sender address, and that spam policy is Googles, nothing we have influence over.

Do note that even if you do everything properly, you still may have delivery issues due to sender reputation, which is often why it can be helpful to route your mail through an SMTP relay service. Those often have a free tier, so you could try that first and see if it is still marked as spam.

You'd probably have better luck asking broader communities with larger audiences of experienced users... if you have been searching the web, then you'd surely have come across these (eg: `serverfault.com`).

**Comment by Skyfay** [comment]
The problem is that is sending the same email with two mail servers. Once with one from the provider Infomaniak and once with my own. It works with Infomaniak, but it's declared as spam for my server.
So I thought there must be a context.

**Comment by polarathene** [comment]
> So I thought there must be a context.

Probably as said above with sender reputation (not the sender address, but the MTA doing the sending, hence why relay services are popular).

If you suspect it's something different, with Gmail web app, you can view both mails and go to the options to view the raw mail. Then compare between them to look if there's anything Infomaniak is doing differently. If there's no notable differences, then it's likely something like sender reputation.

**Comment by gottlike** [comment]
You can also try sending mail to this free tool, to check for the most common issues: https://www.mailgenius.com

**Comment by Skyfay** [comment]
> You can also try sending mail to this free tool, to check for the most common issues: https://www.mailgenius.com

![image](https://user-images.githubusercontent.com/76796007/175223606-5d17d7a0-bd4b-439a-b742-b49081e53eef.jpeg)

**Comment by gottlike** [comment]
Try to get to a score of 100. But apart from that you have to warm up the IP, see https://webhelp.optimizely.com/latest/en/campaign/basics/ip-warmup.htm (it's for Optimizely but the advice is valid for all senders).

**Comment by gottlike** [comment]
Or just use Amazon SES, it's very cheap and works well once you make sure to have a MailGenius score of 100.
