### ISSUE TITLE
[FR] Improve privacy of Message-ID header by replacing the hostname

### ISSUE THREAD

**Issue by caspervk** [docker-mailserver/docker-mailserver#2660]
# Feature Request
The `Message-ID` header of sent emails can contain the hostname of the sending device. As an example, sending an email from [kmail](https://apps.kde.org/kmail2/) results in the header `<5248487.62w6kYTQhz@my-host>`, where `my-host` is the hostname of my local computer.

Personally, before migrating my bare-metal postfix installation to docker-mailserver, I was using the following regex for a long time, though I am not sure if it is optimised:
```
/^Message-ID.*?<(.*)@.*/ REPLACE Message-ID: <$1@mail.example.com>
```
This regex should be added to the [pre-existing list of header rewrites](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/postfix/sender_header_filter.pcre).

### Is your Feature Request related to a Problem?
It is if you consider a minor privacy leak a problem.

### Describe the Solution you'd like
I would like for docker-mailserver to mask my local hostname, possibly by a regex similar to the one outlined above.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it. However, I am not sure what the default value for the hostname should be, as it (probably) cannot be hard-coded like the regex above.

### What are you going to contribute??
A PR if a regular contributor comments that the above solution is sufficient.

### Alternatives you've considered
You could mount a custom `sender_header_filter.pcre` into the container, but it's not a good solution, and I feel like it should be solved upstream for everyone.

### Who will that Feature be useful to?
Everyone who values privacy.

### What have you done already?
Identified the problem.

**Comment by polarathene** [comment]
Just to clarify, you only want to alter the domain-part of the `Message-ID` value?

From what I understand below, removing the header seems like it'd be ok? At least for outgoing mail. I haven't looked much into this Postfix feature and our implementation. Rewriting `Message-ID` for inbound mail to be delivered to Dovecot would presumably treat all mail to the same domain-part, even when that mail isn't from your accounts?

---

According to [this discussion](https://serverfault.com/questions/335988/is-it-possible-to-change-the-postfix-message-id) (same pattern suggested), if the `Message-ID` is removed, Postfix would add it back with the configured hostname appended. Since you want to modify it already, I assume there would not be any difference, but at least by removing `Message-ID` it'd be simpler and append the desired hostname?

My understanding of this header is it primarily serves for debugging and for mail clients threaded views of responses. I don't know if that'll impact the client originally writing the `Message-ID` with it's local copy and later responses received? (_You'd probably know the answer to that from experience?_)

If that's a non-issue, then I assume it doesn't matter when there's different senders with their own hostnames and on Postfix end when email domain-part is not the same as what Postfix has for it's hostname (_eg: `docker-mailserver` has the DNS record `mail.example.com`, and is authorized by `not-example.com` DNS records to send on it's behalf, despite the `Message-ID` getting `@mail.example.com`?_).

Some mail clients like GMail sign with headers it sends, and [this was known to cause problems with `docker-mailserver` removing headers](https://github.com/docker-mailserver/docker-mailserver/issues/1575) when relaying to another client that failed verification of DKIM because of the missing headers.

---

For reference if anyone is curious :sweat_smile: 

- [Message-ID info](https://stackoverflow.com/questions/68504201/what-is-the-use-of-message-id-in-email) 
- [Postfix `header_checks`](https://www.postfix.org/header_checks.5.html) (_[PR that added support + config](https://github.com/docker-mailserver/docker-mailserver/pull/708/files#diff-382e37a673d41779bffd7dfe054feb345c1f3e5f7121698f2a52e7e5322c7169R82) to `docker-mailserver`, `smtp_header_checks` also configured_)
- [Previous discussion on headers to remove for privacy](https://github.com/docker-mailserver/docker-mailserver/issues/681) (2017, issue for the `header_checks` PR)
- Unresolved issue for [improving privacy from container senders instead of mail clients](https://github.com/docker-mailserver/docker-mailserver/issues/1981#issuecomment-863582424). Maintainer decision to contribute to docs instead, or ensure only outgoing mail had headers stripped.

**Comment by georglauterbach** [comment]
Another possible solution is to add this rewrite to the Postfix configuration file via `user-patches.sh` if we do not want to add it to the default configuration. Then document it and that‘d be fine with me too.

**Comment by caspervk** [comment]
I'm sorry, but I don't know enough about this project (and emailing in general) to decide what the best way to implement this is going to be. It seems to me that adding it to `sender_header_filter.pcre`, so that it is simply removed, is the simplest course of action? Thanks a lot for the discussion, @polarathene! A lot of good information!

**Comment by polarathene** [comment]
> It seems to me that adding `Message-ID IGNORE` to `sender_header_filter.pcre`, so that it is simply removed, is the simplest course of action?

It would seem for now there is no strong demand for it and only the additional information I dug up regarding the feature request.

The current decision appears to be that this should be deferred to `user-patches.sh` for the time being. If you'd like to help others wanting the same feature, we'd appreciate you sharing your `user-patches.sh` script here, or contributing it to our docs.

I lack the time to investigate further, so without additional users requesting this or the support for it from other maintainers/contributors, it's unlikely a PR to implement it for everyone by default is going to get approved.

---

If you find another popular mail self-host project (_eg: `mail-in-a-box`, `mailcow`, `mailu` all use Postfix_) that does implement it, please reference that and that would greatly support approval. Some of those projects use `rspamd` instead of `SpamAssassin` which sometimes also handles this kind of thing instead of Postfix.

**Comment by caspervk** [comment]
Thanks for another well-written response! Closing for now then.
