### ISSUE TITLE
Port 25 External Access

### ISSUE THREAD

**Issue by robbalmbra** [docker-mailserver/docker-mailserver#2683]
I'm having a slight issue whereby externally port 25 can be used to send the configured mail domain to another user within the mail domain without any authentication. Such as sending an email from test@test.com to test2@test.com. How can this be remediated?

Any ideas are greatly appreciated.

**Comment by georglauterbach** [comment]
This should definitely **not** be happening! Please first use <https://mxtoolbox.com/diagnostic.aspx> to check your mail server to see whether it is an open relay. If it is, I'd immediately withdraw it from the internet and fix the Postfix configuration. Do you adjust Postfix's configuration (`main.cf`) in any way?

**Comment by polarathene** [comment]
> Without any authentication

I don't believe any authentication is required for inbound mail on port 25? The sender can claim to be from another use of your mail domain, and will be delivered if it passes any checks in place such as SPF / DKIM / DMARC.

In the SPF example, that would require the record to authorize the sending MTA otherwise it should reject the mail.

Mail submission (outbound) is different, and does require you to authenticate to send mail to another MTA.

---

Please provide more information about your setup and how you are reproducing this.
