### ISSUE TITLE
SpamAssassin local DNS lookups

### ISSUE THREAD

**Issue by frugan-it** [docker-mailserver/docker-mailserver#2697]
# Subject

I would like some feedback concerning a use case

## Description

I am finding that some mails are marked as spam despite being legitimate.
The SA tags present in the mail headers are:

```
URIBL_DBL_SPAM
URIBL_BLOCKED
```

Searching a bit on the net, SA seems to recommend running your own local, caching, resolving (not forwarding) DNS.
Here they talk about it:

https://cwiki.apache.org/confluence/display/SPAMASSASSIN/CachingNameserver
https://users.spamassassin.apache.narkive.com/k2QOaYoV/why-do-i-get-both-uribl-dbl-spam-and-uribl-blocked

I looked for the `dns_available` directive inside this repo, but i didn't find anything, so i assume it's not supported yet.

I wanted to know if anyone has already addressed this issue, or if they have advice on how to implement it.

**Comment by georglauterbach** [comment]
A funny coincidence that this issue is opened now, as my last major adjustments to my own mail server where DNS related, and I did it threee times, to get it somewhat right.

---

Here is what I found:

1. When you're running your own mail server and want to use advanced spam filtering, you certainly also want to have your own DNS server, this is probably the most important finding
2. You will need a reasonably fast DNS server
3. It is possible and actually quite nice to "split" the DNS traffic, this is what I currently do, and it works just fine. Here is what and why.

Spam filtering tools like SA, but also Postfix/Postscreen using DNSBLs, _require_ a **non-official**, **recursive** DNS resolver. If you try to use official DNS servers (`1.1.1.1`, `9.9.9.9.`, etc.), you'll find that the answers to your queries are

1. at best, meaningless
2. at worst, classifying legit mails as spam if Postfix for example is not configured correctly

So, I figured: why not resolve the traffic to SpamHaus, Sorbs, DNSWL, SpamEatingMonkey etc. on my own and use official DNS servers for all the other DNS traffic.

I am running Kubernetes, and the cluster-wide DNS server is CoreDNS. It will forward normal DNS traffic to official DNS servers and special, "Spam-Analysis-DNS-traffic" to a container running Bind9 that I created myself (and I will shamelessly promote it myself :D, see [`georglauterbach/k8s-dns`](https://github.com/georglauterbach/k8s-dns)) and which resolves recursively. This seems to work flawlessly. In the `README` of `k8s-dns` you'll find exactly this use case.

**Comment by frugan-it** [comment]
Thanks @georglauterbach , happy to know that sometimes favorable coincidences also happen!
Congratulations on the `k8s-dns` project! It seems to be just what I was looking for.. 
Unfortunately, however, I am not an expert in K8s, nor in DNS, so I will certainly have something to study this summer..

For now it is not very clear to me how to integrate k8s-dns with DMS, I ask you too much to give me an example with `docker-compose.yml` ?

**Comment by polarathene** [comment]
CoreDNS is not too difficult to configure, I can :+1: that choice. I have a [basic example detailed here](https://github.com/docker-mailserver/docker-mailserver/issues/2601#issuecomment-1135520225).

**Comment by georglauterbach** [comment]
> CoreDNS is not too difficult to configure, I can :+1: that choice. I have a [basic example detailed here](https://github.com/docker-mailserver/docker-mailserver/issues/2601#issuecomment-1135520225).

Indeed :D 

And `k8s-dns` is dead simple to configure. It is essentially Bind9 (a DNS server) in a container. You can mount your own Bind9 configuration into the container and query on port 8053, nothing fancy. The default configuration should be a good starting point, and the README should also provide you with another configuration example for CoreDNS.

**Comment by frugan-it** [comment]
Thanks @georglauterbach and @polarathene , I have looked more closely at the examples you have pointed out to me.

What was not clear to me was the link between DMS and the DNS container.
Correct me if I'm wrong, in practice the link is determined more or less like this?

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    dns: <HOST-IPV4-ADDRESS>
    ...

  k8s-dns:
    image: docker.io/andevour/k8s-dns:latest
    ports:
      #https://forums.docker.com/t/dns-issues-with-local-resolver-and-containers-on-the-same-host/102319/4
      - "<HOST-IPV4-ADDRESS>:53:8053/udp"
      - "<HOST-IPV4-ADDRESS>:53:8053/tcp"
    ...
```

PS, how cool CoreDNS! I did not know it..

**Comment by georglauterbach** [comment]
> Thanks @georglauterbach and @polarathene , I have looked more closely at the examples you have pointed out to me.
> 
> 
> 
> What was not clear to me was the link between DMS and the DNS container.
> 
> Correct me if I'm wrong, in practice the link is determined more or less like this?
> 
> 
> 
> ```yml
> 
> services:
> 
>   mailserver:
> 
>     image: docker.io/mailserver/docker-mailserver:latest
> 
>     dns: <HOST-IPV4-ADDRESS>
> 
>     ...
> 
> 
> 
>   k8s-dns:
> 
>     image: docker.io/andevour/k8s-dns:latest
> 
>     ports:
> 
>       #https://forums.docker.com/t/dns-issues-with-local-resolver-and-containers-on-the-same-host/102319/4
> 
>       - "<HOST-IPV4-ADDRESS>:53:8053/udp"
> 
>       - "<HOST-IPV4-ADDRESS>:53:8053/tcp"
> 
>     ...
> 
> ```
> 
> 
> 
> PS, how cool CoreDNS! I did not know it..

I guess this should work. You should swap out DMS with a simple container that has the `dnsutils` package and use `dig` to check whether DNS works properly. Check everything, especially queries to SpamHaus, DNSWL, etc.
