### ISSUE TITLE
[FR] LDAP Mailgroup changes

### ISSUE THREAD

**Issue by jwynn6** [docker-mailserver/docker-mailserver#2712]
The current way mailgroups are implemented, using LDAP, means that you cannot create an LDAP object as a mailgroup, then add mailGroupMember attributes to list members.   Instead you have to add mailGroupMember to each user instead.  This means that nothing really gets kept in one place, which feels out of line with the spirit of using LDAP for groups.

This is configured via postfix's alias features.

I was able to change the behavior by mounting a replacement ldap-groups.cf (based on https://b.aklein.me/ldap-mail-distribution-groups-with-postfix). Essentially I swapped the query filter and the result_attribute.

Original:
`query_filter = (&(mailGroupMember=%s)(mailEnabled=TRUE))
result_attribute = mail
`

New: 
`query_filter = (&(mail=%s)(mailEnabled=TRUE))
result_attribute  = mailGroupMember
`

It would be nice to either have the ability to change the behavior via environment variable or change the default behavior to be as I expected (an LDAP object with a list of mailGroupMember attributes as a mailgroup)

**Comment by polarathene** [comment]
<details>
<summary>Original Response</summary>

> It would be nice to either have the ability to change the behavior via environment variable or change the default behavior to be as I expected (an LDAP object with a list of mailGroupMember attributes as a mailgroup)

We have no active maintainers/contributors with LDAP expertise unfortunately.

Our usual response for changes that would require a new ENV is to defer to contributing a workaround with `user-patches.sh` for our docs for others to benefit from. Alternatively, if enough users chime in with interest for making a change or new ENV official, we can consider that.

I assume making the change in the default behaviour would affect all existing LDAP user setups and be a breaking change? Do you know what sort of impact that would have for existing deployments upgrading?

---

<details>
<summary>Investigation</summary>

Regarding this specific request, if I'm not mistaken we presently have a feature that will match the ENV `LDAP_QUERY_FILTER` to the `query_filter` key. This is handled via a third-party script `configomat.sh`, but would match `query_filter` against all these LDAP config files, where it also seems to override that specific ENV for some reason (**UPDATE:** _I now understand that it's temporarily mapping the ENV with file specific variants to support different values_):

https://github.com/docker-mailserver/docker-mailserver/blob/e99bba2ef52ea74ea31c10621cdc4b9a2fdb4625/target/scripts/startup/setup-stack.sh#L327-L335

For `ldap-groups.cf` that is:

https://github.com/docker-mailserver/docker-mailserver/blob/e99bba2ef52ea74ea31c10621cdc4b9a2fdb4625/target/postfix/ldap-groups.cf#L4

I'm not sure where these `LDAP_QUERY_FILTER` variants are from, I only see one being used here:

https://github.com/docker-mailserver/docker-mailserver/blob/e99bba2ef52ea74ea31c10621cdc4b9a2fdb4625/target/scripts/startup/setup-stack.sh#L469-L474

They are documented [here](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/auth-ldap/#ldap_query_filter_) and in the [ENV docs](https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#ldap_query_filter_group) too. They are also all used in our [LDAP tests container](https://github.com/docker-mailserver/docker-mailserver/blob/e99bba2ef52ea74ea31c10621cdc4b9a2fdb4625/test/mail_with_ldap.bats#L40-L44).

The script seems to override `LDAP_QUERY_FILTER` with the related ENV so that `query_filter` key in the respective LDAP config file is replaced by `configomat.sh`.

</details>

---

</details>

It looks like what you want is [`LDAP_QUERY_FILTER_GROUPS`](https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#ldap_query_filter_group), an ENV that will replace the value of `query_filter` in `ldap-groups.cf` for you.

So it seems you feature request is already implemented? We have those linked ENV docs, and this feature is mentioned in [our LDAP docs page](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/auth-ldap/#ldap_query_filter_). Did you come across either of these pages?

Was the documentation not clear enough on this feature? Could you suggest any improvements to help other future LDAP users discovering this support?

**Comment by polarathene** [comment]
> Instead you have to add `mailGroupMember` to each user instead. This means that nothing really gets kept in one place, which feels out of line with the spirit of using LDAP for groups.

I would appreciate your input along with other LDAP users regarding good defaults. I do not know why the current ones were chosen.

I do not know the impact it would have on existing deployments, although from what I understand, they'd just need to use these same ENV to keep legacy defaults?

---

We have an [LDAP issue regarding `/var/mail` ownership](https://github.com/docker-mailserver/docker-mailserver/pull/2256), the gist of it is what the opening message states:

> _Changing the whole owners of folders inside `/var/mail` ruins the whole LDAP users permissions on their own mail folders._
> _Thus, only `/var/mail` owner should be fixed if necessary (not recursively)._

[They reported the issue](https://github.com/docker-mailserver/docker-mailserver/issues/2238) with the related ENV:

```
ENABLE_LDAP=1
LDAP_START_TLS=yes
LDAP_SERVER_HOST=dc1.internal.MYDOMAIN.com
LDAP_SEARCH_BASE=dc=internal,dc=MYDOMAIN,dc=com
LDAP_BIND_DN=cn=Administrator,cn=users,dc=internal,dc=MYDOMAIN,dc=com
LDAP_BIND_PW=Ch@ngeMe
# Specifies how ldap should be asked for users.
LDAP_QUERY_FILTER_USER=(&(objectclass=person)(mail=%s))
# Specifies how ldap should be asked for groups.
LDAP_QUERY_FILTER_GROUP=(|)
# Specifies how ldap should be asked for aliases.
LDAP_QUERY_FILTER_ALIAS=(|)
# Specifies how ldap should be asked for domains.
LDAP_QUERY_FILTER_DOMAIN=(mail=*@%s)

DOVECOT_TLS=yes
DOVECOT_USER_FILTER=(&(objectclass=person)(sAMAccountName=%n))
DOVECOT_USER_ATTRS==uid=%{ldap:uidNumber},=gid=5000,=home=/var/mail/%Ln,=mail=maildir:~/Maildir
DOVECOT_PASS_ATTRS=sAMAccountName=user,userPassword=password
DOVECOT_AUTH_BIND=yes

ENABLE_SASLAUTHD=1
SASLAUTHD_MECHANISMS=ldap
SASLAUTHD_LDAP_SERVER=dc1.internal.MYDOMAIN.com
SASLAUTHD_LDAP_BIND_DN=cn=Administrator,cn=users,dc=internal,dc=MYDOMAIN,dc=com
SASLAUTHD_LDAP_SEARCH_BASE=dc=internal,dc=MYDOMAIN,dc=com
SASLAUTHD_LDAP_FILTER=(&(sAMAccountName=%U)(objectClass=person))
```

None of us maintainers are familiar enough with LDAP, another LDAP user did chime in with [a suggestion at the end of that PR](https://github.com/docker-mailserver/docker-mailserver/pull/2256#pullrequestreview-811142947):

> > `DOVECOT_USER_ATTRS="=uid=%{ldap:UID},=gid=5000,=home=/var/mail/%Ln,=mail=maildir:~/Maildir"`
> I think that by adding `Maildir` here, the path to the mail folder changed to `/var/mail/<domain>/<user>/Maildir` which led to the test suite error. (I'm using this scheme too but the test suite might not have been doing it)
> Edit: `/var/mail/%Ln` also does not consider the domain name actually, so it should give` /var/mail/<user>/Maildir` here

AFAIK without LDAP there is no issues with all mail folders having the same UID and GID assigned. There has not been much activity from LDAP users expressing the same issue, so I'm not sure if this is a config issue or something we need to resolve for better LDAP support?

In the config above is it only `DOVECOT_USER_ATTRS` that would be responsible for causing the permissions issue with UID differing from the single UID we expect (_due to a `chown -R 5000:5000 /var/mail` at startup or change detection event_)?

**Comment by jwynn6** [comment]
> I do not know the impact it would have on existing deployments, although from what I understand, they'd just need to use these same ENV to keep legacy defaults?

I would hate to break existing installs if my expectations are not shared by everyone, but maybe it would be nice to have a new variable that switches the behavior.

> It looks like what you want is [LDAP_QUERY_FILTER_GROUPS](https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#ldap_query_filter_group), an ENV that will replace the value of query_filter in ldap-groups.cf for you.

This documentation was great, it took me no time at all to get running as documented, though I would have liked it to be a bit clearer on where I needed to use those LDAP values (set in the user entry that is  joining the group instead of in the group entry as I expected).  I use that ENV to set the query filter, and still do even with my config overwrite in place. Modifying the behavior to be as I expected was where I spent my time.  I think a new ENV option that indicates that how the lines are written in the config should be swapped, would work from a user point of view. No idea what that means on the backend for implementation.  

----
> We have an https://github.com/docker-mailserver/docker-mailserver/pull/2256, issue regarding '/var/mail' ownership

This is still very much an issue. Currently, in LDAP, I have to manually set mailGidNumber and mailUidNumber attributes to 5000 for each email account I want, or there are permissions errors in the logs.  For me, I would ideally use the uid and gid that I already assign each user by editing the DOVECOT_USER_ATTRS to match those LDAP attributes.

This did present an an additional issue when it came to LDAP mailgroups too.  By only having DOVECOT_USER_ATTRS and no DOVECOT_GROUP_ATTRS as well, I still couldn't just use the uid and gid because my mailgroups don't have their own uids or gids, I had to add mailGidNumber and mailUidNumber attributes to each.  Having a DOVECOT_GROUP_ATTRS would still require LDAP attributes in my mailgroups but would clean up the "extra" entries in my user LDAP entries.    

Having the system natively default to 5000 unless otherwise specified is not an issue in my mind, that it doesn't do it by default unless overridden, is the problem. That would be a sane default to me.  Especially if I could set DOVECOT_USER_ATTRS to use custom uid and gid attrbutes, and just leave DOVECOT_GROUP_ATTRS alone and it would just use 5000.   Though, I'm not sure what value we get overall from setting custom uid and gid values for each user mailbox, other than historical compatibility and future flexibility.

To the same goal of "decluttering", it would be nice to have the mailHomeDirectory and mailStorageDirectory attributes be optional, and their default be the result of concatinating "/var/mail/", the domain from LDAP_SERVER_HOST (probably this) or the attributes from LDAP_SEARCH_BASE, "/", the LDAP cn attribute. 

I, personally, like to have as few attributes in my LDAP containers as possible. I think it's very doable to have sane defaults that could be edited via ENV's if needed, as they currently are done. Most of them could just be lifted directly from the non-LDAP settings.

Even with the few LDAP hiccups, big kudos to the whole community. There are so few foss projects, especially email servers, even attempting LDAP integration, and this one has done and it is a thing of beauty!

**Comment by polarathene** [comment]
> I think a new ENV option that indicates that how the lines are written in the config should be swapped, would work from a user point of view. No idea what that means on the backend for implementation.

I'm sorry, I don't follow? The current ENV available are not what you needed? What do you propose instead?

> I would have liked it to be a bit clearer on where I needed to use those LDAP values (set in the user entry that is joining the group instead of in the group entry as I expected).
> I use that ENV to set the query filter, and still do even with my config overwrite in place. Modifying the behavior to be as I expected was where I spent my time.

It would be appreciated if you could contribute any improvements to the LDAP docs regarding this?

[The doc page is just a markdown text file](https://github.com/docker-mailserver/docker-mailserver/blob/master/docs/content/config/advanced/auth-ldap.md?plain=1), you can edit it directly in the Github UI by clicking the "Edit" button (pencil icon).

> > We have an [LDAP](https://github.com/docker-mailserver/docker-mailserver/pull/2256) issue regarding `/var/mail` ownership
> This is still very much an issue.

This one I have prepared for, but not found time to learn how to configure LDAP to test myself. If you clone our git repo and delete this one line, then [build a testing image](https://docker-mailserver.github.io/docker-mailserver/edge/contributing/tests/) (_these instructions are a little bit lacking, sorry_), then it shouldn't affect your `/var/mail` permissions:

https://github.com/docker-mailserver/docker-mailserver/blob/e99bba2ef52ea74ea31c10621cdc4b9a2fdb4625/target/scripts/helpers/utils.sh#L36

If that can be confirmed, I can create a PR for it and provided all our tests pass as well, we can make this change for the next major release.

---

> To the same goal of "decluttering", it would be nice to...

> I think it's very doable to have sane defaults that could be edited via ENV's if needed, as they currently are done. Most of them could just be lifted directly from the non-LDAP settings.

We're open to improvements. If you're willing to put together a PR, or open a separate issue clearly stating the before/after changes proposed, we can ping LDAP users from our issue history, along with our changelog/release notes to draw attention to the change proposal for feedback.

If there is no major concerns raised, those would then be part of a major release version. We would ideally want to provide any instructions for existing users to be able to revert back to what they have currently however.

The friction towards such is it's usually difficult to find someone with the expertise and time to contribute such broad changes.

If you are interested, we can help explain anything about the project that we are familiar with. Most of the LDAP specific code is quite small:

**Main LDAP setup logic:**

https://github.com/docker-mailserver/docker-mailserver/blob/e99bba2ef52ea74ea31c10621cdc4b9a2fdb4625/target/scripts/startup/setup-stack.sh#L302-L395

**SASL auth config:**

https://github.com/docker-mailserver/docker-mailserver/blob/e99bba2ef52ea74ea31c10621cdc4b9a2fdb4625/target/scripts/startup/setup-stack.sh#L521-L563

**ENV defaults:**

https://github.com/docker-mailserver/docker-mailserver/blob/e99bba2ef52ea74ea31c10621cdc4b9a2fdb4625/target/scripts/start-mailserver.sh#L69

https://github.com/docker-mailserver/docker-mailserver/blob/e99bba2ef52ea74ea31c10621cdc4b9a2fdb4625/target/scripts/start-mailserver.sh#L82

https://github.com/docker-mailserver/docker-mailserver/blob/e99bba2ef52ea74ea31c10621cdc4b9a2fdb4625/target/scripts/start-mailserver.sh#L119-L166

---

> Even with the few LDAP hiccups, big kudos to the whole community. There are so few foss projects, especially email servers, even attempting LDAP integration, and this one has done and it is a thing of beauty!

Thanks :heart: , but our LDAP support has been very much dependent upon drive-by contributions or past maintainers.

It has even been considered for removal due to the amount of support requests or bugs and burden to maintenance when no maintainer has LDAP expertise :sweat_smile: 

It's fine for now, support is limited, but we cannot guarantee the experience is solid or well tested/documented.

**Comment by Westie** [comment]
To add to this, I had to mess about with my LDAP config by adding extra entries to `/etc/postfix/ldap-groups.cf`

Specifically:

- leaf_result_attribute
- special_result_attribute

**Comment by jwynn6** [comment]
> To add to this, I had to mess about with my LDAP config by adding extra entries to `/etc/postfix/ldap-groups.cf`
> 
> Specifically:
> 
>     * leaf_result_attribute
> 
>     * special_result_attribute

What were you able to accomplish by adding those? Reading the postfix docs left me a little unclear on what they do.

**Comment by Westie** [comment]
It allows you to retrieve a list of members (or more specifically, their e-mails) that are assigned to a group, based on their `dn`

Or am I getting confused with what it is you're after?

Just to clarify, you're after a way for someone to message `group-name@example.com` and all members of the group receive that email?
