### ISSUE TITLE
RELAY for gmail and nothing else

### ISSUE THREAD

**Issue by rhyst** [docker-mailserver/docker-mailserver#2741]
# Subject

Other

## Description

I want to set up a relay for @gmail.com sender addresses so that I can send email from my gmail account. I do not want to relay any other mail.

The documentation indicates that I can set up sender dependent relays and authentication but that they will only be active if RELAY_HOST is set. I do not want to set a default RELAY_HOST, I just want to relay one sender domain. 

Can I set RELAY_HOST to localhost or something? In that case must I also set use my local users email and password as  RELAY_USER and RELAY_PASSWORD?

Thanks for any response.

**Comment by polarathene** [comment]
I worked on the relay support earlier in the year, but my memory of it is a bit foggy. I know that it wasn't implemented as well as I wanted it to be, and would like to find some time to refactor it.

The bulk of the feature support is in this file, and the logic can be followed via this method:

https://github.com/docker-mailserver/docker-mailserver/blob/26053c22bd9c8b41735d6628caa6810316f27bc1/target/scripts/helpers/relay.sh#L198-L217

I haven't read through all that to refresh my memory,  but at a quick glance it looks like `_populate_relayhost_map()` is the problem for you, depending on `RELAY_HOST` to work, but looks at all accounts and aliases setup to add as mappings for using the `RELAY_HOST`.

---

Until I have time to refactor this, you may have to skip the ENV enablement and just directly manage the config files yourself. That means using `user-patches.sh` to add these config changes:

<details>
<summary>Relevant config to apply</summary>

https://github.com/docker-mailserver/docker-mailserver/blob/26053c22bd9c8b41735d6628caa6810316f27bc1/target/scripts/helpers/relay.sh#L190-L196

https://github.com/docker-mailserver/docker-mailserver/blob/26053c22bd9c8b41735d6628caa6810316f27bc1/target/scripts/helpers/relay.sh#L77-L80

https://github.com/docker-mailserver/docker-mailserver/blob/26053c22bd9c8b41735d6628caa6810316f27bc1/target/scripts/helpers/relay.sh#L105-L113

https://github.com/docker-mailserver/docker-mailserver/blob/26053c22bd9c8b41735d6628caa6810316f27bc1/target/scripts/helpers/relay.sh#L58-L61

If you need different relay service auth, then you may also need to user sender dependent mapping (_this means the account and/or password for the relay service is different based on sender_):

https://github.com/docker-mailserver/docker-mailserver/blob/26053c22bd9c8b41735d6628caa6810316f27bc1/target/scripts/helpers/relay.sh#L102

and then finally the sender dependent mapping for relay usage:

https://github.com/docker-mailserver/docker-mailserver/blob/26053c22bd9c8b41735d6628caa6810316f27bc1/target/scripts/helpers/relay.sh#L131-L134

https://github.com/docker-mailserver/docker-mailserver/blob/26053c22bd9c8b41735d6628caa6810316f27bc1/target/scripts/helpers/relay.sh#L187

</details>

---

<details>
<summary>Config reference</summary>

I provided some config examples here:

https://github.com/docker-mailserver/docker-mailserver/blob/26053c22bd9c8b41735d6628caa6810316f27bc1/target/scripts/helpers/relay.sh#L233-L260

https://github.com/docker-mailserver/docker-mailserver/blob/26053c22bd9c8b41735d6628caa6810316f27bc1/target/scripts/helpers/relay.sh#L263-L274

</details>

---

## Example `user-patches.sh`

I haven't tested this but I think it should work:

```bash
#! /bin/bash

function relay_patch_configure_postfix() {
  postconf -e \
    "smtp_sasl_auth_enable = yes" \
    "smtp_sasl_security_options = noanonymous" \
    "smtp_tls_security_level = encrypt"
}

function relay_patch_configure_relay_auth() {
  # Usually contents of `/tmp/docker-mailserver/postfix-sasl-password.cf`
  # /etc/postfix/sasl_passwd
  local RELAY_AUTH_CONFIG='[smtp.relay-service.test]:587    SMTPUSERNAME:SMTPPASSWORD'
  echo "${RELAY_AUTH_CONFIG}" > /etc/postfix/sasl_passwd

  # Set ownership and permissions for security:
  chown root:root /etc/postfix/sasl_passwd
  chmod 0600 /etc/postfix/sasl_passwd

  # Enable it:
  postconf 'smtp_sasl_password_maps = texthash:/etc/postfix/sasl_passwd'
  
  # Optional, if you need sender dependent auth as well (different `SMTPUSERNAME:SMTPPASSWORD`):
  # postconf 'smtp_sender_dependent_authentication = yes'
}

function relay_patch_configure_relay_map() {
  # Usually contents of `/tmp/docker-mailserver/postfix-relaymap.cf`
  # /etc/postfix/relayhost_map
  local RELAY_MAP_CONFIG='@example-domain.test    [smtp.relay-service.test]:587'
  echo "${RELAY_MAP_CONFIG}" > /etc/postfix/relayhost_map

  # Set ownership and permissions for security:
  chown root:root /etc/postfix/relayhost_map
  chmod 0600 /etc/postfix/relayhost_map

  # Enable it:
  postconf 'sender_dependent_relayhost_maps = texthash:/etc/postfix/relayhost_map'
}

relay_patch_configure_postfix
relay_patch_configure_relay_auth
relay_patch_configure_relay_map
```

The docs don't have the best [example usage for the `user-patches.sh` feature](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/user-patches/). You just need to provide it to the config mount to `/tmp/docker-mailserver/` and it should be a file named `user-patches.sh`.

I think you're familiar with what needs to be adjusted in `RELAY_AUTH_CONFIG` and `RELAY_MAP_CONFIG` values, if not feel free to ask or double check :)

`@example-domain.test` in this case probably shouldn't be `@gmail.com`, I can't remember if that would allow anyone to send to you for `@gmail.com` relaying which would be bad if that were the case. You may be better off being more explicit with `user@gmail.com` to declare a sender address instead of just a sender domain to relay for, that would require multiple lines. You could mount a file instead, or append lines like so:

```bash
# This var wasn't all that important, just easier for me to reference the section in discussion
# Comment it out and use `>: /path/to/file` to create a blank file, then we'll append lines with `>> /path/to/file`
# local RELAY_MAP_CONFIG=
>: /etc/postfix/relayhost_map
echo 'user-a@gmail.com    [smtp.relay-service.test]:587' >> /etc/postfix/relayhost_map
echo 'user-b@gmail.com    [smtp.relay-service.test]:587' >> /etc/postfix/relayhost_map
```

**EDIT:** You might not need that, as I recall Postfix having a separate feature to relay mail received from domains, whereas this relay feature should (at least with our configuration) only relay authenticated users.. maybe test that out if you have many users and rather keep it a simple one line `@gmail.com`?

**Comment by rhyst** [comment]
Thank you for the detailed reply!

For my use case I found that I could just set `RELAY_HOST` to some dummy value like `127.0.0.1` and then configure exclusions via `postfix-relaymap.cf`. Given that is a single user server and I only have 3 domains this was quite easy.

**Comment by polarathene** [comment]
> set `RELAY_HOST` to some dummy value like `127.0.0.1`

I haven't looked into what happens there, but I assume it's not going into a loop and Postfix is smart enough not to relay it? Does it still deliver to Dovecot?

> configure exclusions via `postfix-relaymap.cf`.

Just a heads up that a future release will eventually stop supporting that. For some reason the contributor of the relay feature had every account added into the relay map with their own non-standard opt-out syntax feature (the config is otherwise what Postfix expects). In future it will only be for actual accounts to relay.

**Comment by rhyst** [comment]
It certainly seems to work by setting `RELAY_HOST` to `127.0.0.1` but as I said I have excluded all the domains I actually use to send from apart from the gmail address. It's good to know that it will stop working so I will at some point attempt the more proper solution you have suggested.

I'd be interested in contributing a PR to fix this but I worry that I don't understand the reasoning behind the current set up. I would have thought that my use case ("I mostly want to use my own domains but still be able to send some emails with gmail account") would be fairly common.

**Comment by polarathene** [comment]
> would be fairly common.

It probably is, but someone contributed the feature before I became a maintainer. Usually we get contributions from someone to suit their needs, and other maintainers may not be familiar enough with the feature at the time to fully understand the contribution beyond what the contributor describes.

What also happens is the original feature gets re-worked over the years (as this one did), as new contributors add changes or "fixes". Previously the feature was in worse shape for maintaining and very little documentation.

I am rather strict as a reviewer for such features, and such a change needs to be done in a breaking manner rather than a bandaid fix. The `user-patches.sh` workaround will do what you were asking for in the mean time, otherwise it may be better to wait if you can until I find some time in Dec-Jan to work on it.

**Comment by rhyst** [comment]
In case anyone else tries to do this I thought I would update. 

My "simple" method of setting the RELAY_HOST to 127.0.0.1 did in the end cause problems. I added another user account to the server and it could not send mail to any external address instead it got mail reports:

```
[<blah@blah.com>](mailto:blah@blah.com): mail for 127.0.0.1 loops back to myself
```

I used the `user-patches.sh` provided by @polarathene instead and that seems to work perfectly even with multiple users, so thanks again.
