### ISSUE TITLE
Better handling of changelog updates

### ISSUE THREAD

**Issue by casperklein** [docker-mailserver/docker-mailserver#2856]
I really like the idea of documenting changelogs directly with the corresponding PRs.

However this leads to some problems in practice:

1. Not knowing the PR# upfront. So there is the need of an additional commit, after the PR have been opened.
2. When more then one PR is open, this leads automatically to conflicts with `CHANGELOG.md`
3. **Fixing `CHANGELOG.md` conflicts, withdraws already given approvals.** This leads to additional expense for re-approvals.

One solution might be to have a separate PR just for the changelog, which is merged right before a release. Each maintainer would have to update this PR, when merging any relevant PR.

Whats your take on this? Any other thoughts/suggestions?

**Comment by polarathene** [comment]
> 1. Not knowing the PR# upfront. So there is the need of an additional commit, after the PR have been opened.

Non-issue. The majority of PRs will use squash merge, so master branch only has 1 commit.

> \2. When more then one PR is open, this leads automatically to conflicts
> \3. Fixing conflicts, withdraws already given approvals. This adds unnecessary time for a PR to be merged.

I've seen a system around but forget which Github project was doing it (_I think there is a Github action to support it_), where each PR commits a PR-specific file into a `changelog` folder and CI on release does something like look at all the new commits to that directory since, grabs those new files and appends them to the changelog based on their filenaming convention (_to group PRs and link to the appropriate PR_).

It would be good to try look that up again probably and implement it here :sweat_smile:

**Comment by polarathene** [comment]
Ok did some research and almost gave up feeling I could not find what I saw a while back, but I was successful just as I was about to throw down the towel :sunglasses: 

It was Hashicorp's [`go-changelog`](https://github.com/hashicorp/go-changelog)!

They mention some [shortcomings](https://github.com/hashicorp/go-changelog#shortcomings), but I think we could easily add a Github Action requirement check to certain types of pull requests to ensure a changelog file is included before merging :man_shrugging: 

At least I'm pretty sure it was `go-changelog` out all the results I did come across. The bottom of their README references [K8S own release notes generator](https://github.com/kubernetes/release/tree/master/cmd/release-notes) which is similar, and another called [`towncrier`](https://github.com/twisted/towncrier).

---

Other options I came across that may be of interest otherwise:

- [Ansible changelog fragments](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments)
- [Scriv](https://github.com/nedbat/scriv), another tool that avoids merge conflicts by maintaining a directory of changelog fragments to generate the changelog.
- [Random unpopular project that uses yml files for metadata](https://github.com/MaineKuehn/change-log/blob/master/docs/subtool/log.rst) to generate a changelog.
- Some Github Actions that use metadata like labels or other github context to generate a changelog:
  - https://github.com/marketplace/actions/changelog-file-generator
  - https://github.com/marketplace/actions/release-changelog-builder
  - https://github.com/marketplace/actions/changelog-ci

**Comment by casperklein** [comment]
> Non-issue. The majority of PRs will use squash merge, so master branch only has 1 commit.

I was talking about the expense, not the commit count 😉

**Comment by polarathene** [comment]
> > Non-issue. The majority of PRs will use squash merge, so master branch only has 1 commit.
> 
> I was talking about the expense, not the commit count wink

Still a non-issue to me personally. I don't really see much different from adding one more commit with the PR number to that PR vs the suggested update a separate long-lived changelog PR with a commit instead? Same concern, different PR? :man_shrugging: 

The `go-changelog` solution requires that still as part of the filename I think, as does a few others. But some of the Github Actions alternative solutions seem to be able to automate that away if you think one of those might be a better choice?

**Comment by casperklein** [comment]
> Same concern, different PR? 🤷‍♂️

Yes, but an additional benefit of a dedicated PR is, you won't have the problem with conflicts, compared to when multiple PRs concurrently make changes to `CHANGELOG.md`.

I had a look at the solutions you found. Personally I would stick with a [handcrafted CHANGELOG.md + autogenerated changelog at the release page.](https://github.com/docker-mailserver/docker-mailserver/pull/2790#issuecomment-1254063019)

**Comment by polarathene** [comment]
> you won't have the problem with conflicts, compared to when multiple PRs concurrently make changes to `CHANGELOG.md`.

Oh right, good point :+1: 

So mostly just how we used to do it with a release PR, just opening that early and updating it as we go?

**Comment by casperklein** [comment]
Exactly 👍 Or to simplify it further, just use the release PR.

**Comment by casperklein** [comment]
I've created a placeholder PR for the next release. This can be used for `CHANGELOG.md` updates.
