### ISSUE TITLE
[BUG] v11.3.1 was published with update check against the wrong version (v11.3.0)

### ISSUE THREAD

**Issue by Cl00e9ment** [docker-mailserver/docker-mailserver#2952]
### What happened and when does this occur?

`/VERSION` contains `11.3.0` in the image with the `:11.3.1` tag.

### What did you expect to happen?

`/VERSION` to contain `11.3.1`

### How do we replicate the issue?

```bash
# Outputs: `11.3.0`
docker run -it --rm --entrypoint cat mailserver/docker-mailserver:11.3.1 VERSION
```

### DMS version

11.3.1

### Improvements to this form?

My bug report can be summarized in 2 lines. The bug is OS agnostic and doesn't even require any service to be ran. This whole form is nonsense for this particular case. You should allow to bypass it.

**Comment by vedranmiletic** [comment]
Can confirm.

**Comment by polarathene** [comment]
Thanks for the bug report!

We are aware of this issue but it was deemed not likely to cause any real concerns and thus decided to leave as-is (_rather than mess with our git history to adjust the tagged commit or similar inconvenient workarounds_): https://github.com/docker-mailserver/docker-mailserver/pull/2944#issuecomment-1363421102

Closing as resolved (_unless there's an actual problem requiring a 11.3.2 release_).

----

> ### Improvements to this form?
> 
> My bug report can be summarized in 2 lines. The bug is OS agnostic and doesn't even require any service to be ran. This whole form is nonsense for this particular case. You should allow to bypass it.

In future you can raise an issue with the choice **Question / Other**. This will allow you to have control, we only ask you to use the bug report form when requiring support / troubleshooting.

**Comment by Cl00e9ment** [comment]
The only problem that I can see is that docker-mailserver sends a mail with the subject `Mailserver update available! [ 11.3.0 --> 11.3.1 ]` even if it's false. I don't know if it sends it regularly (every day for example). If this is the case, it's a small annoyance/spam.

**Comment by casperklein** [comment]
The update notification is only send once. However, if you restart DMS, you'll get notified again.

**Comment by polarathene** [comment]
Keeping this open and pinning for awareness.

There has been discussion on resolving it, but it looks like due to recent changes with our CI it'll risk introducing a breaking change (platform support) among some other concerns to produce a release this way that we'd rather avoid.

Likely plan is to hold out until a v12 release early Jan which would also resolve the issue. In the meantime if it's an annoyance please temporarily opt out of the update notifications via [`ENABLE_UPDATE_CHECK=0`](https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#enable_update_check), and check back around mid Jan when a new release should be available (_or subscribe to this issue and it'll be closed upon the next release_).

Apologies for the mishap here, we're all humans :sweat_smile: (...right? :grimacing: )

---

Pinning this issue until then for visibility to other users with this concern :+1:

**Comment by wolkenschieber** [comment]
> In the meantime if it's an annoyance please temporarily opt-out of the update notifications via the ENV [`ENABLE_UPDATE_CHECK=0`](https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#enable_update_check), and check back around mid Jan when a new release should be available (_or subscribe to this issue and it'll be closed upon the next release_).

The environment would persist on update. Therefore adjusting the `VERSION` file within the running container would be gone as soon as it's redeployed: `docker exec -it mailserver bash -c 'echo 11.3.1 > VERSION'`.
