### ISSUE TITLE
Unable to send messages

### ISSUE THREAD

**Issue by znepb** [docker-mailserver/docker-mailserver#2954]
I'm trying to set up a mail server, however I can't send messages. I'd assume the problem is with DKIM keys, however when I run `./setup.sh config dkim` nothing is returned (expected?), and the key files in my `docker-data/dms/config/opendkim/keys` folder are empty. Can someone help me resolve this?

**Comment by tanglebridge** [comment]
Is the server otherwise configured? Did you set the hostname in docker-compose.yml? You can test your server without setting up dkim.

When you say you can't send messages - do you mean you are unable to submit them to your smtp server? That is probably a configuration issue.

DKIM is for authentication after the fact. As I understand it, it adds a signature on behalf of the sending server, providing evidence that it was indeed sent from there. It is then up to the receiving mail server to accept messages from a server that does not have DKIM set up. At the least you should be able to send yourself an email, as that would never leave your server.
