### ISSUE TITLE
[Question] How to pass CheckTLS test "TestSenderAssureTLS"?

### ISSUE THREAD

**Issue by williamdes** [docker-mailserver/docker-mailserver#2999]
# Feature Request

Pass this test

## Context

https://www.checktls.com/TestSender?ASSURETLS

### Is your Feature Request related to a Problem?

No

**Comment by polarathene** [comment]
I am not sure we can default to that without enough sources to justify that?

Technically it should be expected that any mail-server you send mail to should support TLS, but I'm not confident defaulting to it without looking into it properly :sweat_smile: 

I know that it's generally expected to not enforce it for inbound mail ([there's an RFC about that](https://www.postfix.org/postconf.5.html#smtpd_enforce_tls)) and I'm not aware of anything since that says otherwise for public facing mail-servers. Not sure about outbound mail though.

---

If I understood correctly from your link, you can support this rather easily via [`smtp_tls_security_level`](https://www.postfix.org/postconf.5.html#smtp_tls_security_level). We adjust this in `master.cf` for the submission ports 465 and 587, it should be left as-is for inbound port 25 (smtpd), but for outbound port 25 (smtp) you can add a `/tmp/docker-mailserver/postfix-master.cf` with the following content:

```
smtp/inet/smtpd_tls_security_level=encrypt
```

That is then configured during container start-up here:

https://github.com/docker-mailserver/docker-mailserver/blob/0ecb647ae2b8e333ee754b2a27f104c222f2ef88/target/scripts/startup/setup-stack.sh#L771

<details>
<summary>Changes in cipher list support (nevermind)</summary>

Do note that once you do this, you will adjust your cipher list compatibility (only relevant for TLS 1.2 connections) to the same as what ports 465 and 587 use:

https://github.com/docker-mailserver/docker-mailserver/blob/0ecb647ae2b8e333ee754b2a27f104c222f2ef88/target/scripts/helpers/ssl.sh#L126-L152

https://github.com/docker-mailserver/docker-mailserver/blob/0ecb647ae2b8e333ee754b2a27f104c222f2ef88/target/scripts/helpers/ssl.sh#L82-L84

Port 25 inbound (smtpd) will continue to use the broader cipher list support found here:

https://github.com/docker-mailserver/docker-mailserver/blob/0ecb647ae2b8e333ee754b2a27f104c222f2ef88/test/tests/parallel/set2/tls/tls_cipherlists.bats#L222-L228

**EDIT:** Actually I seem mistaken there. We do configure the `high` list, but we only set that for `smtpd`, not `smtp`:

https://github.com/docker-mailserver/docker-mailserver/blob/0ecb647ae2b8e333ee754b2a27f104c222f2ef88/target/postfix/main.cf#L39-L41

[The default is `medium`](https://www.postfix.org/postconf.5.html#smtp_tls_mandatory_ciphers), and our cipher suite exclusions are only configured for `smtpd` as seen above.

</details>

---

That should pass that test for you?

From what I understood, it still wants you to connect with StartTLS (explicit TLS), just that it will not acknowledge the connection upgrade to TLS, and expects your mail-server to drop the connection instead of trying to send mail without a secure connection (plain-text).

- `smtp_tls_security_level=encrypt` should match that expectation (_but note the linked docs discourage it_).
- If necessary add `smtp_tls_wrappermode=yes` if you need implicit TLS (_secure from the start, no StartTLS negotiation_), but I don't think that would work and generally shouldn't be used for port 25.

**Comment by williamdes** [comment]
Thank you for such a brilliant and detailed reply !

With `smtp/inet/smtpd_tls_security_level=encrypt` enabled will there be some emails not delivered or is it only if the destination server supports it ?

**Comment by polarathene** [comment]
> will there be some emails not delivered or is it only if the destination server supports it ?

Sorry, just realized that example had `smtpd_` in it and it should have said `smtp_`.. I've edited my earlier message, but you'll want to make sure you add that correction on your end :sweat_smile: 

My understanding is that a connection with TLS is required to be established before mail is sent. Without the wrapper mode, it should start off as plain-text and then try to upgrade to TLS with StartTLS. The test you linked will not respond to the StartTLS upgrade handshake, and normally mail would be sent in plain-text (unencrypted).

With this configuration change to `smtp_tls_security_level=encrypt` it will instead refuse to continue, passing that test.

So if a mail-server doesn't offer TLS, yours with this configuration will not deliver the mail AFAIK. You can probably try verifying by sending to another instance of DMS but without `SSL_TYPE` defined, which should disable TLS on it, so that it only allows plain-text:

https://github.com/docker-mailserver/docker-mailserver/blob/0ecb647ae2b8e333ee754b2a27f104c222f2ef88/target/scripts/helpers/ssl.sh#L313-L315

https://github.com/docker-mailserver/docker-mailserver/blob/0ecb647ae2b8e333ee754b2a27f104c222f2ef88/target/scripts/helpers/ssl.sh#L329-L333

https://github.com/docker-mailserver/docker-mailserver/blob/0ecb647ae2b8e333ee754b2a27f104c222f2ef88/target/scripts/helpers/ssl.sh#L339-L343

---

If you control the other destination, or it's a mail relay service like SendGrid, you can instead use the submission ports with authentication. These often support port 465 with implicit TLS.

If you don't know all the destination hosts DMS will send to, there is a possibility (_probably unlikely for any legitimate service_) that TLS isn't supported (_or if it is, no mutual cipher suite can be negotiated, which'd imply they're not that secure anyway_).

**Comment by polarathene** [comment]
@williamdes do you consider this resolved?

**Comment by williamdes** [comment]
Let's say that it is for now, thank you for your nice and detailed explanations. I really appreciate

I now better understand this TLS check, it seems to bring some breaking behaviors so let's not enable it
