### ISSUE TITLE
How to disable SA_SPAM_SUBJECT?

### ISSUE THREAD

**Issue by ferdinandyb** [docker-mailserver/docker-mailserver#3028]
# Subject

Other

## Description

I tried setting `SA_SPAM_SUBJECT` to empty, and also to `" "`, but in both cases I got the default `***SPAM***` prepended to the subject. Since I'm moving spam to the Junk folder, I don't want anything prepended. How can I achieve this?

**Comment by ferdinandyb** [comment]
I also think it's pretty dangerous to kill spam by default (`SA_TAG2` and `SA_KILL` being on the same level). I think most people would expect spam to arrive to a spam folder by default.

**Comment by georglauterbach** [comment]
Try setting `SA_SPAM_SUBJECT=undef`

**Comment by georglauterbach** [comment]
> I also think it's pretty dangerous to kill spam by default (`SA_TAG2` and `SA_KILL` being on the same level). I think most people would expect spam to arrive to a spam folder by default.

This could probably be adjusted, but I am not an SA expert.

**Comment by georglauterbach** [comment]
IIRC I had some mails markes as Spam in my inbox. Make sure you have set `SPAMASSASSIN_SPAM_TO_INBOX=1` & `MOVE_SPAM_TO_JUNK=1`.

I have moved to Rspamd though (for which support has recently improved (due to #3016)) and support will continue to improve. Maybe this is interesting for you :)

**Comment by polarathene** [comment]
We have a test that covers ENV config to send spam to Inbox or a Junk folder. I can agree with the latter being a smarter default and we could switch to that:

https://github.com/docker-mailserver/docker-mailserver/blob/05db27f817aa0a512f710c10eafe3ab71903f99a/test/tests/parallel/set1/spam_virus/spam_junk_folder.bats#L57-L59

> but having `SA_TAG2 = SA_KILL` means nothing ever goes to the spam folder, everything that is regarded as spam is silently deleted.

[This explains the config fairly well](http://gogs.info/books/debian-mail/chunked/antispam.amavis.html) (_**NOTE:** Lookup the actual config key like `sa_kill_level_deflt`, not our DMS specific ENV `SA_KILL`_). `SA_KILL` is a bit misleading in that sense as it's intended to be a value to trigger an action (`final_spam_destiny`) at a certain threshold value.

By setting it to an excessively high value, you're just opting out of that ever being used. The two ENV mentioned to get your mail into inbox or junk mail actually depend on that via `D_PASS` action instead of `D_BOUNCE`, and to redirect to junk folder via a Dovecot sieve script:

https://github.com/docker-mailserver/docker-mailserver/blob/05db27f817aa0a512f710c10eafe3ab71903f99a/target/scripts/startup/setup-stack.sh#L923-L934

https://github.com/docker-mailserver/docker-mailserver/blob/05db27f817aa0a512f710c10eafe3ab71903f99a/target/scripts/startup/setup-stack.sh#L244-L252

---

Seems that rather  than changing `SA_KILL`, this is more of a configuration and documentation issue.

We could improve the docs and default config, although I'm not sure if anyone wants to put too much time into that as from what I understand @georglauterbach is planning to replace SA + Amavis with the WIP Rspam feature. Both are likely to be around a few releases during the transition, so it's possibly worthwhile in the meantime.

**Comment by georglauterbach** [comment]
> We could improve the docs and default config, although I'm not sure if anyone wants to put too much time into that as from what I understand @georglauterbach is planning to replace SA + Amavis with the WIP Rspam feature. Both are likely to be around a few releases during the transition, so it's possibly worthwhile in the meantime.

I'm not an SA / Amavis expert, really. Hence I got this wrong too, thanks for clarifying this! I can encourage everyone to try Rspamd indeed; from my experience, the experience is way nicer. It lacks the extreme customizability of SA, but I actually believe this to be a good thing. For examle, with Rspamd, you can easily adjust [`actions.conf`](https://github.com/rspamd/rspamd/blob/master/conf/actions.conf) and set the values you want for 1. adding a header, 2. rewriting subject, 3. greylisting and 4. 4. rejection.

I am currently working on a feature that should make adjusting these options even easier with DMS.

**Comment by ferdinandyb** [comment]
> > I think most people would expect spam to arrive to a spam folder by default.
> 
> **EDIT:** These are the actual defaults...? Mail should be moved to junk already for you, not silently deleted (_bounced rather_). What is your config?

This is my config _now_, but the only two things I changed is a very high `SA_KILL` and the spam subject and I'm on `11.3.0` (I always get an email that there's a `11.3.1` but `docker pull` doesn't update anything and I have left it at that for now). 

```
  ENABLE_SPAMASSASSIN=1
 
  # deliver spam messages in the inbox (eventually tagged using SA_SPAM_SUBJECT)
  SPAMASSASSIN_SPAM_TO_INBOX=1
 
  # KAM is a 3rd party SpamAssassin ruleset, provided by the McGrail Foundation.
  # If SpamAssassin is enabled, KAM can be used in addition to the default ruleset.
  # - **0** => KAM disabled
  # - 1 => KAM enabled
  #
  # Note: only has an effect if `ENABLE_SPAMASSASSIN=1`
  ENABLE_SPAMASSASSIN_KAM=0
 
  # spam messages will be moved in the Junk folder (SPAMASSASSIN_SPAM_TO_INBOX=1 required)
  MOVE_SPAM_TO_JUNK=1
 
  # add spam info headers if at, or above that level:
  SA_TAG=2
 
  # add 'spam detected' headers at that level
  SA_TAG2=6.31
 
  # triggers spam evasive actions
  SA_KILL=10000
 
  # add tag to subject if spam detected
  SA_SPAM_SUBJECT=undef
```

> I'm not an SA / Amavis expert, really. Hence I got this wrong too, thanks for clarifying this! I can encourage everyone to try Rspamd indeed; from my experience, the experience is way nicer. It lacks the extreme customizability of SA, but I actually believe this to be a good thing. For examle, with Rspamd, you can easily adjust [actions.conf](https://github.com/rspamd/rspamd/blob/master/conf/actions.conf) and set the values you want for 1. adding a header, 2. rewriting subject, 3. greylisting and 4. 4. rejection.

For a project like this I would also say straightforward configuration is probably better, than way too much.

**Comment by polarathene** [comment]
> This is my config _now_

Ok, but you don't need the high `SA_KILL` right? As the other ENV mentioned handle not bouncing the mail, it should still be delivered due to `D_PASS`, and then moved to junk folder?

> I'm on `11.3.0` (I always get an email that there's a `11.3.1` but `docker pull` doesn't update anything and I have left it at that for now).

That was a release error where the decision was it'd be better to just live with that for a brief duration until the next release is made. We have an open pinned issue for tracking when that happens if you want to be notified.

A new release was intended to be out by now, but delayed due to some larger overhaul work going on (_ideally completed within the next week, so a new major release should be out mid-late Feb_)

**Comment by ferdinandyb** [comment]
> > This is my config _now_
> 
> Ok, but you don't need the high `SA_KILL` right? As the other ENV mentioned handle not bouncing the mail, it should still be delivered due to `D_PASS`, and then moved to junk folder?

I don't need a super high one, but when it was equal to `SA_TAG2` I'm pretty sure I did not get anything delivered to Spam/Junk. I could go back and double check if needed.

> That was a release error where the decision was it'd be better to just live with that for a brief duration until the next release is made. We have an open pinned issue for tracking when that happens if you want to be notified.
> 
> A new release was intended to be out by now, but delayed due to some larger overhaul work going on (_ideally completed within the next week, so a new major release should be out mid-late Feb_)

In that case my do nothing hunch was great :D
