### ISSUE TITLE
[BUG] ClamAV security vulnerability

### ISSUE THREAD

**Issue by GoliathLabs** [docker-mailserver/docker-mailserver#3098]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

ClamAV

### What happened and when does this occur?

See: https://blog.clamav.net/2023/02/clamav-01038-01052-and-101-patch.html

### What did you expect to happen?

We should update our debian base image

### How do we replicate the issue?

1.
2.
3.
...

### DMS version

latest

### What operating system is DMS running on?

Linux

### Which operating system version?

Debian 11

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### Other relevant information

https://blog.clamav.net/2023/02/clamav-01038-01052-and-101-patch.html

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [ ] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

**Comment by georglauterbach** [comment]
Can you elaborate on what's _exactly_ the issue is / which CVE you're referring to? And is a base image Update really justified?

**Comment by kub3let** [comment]
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-20032

https://blog.clamav.net/2023/02/clamav-01038-01052-and-101-patch.html

There is no patch in debian repositories yet https://security-tracker.debian.org/tracker/CVE-2023-20032

Solution would be to add clamav 1.0.1 from https://www.clamav.net/downloads, however there are no arm builds.

**For anyone, recreate your container with ENABLE_CLAMAV=0 for now until it is patched.**

**Comment by georglauterbach** [comment]
TBH, I'm really not sure about this. I cannot find the CVE score right now (can you help me here?), and changing the base image is one of the most breaking changes you can actually do.. this seems a bit like taking a sledgehammer to crack a nut. Since there are no ARM builds on the official ClamAV website, I'd not like to use this either. @polarathene any idea, what do you think about this?

**Comment by fdellwing** [comment]
> I cannot find the CVE score right now (can you help me here?)

The CVSS v3.1 is 9.8 and it is a (possible) RCE in the HFS+ file parser of clamd.

**Comment by GoliathLabs** [comment]
Otherwise we could wait for debian to update the package and just rebuild the image with the new base image patch set.

**Comment by davidconnard** [comment]
Maybe consider updating docker-mailserver to temporarily ignore a **ENABLE_CLAMAV=1** setting, ie. force disable ClamAV, until the updated package is available from Debian.  After all, that is what everyone should be doing anyway in the mean time.  Preventing the enabling ClamAV in the mean time will ensure that anyone who is unaware of the issue, but auto-updates their docker-mailserver, would at least be covered.

Although, perhaps this is not worth it, if the updated Debian package would be available soon ... but ... who knows..?

FYI - https://www.theregister.com/2023/02/17/cisco_clamav_critical_flaw/

**Comment by kub3let** [comment]
Personally I would wait for debian repository updates.

The only options would be to either compile from source or use unstable repo and install the sid version which both is not optimal.

Note that attackers can easily gain persistence on the docker-mailserver container, so disable clamav for now.

**Comment by polarathene** [comment]
> @polarathene any idea, what do you think about this?

The project is not well setup for publishing hot fixes even if that were an option.

I think we can branch the previous release tag, make a change there and tag it for a release, but I recall us discussing something like this in December to resolve the update notifier mistake (_forgetting to bump the version file checked before tagging release_). We decided that wasn't worth pursuing.

Likewise, probably not good to rush out the upcoming breaking change release v12 :sweat_smile: 

---

Best we can do is probably pin an issue with clearly visible advice on the vulnerability. Disabling ClamAV might avoid it, but at the same time I can't imagine users that want the anti-virus feature to trade one vulnerability for another (_allowing viruses to be delivered?_).

I believe we're quite close to preparing a new release, so Debian may have a fix pushed before then.

---

https://sec.cloudapps.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-clamav-q8DThCy

> An attacker could exploit this vulnerability by submitting a crafted HFS+ partition file to be scanned by ClamAV on an affected device.
> 
> A successful exploit could allow the attacker to execute arbitrary code with the privileges of the ClamAV scanning process, or else crash the process, resulting in a denial of service (DoS) condition.

From that explanation, the DoS sounds concerning, but likely more noticeable and can be worked around with minimal damage?

The remote execution as a ClamAV user, would still need to switch to root to do any real damage? Or perhaps they can escape the container, it's been a while since I reviewed those kind of attacks.

There's also not much to go on about the file type that can be exploited. A partition image file is usually large, it's unclear how large (or small) it needs to be to make it capable of the exploit. If it cannot be done with the default 10 MB attachment limit, I don't think most of our users would be vulnerable then.

While it was reported from an engineer at Google, presently there's no known malicious use according to ClamAV. The attacker would need to know how to craft that partition file to trigger the exploit, if they lack that knowledge, it has to be worth their time to invest creating that exploit whilst knowing that many of the valuable targets will be patched? Someone might still do it and share or sell it for profit I guess.

---

My stance is:
- **Wait until Debian updates ClamAV.** Our users can rebuild the image locally to receive those updates, or wait until we've published v12 and pull that.
- **Our users that deploy with ClamAV can weigh up if this vulnerability is worth avoiding by instead allowing malware attachments** to be received to their mailboxes (_if they're ok with that, I'm not sure why they're using ClamAV to begin with_). An attacker capable of carrying out this exploit would just as likely try their luck with sending malware as well AFAIK. My personal opinion is the likelihood of the exploit being used successfully is much lower than permitting malware distribution.

**Comment by georglauterbach** [comment]
I agree with @polarathene, we should try and wait for a hotfix in the Debian repos and then our CI will automatically build an updated image and push it for `:edge`, which should go into v12 or in a path release for v12.

**Comment by georglauterbach** [comment]
@polarathene if you deem it worthwhile, I can look into <https://github.com/anchore/scan-action> which is based on <https://github.com/anchore/grype>. It would be another GH Action we could run (should be easy to implement I guess/hope). This would enable us to see whether there are security vulnerabilities automatically (we do not need to fail builds because of this for now, just for informational purposes).

**Comment by polarathene** [comment]
> A generic workflow file could look like this:

That looks good, if it helps keep tabs on this sort of thing I'm all for it if you've got the time to work on it :+1: 

Glanced over the action README, and while we can build the image with a run step, if you want to leverage the buildx cache, then you'd need to add two steps to import the build cache and load the image into the docker daemon like the testing workflow does:

https://github.com/docker-mailserver/docker-mailserver/blob/853301338cf355d440561d1f17c45ebaf8d26301/.github/workflows/generic_test.yml#L37-L56

**Comment by georglauterbach** [comment]
Great! Do you think we should just schedule it in the weekly build-publish workflow for `:edge` (not failing the build but possibly reporting information via GitHub)? I guess it may not add too much value to PRs since most of the do not touch packages anyways?

And thanks for the hint to _actually build the image_ :D Completely forgot that.. I will also add a short `SECURITY.md` just so users can glance over the very basics.

**Comment by polarathene** [comment]
> Great! Do you think we should just schedule it in the weekly build-publish workflow for `:edge` (not failing the build but possibly reporting information via GitHub)?

Yeah that sounds best :)

>  I guess it may not add too much value to PRs since most of the do not touch packages anyways?

Agreed, and this kind of issue wouldn't reliably show up on PRs, better to be caught from scheduled checks that automate raising an issue to report :+1: 

> I will also add a short `SECURITY.md` just so users can glance over the very basics.

:heart:

**Comment by casperklein** [comment]
fyi: There is now an update available in the Debian repository.
