### ISSUE TITLE
[FR] please enable auto spam learning with rspamd using junk folder learning

### ISSUE THREAD

**Issue by hanscees** [docker-mailserver/docker-mailserver#3099]
# Feature Request
Hi. could you enable auto-spam learning with rspamd? 

As described here 
https://workaround.org/ispmail/stretch/filtering-out-spam-with-rspamd

## Context
I am using rpsamd with version 13.1 I think.
I have trained the spam and ham algorhitms and would like users to keep learning rspamd what is spam or ham by moving emails in and out of the junk folder

### Is your Feature Request related to a Problem?
No, its improvement

### Describe the Solution you'd like
see above/ When a user moves an email in junk folder rpsamd learns that its spam and improves its algo.

### Are you going to implement it?
I have no idea how. 
I can built it with the userscript, but thats not what you want probably?

### Who will that Feature be useful to?
All users basically because no-one wants spam right?

### What have you done already?
considered to built it myself with the user script. I might do that anyway.

**Comment by georglauterbach** [comment]
You should be able to do this really easily now because #3059 is merged. Here are the docs: <https://docker-mailserver.github.io/docker-mailserver/edge/config/security/rspamd/#with-the-help-of-a-custom-file>. Just place a file called `rspamd-modules.conf` into the directory `/tmp/docker-mailserver/` inside the container and it will be parsed. I am using it too to enable auto-learning:

```cf
set-option-for-module classifier-bayes autolearn true
```

I'd refrain from enabling it per-default for now though, since I want to see whether it works well. The worst thing for a mail server (besided hijacking it of course) is rejecting legitimate email. When I see that the feature works as expected, I will add it to the default configuration.

**Comment by georglauterbach** [comment]
```txt
COMMAND               MODULE NAME     OPTION    VALUE
<-------------------> <--------------> <-------> <-->
set-option-for-module classifier-bayes autolearn true
```

This will create `/etc/rspamd/override.d/classifier-bayes.conf` and insert the line `autolearn = true;`.

**Comment by hanscees** [comment]
thanks! 

I have produced a script that enables the server to learn spam and ham by moving email in and out the email box.
Perhaps it is something you can add to the server in some form. 

[rspamd-patches.txt](https://github.com/docker-mailserver/docker-mailserver/files/10864507/rspamd-patches.txt)

**Comment by georglauterbach** [comment]
Thank you the for the script! I am currently already oversubscribed with issues, and the next release is on the horizon, but I may come back to it :) 

I will close this for now; I think I will do one more docs overhaul before v12.0.0 is release, which should contain an example for the script, which should make it easier for others to grasp :)
