### ISSUE TITLE
Parser for ENV

### ISSUE THREAD

**Issue by georglauterbach** [docker-mailserver/docker-mailserver#3101]
# Feature Request

## Context

So I wrote a parser for ENV files.

### Is your Feature Request related to a Problem?

`mailserver.env` and our documentation can fall out of sync (they already have when considering the description for variables).

### Describe the Solution you'd like

A parser that takes one file and provides two new files: a Markdown documentation & a `.env` file. This way, all is in sync and has a uniform style.

### Are you going to implement it?

Yes, I already have: <https://github.com/docker-mailserver/env-generator>. Check out the `dev` branch. There is a YAML example file under `tests`. The parser is written in Rust and uses `clap` and `serde` + `serde-yaml`.

### What Still Needs to be Done

I am not sure how to integrate it best yet. Moreover, I have only adapted a part of our current Markdown docs into the new YAML file.

---

Let me know what you think :D

**Comment by polarathene** [comment]
You read my mind haha :laughing: 

I had been thinking of writing something like this for a while but never got around to it. Input file that outputs both `.env` and `.md` content, good job! :muscle: 

For integration, I'd need to give it some thought. Easiest way to bring it in probably is to have that repo publish a release with static linked binaries, then our CI over here can just pull that in for docs workflows to run it (_and similar for `.env` on master, while PRs only need to review the `.yaml`_). Shouldn't have much overhead :+1: 

I've built static builds with rust before, so could contribute that if you like.

I'd need to look over the docs page as some of that content needs a bit more special handling than the `.env` uses I think. It'd also be good to group / categorize ENV (_I suppose that can be handled via declaration order, but the docs page does some actual separation, so either another field, or using a directory with multiple yaml files as input could work_).

Then there's also links (_and possibly other formatting differences such as admonitions_) that might need to be given some thought too. That or we keep the `.env` as a simplified version, since we have more detailed docs page that can be referenced, I don't think the inline comments for `.env` matter too much given the context :sweat_smile:

**Comment by georglauterbach** [comment]
Exactly my thougts as well. I am not sure whether we really need a statically linked binary on the runners (`glibc` anc Co. should be present, right?), but with Rust, shouldn't be too hard (using MUSL I guess?).

The parser is pretty good when it comes to Markdown since it just takes the YAML description field and copies it 1:1 into the Markdown file, so we can basically write plain Markdown, which is great (and easy with YAML's `>` or `|` syntax). Admonitions are therefore no problem.

I'd like to keep the parser simple, so we may need to opt for multiple YAML files in case we really want to keep the grouping like in the docs. I am not 100% certain whether we need that; we could do something similar to our scripts, which may be a good idea. Then I'd opt for the simple method of multiple YAML files creating multiple doc & env files that will just be properly appended.

The `.env` files I'd simplify. Add a link to our docs, and at most provide the possible values above the variables in a comment (not yet implemented, but should be trivial). The description of a value is typically simple, so we should not run into big issues there either.

I will adjust the parser a bit more. Then provide a script to evaluate multiple files. Maybe I can even add some tests to the parser :D

**Comment by polarathene** [comment]
> Exactly my thoughts as well. I am not sure whether we really need a statically linked binary on the runners (`glibc` anc Co. should be present, right?), but with Rust, shouldn't be too hard (using MUSL I guess?).

AFAIK, it can be an issue if you [compile on a different system and try to use that build on another with an older version of `glibc`](https://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html), which would be the case with the Ubuntu CI vs our Debian image for other usage (_if we adopt rust elsewhere in the project_), but non-issue I guess for CI only usage.

In the past I had a docker image that built with alpine and musl and that seemed to work well. I can go find that Dockerfile. If we need caching in CI for the crates to speed up fresh builds, I've not yet done that, but recall cargo wharf, and cargo chef as projects related to that, Earthly also has an example for rust projects IIRC.

> which is great (and easy with YAML's `>` or `|` syntax). Admonitions are therefore no problem.

Oh I was thinking more of presentation, unless that markdown syntax in the ENV comments is fine? The docs have bullet-point lists, links, code fences, bold, escaped (`***`) syntax, inline code blocks (some that are also hyperlinks). **EDIT:** Oh nvm, you later mentioned keeping the description out of the `.env` :+1: 

Depends how useful we consider the `.env` file I suppose? A project I've been wanting to tackle that benefits from having a YAML config like you're working with, is a small web app that is a config wizard, we could then have a form generated from that and it can output a `.env` for the user, while providing descriptions in markdown too. One of the competing mail docker projects offers something like this IIRC.

Alternatively, the rust struct for the ENV management could also in future be adapted / integrated into the project for getting ENV and/or reading a config file beyond `.env` since Rust has support for that sort of thing already.

> I'd like to keep the parser simple, so we may need to opt for multiple YAML files in case we really want to keep the grouping like in the docs.

Up to you. Our docs `mkdocs.yml` file uses yaml with nesting to group related content:

https://github.com/docker-mailserver/docker-mailserver/blob/853301338cf355d440561d1f17c45ebaf8d26301/docs/mkdocs.yml#L116-L134

Multiple files referenced with the main yaml config providing the hierarchy. I think we'd only need one level though, but an extra field for a "tag" / "group" / "category" value would also work just as easily?:

```rust
use std::collections::HashMap;

// Just iterating your `variables` vec to bucket elements by `group` key into a hashmap:
fn main() {
  let mut env_groups = HashMap::new();

  for env_var in variables {
    let mut env_group = env_groups.entry(env_var.group.clone()).or_insert(vec![]);
    env_group.push(env_var);
  }

  // Continue processing, but now you iterate the hashmap key (ENV groups), and inner loop of their vec value (ENVs filtered from variables)
  println!("{:#?}", env_groups);
}
```

> The `.env` files I'd simplify. Add a link to our docs, and at most provide the possible values above the variables in a comment (not yet implemented, but should be trivial). The description of a value is typically simple, so we should not run into big issues there either.

Sounds good :+1:

**Comment by polarathene** [comment]
> I think a manual integration is suffient for now, we integrate the whole thing into CI later.

That's fine. Open a PR with the YAML config, include a README to describe the directory content and link to the rust parser with instructions on running it to generate the `.md` and `.env ` files.

I have limited review capacity atm, but should have time in the weekend.

**Comment by georglauterbach** [comment]
I had an idea yesterday: what if we do not need to parse YAML (or any other format), but use Rust's powerful macros? Writing a macro that is basically similar to the YAML definition, thing would become easier I think, and we could throw out parsing logic.

What do you think? Usability should be quite good, I image something like:

```rust
// default creation of an ENV
create_env!{
  "ONE_DIR",                                   // name of the ENV
  "The description for ONE_DIR belongs here",  // description
  create_env_values!(                          // additional macro to create a vector of values
    ("0", "Disabled"),
    ("1", "Enabled")
  ),
  "1"                                          // default
};

// create en ENV that enables/disables a service
create_env_enable!{
  "ENABLE_RSPAMD",  // name
  "A description",  // description
  "0",              // default
}
```

This way, we could run even more checks, sort the values more easily I guess, etc.

---

Creating

1. the documentation in Markdown
2. the `.env` file
3. the shell file `variables-stack.sh`

should be easy too. This is a best-case scenario, so no drift happens at all.

**Comment by polarathene** [comment]
> Writing a macro that is basically similar to the YAML definition, thing would become easier I think, and we could throw out parsing logic.

I can't say I'm too fond of the macro example myself. I could get behind actual Rust structs + types and using doc comments, but that may be more explicit / verbose than needed atm. YAML is perhaps more friendly to any maintainers / contributors that aren't as familiar with Rust (_although, I think once setup the maintenance shouldn't be much of a concern_).

> What do you think? Usability should be quite good, I image something like:

Could just be my personal bias, but I like having keys + structure. A tuple of strings (_with some optional comments on the side_) being input into a macro doesn't quite sit well for me :sweat_smile: 

---

> This is a best-case scenario, so no drift happens at all.

I'm open to exploring the options.

I think we can use a config crate (_Figment in particular might be a good choice_) and have the default values managed via attributes. Clap and serde can be pretty good at such things.

We could then write out a `.env` example config and markdown docs like your project already does. In addition it'd be able to read in the ENV for `start-mailserver.sh` / `variables.sh` and output the settings `/etc/dms-settings` file for scripts to source.

---

Small snippet of Config I experimented with a few crates like clap:

```rust
#[derive(clap::ValueEnum, Clone, Debug)]
enum SupervisorLogLevel {
  /// Only show critical messages
  CRITICAL,

  /// Only show erroneous output
  ERROR,

  /// Show warnings
  WARN,

  /// Normal informational output
  INFO,

  /// Also show debug messages
  DEBUG,
}

#[derive(Parser, Debug)]
#[command(about, version)]
struct Config {
  /// Here you can adjust the log-level for Supervisor.
  /// 
  /// The log-level will show everything in its class and above.
  #[arg(env, default_value = "warn", value_enum)]
  supervisor_loglevel: SupervisorLogLevel,

  /// Set the log level for DMS. This is mostly relevant for container startup scripts and change detection event feedback.
  #[arg(env, default_value="info", value_parser=["error", "warn", "info", "debug", "trace"])]
  log_level: log::Level,
}
```

Output for short help (first line of doc comments for an arg:

```
  [SUPERVISOR_LOGLEVEL]  Here you can adjust the log-level for Supervisor [env: SUPERVISOR_LOGLEVEL=] [default: warn]
                         [possible values: critical, error, warn, info, debug]
  [LOG_LEVEL]            Set the log level for DMS. This is mostly relevant for container startup scripts and change
                         detection event feedback [env: LOG_LEVEL=] [default: info] [possible values: error, warn, info,
                         debug, trace]
```

Long version:

```
  [SUPERVISOR_LOGLEVEL]
          Here you can adjust the log-level for Supervisor.
          
          The log-level will show everything in its class and above.
          
          [env: SUPERVISOR_LOGLEVEL=]
          [default: warn]

          Possible values:
          - critical: Only show critical messages
          - error:    Only show erroneous output
          - warn:     Show warnings
          - info:     Normal informational output
          - debug:    Also show debug messages

  [LOG_LEVEL]
          Set the log level for DMS. This is mostly relevant for container startup scripts and change detection event
          feedback
          
          [env: LOG_LEVEL=]
          [default: info]
          [possible values: error, warn, info, debug, trace]
```

[Crates like `doku`](https://github.com/anixe/doku) are able to provide a bit more control of leveraging derive on a struct to iterate through with access to doc comments and write your own preferred output, albeit probably not worth the effort for us to bother with vs the more direct approach you've been doing.

[`fundoc` can parse out inline markdown doc comments](https://github.com/daynin/fundoc) and output markdown files from that which was kinda neat, but probably not as useful. Or if you want to [write your own macros](https://stackoverflow.com/questions/33999341/generating-documentation-in-macros),  that link seem to share some advice.

If the tool does get to a point that it handles setup ENV parsing, quite a few crates didn't seem to support converting the `0` / `1` / _invalid_ values from ENV to `bool` type.

Clap can support it reasonably well with [`BoolishValueParser`](https://docs.rs/clap/latest/clap/builder/struct.BoolishValueParser.html) instead of a separate pre-process / post-process step for that. I didn't look too deeply into support in other crates, and the Clap approach is a bit noisy/verbose since you seem to need to append this to each bool ENV arg (_no way to adjust default as it's more CLI arg focused than the additional ENV mapping to args support_):

```rust
#[arg(env, value_parser=clap::builder::BoolishValueParser::new())]
```

Not something I can commit much time to, but thought I'd chime in with that :)

**Comment by georglauterbach** [comment]
Very interesting! Thanks for the hints. I have ot started working on the macros; and I'm fine with parsing YAML - in the end, it was just an idea :)

**Comment by georglauterbach** [comment]
I will close this issue in this repo for now; I think we should continue in < https://github.com/docker-mailserver/env-generator>. I do not have time anymore to take care of this soon, but the first steps are done. I will make sure the Rspamd integration is maturing, so we can make it the default in the future.

**Comment by polarathene** [comment]
> I do not have time anymore to take care of this soon, but the first steps are done.

It's not too important, just a QoL improvement for maintenance mostly. Like many other wishlist items I'd love to tackle but struggle to find time for :sweat_smile: 

I don't see any problem leaving a feature request open for tracking, but that is your call :+1: 

> I will make sure the Rspamd integration is maturing, so we can make it the default in the future.

Sounds great! :grin: 

It will eventually replace Amavis + SpamAssassin + OpenDMARC + OpenDKIM?

**Comment by georglauterbach** [comment]
> It will eventually replace Amavis + SpamAssassin + OpenDMARC + OpenDKIM?

Absolutely! :D
