### ISSUE TITLE
How to run mailserver only on subdomain mail.example.com and not example.com?

### ISSUE THREAD

**Issue by sebastian-ruiz** [docker-mailserver/docker-mailserver#3152]
# I would like to run mailserver ONLY on mail.example.com

I already point example.com to an public mail server (mailbox.org), via MX records, so I don't want to interfere with this.

I would like to run the mailserver only on mail.example.com and create an email address user@mail.example.com.

## My configuration

I don't create any new MX records for `mail.example.com`.

I am using traefik that manages letsencrypt certificates, so following the documentation I have added the acme.json as a volume. I verify that my `acme.json` contains mail.example.com.

I looked at the documentation, but I am unclear on how exactly to restrict docker-mailserver to my subdomain. I tried various things like `hostname: mail.example.com` and  `- OVERRIDE_HOSTNAME=mail.example.com`.

My `docker-compose.yml` file is as follows:

``` yaml
services:

  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.example.com
    domainname: mail.example.com
    ports:
    #   - "25:25"
      - "587:587"
      - "993:993"
    volumes:
      - ./traefik-data/acme.json:/etc/letsencrypt/acme.json:ro
      - ./data/dms/mail-data/:/var/mail/
      - ./data/dms/mail-state/:/var/mail-state/
      - ./data/dms/mail-logs/:/var/log/mail/
      - ./data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OVERRIDE_HOSTNAME=mail.example.com
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=mail.example.com
      - TLS_LEVEL=intermediate
      - ENABLE_SPAMASSASSIN=0
      - SPAMASSASSIN_SPAM_TO_INBOX=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - SPOOF_PROTECTION=0
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: unless-stopped

  whoami:
    image: docker.io/traefik/whoami:latest
    networks:
      - web
    labels:
      - "traefik.http.routers.whoami.rule=Host(`mail.example.com`)"

networks:
  web:
    external: true
```
## Logs

```
[   INF   ]  Welcome to docker-mailserver 11.3.0
[   INF   ]  Initializing setup
[   INF   ]  Checking configuration
[   INF   ]  Configuring mail server
[ WARNING ]  You need at least one mail account to start Dovecot (120s left for account creation before shutdown)
[   INF   ]  Post-configuration checks
[   INF   ]  Starting miscellaneous tasks
[   INF   ]  Starting daemons
[   INF   ]  mail.example.com is up and running
Mar  4 22:11:17 mail amavis[553]: starting. /usr/sbin/amavisd-new at mail.example.com amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"
Mar  4 22:11:17 mail amavis[553]: perl=5.032001, user=, EUID: 110 (110);  group=, EGID: 112 112 (112 112)
Mar  4 22:11:17 mail amavis[553]: Net::Server: Group Not Defined.  Defaulting to EGID '112 112'
Mar  4 22:11:17 mail amavis[553]: Net::Server: User Not Defined.  Defaulting to EUID '110'
Mar  4 22:11:17 mail amavis[553]: No ext program for   .zoo, tried: zoo
Mar  4 22:11:17 mail amavis[553]: No ext program for   .doc, tried: ripole
Mar  4 22:11:17 mail amavis[553]: No decoder for       .F
Mar  4 22:11:17 mail amavis[553]: No decoder for       .doc
Mar  4 22:11:17 mail amavis[553]: No decoder for       .zoo
Mar  4 22:11:17 mail postfix/postdrop[573]: warning: unable to look up public/pickup: No such file or directory
Mar  4 22:11:19 mail postfix/master[1212]: daemon started -- version 3.5.17, configuration /etc/postfix
Mar  4 22:11:19 mail postfix/pickup[1216]: BE6811AEA3EE: uid=0 from=<root>
Mar  4 22:11:19 mail postfix/cleanup[1221]: warning: connect to Milter service inet:localhost:8891: Cannot assign requested address
Mar  4 22:11:19 mail postfix/cleanup[1221]: BE6811AEA3EE: message-id=<20230304211119.BE6811AEA3EE@mail.example.com>
Mar  4 22:11:19 mail postfix/qmgr[1217]: BE6811AEA3EE: from=<root@mail.example.com>, size=713, nrcpt=1 (queue active)
Mar  4 22:11:19 mail postfix/smtp[1231]: connect to mxext1.mailbox.org[2001:67c:2050:104:0:1:25:1]:25: Cannot assign requested address
Mar  4 22:11:20 mail postfix/smtp[1231]: Trusted TLS connection established to mxext2.mailbox.org[80.241.60.215]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange ECDHE (P-384) server-signature RSA-PSS (4096 bits) server-digest SHA256
Mar  4 22:11:20 mail postfix/smtp[1231]: BE6811AEA3EE: to=<postmaster@example.com>, relay=mxext2.mailbox.org[80.241.60.215]:25, delay=2.9, delays=2.3/0.01/0.38/0.24, dsn=5.1.1, status=bounced (host mxext2.mailbox.org[80.241.60.215] said: 550 5.1.1 <postmaster@example.com>: Recipient address rejected: User unknown in relay recipient table (in reply to RCPT TO command))
Mar  4 22:11:20 mail postfix/cleanup[1221]: 6B5E91AEA3F2: message-id=<20230304211120.6B5E91AEA3F2@mail.example.com>
Mar  4 22:11:20 mail postfix/bounce[1241]: BE6811AEA3EE: sender non-delivery notification: 6B5E91AEA3F2
Mar  4 22:11:20 mail postfix/qmgr[1217]: 6B5E91AEA3F2: from=<>, size=2838, nrcpt=1 (queue active)
Mar  4 22:11:20 mail postfix/trivial-rewrite[1227]: warning: do not list domain mail.example.com in BOTH mydestination and virtual_mailbox_domains
Mar  4 22:11:20 mail postfix/qmgr[1217]: BE6811AEA3EE: removed
Mar  4 22:11:20 mail postfix/cleanup[1221]: 6E69B1AEA3F1: message-id=<20230304211120.6B5E91AEA3F2@mail.example.com>
Mar  4 22:11:20 mail postfix/local[1244]: 6B5E91AEA3F2: to=<root@mail.example.com>, relay=local, delay=0.02, delays=0.01/0/0/0, dsn=2.0.0, status=sent (forwarded as 6E69B1AEA3F1)
Mar  4 22:11:20 mail postfix/qmgr[1217]: 6E69B1AEA3F1: from=<>, size=2967, nrcpt=1 (queue active)
Mar  4 22:11:20 mail postfix/qmgr[1217]: 6B5E91AEA3F2: removed
Mar  4 22:11:20 mail postfix/smtp[1231]: connect to mxext2.mailbox.org[2001:67c:2050:104:0:2:25:1]:25: Cannot assign requested address
Mar  4 22:11:20 mail postfix/smtp[1231]: connect to mxext1.mailbox.org[2001:67c:2050:104:0:1:25:1]:25: Cannot assign requested address
Mar  4 22:11:20 mail postfix/smtp[1231]: Trusted TLS connection established to mxext1.mailbox.org[80.241.60.212]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange ECDHE (P-384) server-signature RSA-PSS (4096 bits) server-digest SHA256
Mar  4 22:11:20 mail postfix/smtp[1231]: 6E69B1AEA3F1: to=<postmaster@example.com>, orig_to=<root@mail.example.com>, relay=mxext1.mailbox.org[80.241.60.212]:25, delay=0.41, delays=0/0/0.33/0.08, dsn=5.1.1, status=bounced (host mxext1.mailbox.org[80.241.60.212] said: 550 5.1.1 <postmaster@example.com>: Recipient address rejected: User unknown in relay recipient table (in reply to RCPT TO command))
Mar  4 22:11:20 mail postfix/qmgr[1217]: 6E69B1AEA3F1: removed
Mar  4 22:11:35 mail dovecot: imap-login: Disconnected (disconnected before auth was ready, waited 0 secs): user=<>, rip=192.168.1.1, lip=172.31.0.2, TLS handshaking: Connection closed, session=<ivvKgRn298vAqAEB>
```
As you can see, something isn't setup correctly, because there are many references to `mailbox.org` which is the mail server running on `example.com`

Furthermore, when I try and connect as `user@mail.example.com` with Thunderbird I get the error:
```
Mar  4 22:11:35 mail dovecot: imap-login: Disconnected (disconnected before auth was ready, waited 0 secs): user=<>, rip=192.168.1.1, lip=172.31.0.2, TLS handshaking: Connection closed, session=<ivvKgRn298vAqAEB>
```

Any help would be really welcome. Thank you!

**Comment by polarathene** [comment]
This is likely due to a long-standing issue which I can hopefully find time to finally resolve later this month.

It requires our test suite to be more thorough so that various supported configs (_and improved tests, along with proper DNS records_) can properly assess that we change it correctly without breaking stuff for everyone else.

Presently I think you can do:

- DMS MTA with bare-domain: `example.com`, configures partially for `@example.com`.
- DMS MTA with subdomain: `mail.example.com`, also configures partially for `@example.com`.

That's just the mail-server though which your MX records for an email address would direct mail to be sent to.
- If you expect mail from `hello@mail.example.com` to go to IP address + port for DMS A record of `mail.example.com`, then configure one (you said you did not).
- `hello@example.com` will find the MX record you have configured for `example.com` which will direct mail to `mailbox.org` mail-server instead.

So what we see is a mail is sent in the container from the `root` system account (`root@mail.example.com`), and something doesn't go well, so it tries to notify the server admin via the `postmaster` address (_in this case `postmaster@example.com` which is not DMS_):

https://github.com/docker-mailserver/docker-mailserver/blob/2234a53b60dea98a19b17e0ff1d2c091df444040/target/scripts/startup/variables-stack.sh#L43

More on why that snippet is a problem below.

Other configurations on your end aside, I'm pretty sure it's a bug where current code strips out the left most DNS label (_unless bare-domain with only two labels_). AFAIK everything works fine if you wanted `hello@example.com` regardless of the MX record for DMS, but in this case you also want `mail.example.com`. I could be wrong though :sweat_smile: 

---

If you want to investigate it yourself in the meantime, I'd say `DOMAINNAME` that is set here is probably relevant:

https://github.com/docker-mailserver/docker-mailserver/blob/2234a53b60dea98a19b17e0ff1d2c091df444040/target/scripts/helpers/dns.sh#L35-L60

Which impacts these (_and perhaps a few others, but these are most relevant for the issue_):

https://github.com/docker-mailserver/docker-mailserver/blob/2234a53b60dea98a19b17e0ff1d2c091df444040/target/scripts/helpers/postfix.sh#L76-L84

https://github.com/docker-mailserver/docker-mailserver/blob/2234a53b60dea98a19b17e0ff1d2c091df444040/target/scripts/startup/setup.d/networking.sh#L3-L7

https://github.com/docker-mailserver/docker-mailserver/blob/2234a53b60dea98a19b17e0ff1d2c091df444040/target/scripts/startup/setup.d/postfix.sh#L192-L197

https://github.com/docker-mailserver/docker-mailserver/blob/2234a53b60dea98a19b17e0ff1d2c091df444040/target/scripts/startup/variables-stack.sh#L43

---

## Config issues

> ```yaml
>     hostname: mail.example.com
>     domainname: mail.example.com
> ```

You shouldn't be using both together like that. Ideally only `hostname` should be used, `domainname` is for NIS domains that aren't relevant to the project AFAIK. I've not seen any report where it's actually been necessary to use `domainname`.

---

> ```yaml
> image: docker.io/mailserver/docker-mailserver:latest
> ```

I wouldn't advise using `:latest`, be more explicit with our actual latest versions (_also helps for bug reports to know which version you're actually using_)

---

> ```yaml
>       - OVERRIDE_HOSTNAME=mail.example.com
> ```

It should be rare that you need this, especially for subdomain. AFAIK it's relevant when the container is unable to internally recognize the `hostname` setting in the compose config. This happens with host mode networking, or within k8s AFAIK. You shouldn't need it.

---

> ```yaml
>       - SSL_DOMAIN=mail.example.com
> ```

`SSL_DOMAIN` should not be needed AFAIK and planned for removal in future. It should look in `acme.json` to match the value of `HOSTNAME` (_set by `hostname` in compose, or the `OVERRIDE_HOSTNAME` ENV_), and if no match there, it checks the `DOMAINNAME` (`example.com`):

https://github.com/docker-mailserver/docker-mailserver/blob/2234a53b60dea98a19b17e0ff1d2c091df444040/target/scripts/helpers/ssl.sh#L125-L139

I believe `SSL_DOMAIN` was originally added as an override for wildcard cert support, or to change that `acme.json` search order:

https://github.com/docker-mailserver/docker-mailserver/blob/2234a53b60dea98a19b17e0ff1d2c091df444040/test/tests/parallel/set1/tls/letsencrypt.bats#L72-L73

https://github.com/docker-mailserver/docker-mailserver/blob/2234a53b60dea98a19b17e0ff1d2c091df444040/test/tests/parallel/set1/tls/letsencrypt.bats#L132-L134

https://github.com/docker-mailserver/docker-mailserver/blob/2234a53b60dea98a19b17e0ff1d2c091df444040/target/scripts/helpers/ssl.sh#L181-L191

---

> ```yaml
>       - TLS_LEVEL=intermediate
> ```

There's nothing wrong with this. I am just curious if you chose it because you know `modern` was not sufficient, or just as a precaution / troubleshooting?

---

> ```yaml
>     ports:
>     #   - "25:25"
> ```

You do not intend to receive any mail to DMS? Is that why you have this port commented out and no MX record for it?

If so, then your problem is specifically about the internal issue with DMS trying to send mail via `postmaster@example.com`, which does an MX lookup to `mailbox.org` mail-server to send to?

You can try setting the Postmaster address explicitly, to avoid the internal bug where it thinks it's doing the right thing.
- If `hostname: example.com` that is simple to imply, and most users with `hostname: mail.example.com` would want the implicit default `@example.com` for addresses like the Postmaster one.
- See our ENV docs for [`POSTMASTER_ADDRESS`](https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#postmaster_address).
- The [`Usage` docs](https://docker-mailserver.github.io/docker-mailserver/edge/usage/#starting-for-the-first-time) also briefly touch on configuring the postmaster address (_or rather an alias for it as an alternative to the ENV_)

**Comment by sebastian-ruiz** [comment]
Thank you for your help. It works with SMTP port 25 but not port 587

I created an MX record:
```
Hostname: mail.example.com 
Value: mail.example.com
Priority: 1
TTL: 60
```
Also I have my A record (I already had this one):
```
Hostname: mail.example.com
Redirects to: xxx.xxx.xxx.xxx
TTL: 1800
```

```yaml
services:

  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.example.com
    ports:
      - "25:25" # SMTP
      - "587:587" # SMTP SSL
      - "993:993" # IMAP SSL
    volumes:
      - ./traefik-data/acme.json:/etc/letsencrypt/acme.json:ro
      - ./data/dms/mail-data/:/var/mail/
      - ./data/dms/mail-state/:/var/mail-state/
      - ./data/dms/mail-logs/:/var/log/mail/
      - ./data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SSL_TYPE=letsencrypt
      - TLS_LEVEL=intermediate
      - POSTMASTER_ADDRESS=user@mail.example.com
      - ENABLE_SPAMASSASSIN=0
      - SPAMASSASSIN_SPAM_TO_INBOX=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - SPOOF_PROTECTION=0
      - LOG_LEVEL=debug

      - PERMIT_DOCKER=connected-networks
    cap_add:
      - NET_ADMIN # For Fail2Ban to work

    restart: unless-stopped

  whoami:
    image: docker.io/traefik/whoami:latest
    networks:
      - web
    labels:
      - "traefik.http.routers.whoami.rule=Host(`mail.example.com`)"

networks:
  web:
    external: true
```

Created `data/dms/config/postfix-main.cf` with:
```
mydestination = localhost.$mydomain, localhost
```
as written in the [wiki](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#can-i-use-a-nakedbare-domain-ie-no-hostname).

I enabled `port 25`. I originally had it disabled because I didn't want to use the mailserver to send emails. However, now I enabled it and **when I connect via Thunderbird and specify the SMTP port as 25, I can connect!!**

However, when I use `port 587`, I cannot connect and this is what I get in my logs:

```
[   INF   ]  Post-configuration checks
[  DEBUG  ]  Checking /var/mail permissions
[   INF   ]  Starting miscellaneous tasks
[  DEBUG  ]  Consolidating all state onto /var/mail-state
[   INF   ]  Starting daemons
[  DEBUG  ]  Starting cron
[  DEBUG  ]  Starting rsyslog
[  DEBUG  ]  Starting dovecot
[  DEBUG  ]  Starting update-check
[  DEBUG  ]  Starting opendkim
[  DEBUG  ]  Starting opendmarc
[  DEBUG  ]  Starting postfix
[  DEBUG  ]  Starting changedetector
[  DEBUG  ]  Starting amavis
[   INF   ]  mail.example.com is up and running
Mar  5 16:56:07 mail amavis[567]: starting. /usr/sbin/amavisd-new at mail.example.com amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"
Mar  5 16:56:07 mail amavis[567]: perl=5.032001, user=, EUID: 110 (110);  group=, EGID: 112 112 (112 112)
Mar  5 16:56:07 mail amavis[567]: Net::Server: Group Not Defined.  Defaulting to EGID '112 112'
Mar  5 16:56:07 mail amavis[567]: Net::Server: User Not Defined.  Defaulting to EUID '110'
Mar  5 16:56:07 mail amavis[567]: No ext program for   .zoo, tried: zoo
Mar  5 16:56:07 mail amavis[567]: No ext program for   .doc, tried: ripole
Mar  5 16:56:07 mail amavis[567]: No decoder for       .F
Mar  5 16:56:07 mail amavis[567]: No decoder for       .doc
Mar  5 16:56:07 mail amavis[567]: No decoder for       .zoo
Mar  5 16:56:09 mail postfix/master[1214]: daemon started -- version 3.5.17, configuration /etc/postfix
Mar  5 16:56:09 mail postfix/pickup[1218]: C7A7F1AEA3FB: uid=0 from=<root>
Mar  5 16:56:09 mail postfix/cleanup[1223]: C7A7F1AEA3FB: message-id=<20230305155609.C7A7F1AEA3FB@mail.example.com>
Mar  5 16:56:09 mail opendkim[507]: C7A7F1AEA3FB: no signing table match for 'root@mail.example.com'
Mar  5 16:56:09 mail opendkim[507]: C7A7F1AEA3FB: no signature data
Mar  5 16:56:09 mail postfix/qmgr[1219]: C7A7F1AEA3FB: from=<root@mail.example.com>, size=713, nrcpt=1 (queue active)
Mar  5 16:56:09 mail dovecot: lmtp(1237): Connect from local
Mar  5 16:56:09 mail dovecot: lmtp(user@mail.example.com)<1237><TLwfMpm7BGTVBAAA48X4Kg>: msgid=<20230305155609.C7A7F1AEA3FB@mail.example.com>: saved mail to INBOX
Mar  5 16:56:09 mail dovecot: lmtp(1237): Disconnect from local: Client has quit the connection (state=READY)
Mar  5 16:56:09 mail postfix/lmtp[1234]: C7A7F1AEA3FB: to=<user@mail.example.com>, relay=mail.example.com[/var/run/dovecot/lmtp], delay=2.4, delays=2.3/0/0.01/0.01, dsn=2.0.0, status=sent (250 2.0.0 <user@mail.example.com> TLwfMpm7BGTVBAAA48X4Kg Saved)
Mar  5 16:56:09 mail postfix/qmgr[1219]: C7A7F1AEA3FB: removed
Mar  5 16:56:36 mail dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=192.168.1.1, lip=172.31.0.2, TLS handshaking: Connection closed, session=<OCAkOSn2QdPAqAEB>
```
Any ideas why port 587 doesn't work? Something must be wrongly configured.

**Comment by polarathene** [comment]
> Any ideas why port 587 doesn't work? Something must be wrongly configured.

A rough guess is that port 25 is using plain-text (no STARTTLS). If this is the case, 587 may be problematic due to your reverse-proxy with Traefik not handling that properly. AFAIK Traefik is compatible, whereas others like Nginx and Caddy are not (_technically nginx can via extra config and module for handling starttls, Caddy may also have a plugin that can do similar_).

You can try exposing port 465 and connecting to that instead. This serves the same purpose, but instead of STARTTLS that port 587 uses, it would implicitly use TLS straight-away, no protocol negotiation to upgrade involved, and that should work. If that does then your Traefik config is not correct for handling port 587 (must proxy TCP).

**Comment by sebastian-ruiz** [comment]
The ports aren't going through traefik. Traefik is only on port `443` and is used to generate the letsencrypt certificate.

Both ports `587` (STARTTLS) and `465` (SSL/TLS) work now! I'm not sure what was originally wrong with my `587` configuration.
