### ISSUE TITLE
[FR] Make it easier for people to find the docs for the latest release

### ISSUE THREAD

**Issue by jrpear** [docker-mailserver/docker-mailserver#3173]
# Feature Request

Essentially, I'd like to change all user-facing documentation links to point to `latest` rather then `edge`. I also propose changing the docs theme to make it more obvious what documentation version you're using.

## Context

#3169 

### Is your Feature Request related to a Problem?

I was confused about the absence of an unreleased feature from the latest release because I was reading the docs for edge rather than the latest release.

I remember seeing the message on the landing page that "This documentation is versioned". I didn't know that I'd pulled "latest" rather than "edge" from docker hub. By the time I'd encountered the version-related issue, I'd forgotten that I was on the `edge` documentation rather than `latest`.

Here's what I did:

* I used the docs linked from project description, which took me to the docs for edge.

* I started on [the usage page](https://docker-mailserver.github.io/docker-mailserver/edge/usage/). That page had me download `docker-compose.yml` and `mailserver.env` from `master`.
  * The path of least resistance had me working with master/edge rather than the latest release, which is maybe not ideal, but it was consistent so far.

* I edited `mailserver.env` according to the comments in it (big fan of this workflow btw).

* I ran `docker-compose`. The `docker-compose.yml` from `master` pulls `latest`, not `edge`. So now I was working with the image from `latest`, but with the docs and commented `mailserver.env` from `edge`.

* Not wanting to bother with DKIM initially, I set `ENABLE_OPENDKIM=0`, an `edge`-only feature. It didn't work, so I opened 
#3169 in error.

#### Change the user-facing links

I think we should replace every user-facing link to the `edge` docs with a link to the `latest` docs. Everyone who is getting started with docker-mailserver will start with the latest release. So this would mean certainly changing the **project description**, **README**,  **docker hub description**, **`mailserver.env` comments**, and maybe more.

...But what about links in the docs? Right now the `edge` "Usage" page has people download `mailserver.env` and `docker-compose.yml` from master. How will each version after 12 tell people to download the right `docker-compose.yml` and the right `mailserver.env`? Does this problem show up anywhere else in the docs? Has it already been solved somehow? I don't know. Does anyone know?

#### Make the documentation version easier to identify

Change the mkdocs theme to display the version even after scrolling down. Now, if you're scrolled down, the only way to know what version you're looking at is the URL.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute??

One thing I could do is make a `latest` version of the docs that points to the last release, so that the links in the description etc. wouldn't have to be changed every release, then change the links.

I could also look into modifying the theme to keep the version displayed after scrolling down. Perhaps with the first change this won't even be necessary though!

### Alternatives you've considered

I outlined two solutions that could both be implemented, but if one of them is unsatisfactory, I could just do one or the other.

### Who will that Feature be useful to?

New users

### What have you done already?

Nothing

**Comment by polarathene** [comment]
> Change the user-facing links

I am not sure how easy it would be to provide a `latest` version that maps to the last released tag. I think it would require some juggling in the mentioned `versions.json` below or manual intervention (_which is a bit of a hassle with the current setup_).

If that were resolved, you'd have a `latest` version like the `edge` available, which is helpful for some user-facing links (and why we use `edge` presently I think).

Regarding other links, the docs are designed with relative links in the markdown files, and these are resolved to the version they're built for at build time. So nothing to worry about that :+1: 

Links to files in our master branch, this is a little bit difficult to adjust to tagged commits instead. Some links to our repo are already referencing static points in time IIRC, you'd probably be able to use `sed` with a pattern to only adjust the ones that are necessary, and I believe the commit hash is available during our workflow that builds the docs, so it could make this change before performing the build.

More of an issue outside the docs in other locations you mentioned perhaps. I'd rather master / edge links vs outdated links that we forget to manually bump for several releases, especially since it's not really viable for anything in our git history to be rewritten, once it's released with our current release approach (master branch tagged commits), it's forever that way (_docs can be amended manually though as they live on `gh-pages` branch split by directories_).

One way to sort of avoid that issue is to add a scheduled workflow that runs `lychee` or similar to check (_pattern matching is probably doable_). Presently we tag via Github Releases with our release notes, and then CI performs release jobs, that has bitten us in the past, and probably should be tagged by CI from a manual trigger that runs some checks first, just no one has found time to set that up :sweat_smile: 

---

> Make the documentation version easier to identify

I've detailed this further below for you, there's a few options available to tackle that, some will be easier, others perhaps more trouble than it's worth :sweat_smile: 

---

> I also propose changing the docs theme to make it more obvious what documentation version you're using.

It's been a while since I looked into the [docs of "mkdocs material"](https://squidfunk.github.io/mkdocs-material/) (_the project we use for generating our docs_), maybe they've improved support for the version selector visibility or theming, I'm not sure.

I do recall some basic theme support is in place, so we could make this more obvious with our `:edge` docs changing something there perhaps.

---

Here's a bunch of information to help navigate how we manage our docs, which should better enable to you to contribute the feature:

- You'll find basic [theme config here in `mkdocs.yml`](https://github.com/docker-mailserver/docker-mailserver/blob/0baf82f7d0d1f160edef86012ebcac4131ea9ebe/docs/mkdocs.yml#L39).
- In that same config is [extra CSS](https://github.com/docker-mailserver/docker-mailserver/blob/0baf82f7d0d1f160edef86012ebcac4131ea9ebe/docs/mkdocs.yml#L57-L59) that I wrote to make some adjustments / fixes. The CSS file it points to does have some styles that [targets and modifies the version selector](https://github.com/docker-mailserver/docker-mailserver/blob/0baf82f7d0d1f160edef86012ebcac4131ea9ebe/docs/content/assets/css/customizations.css#L37-L42). You might be able to restore visibility via CSS, presumably JS is used to toggle visibility.

- A quick scan through the docs, there is a [version warning banner offered now](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#version-warning) that could be added.
- Version selector uses a [JSON config from](https://github.com/docker-mailserver/docker-mailserver/blob/gh-pages/versions.json) (_lives only on the `gh-pages` branch_) a third-party plugin I think called `mike`, but we've got a slightly custom setup where [we manage the JSON ourselves](https://github.com/docker-mailserver/docker-mailserver/blob/0baf82f7d0d1f160edef86012ebcac4131ea9ebe/docs/mkdocs.yml#L61-L66) (_`mkdocs.yml` config, the actual modifications to JSON occurs in [this workflow step](https://github.com/docker-mailserver/docker-mailserver/blob/0baf82f7d0d1f160edef86012ebcac4131ea9ebe/.github/workflows/docs-production-deploy.yml#L72-L107)_) instead of the `mike` command. So although there are now [docs about setting a default version](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#setting-a-default-version), keep that in mind.
- Our actual updates to that JSON config for the version selector is managed in [this shell script file with `jq`](https://github.com/docker-mailserver/docker-mailserver/blob/0baf82f7d0d1f160edef86012ebcac4131ea9ebe/.github/workflows/scripts/docs/update-versions-json.sh#L41-L56). I don't remember too much here, but it might be possible to make a `latest` version or alias, and update that each time a new tag/release is being added (that isn't `edge`).
- The production docs deploy (_our preview docs for PRs don't use a version selector_), has [a separate script to build](https://github.com/docker-mailserver/docker-mailserver/blob/0baf82f7d0d1f160edef86012ebcac4131ea9ebe/.github/workflows/scripts/docs/build-docs.sh). But our customization changes between `edge` and release tags is [in the production deploy workflow](https://github.com/docker-mailserver/docker-mailserver/blob/0baf82f7d0d1f160edef86012ebcac4131ea9ebe/.github/workflows/docs-production-deploy.yml#L33-L41), where you can see a change is made to `mkdocs.yml`. It may be simpler changing theme colour there, or using the version banner feature instead of messing with the `versions.json` file / scripts.

---

All the best with tackling this to whatever extent you're comfortable with :+1: 

No worries if you change your mind though, it's now documented here for anybody that would like to tackle it :sunglasses:

**Comment by jrpear** [comment]
> I'd rather master / edge links vs outdated links that we forget to manually bump for several releases

Strong agree. Making a `latest` version of the docs would address this, right? Just want to make sure I've understood you here.

> All the best with tackling this to whatever extent you're comfortable with
> 
> No worries if you change your mind though, it's now documented here for anybody that would like to tackle it

Thanks! I appreciate all the guidance :)

The first thing I'll do is look into making a `latest` version of the docs. I think that and the link changes will be the best bang for my buck.

**Comment by polarathene** [comment]
> Making a `latest` version of the docs would address this, right? Just want to make sure I've understood you here.

It should, I assume this would be an alias in `versions.json`, but it's been a couple years since I last worked on that.

You'd need the script to first check for an existing `latest` and remove that, then add it to the new version - which could be the same one (_`11.3.0` and `11.3.1` are separate tags, but share the same `11.3` docs version_), and obviously `edge` should not assigned the `latest` alias_).

- We deploy docs on Github Pages, which I recall being a bit more limited than other platforms like Netlify (_which we use for our doc previews in PRs_). I am not sure how well that will handle the URL with `latest` since it wouldn't match any directory, so the version selector may work (_if it redirects the `latest` version alias to the version it was assigned, eg `11.3`_), but the URL part may not. Possibly could duplicate the latest release dir into a `latest` dir (on the `gh-pages` branch), or maybe Github Pages supports symlinks, neither is particularly ideal though :sweat_smile: 
- That's a lot of hassle vs the banner feature mkdocs material has. It will display if the displayed version does not have the `latest` alias assigned in `versions.json`, so that'd also display for `edge` which works well even if that remains the default.
