### ISSUE TITLE
Unit tests failing with messages like `No such container: dms-test_pop3`

### ISSUE THREAD

**Issue by jrpear** [docker-mailserver/docker-mailserver#3191]
# Subject

I would like to contribute to the project

## Description

I'm testing a change I'd like to propose, and I couldn't get the tests to pass on `master`.

I run these commands on my Debian (unstable) machine (copied from [contributing](https://docker-mailserver.github.io/docker-mailserver/edge/contributing/tests/)):

```bash
sudo apt-get -y install jq parallel

git clone https://github.com/docker-mailserver/docker-mailserver.git

cd docker-mailserver
git submodule update --init --recursive

make clean tests
```

I get lots of test failures on the form:

```
mail_pop3.bats
 ✗ setup_file failed []
   (from function `assert_success' in file test/test_helper/bats-assert/src/assert_success.bash, line 42,
    from function `_common_container_create' in file test/helper/setup.bash, line 174,
    from function `_common_container_setup' in file test/helper/setup.bash, line 195,
    from function `setup_file' in test file test/tests/serial/mail_pop3.bats, line 15)
     `_common_container_setup 'CUSTOM_SETUP_ARGUMENTS'' failed
   
   -- command failed --
   status : 1
   output (2 lines):
     Unable to find image 'mailserver-testing:ci' locally
     Error response from daemon: pull access denied for mailserver-testing, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
   --
   
   Error: No such container: dms-test_pop3
```

Any guidance?

<details>
<summary>Note to self</summary>
related: #2280
</details>

**Comment by polarathene** [comment]
I think the error is a bit misleading here.

Your actual failure is due to no local image of `mailserver-testing:ci`. You get this image by building a new Docker image from the git project you just cloned, but you need to invoke `make build` to do that.

This is [mentioned on the same docs you've referenced](https://docker-mailserver.github.io/docker-mailserver/edge/contributing/tests/#executing-tests), you've just accidentally missed that part:

> You will first need to build the container image via `make build`.

---

Perhaps the docs should shift that down into the list as the first step instead for better visibility?

**Comment by jrpear** [comment]
Ah yep, I did miss that. I was just reading the bullets :sweat_smile:. I think it would be slightly better if that instruction were in the list. But I should have just read better. I'll open a PR.

**Comment by polarathene** [comment]
Closing as this has been resolved :+1:
