### ISSUE TITLE
Client host rejected: cannot find your hostname

### ISSUE THREAD

**Issue by johncadengo** [docker-mailserver/docker-mailserver#3224]
I have a special setup and I can't really find information about this elsewhere. I have two ISPs. One ISP comes through on my standard IP address on my lan, `192.168.1.1`. When pointing the MX record to the public facing IP that routes in through `192.168.1.1` I receive emails just fine. However, for my second ISP, I wanted to setup a 2nd backup MX record. I wanted to test what would happen if the first were to fail. When the first MX record fails and then it routes through the 2nd one, it routes through my other gateway on the LAN at `192.168.1.21`.

It then gives me an error like this:
```
mail    | Apr  5 19:31:45 hostname postfix/smtpd[1493]: NOQUEUE: reject: RCPT from unknown[192.168.1.21]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.1.21]; from=< example@gmail.com> to=<example@domain.com> proto=ESMTP helo=<mail-ot1-f48.google.com>
```

How can I set it up to be able to accept emails routing through `192.168.1.21` as well as the original `192.168.1.1`?

**Comment by polarathene** [comment]
I don't have time to try assist, but I can direct you to potentially relevant information that may help you troubleshoot:
- https://github.com/docker-mailserver/docker-mailserver/issues/2970#issuecomment-1371935103
- https://github.com/docker-mailserver/docker-mailserver/pull/2691
- https://github.com/docker-mailserver/docker-mailserver/pull/3061#issuecomment-1418297082

If you put the error you used as the [issue title into the github issue search for this project](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue+%22Client+host+rejected%3A+cannot+find+your+hostname%22), you'd have landed on that too (_ironic, since I was reviewing doc improvements today that make a point of this_).

---

If you don't have luck following those breadcrumbs, you may want to raise a proper bug report to improve your chances of getting assistance from other maintainers who are likely to close this issue.

**Comment by johncadengo** [comment]
@polarathene I understand your frustration with receiving so many numerous bug reports or poorly described issues. 

I was a bit confused about the `issue/no template - no support` tag being added to my issue. Felt unwarranted. It appears that around the time of answering this question the issue templates were updated: https://github.com/docker-mailserver/docker-mailserver/commit/e4543da4d5f2e618fa4b3683586b062545fe72b2 but unfortunately none of the templates seem to match my issue, which is why I went with a generic one and just wrote my issue out with words instead of filing in a template.

I didn't mean to trigger some "oh no not this again" response for you. But I want to be clear that this isn't yet another instance of whatever you felt was happening. Of course I had looked up my actual bug, I spent several hours debugging and troubleshooting, and none of the issues you linked, nor the issues I examined actually addressed my issue. Which is why I posted. It seems I needed some proof of having done my homework before posting because the assumption is that I didn't look through them in the first place if I didn't use a template.

I appreciate the work that you and the other maintainers have done on this repository. It appears you're short on time and that's understandable. If this isn't the place to seek support, I get it. I have a workaround to my issue. I just thought someone who has some experience in this area might know the solution to my problem and be able to offer some pointers in the right direction. It doesn't look like I'm looking in the right place. Thanks for your time.

**Comment by georglauterbach** [comment]
I'd like to quickly chime in here as well :) Please always keep in mind that we do not offer personal support on the issue tracker. One might argue your issue would be personal support.

I wouldn't actually say so though; mainly because this could be interesting for other users as well. The actual problem, and the reason I think the label was added, was that we as maintainers need _as much information as you can offer_, and to be blunt: your initial text simply doesn't offer enough information (which version of DMS are you using; what's the value of `PERMIT_DOCKER`; are you using NAT? if so, how even does it work for the first ISP?; all of the addresses are local reserved addresses mail servers usually do not like to work with - have you anonymstes them?; you get the idea..). Even though this might not fit a bug 100%, the bug template would force you into providing more information.

Hence, we would greatly appreciate if you could take the time and fill out the bug template for your issue, with as much info as possible, and also provide your workaround, so other users might be able to benefit from it as well. We could consider adding it to the docs then.

**Comment by johncadengo** [comment]
@georglauterbach Thanks for the understanding. This is precisely why I brought up the issue at all -- so that others who run into my situation might benefit. It's why I have an account on Github, it's why I try my best to be part of the open source community, chime in when I can, and contribute when I can. I didn't think of it as personal support and I'm not really seeking personal support here. 

When I have time I'll open up a new issue and provide a more detailed description of what I experienced and see if that helps.

**Comment by polarathene** [comment]
> I raised a "help wanted" question, not a bug report.
> which is why I went with a generic one and just wrote my issue out with words instead of filing in a template.

Ok, but if you want to say "I have a problem, something isn't working right", then provide no insights by sharing your config (_which we often see is misconfiguration by the user too_), it's just going to result in us asking for that information most of the time.

>  spent several hours debugging and troubleshooting, and none of the issues you linked (which I had already seen), nor the other issues I examined actually addressed my issue.
> It seems I needed some proof of having done my homework before posting because the assumption is that I didn't look through them in the first place if I didn't use a template.

Yes, that is our go-to response to assume such, since it's usually the case. When you don't share what you've tried, or references issues that seem to have the same error you shared (_and explaining why they're not applicable_)... how would we know?

If you actually bring that to our attention upfront, we can better utilize our time to engage with you, and it makes the issue more easier to discover by the next user that potentially runs into the same or similar problem.

> I appreciate the work that you and the other maintainers have done on this repository. It appears you're short on time and that's understandable.
> It doesn't look like I'm looking in the right place. Thanks for your time.

It was almost 2am for me and I'm close to burn out from all my volunteer commitments, in addition to regular pressures of life.

I tried:
- To be helpful with some links to look into.
- Clarified that I am pressed for time (_granted, I communicated that poorly and could have tried to be more welcoming_).
- Relayed to you that if the links weren't helpful and you would like to improve chances to get assistance, to provide more information via a proper bug report.

I hope you can understand that I didn't mean to be rude and dismissive.

---

> When I have time I'll open up a new issue and provide a more detailed description of what I experienced and see if that helps.

That sounds great! :grin: 

Be sure to link back to this issue and if you think the workaround would be helpful to others, share that too.

Also, I know you've dismissed the links I provided, but you're certain that the [following rules mentioned here](https://github.com/docker-mailserver/docker-mailserver/issues/2650#issuecomment-1160004457) do not apply in your situation?

As you've not shared proper configuration with us, it's difficult to tell, but the log you shared:

```
RCPT from unknown[192.168.1.21]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.1.21]; from=< example@gmail.com> to=<example@domain.com> proto=ESMTP helo=<mail-ot1-f48.google.com>
```

- What is the hostname for `192.168.1.21`?
- What is your containers `/etc/hosts` looking like?
- Does it define both of these private network addresses to a hostname that matches the one assigned to the container? (_you're definitely using only `hostname:` and not `domainname:` in compose config right?_)
- These IP are assigned to the containers network? Or is a proxy involved that is confusing Postfix of the original client IP? NAT?

One of the linked issues had a [comment with the same error log](https://github.com/docker-mailserver/docker-mailserver/pull/2691#issuecomment-1279199755), private IP address despite being from `@gmail` and `google.com` helo... AFAIK, the IP to the right of _"cannot find your hostname"_ is meant to belong to the client delivering you mail (_`google.com` helo from their MTA_). That would all align with the rules I linked you to, and would require you to resolve that incorrect IP of the actual client.

I don't know what your workaround presently is but I'm pretty sure the error is due to the feature the linked PR added as that is what should cause the error to happen in the first place...?

[`/tmp/docker-mailserver/user-patches.sh`](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/override-defaults/user-patches/):

```bash
#! /bin/bash

# Disable this smtpd_sender_restriction
sed 's/, reject_unknown_client_hostname//' /etc/postfix/main.cf
```

That should be compatible with current releases and v12 (_moved from `smtpd_sender_restrictions` to `dms_smtpd_sender_restrictions`_) :+1: 

---

@georglauterbach possibly relevant now since you're pursing rspamd integration, the Postfix feature I linked to has an ]rspamd equivalent AFAIK and another competing project to us switched to it](https://github.com/docker-mailserver/docker-mailserver/issues/2650#issuecomment-1186637668). Might be worth looking into :+1:

**Comment by georglauterbach** [comment]
> @georglauterbach possibly relevant now since you're pursing rspamd integration, the Postfix feature I linked to has an https://github.com/docker-mailserver/docker-mailserver/issues/2650#issuecomment-1186637668. Might be worth looking into 👍

Very interesting indeed! There have been requests to make this configurable. I will tackle this soon.
