### ISSUE TITLE
[QUESTION]: How to use custom SpamAssassin rules with Amavis?

### ISSUE THREAD

**Issue by lugdunum-1964** [docker-mailserver/docker-mailserver#3308]
### Subject

I would like to configure a not documented mail server use case

### Description

Hi,

I'm currently inundated with RB-USA Sunglasses spam. In order to block it, I wrote an extra spamassassin rule in config/spamassassin-rules.cf and enabled local_user_rules in local.cf using user-patches.sh

Testing the mail with spamassassin -t on the mailserver node now does indeed flag the mails as spam, but docker mailserver keeps on passing them on to my inbox, without a spam report.

I found an earlier issue saying that docker mailserver uses amavis, which in turn uses the spamassassin libraries, but not the script or the daemon.

The question now is how do I configure amavis to block the mails, either based on the spamassassing config or other rules testing the "From" field or the body.

--
Regards,
Lyon

**Comment by lugdunum-1964** [comment]
Thanks for the quick reply. 
I have both enabled, but to me it appears as if my custom rules are not applied.  To all appearances the mails are now not recognized as spam by the server (no X-SPAM header). Whereas when I run the spamassassin script on the node itself, from the commandline, it does flag the mails as spam.

Maybe this is because spamassassin or the spamd are not used directly by amavis? And therefor the custom rules or the allow_user_rules flag are not seen?

This is what I get when I run spamassassin -t on one of these mails:
```
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on mail.redlemon.nl
X-Spam-Flag: YES
X-Spam-Level: **************************
X-Spam-Status: Yes, score=26.9 required=5.0 tests=DKIM_SIGNED,DKIM_VALID,
    DKIM_VALID_AU,DKIM_VALID_EF,FROM_SUSPICIOUS_NTLD,
    FROM_SUSPICIOUS_NTLD_FP,HTML_FONT_LOW_CONTRAST,HTML_IMAGE_RATIO_04,
    HTML_MESSAGE,LOCALPART_IN_SUBJECT,MIME_HTML_ONLY,PYZOR_CHECK,
    RCVD_IN_DNSWL_HI,RCVD_IN_ZEN_BLOCKED_OPENDNS,SPF_HELO_PASS,
    T_PDS_OTHER_BAD_TLD,T_SCC_BODY_TEXT_LINE,T_SPF_PERMERROR,
    URIBL_ABUSE_SURBL,URIBL_BLOCKED,URIBL_DBL_BLOCKED_OPENDNS,
    URIBL_ZEN_BLOCKED_OPENDNS,URI_TRUNCATED,
    **USER_FROM_RB_USA**
    autolearn=unavailable autolearn_force=no version=3.4.6
```

The USER_FROM_RB_USA is my custom rule, giving a score of +25

And this is what the headers are in my inbox:
```
X-Virus-Scanned: Yes
Received-SPF: Permerror (mailfrom) identity=mailfrom; client-ip=104.148.75.179; helo=channel.stingo.top; envelope-from=channel@stingo.top; receiver=<UNKNOWN> 
Authentication-Results: mail.redlemon.nl; dmarc=fail (p=none dis=none) header.from=stingo.top
X-Greylist: delayed 602 seconds by postgrey-1.36 at mail; Fri, 05 May 2023 18:07:50 CEST
Received: from channel.stingo.top (channel.stingo.top [104.148.75.179])
	by mail.redlemon.nl (Postfix) with ESMTPS id CA38A50B16
X-MSMail-Priority: Normal
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.2869
 List-Unsubscribe: <https://www.sexydoll4u.com/list.cgi?cmd=unsub&lst=list>,
 <mailto:allen@sexydoll4u.com?subject=unsubscribe>
MIME-Version: 1.0
From: =?utf-8?Q?RB=2DUSA=C2=AE_Sunglasses?= <channel@stingo.top>
Content-Transfer-Encoding: base64
```

**Comment by georglauterbach** [comment]
Truth be told, I really don't have too much clue about SpamAssassin. I am the maintainer that pushed Rspamd forward over the last month, and with the soon upcoming v12.1.0 (May 10), Rspamd is stable in DMS.

This may not sound like the greatest advise, but you could try using Rspamd instead of SA/Amavis when v12.1.0 drops. Here is a [link to a page that describes blacklisting with Rspamd](https://www.allerstorfer.at/whitelists-with-rspamd/). You could set the action to `add-header` (I think) and then use `MOVE_SPAM_TO_JUNK=1` (and probably you want `RSPAMD_LEARN=1` as well). Or set the action to plain `reject`.

**Comment by lugdunum-1964** [comment]
Thanks for the advise. I guess I can wait 3 more days :)

**Comment by casperklein** [comment]
Via `user-patches.sh`

```
# DISCARD/REJECT mails based on header
# http://www.postfix.org/header_checks.5.html
echo '/^Subject:.*Buy Viagra.*/                 DISCARD spam' >> /etc/postfix/maps/header_checks.pcre
echo '/^Subject: The Best Way to Invest.*/      DISCARD spam' >> /etc/postfix/maps/header_checks.pcre
```

**Comment by lugdunum-1964** [comment]
That worked immediately! Cheers!

**Comment by georglauterbach** [comment]
@ghnp5 technically, there is no problem. You will see a warning in the log, as this setup is discourages. This is not _necessarily_ due to technical reasons, but more because we are going to deprecate Amavis/SA with upcoming releases.

Your setup _should_ work fine. That being said, there are some reasons you might want to avoid it:

1. Double the count of DNS queries to DNSBLs
2. The order in which e-mails are checked is not entirely clear to me (is Amavis/SA first, or Rspamd)
3. Technically, Amavis/SA can do the same as Rspamd (and vice versa), hence using one is easier to maintain

**But yes**, you should be able to use both simultaneously.

**Comment by ghnp5** [comment]
Thank you very much for your reply!

> more because we are going to deprecate Amavis/SA with upcoming releases

Aaahhhh...... I know very little about rspamd, but do you know if there's a way to easily migrate all SA configs to rspamd, in a way that all the current behavior is replicated?

Cheers!

**Comment by georglauterbach** [comment]
> Aaahhhh...... I know very little about rspamd, but do you know if there's a way to easily migrate all SA configs to rspamd, in a way that all the current behavior is replicated?

Sadly, I don't..
