### ISSUE TITLE
[QUESTION]: How to configure certificates for multiple domains?

### ISSUE THREAD

**Issue by Jarrodsz** [docker-mailserver/docker-mailserver#3313]
### Subject

Problem with configuration?

### Description

Setup multiple 
Mail.domain.ltd pointing to my mailserver ip.

However, when mail.domain.ltd is the main domain i always get errors when i try to setup other emsil accounts.

if i configure mail.secondary.ltd i get an error the certificate is incorrect and it tries to load the mail.domain.ltd certificate.

i have enabled ssl with letsencrypt on port 587 and disabled port 25.

what am i missing here?
I expected it would pick the right certificate for each domain but it does not.

**Comment by polarathene** [comment]
Please file a proper bug report, other maintainers expect it to provide any assistance so that we don't have to guess as much such as with config.

- It is unclear if you're talking about a single certificate with multiple domains or multiple certificates each with their own domain.
- You may have a misunderstanding of configuration. The certificate is not for mail account domains, it is only for the mail server itself, eg `mail.example.com`. If you only run one mail server, then you only need the one certificate. We support additional certificates if you want to support both RSA and ECDSA types (_eg: primarily use ECDSA, but for clients without support RSA is used as an alternative fallback cert_).
- The certificate is to verify trust that you are connected to the mail server it claims to be representing, not some malicious server that hijacked the connection in some manner to be routed through itself instead. As the private key is necessary for the server to sign in the handshake and your client must have the CA (LetsEncrypt) in it's own trust store, these two things help establish trust that the server can prove it was authorized by the CA. Now a secure TLS connection can be established.

Hope that explains things. This is not relevant to the mail account domains, which use different DNS records to direct where mail for that domain is sent to, and what servers/hosts are authorized to send mail on their behalf. Your mail server is not tied to any of those domains, even if it is hosted within one. Since no connection is established to another server related to those domains, they're not relevant to the connection, thus don't need certs to verify trust in the connection.

**Comment by georglauterbach** [comment]
Closing as user-related misconfig.
