### ISSUE TITLE
other: DockerMailserver无法给qq邮箱发送邮件

### ISSUE THREAD

**Issue by wang-dagou** [docker-mailserver/docker-mailserver#3352]
### Subject

I would like to contribute to the project

### Description

Docker Mailserver cannot send mail to QQmail after logging in through LDAP authentication, because the recipient's LDAP authentication is performed when sending mail to QQmail, but this error will not occur when sending mail to other mailboxes, such as mailbox 163. My Lucky Star, my Docker Mailserver can log in through the mail configured in LDAP, but when it is sent to QQmail, it will encounter the following error:

```
mailserver  | May 18 05:42:42 mail postfix/smtp-amavis/smtp[1036]: 4D765A0192A0: to=<1209718728@qq.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=0.27, delays=0.13/0.01/0/0.12, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 87D5EA0192A1)
mailserver  | May 18 05:42:42 mail postfix/qmgr[905]: 4D765A0192A0: removed
mailserver  | May 18 05:42:42 mail dovecot: lmtp(1042): Connect from local
mailserver  | May 18 05:42:42 mail dovecot: auth: ldap(xxxxx@qq.com): unknown user
mailserver  | May 18 05:42:42 mail postfix/lmtp[1041]: 87D5EA0192A1: to=<xxxx@qq.com>, relay=mail.sichuancredit.cn[/var/run/dovecot/lmtp], delay=0.12, delays=0.02/0.01/0.01/0.08, dsn=5.1.1, status=bounced (host mail.sichuancredit.cn[/var/run/dovecot/lmtp] said: 550 5.1.1 <1209718728@qq.com> User doesn't exist: 1209718728@qq.com (in reply to RCPT TO command))
```

After failing to send an email, I will receive an email informing me why I cannot send the email:

> This is the mail system at host `mail.sichuancredit.cn`.
> 
> I'm sorry to have to inform you that your message could not
> be delivered to one or more recipients. It's attached below.
> 
> For further assistance, please send mail to postmaster.
> 
> If you do so, please include this problem report. You can
> delete your own text from the attached returned message.
> 
>                   The mail system
> 
> ```
> <xxxx@qq.com>: host mail.sichuancredit.cn[/var/run/dovecot/lmtp] said:
>     550 5.1.1 <xxxxxx@qq.com> User doesn't exist: 1209718728@qq.com (in
>     reply to RCPT TO command)
> ```

The following is the configuration of environment variables in my Docker Compose file:

```yaml
    environment:
      - ENABLE_SPAMASSASSIN=0
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - ONE_DIR=1

      - ACCOUNT_PROVISIONER=LDAP
      - LDAP_SERVER_HOST=xxxx:10389
      - LDAP_SEARCH_BASE=ou=users,dc=ldap,dc=sichuancredit,dc=cn
      - LDAP_BIND_DN=cn=admin,dc=ldap,dc=sichuancredit,dc=cn
      - LDAP_BIND_PW=xxxxx
      #- LDAP_QUERY_FILTER_USER=(&(|(objectClass=inetOrgPerson))(|(memberOf=cn=mail,ou=groups,dc=ldap,dc=sichuancredit,dc=cn)(memberOf=cn=sichuancredit,ou=groups,dc=ldap,dc=sichuancredit,dc=cn))(mail=%u))
      - LDAP_QUERY_FILTER_USER=(&(|(objectClass=inetOrgPerson))(|(memberOf=cn=mail,ou=groups,dc=ldap,dc=sichuancredit,dc=cn)(memberOf=cn=sichuancredit,ou=groups,dc=ldap,dc=sichuancredit,dc=cn))(|(mail=%u)(mail=*@%s)))

      - LDAP_QUERY_FILTER_GROUP=(&(objectClass=inetOrgPerson)(mail=%u@sichuancredit.cn))
      - LDAP_QUERY_FILTER_ALIAS=(&(objectClass=inetOrgPerson)(mail=%u@sichuancredit.cn))
      - LDAP_QUERY_FILTER_DOMAIN=(mail=*@%s)
      - LDAP_QUERY_FILTER_SENDERS=(mail=%s)

      # <<< Dovecot Authentication
      - DOVECOT_PASS_FILTER=(&(|(objectClass=inetOrgPerson))(|(memberOf=cn=mail,ou=groups,dc=ldap,dc=sichuancredit,dc=cn)(memberOf=cn=sichuancredit,ou=groups,dc=ldap,dc=sichuancredit,dc=cn))(mail=%u))
      #- DOVECOT_PASS_ATTRS=uid=user,userPassword=password
      - DOVECOT_USER_FILTER=(&(|(objectClass=inetOrgPerson))(|(memberOf=cn=mail,ou=groups,dc=ldap,dc=sichuancredit,dc=cn)(memberOf=cn=sichuancredit,ou=groups,dc=ldap,dc=sichuancredit,dc=cn))(mail=%u))
      - DOVECOT_USER_ATTRS=homeDirectory=home,=uid=5000,=gid=5000
      # <<< Dovecot Authentication

      - ENABLE_SASLAUTHD=0
      - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_SERVER=xxxxxx:10389
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=ldap,dc=sichuancredit,dc=cn
      - SASLAUTHD_LDAP_PASSWORD=xxxxx
      - SASLAUTHD_LDAP_SEARCH_BASE=ou=users,dc=ldap,dc=sichuancredit,dc=cn
      - SASLAUTHD_LDAP_FILTER=(&(|(objectClass=inetOrgPerson))(|(memberOf=cn=mail,ou=groups,dc=ldap,dc=sichuancredit,dc=cn)(memberOf=cn=sichuancredit,ou=groups,dc=ldap,dc=sichuancredit,dc=cn))(mail=%u))
      - POSTMASTER_ADDRESS=wangyixiang@sichuancredit.cn
      - POSTFIX_MESSAGE_SIZE_LIMIT=100000000

      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/ssl/mail.sichuancredit.cn_bundle.pem
      - SSL_KEY_PATH=/tmp/ssl/mail.sichuancredit.cn.key
```

A friend can tell me why I can't send an email to QQmail because of this problem. Maybe it's because the address of QQmail is composed of pure numbers, while mailbox 163 is not composed of pure numbers (this is just my guess).

**Comment by polarathene** [comment]
> `mail dovecot: auth: ldap(xxxxx@qq.com): unknown user`
> `User doesn't exist: 1209718728@qq.com`

You are trying to login with LDAP to the `@qq.com` account? Your LDAP auth does not seem aware of this user, so fails login through Dovecot (DMS). It is not advised to have login account for domain you do not own.

If you want to send as `user@qq.com`, then you need to [configure relay host](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/mail-forwarding/relay-hosts/), if QQ support this (Gmail does). That will let you login DMS as `me@sichuancredit.cn` and send mail as `user@qq.com`.

If you have more than one person use DMS, be careful as default config allow all user on DMS send as your `user@qq.com`, instead you would need to create separate QQ login for each user that need this with [Sender-dependent Authentication](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/mail-forwarding/relay-hosts/#sender-dependent-authentication).

---

Maybe I misunderstood, and this happen from failure to send mail to `@qq.com` recipient.

It would be good to check if same problem when not use LDAP. Maybe also try `ENABLE_AMAVIS=0`.

> Maybe it's because the address of QQmail is composed of pure numbers

Maybe. If so, you must find what part does not like the numbers-only address. This is why it is good to check without LDAP and without Amavis.

If `@qq.com` can support account like `user@qq.com`, try this to confirm. Or try account at another mail service with numbers-only username in the address.

**Comment by wang-dagou** [comment]
Thank you for your reply. I am trying to add - ENABLE_ AMAVIS=0, but that still hasn't worked, and it's strange that the recipient still needs to authenticate with LDAP.

mailserver | May 19 00:46:23 mail postfix/smtps/smtpd[921]: disconnect from unknown[192.168.200.124] ehlo=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=6

mailserver | May 19 00:46:23 mail dovecot: lmtp(928): Connect from local

mailserver | May 19 00:46:23 mail dovecot: auth: ldap( 1209718728@qq.com ): unknown user

I have attached the log of my email sent to NetEase email below, hoping that it can help you analyze it




mailserver  | May 19 00:46:23 mail dovecot: lmtp(928): Disconnect from local: Logged out (state=READY)
mailserver  | May 19 00:46:23 mail postfix/lmtp[927]: 7AD6AA0192A0: to=<wangyixiang@sichuancredit.cn>, relay=mail.sichuancredit.cn[/var/run/dovecot/lmtp], delay=0.1, delays=0.04/0/0/0.07, dsn=2.0.0, status=sent (250 2.0.0 <wangyixiang@sichuancredit.cn> GCgPHx//ZmSgAwAAs4oxtw Saved)
mailserver  | May 19 00:46:23 mail postfix/qmgr[904]: 7AD6AA0192A0: removed
mailserver  | May 19 00:49:43 mail postfix/anvil[924]: statistics: max connection rate 1/60s for (smtps:192.168.200.124) at May 19 00:46:23
mailserver  | May 19 00:49:43 mail postfix/anvil[924]: statistics: max connection count 1 for (smtps:192.168.200.124) at May 19 00:46:23
mailserver  | May 19 00:49:43 mail postfix/anvil[924]: statistics: max cache size 1 at May 19 00:46:23
mailserver  | May 19 00:50:36 mail postfix/smtps/smtpd[931]: connect from unknown[192.168.200.124]
mailserver  | May 19 00:50:36 mail postfix/smtps/smtpd[931]: Anonymous TLS connection established from unknown[192.168.200.124]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
mailserver  | May 19 00:50:36 mail postfix/smtps/smtpd[931]: 99954A0192A0: client=unknown[192.168.200.124], sasl_method=LOGIN, sasl_username=wangyixiang@sichuancredit.cn
mailserver  | May 19 00:50:36 mail postfix/sender-cleanup/cleanup[936]: 99954A0192A0: replace: header Mime-Version: 1.0 from unknown[192.168.200.124]; from=<wangyixiang@sichuancredit.cn> to=<wangyixiang0103@163.com> proto=ESMTP helo=<wangyx>: MIME-Version: 1.0
mailserver  | May 19 00:50:36 mail postfix/sender-cleanup/cleanup[936]: 99954A0192A0: message-id=<202305191250348654196@sichuancredit.cn>
mailserver  | May 19 00:50:36 mail opendkim[775]: 99954A0192A0: DKIM-Signature field added (s=mail, d=sichuancredit.cn)
mailserver  | May 19 00:50:36 mail postfix/qmgr[904]: 99954A0192A0: from=<wangyixiang@sichuancredit.cn>, size=2871, nrcpt=1 (queue active)
mailserver  | May 19 00:50:36 mail postfix/smtps/smtpd[931]: disconnect from unknown[192.168.200.124] ehlo=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=6
mailserver  | May 19 00:50:38 mail postfix/smtp[937]: Trusted TLS connection established to 163mx01.mxmail.netease.com[220.181.12.117]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256
mailserver  | May 19 00:50:38 mail postfix/smtp[937]: 99954A0192A0: to=<wangyixiang0103@163.com>, relay=163mx01.mxmail.netease.com[220.181.12.117]:25, delay=1.7, delays=0.15/0.01/1.3/0.25, dsn=2.0.0, status=sent (250 Mail OK queued as zwqz-mx-mta-g9-2,_____wAX744cAGdkE2AiAA--.28687S3 1684471838)
mailserver  | May 19 00:50:38 mail postfix/qmgr[904]: 99954A0192A0: removed

One minute later, I received my test email

**Comment by polarathene** [comment]
> I have attached the log of my email sent to NetEase email below, hoping that it can help you analyze it

- Try send to account with numbers-only username, `1234@163.com`, so that it is like the `@qq.com`. If that works, then it is not the problem.
- Did you try send mail to `@qq.com` without LDAP login for DMS sender? If that works, but LDAP does not, it is helpful information.
- Are you sure there is nothing configured in DMS/LDAP that has `@qq.com` address? Like an alias? This can confuse DMS.

It looks like the mail you send to `@qq.com` thinks it should be delivered to DMS. Perhaps you can try test DMS with only 1 account configured, no aliases. Sending may work properly, this would mean you have configuration problem with your accounts / aliases.

Remember to use `docker compose down && docker compose up` or `docker compose up --force-recreate` when changing your `compose.yaml` file. It will ensure changes are applied properly.

**Comment by wang-dagou** [comment]
I have tried various methods, and only when sending an email to qq.com will there be ldap authentication for the recipient
mailserver  | Jul 12 01:54:48 mail dovecot: lmtp(1079): Connect from local
mailserver  | Jul 12 01:54:48 mail dovecot: auth: ldap(sssasdasdas@qq.com): unknown user

mailserver  | Jul 12 01:58:18 mail dovecot: lmtp(1099): Connect from local
mailserver  | Jul 12 01:58:18 mail dovecot: auth: ldap(120387213ssss@qq.com): unknown user

mailserver  | Jul 12 01:58:33 mail postfix/smtp[1101]: Trusted TLS connection established to 163mx03.mxmail.netease.com[220.181.12.119]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256
mailserver  | Jul 12 01:58:34 mail postfix/smtp[1101]: 8D4D3A019180: to=<120387213ssss@163.com>, relay=163mx03.mxmail.netease.com[220.181.12.119]:25, delay=1.4, delays=0.01/0/0.35/1, dsn=5.0.0, status=bounced (host 163mx03.mxmail.netease.com[220.181.12.119] said: 550 User not found: 120387213ssss@163.com (in reply to RCPT TO command))

And when you don't use ldap as a unified authentication method, you can send emails to QQ, so I think this is definitely a bug

**Comment by polarathene** [comment]
> And when you don't use ldap as a unified authentication method, you can send emails to QQ, so I think this is definitely a bug

Someone will need to look into it, I don't think any maintainers have the time to try investigate as none of us use LDAP or use QQ.

It could be a bug in DMS, or an incompatibility with the LDAP provider, or it could be a user misconfiguration somewhere. Maybe someone else will experience this problem too, that could be helpful.

**Comment by wang-dagou** [comment]
The point is that when my user is trying to send a message to the recipient, they should not search for the recipient in ldap, and this strange phenomenon only occurs when sending an email to qq.com. Although what you said may sound correct about the issue with ldap, it seems that the problem has nothing to do with ldap. Perhaps this is a mysterious problem, and if any other friends have also encountered this problem, I hope you can point out my mistake.

**Comment by polarathene** [comment]
> The point is that when my user is trying to send a message to the recipient, they should not search for the recipient in ldap, and this strange phenomenon only occurs when sending an email to `qq.com`

It could happen if you created an alias / wildcard that would resolve to `@qq.com` maybe. Or if you have any other configuration / account that involves a `@qq.com` address perhaps it introduces the problem.

Sorry that we cannot be of much help here :sweat_smile:

**Comment by Phreeman33** [comment]
使用AD作為LDAP伺服器也遇到相同的問題（無法傳給gmail），而且已能夠穩定復現：當在`LDAP_SEARCH_BASE`中有至少1名使用者的mail屬性為***@gmail.com時，即無法發送至gmail。
查詢DNS Server，郵件發送失敗的時候沒有查詢gmail.com mx紀錄的請求，所以我猜測原因是DMS將LDAP使用者的郵件地址網域視為內部網域，查找不到對應的***@gmail.com地址或內部DNS解析失敗。
所以目前的解決方案就是別讓DMS查詢到不屬於內部網路的郵件網域，將造成問題的使用者放在DMS查詢不到BASE或將外部郵件地址放在DMS查詢不到的屬性是比較合理的方式。

When using AD as an LDAP server, the same issue occurs (unable to send to Gmail), and it can now be reproduced consistently: when at least one user in the `LDAP_SEARCH_BASE` has a mail attribute of ***@gmail.com, it fails to send to Gmail.
Upon checking the DNS server, when the mail sending fails, there is no request for the MX record of gmail.com. Therefore, I suspect the reason is that the DMS treats the email domain of LDAP users as an internal domain, making it unable to find the corresponding ***@gmail.com address, or the internal DNS resolution fails.
So the current solution is to prevent the DMS from querying email domains that do not belong to the internal network. The more reasonable approaches would be to either place problematic users in a BASE that the DMS cannot query, or to put external email addresses in an attribute that the DMS cannot query.

**Comment by polarathene** [comment]
> Therefore, I suspect the reason is that the DMS treats the email domain of LDAP users as an internal domain, making it unable to find the corresponding ***@gmail.com address, or the internal DNS resolution fails.

As mentioned previously: https://github.com/docker-mailserver/docker-mailserver/issues/3352#issuecomment-1553793581

> _It is not advised to have login account for domain you do not own._
> 
> _If you want to send as `user@qq.com`, then you need to [configure relay host](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/mail-forwarding/relay-hosts/), if QQ support this (Gmail does). That will let you login DMS as `me@sichuancredit.cn` and send mail as `user@qq.com`._

Do not configure DMS to handle mail users with mail domains that DMS does not own. DMS would not receive mail intended for `@gmail.com` or `@qq.com` mail domains, so why configure mail accounts with these address?

You can send mail as any sender address, including `@gmail.com`, but as DMS will not be authorized to do so on behalf of Gmail, this should be rejected. You need to relay to Gmail for that.

For recipient address (_the destination email address DMS will send mail to_), `@gmail.com` will work correctly too, **but** DMS must not think that it is responsible of managing that mail domain.

> or to put external email addresses in an attribute that the DMS cannot query.

Yes, this would be wiser. If you cannot control this information you need to ensure that DMS is only querying LDAP for attributes with valid mail accounts that DMS manages for login identity.

This is often confusing in this scenario unfortunately. DMS accounts technically do not need to be email addresses, they could just be a user name like `john.doe` instead of `john.doe@example.com`, however I am not sure if DMS is configured properly to support that as it assumes a mail address for the `ACCOUNT_PROVISIONER=FILE` (default), those assumptions may exist elsewhere too.

---

https://docker-mailserver.github.io/docker-mailserver/v14.0/config/advanced/auth-ldap/#ldap_query_filter_

> ```env
> LDAP_QUERY_FILTER_DOMAIN=(mail=*@%s)
> ```

https://github.com/docker-mailserver/docker-mailserver/blob/26a44995a9bba825b1348dbf3551687c2100f7a3/target/postfix/ldap-domains.cf#L4-L5

https://github.com/docker-mailserver/docker-mailserver/blob/26a44995a9bba825b1348dbf3551687c2100f7a3/target/scripts/startup/setup.d/ldap.sh#L65-L67

https://github.com/docker-mailserver/docker-mailserver/blob/26a44995a9bba825b1348dbf3551687c2100f7a3/target/scripts/helpers/postfix.sh#L75-L82

https://github.com/docker-mailserver/docker-mailserver/blob/26a44995a9bba825b1348dbf3551687c2100f7a3/target/scripts/helpers/postfix.sh#L20-L38

The above is the related configuration for how Postfix in DMS will identify mail domains it owns. If your LDAP configuration results in `@gmail.com` there then you have told DMS that it manages `@gmail.com` so it should not need to send mail out for that domain. That is a misconfiguration.
