### ISSUE TITLE
bug report: `setup alias add` may fail when recipient exists for another alias

### ISSUE THREAD

**Issue by 42l-neil-tmp** [docker-mailserver/docker-mailserver#3358]
### Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I read

  - the [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue;
  - the [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue;
  - this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree;
  - the [documentation about filing a bug report](https://docker-mailserver.github.io/docker-mailserver/latest/contributing/issues-and-pull-requests/#filing-a-bug-report).

### What operating system is the host running?

Linux

### Which operating system version?

Debian 11

### What computer architecture is the host running?

AMD64 (x86_64)

### What container orchestration tool are you using?

Docker Compose

### DMS version

v12.1.0

### What happened and when does this occur?

This issue is similar to #3350 and #3262.

I want to create group aliases, as described in https://github.com/docker-mailserver/docker-mailserver/issues/3262#issuecomment-1509366419 : a fairly simple setup involving two existing mailboxes and an alias used to redirect a mail to those two mailboxes.

Those mailboxes are **not external**: they are **hosted by our DMS instance**, unlike the aforementioned bug reports, hence this new report.

In the following example, **both domain.org and other-domain.org are hosted on our DMS instance**.

```sh
$> ./setup.sh email add testemail1@domain.org
Enter Password:
$> ./setup.sh email add testemail2@domain.org
Enter Password:
$> ./setup.sh alias add group@domain.org testemail1@domain.org
$> ./setup.sh alias add group@domain.org testemail2@domain.org
$> ./setup.sh alias list | grep group
* group@domain.org testemail1@domain.org,testemail2@domain.org
$> ./setup.sh alias add group@other-domain.org testemail1@domain.org
$> ./setup.sh alias add group@other-domain.org testemail2@domain.org
[  ERROR  ]  'group@other-domain.org' is already an alias for recipient: 'testemail2@domain.org'
[  ERROR  ]  Aborting
$> ./setup.sh alias del group@other-domain.org testemail1@domain.org
$> ./setup.sh alias del group@domain.org testemail2@domain.org
$> ./setup.sh alias del group@domain.org testemail1@domain.org
$> ./setup.sh alias add group@other-domain.org testemail1@domain.org
$> ./setup.sh alias add group@other-domain.org testemail2@domain.org
$> ./setup.sh alias add group2@domain.org testemail1@domain.org
$> ./setup.sh alias add group2@domain.org testemail2@domain.org
[  ERROR  ]  'group2@domain.org' is already an alias for recipient: 'testemail2@domain.org'
[  ERROR  ]  Aborting
```

It seems that DMS lets me create one group alias, but creating the second always fails somehow.
It *may* be linked to our usage of DMS with multiple domain names.

Am I doing something wrong, or is it an unintended side effect of #3270 ?

### What did you expect to happen?

I expect to see created aliases without issue.

I agree on the idea of preventing aliases from being accounts (which is the initial goal of #3270), though it seems to have introduced bugs in the `alias add` feature.

### Container configuration files

```yml
[Docker-compose file](https://git.42l.fr/42l/core/src/branch/root/services/mail/docker-compose.yml)
```

### What level of experience do you have with containers, mail servers, and using a terminal?

- [ ] I am inexperienced with containers
- [X] I am rather experienced with containers
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with using a terminal (CLI)
- [X] I am rather comfortable with using a terminal (CLI)

**Comment by polarathene** [comment]
Thanks for raising this bug report, the reproduction provided was helpful to track down the bug :+1: 

This looks like it's a bug in `__db_list_already_contains_value()` that was introduced some time ago, either [during my refactor](https://github.com/docker-mailserver/docker-mailserver/pull/2654) or the previous iteration of those scripts before refactoring into a DB utility.

---

## Failure location

The recent PR change you referenced outputs a different error than the one you encountered:

https://github.com/docker-mailserver/docker-mailserver/blob/da8d3654b83eb78fdd2b22b1fe2c6b5eaf779869/target/scripts/helpers/database/manage/postfix-virtual.sh#L49-L50

https://github.com/docker-mailserver/docker-mailserver/blob/da8d3654b83eb78fdd2b22b1fe2c6b5eaf779869/target/scripts/helpers/database/manage/postfix-virtual.sh#L25-L32

Instead we're seeing the top-level `setup alias add` error message:

https://github.com/docker-mailserver/docker-mailserver/blob/da8d3654b83eb78fdd2b22b1fe2c6b5eaf779869/target/bin/addalias#L13-L14

So the `setup alias add` is attempted via the above `_db_entry_add_or_append()` call:

https://github.com/docker-mailserver/docker-mailserver/blob/da8d3654b83eb78fdd2b22b1fe2c6b5eaf779869/target/scripts/helpers/database/db.sh#L34

https://github.com/docker-mailserver/docker-mailserver/blob/da8d3654b83eb78fdd2b22b1fe2c6b5eaf779869/target/scripts/helpers/database/db.sh#L65-L74

and here is where the bug occurs by calling `__db_list_already_contains_value()`:

https://github.com/docker-mailserver/docker-mailserver/blob/da8d3654b83eb78fdd2b22b1fe2c6b5eaf779869/target/scripts/helpers/database/db.sh#L130-L140

---

## Reproduction

Revised version of the above, since it's not related to multi-domain aliases, but bug in the "database" manager that could affect other databases or methods beyond `setup alias add`.

```bash
docker run --rm -it --hostname example.test mailserver/docker-mailserver bash

setup email add a@example.test password-here
setup email add b@example.test password-here
setup alias add x@example.test a@example.test
setup alias add x@example.test b@example.test
setup alias add y@example.test a@example.test
setup alias add y@example.test b@example.test
# [  ERROR  ]  'y@example.test' is already an alias for recipient: 'b@example.test'
# [  ERROR  ]  Aborting

cat /tmp/docker-mailserver/postfix-virtual.cf
# x@example.test a@example.test,b@example.test
# y@example.test a@example.test

# Incorrectly reports target alias as containing the value (zero status code returned: `echo $?`):
sed -e "s/^y@example\.test\s\(.*\)/\1/" -e "s/,/\n/g" /tmp/docker-mailserver/postfix-virtual.cf | grep -qi "^b@example\.test$"

# Failure due to the output from sed (for grep to filter) was not what was intended/expected:
# (the first two lines are from the `x@example.test` alias)
sed -e "s/^y@example\.test\s\(.*\)/\1/" -e "s/,/\n/g" /tmp/docker-mailserver/postfix-virtual.cf                               
# x@example.test a@example.test
# b@example.test
# a@example.test
```

That would have also been what was causing the bug for the earlier alias reports outputting the same error (_before the recent PR added a guard to disallow that_).

Via `git blame` on [the commit history of my PR](https://github.com/docker-mailserver/docker-mailserver/pull/2654):
- [Introduced the method](https://github.com/polarathene/docker-mailserver/commit/c87a9e1719a5e8d3d8a95006673936b27312f65b)
- [Adjusted the sed logic](https://github.com/polarathene/docker-mailserver/commit/0befd04bd8af2ac635dddeb1e08647e1ec42497a) (_commit message has relevant notes_)

It seems that neither were suitable though. One of the other maintainers may have a better solution, but this change fixes the bug:

```bash
# Add back `-n` + `/p`,  needed to print out only the matched entry (with the key and it's delimiter omitted).
# Pipe to 2nd sed expression instead, as the first `-e` was intended to be input into the 2nd.
# NOTE: Added `\+` to match keys with repeated key delimiter (unsure if this risks regression)
sed -n -e "s/^y@example\.test\s\+\(.*\)/\1/p" /tmp/docker-mailserver/postfix-virtual.cf | sed -e "s/,/\n/g"
```

---

## Fix

I just need to open a PR for this :sunglasses: (_but haven't run test suite against it, or considered if it could introduce any regressions, I don't think it would?_ :sweat_smile: )

```bash
# Internal method for: _db_operation
function __db_list_already_contains_value
{
  # Avoids accidentally matching a substring (case-insensitive acceptable):
  # 1. Extract the current value of the entry (`\1`),
  # 2. Value list support: Split values into separate lines (`\n`+`g`) at V_DELIMITER,
  # 3. Check each line for an exact match of the target VALUE
  sed -ne "s/^${KEY_LOOKUP}\+\(.*\)/\1/p" "${DATABASE}" \
    | sed -e "s/${V_DELIMITER}/\n/g" \
    | grep -qi "^${_VALUE_}$"
}
```

**Comment by polarathene** [comment]
@42l-neil-tmp I'm not sure when v13 will be released, but you might be able to temporarily run `:edge` with your config mounted to perform the `setup` commands. Should be fine to do that while your existing deployment is running AFAIK.

```bash
docker run --rm -it --hostname example.test -v "<your local config folder path>/tmp/docker-mailserver" mailserver/docker-mailserver:edge bash

# Now you have a shell which should already have your email accounts from `postfix-accounts.cf`,
# Just add your aliases:
setup alias add alias@example.test account@example.test

# Now `postfix-virtual.cf` should be updated, and your other DMS instance should recognize the change,
# and trigger change detection event to update Postfix and Dovecot. Exit this container
exit
```

**Comment by 42l-neil-tmp** [comment]
Thank you for fixing the bug so quickly :)
We are running a [quite unusual setup](https://lacontrevoie.fr/en/services/mail/) − our users are creating their mailboxes/aliases from a web interface, we’ve developed some kind of [docker-mailserver-admin](https://github.com/docker-mailserver/docker-mailserver-admin/) for our needs − so we can’t create mails/aliases that way. We’ll wait for the patch / release then.

**Comment by polarathene** [comment]
> We are running a [quite unusual setup](https://lacontrevoie.fr/en/services/mail/) − our users are creating their mailboxes/aliases from a web interface, we’ve developed some kind of [docker-mailserver-admin](https://github.com/docker-mailserver/docker-mailserver-admin/) for our needs

Oh, that's very cool! Thanks for sharing :grin:
