### ISSUE TITLE
bug report: dkim=neutral (body hash did not verify) 

### ISSUE THREAD

**Issue by konstantin83** [docker-mailserver/docker-mailserver#3410]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

When sending email from desktop client (in my case Mainspring), headers of email contain `dkim=pass`, set by receiving gmail servers.

But when I'm sending an email from linux with Golang script with "net/smtp" package, I see `dkim=neutral (body hash did not verify)` in message headers, set by receiving gmail servers.

### 👟 Reproduction Steps

![dkim](https://github.com/docker-mailserver/docker-mailserver/assets/13274062/0bf9c183-3c92-4f8e-8f98-b21069ef67aa)

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

Debian 11

### ⚙️ Container configuration files

```yml
default
```

**Comment by polarathene** [comment]
> Config: `default`

Not that helpful. What is `default`?

---

To confirm that I understand the issue correctly. You are saying that:
- Everything works when mail is sent via the desktop client (Mailspring), a MUA.
- It fails when you send mail via your own Go code using `net/smtp`?

That would suggest there is nothing wrong with DMS per se. Mailspring knows what it's doing, whereas your own tool is perhaps is less robust.

There's a chance that something in DMS can try to fix that when it receives it (_parsing/sanitizing perhaps_), but it'd be helpful if you identify what your code is doing differently from Mailspring.

---

Did you search `dkim=neutral (body hash did not verify)` at all?
  - [First result I got](https://easydmarc.com/blog/what-you-need-to-know-about-dkim-dkim-fail/), in particular look at the page content there for "DKIM= neutral (body hash did not verify)".
    > _When you get the status of a DKIM signature “body hash not verified”, that means the computed hash of the message body does not agree with the body hash value stored in the `bh=` tag of the DKIM signature._
  - If you're using OpenDKIM you [may be experiencing this issue](https://serverfault.com/questions/959573/dkim-signature-failure-only-on-cron-jobs/959656#959656) (_the 2nd search result I got_) and can try adjust the config as suggested, let us know if it resolves the issue for you.
 - [Another result](https://support.google.com/a/answer/11612790?hl=en) is Googles own support docs for troubleshooting this DKIM issue:
    > _Make sure the message wasn’t changed during transit. Find the part of the message header that starts with `Authentication-Results`._
    > _If the text next to the `dkim` entry is `body hash did not verify`, the **message was modified during transit**._

Alternatively consider trying Rspamd as per [our DKIM docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/best-practices/dkim_dmarc_spf/)? There was also some changes since 12.1 release, you may want to see if using `:edge` has already fixed a bug with Rspamd/OpenDKIM support.

**Comment by konstantin83** [comment]
Thank you for such a detailed answer, I appreciate that!
Alot of what yuo said inspired me to new experiments.
There was a problem only when encoding mesage body to base64. I tried everything. But nothing helped.
So I decided to try to send message body without encoding and it works absolutely perfect now.
I'm not an expert, and don't know what will be the consequences of this )) But for now everything works great!
