### ISSUE TITLE
bug report: Postfix can not start

### ISSUE THREAD

**Issue by carlosfrodriguez** [docker-mailserver/docker-mailserver#3418]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

postfix can not start

### 👟 Reproduction Steps

Start from scratch on an m2 Mac 
Create the fist email address with the .setup.sh script
Look at the logs

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

MacOS 13.4.1 M2

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail
    domainname: sith.net
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      # - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text
023-07-04 09:17:38 Jul  4 09:17:37 mail postfix/postfix-script[2752]: starting the Postfix mail system
2023-07-04 09:17:38 Jul  4 09:17:37 mail postfix/master[2753]: fatal: bind: public/sender-cleanup: Invalid argument
2023-07-04 09:17:44 Jul  4 09:17:44 mail postfix/postfix-script[2849]: starting the Postfix mail system
2023-07-04 09:17:44 Jul  4 09:17:44 mail postfix/master[2850]: fatal: bind: public/sender-cleanup: Invalid argument
2023-07-04 09:17:50 Jul  4 09:17:50 mail postfix/postfix-script[2937]: starting the Postfix mail system
2023-07-04 09:17:50 Jul  4 09:17:50 mail postfix/master[2938]: fatal: bind: public/sender-cleanup: Invalid argument
2023-07-04 09:17:56 Jul  4 09:17:56 mail postfix/postfix-script[3025]: starting the Postfix mail system
2023-07-04 09:17:56 Jul  4 09:17:56 mail postfix/master[3026]: fatal: bind: public/sender-cleanup: Invalid argument
2023-07-04 09:18:02 Jul  4 09:18:02 mail postfix/postfix-script[3120]: starting the Postfix mail system
```

**Comment by polarathene** [comment]
> MacOS 13.4.1 M2

Unfortunately this cannot be supported by any maintainer well (none of us have macs), as the issue template notes:

> _**NOTE:** Windows and macOS have limited support._

I'm not aware of anyone needing to deploy DMS to production on a mac, so this sort of issue usually happens for local dev / testing environments.

---

On macOS Docker will be running via a VM which from my understanding you have limited control over, and there are various issues/limitations that you can encounter with it.

### Possible cause 1

Your error looks related to this part of `master.cf`:

https://github.com/docker-mailserver/docker-mailserver/blob/ee7c4b1ede534fcc565c2c8c4b1f085203859257/target/postfix/master.cf#L47-L49

There was a change to [remove chroot with v12](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v12.0.0), you might want to check if you get the problem with v11.3, as the `public/` part looks like it's a runtime directory that Postfix creates.

### Possible cause 2 (most likely)

The error is not entirely clear, but I think it is trying to bind a unix socket `sender-cleanup` at this location. That location is adjusted when you use a volume for mail-state:

https://github.com/docker-mailserver/docker-mailserver/blob/ee7c4b1ede534fcc565c2c8c4b1f085203859257/target/scripts/startup/setup.d/mail_state.sh#L111

What might be happening here is an incompatibility with that volume mount on macOS, try removing `./docker-data/dms/mail-state/:/var/mail-state/` and if the error is no longer present you will have your answer. Raise it as a bug report to Docker macOS, they have other volume bind mount issues as well IIRC.

---

Other than the advice above, there is not much else we can do for you unfortunately.

It would be appreciated if you could give the advice above a try and comment back on your findings. It would help other macOS users who run into the same issue.

The advice we usually give is to just run a VM guest with linux and docker installed in that yourself. A little bit more work, but sufficient to play around with DMS locally, I do that often myself. If you need any suggestions, VMWare Player is free and works well in my experience.

**Comment by carlosfrodriguez** [comment]
Hi,

I tried both but it is the same, however I discover a workaround (for me it is hard to believe it) but during my tests I create new containers from the scratch (meaning removing the old container and the image).

The current parent directory was named `MailServer` and this is where this sender-cleanup file was not working
Then I create a new container in the `DockerMailServer` directory and then another file was not working (but a different one)
Then I create another container in the `DMS` directory and from here it works without any issues again (as it was woking on my old intel Mac from the `MailServer` directory).

I have no idea how this is related or if it is a coincidence, but I did it several times and it was the same results. The directories only contained the `docker-compose.yml`,  the `setup.sh` and the `mailserver.env` files.

**Comment by polarathene** [comment]
If you ever do `docker stop container_name && docker start container_name` or `docker restart container_name` or similar `docker compose` commands, including `docker compose up` with Ctrl+C or similar to quit without using `docker compose down`, then you are restarting a container and not creating the container fresh.

DMS should be started fresh, not restarting existing container instance. There can be problems that happen otherwise. Volumes shouldn't affect this.

> (as it was woking on my old intel Mac from the MailServer directory).

If the old directory was also different version of DMS, then there may have been some incompatibility. If you copied the directory, you may also not have copied the data properly (_some filesystems aren't good at keeping some file attributes, especially when copied across different filesystems where there isn't feature parity_). It's possible any of this broke the file content, likely attributes.

**Comment by carlosfrodriguez** [comment]
No No, I always mean to use docker-compose down and also delete the image to start really fresh

**Comment by carlosfrodriguez** [comment]
The comparison of the old Intel Mac was done by only having the 3 files mentioned, the compose, the environment and the setup script for sure, nothing else

**Comment by miamilabs** [comment]
> ### 📝 Preliminary Checks
> 
>     * [x]  I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.
> 
> 
> ### 👀 What Happened?
> 
> postfix can not start
> ### 👟 Reproduction Steps
> 
> Start from scratch on an m2 Mac Create the fist email address with the .setup.sh script Look at the logs
> ### 🐋 DMS Version
> 
> v12.1.0
> ### 💻 Operating System and Architecture
> 
> MacOS 13.4.1 M2
> ### ⚙️ Container configuration files
> 
> ```yaml
> services:
>   mailserver:
>     image: ghcr.io/docker-mailserver/docker-mailserver:latest
>     container_name: mailserver
>     # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
>     hostname: mail
>     domainname: sith.net
>     env_file: mailserver.env
>     # More information about the mail-server ports:
>     # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
>     # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
>     ports:
>       - "25:25"    # SMTP  (explicit TLS => STARTTLS)
>       - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
>       - "465:465"  # ESMTP (implicit TLS)
>       - "587:587"  # ESMTP (explicit TLS => STARTTLS)
>       - "993:993"  # IMAP4 (implicit TLS)
>     volumes:
>       - ./docker-data/dms/mail-data/:/var/mail/
>       - ./docker-data/dms/mail-state/:/var/mail-state/
>       - ./docker-data/dms/mail-logs/:/var/log/mail/
>       - ./docker-data/dms/config/:/tmp/docker-mailserver/
>       # - /etc/localtime:/etc/localtime:ro
>     restart: unless-stopped
>     stop_grace_period: 1m
>     # Uncomment if using `ENABLE_FAIL2BAN=1`:
>     # cap_add:
>     #   - NET_ADMIN
>     healthcheck:
>       test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
>       timeout: 3s
>       retries: 0
> ```
> 
> ### 📜 Relevant log output
> 
> ```
> 023-07-04 09:17:38 Jul  4 09:17:37 mail postfix/postfix-script[2752]: starting the Postfix mail system
> 2023-07-04 09:17:38 Jul  4 09:17:37 mail postfix/master[2753]: fatal: bind: public/sender-cleanup: Invalid argument
> 2023-07-04 09:17:44 Jul  4 09:17:44 mail postfix/postfix-script[2849]: starting the Postfix mail system
> 2023-07-04 09:17:44 Jul  4 09:17:44 mail postfix/master[2850]: fatal: bind: public/sender-cleanup: Invalid argument
> 2023-07-04 09:17:50 Jul  4 09:17:50 mail postfix/postfix-script[2937]: starting the Postfix mail system
> 2023-07-04 09:17:50 Jul  4 09:17:50 mail postfix/master[2938]: fatal: bind: public/sender-cleanup: Invalid argument
> 2023-07-04 09:17:56 Jul  4 09:17:56 mail postfix/postfix-script[3025]: starting the Postfix mail system
> 2023-07-04 09:17:56 Jul  4 09:17:56 mail postfix/master[3026]: fatal: bind: public/sender-cleanup: Invalid argument
> 2023-07-04 09:18:02 Jul  4 09:18:02 mail postfix/postfix-script[3120]: starting the Postfix mail system
> ```
> 
> ### Improvements to this form?
> 
> _No response_

did you manage somehow to fix this?
Fighting now for 2 days with docker and mac.

**Comment by polarathene** [comment]
> did you manage somehow to fix this?
> Fighting now for 2 days with docker and mac.

Use a hypervisor like VMware (it's free), and run Docker inside that. It won't be too different AFAIK, and you can still have shared folders with a host if you need that (but with VMware you also have drag/drop file transfer).

Only a little bit of friction if you've never used Linux before but really installing Ubuntu or Fedora and then Docker is really simple. VM setup isn't that tricky either if you've never done that. All GUI (_maybe a little bit of command line in the linux guest if you install Docker by following the official Docker docs install guides_).

Otherwise the issue is with Docker on Mac, which you're not really planning to deploy DMS into production on are you? Just try it locally? Go with the virtual machine, it'll be a far better experience. Alternatively if you're comfortable with CLI, rent a headless VPS (it's like $5 for a month?).

You can search through issues on our repo here that have the `os/macOS` label, there should be some with links to relevant github repo/issues related to macOS bugs upstream that you can track. You may have luck if you change the volume/filesystem driver (_was something like that IIRC_).

---

macOS compatibility issues aside. You should be able to avoid the problem AFAIK by not having a `mail-state` volume attached:

> ```yaml
> - ./docker-data/dms/mail-state/:/var/mail-state/
> ```

That should be where it's trying to bind `public/sender-cleanup` and failing. If that is left within the container filesystem it may work successfully. Since this is not for production deployment on macOS, only whatever other reason you have, you don't need to persist `mail-state`.

I actually suggested exactly this above: https://github.com/docker-mailserver/docker-mailserver/issues/3418#issuecomment-1620777542

The issue reporter claims they tried this and it didn't work, but then starting from scratch (fresh volumes effectively) it worked or them. There seemed to be some confusion on their end regarding image vs container, so I'm not surprised if they misunderstood what I was suggesting with the `mail-state` volume being avoided.

Try it.

**Comment by carlosfrodriguez** [comment]
> The issue reporter claims they tried this and it didn't work, but then starting from scratch (fresh volumes effectively) it worked or them. There seemed to be some confusion on their end regarding image vs container, so I'm not surprised if they misunderstood what I was suggesting with the `mail-state` volume being avoided.
> 
> Try it.

Actually it seems to work, I got a warning message (with both VirtioFS and gRPC FUSE): 
`mailserver  | [ WARNING ]  'ONE_DIR=1' but no volume was mounted to '/var/mail-state'`

But so far is starting the services correctly and functionality seems normal even after some restarts.

**Comment by polarathene** [comment]
> I was actually stopping the container with docker compose down and **really** removing the image to start totally and completely fresh from the scratch.

There is no misunderstanding from that clarification.

If you used a tagged image like `mailserver/docker-mailserver:14.0.0` then there is no difference removing that image. Pulling the image again will provide you the same exact image. Unlike with `:latest` which will be the latest tagged release we published. Or with `:edge` which is the last publish from master branch.

`docker compose up --force-recreate` will ensure that the container is fresh. Otherwise the container could resume/restart from a previous run, but keep any file changes that happened in the container.

If you use named or anonymous volumes as well, I think Docker Compose also makes an effort to keep those (_unlike `docker run`_), which can likewise be a bit unexpected when it turns out to be the source of the problem, but you thought you had really started from scratch.

---



> I got a warning message (with both VirtioFS and gRPC FUSE):
> `mailserver | [ WARNING ] 'ONE_DIR=1' but no volume was mounted to '/var/mail-state'`

This warning is about a misconfiguration. `ONE_DIR=1` expects a bind volume mount to `/var/mail-state` to unify run-time state. If you have no volume mounted there, you would use `ONE_DIR=0` as no unified state dir is attempted:

https://github.com/docker-mailserver/docker-mailserver/blob/0c7e49e654fb64a0b23abae2b423f54e8312beeb/target/scripts/startup/setup.d/mail_state.sh#L8-L11

https://github.com/docker-mailserver/docker-mailserver/blob/0c7e49e654fb64a0b23abae2b423f54e8312beeb/target/scripts/startup/setup.d/mail_state.sh#L114-L118

In v14 release we have removed this `ONE_DIR` environment variable (_as per the `CHANGELOG.md`_), instead we only check that `/var/mail-state` exists now.

On v14 you would not get that warning, but some users did not pay attention to this change, reporting bug with upgrade because of the opposite (_[`ONE_DIR=0` with `/var/mail-state` volume mount](https://github.com/docker-mailserver/docker-mailserver/issues/4082#issuecomment-2181770792)_).

v14 also includes a change to skip many startup scripts from running when it detects the container is not fresh, so it will be a bit more resilient to problems from non-fresh container startups.

**Comment by carlosfrodriguez** [comment]
> v14 also includes a change to skip many startup scripts from running when it detects the container is not fresh, so it will be a bit more resilient to problems from non-fresh container startups.

That is great! so it might soon work as other containers that you can just stop without remove?

**Comment by polarathene** [comment]
> it might soon work as other containers that you can just stop without remove?

I'm not sure. DMS is mostly glue/integration of other projects with scripts. We convert configs or ENV into the equivalent for the services we bundle. Whereas most other images are just the direct service alone without any of that. As such, we have that container state issue to deal with.

I think the v14 improvement resolves most of it but there is quite a bit of stuff going on in the container, so if there's still some lingering state that shouldn't be there it would be an issue. Likewise since we skip the startup scripts now on a detected restart, if there was a change made that would only be relevant for those startup scripts, it would not be applied when changed until a fresh container instance is run.

Some users may report bugs related to it, but for those that follow our top troubleshooting advice to force a fresh container... we may not actually get reports due to that restart behaviour 😅 

---

There are other projects like Mailu I think which take a different approach of many containers, one for each service. That should avoid the problem, while others prefer a single container solution with DMS there are drawbacks sometimes like this one.
