### ISSUE TITLE
other:  Best way to add configuration to Dovecot mailboxes (15-mailboxes.conf)

### ISSUE THREAD

**Issue by Codelica** [docker-mailserver/docker-mailserver#3434]
### Subject

I would like to configure a not documented mail server use case

### Description

Just a sanity check here in case I'm missing a better way to do this.  

Basically I wan't to `autoexpunge` the Junk folder after 30 days which would go in its entry in `15-mailboxes.conf`.  (So users can leave it alone, otherwise manual cleanup will trigger rspamd to think it's ham it appears)

It seems I could either completely overwrite `15-mailboxes.conf` with a full copy and my edits (which I'd prefer not to do for changes going forward), or make use of `user-patches.sh` with something like:

```bash
#!/bin/bash

# Dovecot: Auto-delete Junk (30 days) and Trash (90 days)
sed -i /etc/dovecot/conf.d/15-mailboxes.conf \
    -e '/autoexpunge/d' \
    -e 's|special_use = \\Junk|special_use = \\Junk\n    autoexpunge = 30d|' \
    -e 's|special_use = \\Trash|special_use = \\Trash\n    autoexpunge = 90d|'
```

Or is there some other / better way to modify the mailbox config that I'm missing?

Thanks!

**Comment by polarathene** [comment]
> It seems I could either completely overwrite `15-mailboxes.conf` with a full copy and my edits (which I'd prefer not to do for changes going forward)

Yeah, don't do that :sweat_smile: 

We sometimes make changes to the configs we ship, and in the v12 release this broke some users when we changed the SASL socket path because they took this overwrite entire file approach, causing broken configuration.

> Or is there some other / better way to modify the mailbox config that I'm missing?

I think if you define the value again it overwrites the earlier definition(s). Dovecot configs have an `!include` macro feature that you'll often see used at the end of the files to bring in more configs. We use `#` to comment out / disable those inclusions based on DMS config, but you could add your own line to import your own separate config file if you prefer:

https://github.com/docker-mailserver/docker-mailserver/blob/7d5c2736cec0cc6db198da57e94a8ca589570d9f/target/dovecot/10-auth.conf#L125

In this case it's a bit more of a hassle since the lines you want to change seem to be in nested config, so the `sed` approach with `user-patches.sh` is probably the right way to go.

---

There is some Dovecot CLI commands for updating configs, but I'm not sure how that works for these kind of settings.

Here's the [docs for the mailbox CLI commands](https://doc.dovecot.org/3.0/man/doveadm-mailbox.1/#mailbox-metadata-set), that `metadata set` command should be what you want, and the `mailbox` arg says it [should include the `namespace` as a prefix](https://doc.dovecot.org/3.0/man/doveadm-mailbox.1/#arguments).

**`user-patches.sh`:**

```bash
#!/bin/bash

# Dovecot: Auto-delete Junk (30 days) and Trash (90 days)
doveadm mailbox metadata set inbox/Junk autoexpunge 30d
doveadm mailbox metadata set inbox/Trash autoexpunge 90d
```

`inbox/Junk` is presumably the correct value. You can try the [`list` example](https://doc.dovecot.org/3.0/man/doveadm-mailbox.1/#example) or a variant of it to try get that correct information. You could also try the `metadata get` method to read the [existing values configured like `special_use`](https://github.com/docker-mailserver/docker-mailserver/blob/7d5c2736cec0cc6db198da57e94a8ca589570d9f/target/dovecot/15-mailboxes.conf#L47-L68), and if it returns the expected value then the `metadata set` command should work as expected :+1: 

That should accomplish the same thing as you're doing with `sed`, but a failure might be more apparent should something change with a DMS update.

**Comment by Codelica** [comment]
Thanks for all the info! 👍 

I like the idea of using `doveadm` (new to me coming from years of cyrus imap), although I'm thinking it won't be possible since `user-patches.sh` claims to be run *before* dovecot would even be started.  Also I played around a bit with the `doveadm` command  and for some reason it doesn't appear that `autoexpunge` config is metadata, or if it is, it doesn't seem to get returned via `doveadm mailbox metadata list` or `doveadm mailbox metadata get` -- yet I see it in my current setting via `doveconf -n`.

No worries though.  After more Googling I seem to have found another option using `doveadm` in a cron job which I really like.  Seems to give some more control vs `autoexpunge` deleting on user disconnect.  Just in case someone else it looking someday:

```bash
#!/bin/bash
doveadm expunge -A mailbox Junk savedbefore 30d
doveadm expunge -A mailbox Trash savedbefore 90d
```

Thanks again!
