### ISSUE TITLE
other: Unable to use DMS as a local mail relay

### ISSUE THREAD

**Issue by dtrunk90** [docker-mailserver/docker-mailserver#3437]
### Subject

Other

### Description

My use case: I would like to set up apticron on my host to get notified about new package updates. My DMS container is up and running perfectly fine (+ SSL/SPF/DKIM/DMARC) with mail accounts set up. So, first I've set `PERMIT_DOCKER=host` and `POSTFIX_INET_PROTOCOLS=ipv4`.

After installing the package `apticron-systemd` (Debian 12) I've followed this guide: https://docker-mailserver.github.io/docker-mailserver/latest/examples/tutorials/basic-installation/#using-dms-as-a-local-mail-relay-for-containers

I've skipped some steps because everything else is set up already like SSL, SPF and so on.
Now I'm stuck at step 6 (with `SPOOF_PROTECTION=1`).

These steps will lead to:
```
[  ERROR  ]  'admin.gmail@example.com' is already defined as an account`
[  ERROR  ]  Aborting
```

How do I have to configure DMS and probably mailx/exim4 (which is used by apticron) to send mails through DMS?
Found https://github.com/docker-mailserver/docker-mailserver/issues/1582 but still not sure how to configure DMS here. Do I still need `PERMIT_DOCKER=host` for that? Is there any way to NOT store a plaintext password in a config file?

**Comment by casperklein** [comment]
> Found https://github.com/docker-mailserver/docker-mailserver/issues/1582 but still not sure how to configure DMS here. Do I still need PERMIT_DOCKER=host for that?

Yes. `PERMIT_DOCKER` disables authentication. for the host/docker network. Alternatively, you could also configure nullmailer to authenticate against DMS.

**Comment by polarathene** [comment]
> Now I'm stuck at step 6 (with `SPOOF_PROTECTION=1`).

There was some recent issues (_[here we go, read this](https://github.com/docker-mailserver/docker-mailserver/issues/3350#issuecomment-1550528898)_) regarding this and the linked guide advice.

Please note it's a community guide and IIRC this particular advice was not good, just no one has gotten around to updating it.

---

Just so I understand your needs correctly, you want to send mail from the host to the DMS container, and have that relay mail to your external gmail address?

Can you try without `SPOOF_PROTECTION=1` for now?
- Create a virtual alias for your gmail account (eg: `setup alias add admin.gmail@example.com john.doe@gmail.com`), **not an account** (`setup email add admin.gmail@example.com`)
- There should only be an account for delivery /authentication when DMS is the final destination.
- A virtual alias will accept the mail arriving, and change the recipient address like a redirect.
- If the recipient address is for an actual account (`setup email add ...`) it'll be delivered to Dovecot.
  - **NOTE:** DMS may also be configured for system accounts at (eg: `amavis@mail.example.com`), without Postfix aliases to redirect them, they get delivered to Postfix local delivery (_`/var/mail`, but not handled by Dovecot, not useful to DMS_), usually they're aliased (not virtual alias) to an actual account (`postmaster@example.com` or `john.doe@gmail.com`).
- When mail is sent to DMS for the virtual alias `admin.gmail@example.com`, it should now be redirected to `john.doe@gmail.com`. Verify that's successful, then try with `SPOOF_PROTECTION=1` (_**NOTE:** Recreate the DMS container properly with `docker compose up --force-recreate`, or `docker compose down && docker compose up`, **do not** rely only on `docker compose restart` or CTRL+C followed by `docker compose up_).

---

> I would prefer not to store my password as plaintext inside a file which would be the case for nullmailer, isn't it? Or do I just have to omit the password because I've set `PERMIT_DOCKER=host`?

`PERMIT_DOCKER=host` should allow you to send mail from the host to DMS without the client (nullmailer) needing to be trusted (_sender pass SPF, etc_). It may also bypass submission authentication (can't recall right now), but that would allow anyone (_or process_) on that host to send mail outbound without authentication too...

You're worried about a plaintext password, but bypassing authentication sounds worse (_unless you're using that password outside of a DMS account? Which you shouldn't.._). If there's a file with a password on it that can be read, the user can probably run a process to send mail to DMS.

By having a unique password to the specific DMS account, you restrict the damage that can be done, usually it's a randomly generated one like an API token and you can have a policy to change it every 3-6 months if you like. You'd have better insights to being compromised there, and can restrict the account intent to be for machines rather than humans, one perk of `SPOOF_PROTECTION=1` was for that scenario IIRC.

It's not uncommon in some cases to store a password this way, but you can limit access with owner/group RWX permissions (_eg: restrict to a specific user like `chown root`, and don't allow anyone else to read it's contents with `chmod 600`_)

However in this case, you're not sending mail to DMS to be sent outbound (_via inbound submission ports 465/587_). Any mail sent to `admin.gmail@example.com` (_including from external third-parties_) would be routed to the `john.doe@gmail.com` address as if they sent to that one directly instead. That can all happen over port 25.

If you need an actual relay, you can create an account on DMS that is used for relaying. Use authentication on the submission ports to submit mail for DMS to send outbound, your mail client will connect to DMS through that account and send as whatever sender address you provide (`SPOOF_PROTECTION=1` should expect that to match the account address), and can send to any recipient directly (_not just `john.doe@gmail.com`_), no need to indirectly send to `admin.gmail@example.com` (_although you can use that as your sender address_).

DMS can additionally send mail through a relay service, be that SendGrid or Gmail, much in the same way as described above, any outbound mail will authenticate through an account at the relay service (like `john.doe@gmail.com`) which requires that accounts credentials (_now it's a security concern for you with the plain text when it's a personal account_), and mail will be sent from that relay service for delivery reputation, but still respect your sender and recipient addresses when you sent the mail from your MUA (mail client).

---

There's other options but those are the main ones that are usually relevant. For your needs, just setup the alias and send mail to DMS over port 25 :+1: (no password needed)
