### ISSUE TITLE
bug report: in v12 NOQUEUE: reject: RCPT from <>; Relay access denied;

### ISSUE THREAD

**Issue by wzrdtales** [docker-mailserver/docker-mailserver#3438]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

When trying to send from a kubernetes service, calling the mailserver directly via a cluster IP, the mail gets rejected without reason. Trying to connect and via a public IP does not result in the same problem.

The same setup works in v11, but does not in v12.

```
Jul 22 10:53:35 mailserver-0 postfix/postscreen[667]: CONNECT from [10.42.128.117]:58022 to [10.42.128.72]:25
Jul 22 10:53:35 mailserver-0 postfix/postscreen[667]: PASS OLD [10.42.128.117]:58022
Jul 22 10:53:35 mailserver-0 postfix/smtpd[668]: connect from keycloak-keycloakx-0.keycloak-keycloakx-headless.keycloakprod.svc.cluster.local[10.42.128.117]
Jul 22 10:53:35 mailserver-0 postfix/smtpd[668]: Anonymous TLS connection established from keycloak-keycloakx-0.keycloak-keycloakx-headless.keycloakprod.svc.cluster.local[10.42.128.117]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256
Jul 22 10:53:35 mailserver-0 postfix/smtpd[668]: NOQUEUE: reject: RCPT from keycloak-keycloakx-0.keycloak-keycloakx-headless.keycloakprod.svc.cluster.local[10.42.128.117]: 554 5.7.1 <to@addr.com>: Relay access denied; from=<from@addr.com> to=<to@addr.com> proto=ESMTP helo=<keycloak-keycloakx-0.keycloak-keycloakx-headless.keycloakprod.svc.cluster.local>
Jul 22 10:53:35 mailserver-0 postfix/smtpd[668]: disconnect from keycloak-keycloakx-0.keycloak-keycloakx-headless.keycloakprod.svc.cluster.local[10.42.128.117] ehlo=2 starttls=1 mail=1 rcpt=0/1 rset=1 quit=1 commands=6/7
```

We tried to debug, but didn't find too much more.

### 👟 Reproduction Steps

Setup mailserver/docker-mailserver:12.1.0 in a k8s cluster and try to send a mail via a clusterIP.

### 🐋 DMS Version

mailserver/docker-mailserver:12.1.0

### 💻 Operating System and Architecture

mailserver/docker-mailserver:12.1.0

### ⚙️ Container configuration files

```yml
- name: ONE_DIR
              value: '1'
            - name: SSL_CERT_PATH
              value: /etc/ssl/mailserver/tls.crt
            - name: SSL_KEY_PATH
              value: /etc/ssl/mailserver/tls.key
            - name: SSL_TYPE
              value: manual
            - name: ENABLE_SRS
              value: '1'
            - name: SRS_SENDER_CLASSES
              value: envelope_sender,header_sender
            - name: SRS_DOMAINNAME
              value: censored.de
            - name: DOVECOT_INET_PROTOCOLS
              value: ipv4
            - name: SPOOF_PROTECTION
              value: '0'
            - name: OVERRIDE_HOSTNAME
              value: censored.de
            - name: LOG_LEVEL
              value: debug



apiVersion: v1
data:
  KeyTable: ''
  SigningTable: ''
  TrustedHosts: |-
    127.0.0.1
    localhost
    example.de
  postfix-accounts.cf: >-
    example@example.de|{SHA512-CRYPT}censored/
  postfix-virtual.cf: >-
    example@example.de support.nxt@test.de
```

### 📜 Relevant log output

```Text
Jul 22 10:53:35 mailserver-0 postfix/postscreen[667]: CONNECT from [10.42.128.117]:58022 to [10.42.128.72]:25
Jul 22 10:53:35 mailserver-0 postfix/postscreen[667]: PASS OLD [10.42.128.117]:58022
Jul 22 10:53:35 mailserver-0 postfix/smtpd[668]: connect from keycloak-keycloakx-0.keycloak-keycloakx-headless.keycloakprod.svc.cluster.local[10.42.128.117]
Jul 22 10:53:35 mailserver-0 postfix/smtpd[668]: Anonymous TLS connection established from keycloak-keycloakx-0.keycloak-keycloakx-headless.keycloakprod.svc.cluster.local[10.42.128.117]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256
Jul 22 10:53:35 mailserver-0 postfix/smtpd[668]: NOQUEUE: reject: RCPT from keycloak-keycloakx-0.keycloak-keycloakx-headless.keycloakprod.svc.cluster.local[10.42.128.117]: 554 5.7.1 <to@addr.com>: Relay access denied; from=<from@addr.com> to=<to@addr.com> proto=ESMTP helo=<keycloak-keycloakx-0.keycloak-keycloakx-headless.keycloakprod.svc.cluster.local>
Jul 22 10:53:35 mailserver-0 postfix/smtpd[668]: disconnect from keycloak-keycloakx-0.keycloak-keycloakx-headless.keycloakprod.svc.cluster.local[10.42.128.117] ehlo=2 starttls=1 mail=1 rcpt=0/1 rset=1 quit=1 commands=6/7
```

**Comment by polarathene** [comment]
Do you have control over the `.local` TLD used there? I'm assuming it's handled by k8s?

I am not familiar with k8s (_@georglauterbach has experience with this and might have a better idea of the reason_), `.local` is intended for mDNS, so you shouldn't use it for a TLD with regular DNS lookups, the amount of DNS labels used also exceeds what standard mDNS permits. On Linux this would be handled by avahi process/config (along with NSS).

@williamdes might also have input here, and has been working with a clustered deployment IIRC.

**Comment by wzrdtales** [comment]
. local is not intended for men's just for local domains. In k8s case those are resolveable anywhere in the cluster 

Sent from Nine

-- 

Best

--
Tobias Gurtzick
CEO
WizardTales GmbH

Additional Contacts:
@github | ***@***.***
--
Website: https://www.wizardtales.com
***@***.***
nmlpm: -- coming soon & open source --

Please tag your mails with "request", "issue" or "proposal", unless none of these fit or there already exists a thread.

-- Why should one reach for what one may be capable reaching, that's awfully boring and after all one still be ones yesterday being. --

Sitz der Gesellschaft: Ratingen
Kokkolastr. 5
40882 Ratingen
Germany

Registergericht: Amtsgericht Düsseldorf, HRB 84140
Geschäftsführer: Tobias Gurtzick
________________________________
Von: Brennan Kinney ***@***.***>
Gesendet: Samstag, 22. Juli 2023 23:06
An: docker-mailserver/docker-mailserver
Cc: Tobias Gurtzick; Author
Betreff: Re: [docker-mailserver/docker-mailserver] bug report: in v12 NOQUEUE: reject: RCPT from <>; Relay access denied; (Issue #3438) 

Do you have control over the .local TLD used there? I'm assuming it's handled by k8s?
I am not familiar with k8s ***@***.*** has experience with this and might have a better idea of the reason), .local is intended for mDNS, so you shouldn't use it for a TLD with regular DNS lookups, the amount of DNS labels used also exceeds what standard mDNS permits. On Linux this would be handled by avahi process/config (along with NSS).
@williamdes might also have input here, and has been working with a clustered deployment IIRC.

**Comment by wzrdtales** [comment]
We also found out that this problem only persists when connecting to port 25 port 587 it works so something in the config for port 25 changed in v12

Sent from Nine

-- 

Best

--
Tobias Gurtzick
CEO
WizardTales GmbH

Additional Contacts:
@github | ***@***.***
--
Website: https://www.wizardtales.com
***@***.***
nmlpm: -- coming soon & open source --

Please tag your mails with "request", "issue" or "proposal", unless none of these fit or there already exists a thread.

-- Why should one reach for what one may be capable reaching, that's awfully boring and after all one still be ones yesterday being. --

Sitz der Gesellschaft: Ratingen
Kokkolastr. 5
40882 Ratingen
Germany

Registergericht: Amtsgericht Düsseldorf, HRB 84140
Geschäftsführer: Tobias Gurtzick
________________________________
Von: Brennan Kinney ***@***.***>
Gesendet: Samstag, 22. Juli 2023 23:06
An: docker-mailserver/docker-mailserver
Cc: Tobias Gurtzick; Author
Betreff: Re: [docker-mailserver/docker-mailserver] bug report: in v12 NOQUEUE: reject: RCPT from <>; Relay access denied; (Issue #3438) 

Do you have control over the .local TLD used there? I'm assuming it's handled by k8s?
I am not familiar with k8s ***@***.*** has experience with this and might have a better idea of the reason), .local is intended for mDNS, so you shouldn't use it for a TLD with regular DNS lookups, the amount of DNS labels used also exceeds what standard mDNS permits. On Linux this would be handled by avahi process/config (along with NSS).
@williamdes might also have input here, and has been working with a clustered deployment IIRC.

**Comment by casperklein** [comment]
Not sure if related: [authentication on port 25 has been removed in v12](https://github.com/docker-mailserver/docker-mailserver/pull/3006)

**Comment by georglauterbach** [comment]
Probably related to what @casperklein already said. Indeed, `*.local` is a cluster-internal name that cluster-DNS-services like coreDNS can resolve cluster-wide. I have configured my cluster to use my proper FQDN though including TLS and everything. The issue should be with authentication on port 25 though, and re-enabling it should solve the issue.

**Comment by wzrdtales** [comment]
This might be very well it. I have to place one critique here then though.

We explicitly checked for breaking changes, there were non officially listed. This change is very unexpected, in the past you properly maintained publishing breaking changes. Would be great if you would start a proper release management again. Maybe adopt https://www.conventionalcommits.org/en/v1.0.0/ to lower the maintenance cost.

**Comment by polarathene** [comment]
> . local is not intended for MDNs only, was just ment for local domains and reserved so this tld will never be taken. In k8s case those are resolveable anywhere in the cluster

No, it's an IETF (RFC 6762) reserved domain for mDNS: https://en.wikipedia.org/wiki/.local

Even [k8s devs are aware of this mistake on their part](https://github.com/kubernetes/kubernetes/issues/115300).

---

> The issue should be with authentication on port 25 though, and re-enabling it should solve the issue.

Port 25 is only intended for receiving mail, not for sending outbound. We disabled that for a reason, there was plenty of discussion / references IIRC to justify it (**EDIT:** _[Relevant PR](https://github.com/docker-mailserver/docker-mailserver/pull/3006#issuecomment-1386326524)_).

As @wzrdtales mentions using port 587 works fine for them. What is the motivation to submit mail through port 25 instead?

Do not revert the change. We can document how to allow port 25 for SMTP authentication for those that have an actual need for it. I don't think we need to support a config toggle for that though.

---

> We explicitly checked for breaking changes, there were none officially listed. This change is very unexpected, in the past you properly maintained publishing breaking changes. Would be great if you would start a proper release management again.

This was [highlighted in our release notes\(https://github.com/docker-mailserver/docker-mailserver/releases/tag/v12.0.0). While it wasn't placed under a breaking changes heading, it was a major release version which implies breaking changes. The actual [CHANGELOG.md](https://github.com/docker-mailserver/docker-mailserver/blob/a0fde8b83ff6084e4b79d2d327dc00a185d48f5a/CHANGELOG.md?plain=1#L60-L67) file is a bit better in that regard.

While we could format those better, it mostly comes down to lack of maintainer availability. In the past I had suggested PRs to include release note fragments which CI could bundle semantically to automate this better for us, but there was not a strong interest from other maintainers. I try to use conventional commits for merged PRs, but that is not always followed by other maintainers merging PRs.

**Comment by wzrdtales** [comment]
> Do not revert the change. We can document how to allow port 25 for SMTP authentication for those that have an actual need for it. I don't think we need to support a config toggle for that though.

It is a default behavior and unexpected. We have postfix running for more than 20 years and 25 was always available for sending mail. So this is simply an **unexpected behavior**, so all you have to do is to document it to avoid issues being generated for this. 

> This was [highlighted in our release notes(https://github.com/docker-mailserver/docker-mailserver/releases/tag/v12.0.0). While it wasn't placed under a breaking changes heading, it was a major release version which implies breaking changes. The actual [CHANGELOG.md](https://github.com/docker-mailserver/docker-mailserver/blob/a0fde8b83ff6084e4b79d2d327dc00a185d48f5a/CHANGELOG.md?plain=1#L60-L67) file is a bit better in that regard.

Also the changelog didn't highlight it anymore as breaking changes. It used to though. https://github.com/docker-mailserver/docker-mailserver/blob/a0fde8b83ff6084e4b79d2d327dc00a185d48f5a/CHANGELOG.md?plain=1#L518-L531
If you're doing a lot of things you start automating, what we automate is pulling breaking changes from projects automatically. However, as already said, this project was once reliable, and was expected to still be, so we never got note of this change.

As you say, yes major release, we expected things to break, but no description came up. And what you also need to understand is: You think that is a general expectation. I wish this would be true. As a matter of fact a lot of projects do release versions just randomly and don't actually have a scheme behind them. Especially big corps like mellanox (now nvidia) love to do that.

**Comment by wzrdtales** [comment]
> I try to use conventional commits for merged PRs, but that is not always followed by other maintainers merging PRs.

We used to use https://github.com/z0al/commitlint-bot to enforce it on a basic level, that is not a catch all though, as it of course doesn't recognize the need to specify a breaking change (with the `!`). Maybe adding a `CONTRIBUTE.md` or `developer` section to the readme describing the processes will help.

**Comment by polarathene** [comment]
> However, as already said, this project was once reliable, and was expected to still be, so we never got note of this change.
> As you say, yes major release, we expected things to break, but no description came up.

While neither the Changelog file or the release notes explicitly placed the change under a "Breaking" heading, it was a major version and the change was prominently displayed early in both files.

Having the heading actually present would make no difference, beyond skimming benefit that chooses to ignore the semantic version convention of major versions equating to breaking changes being present.. even though we've used semantic versioning correctly.

---

> As you say, yes major release, we expected things to break, but no description came up. And what you also need to understand is: You think that is a general expectation. I wish this would be true. As a matter of fact a lot of projects do release versions just randomly and don't actually have a scheme behind them

No heading for "breaking" came up. The project has been known to respect semver and we haven't deviated from that. The release notes aren't consistent as different maintainers take turns producing them. While we could improve on that, we do our best to communicate all the relevant changes and draw attention to anything important early on.

---

> Maybe adding a `CONTRIBUTE.md` or `developer` section to the readme describing the processes will help.

We don't put a restriction on PR commits as we use a squash merge on commit history instead of a merge commit or rebase merge. A CI check on the PR title could help better enforce maintainers from merging without a conventional style commit, but someone has to implement it, right now AFAIK no maintainer has the time to spare for that.

---

> It is a default behavior and unexpected. We have postfix running for more than 20 years and 25 was always available for sending mail. So this is simply an **unexpected behavior**, so all you have to do is to document it to avoid issues being generated for this.

As the [linked PR relevant to the change](https://github.com/docker-mailserver/docker-mailserver/pull/3006#issuecomment-1386326524) I provided in my last comment opens with:

> _As the linked issue notes, authentication on port 25 isn't something popular vendors like GMAIL offer, nor competing dockerized mail-server projects. It's disabled by default in Postfix config upstream as well._

It's not a common default anymore, even it was in the past. You are advised to submit mail via the standard submisison(s) ports 465 and 587, not port 25. If you want that you need to deviate from the default config we and many other alternatives provide. When it changed for Postfix I don't recall, but there is a Github upstream mirror with commit history that you can use `git blame` with if you're curious.

In the release notes it's the 5th change highlighted with a subheading for visibility. In the CHANGELOG.md (_which the release notes are very quick to insist you read **thoroughly** for v12_), it's the 6th bullet point:

https://github.com/docker-mailserver/docker-mailserver/blob/a0fde8b83ff6084e4b79d2d327dc00a185d48f5a/CHANGELOG.md?plain=1#L67

You're raising an issue with it, because you didn't take the time to read these changes for a major version, purely because we didn't organize it under a "breaking" changes heading? Our release process may not be perfect, but it's not terribly flawed like others you've cited. Considering there's effectively 3 active maintainers that volunteer time to the project for several years now, it's acceptable.

---

> If you're doing a lot of things you start automating

We have a fair bit of automation already. I dedicated a fair amount of time improving that, especially for the docs and tests. I just don't have as much time anymore and this is likely my last year as an active maintainer to the project.

I would suggest you contribute with PRs, either in helping with our automation or when we are putting together the release notes / changelog.md updates so that you can help us deliver a better quality experience.

Alternatively, you may want to seek out another project as despite our best efforts to provide support, and considerable improvement to docs, ci, and overall code base, we've not had much luck attracting more maintainers, just the occasional contribution (_often drive-by, never to be seen again, some wasting valuable time_).

**Comment by wzrdtales** [comment]
> While neither the Changelog file or the release notes explicitly placed the change under a "Breaking" heading, it was a major version and the change was prominently displayed early in both files.
> Having the heading actually present would make no difference, beyond skimming benefit that chooses to ignore the semantic version convention of major versions equating to breaking changes being present.. even though we've used semantic versioning correctly.

It does make a difference. Please start to understand this simple principle everyone in the industry follows: "I am not the user.". So don't make statements what "makes no difference". B/c it is not you deciding this. Unless you don't care about your users, this is as it is. and it makes a big difference, which is why **the whole industry** is outlining breaking changes explicitly.

Thank you.

**Comment by polarathene** [comment]
> It does make a difference. Please start to understand this simple principle everyone in the industry follows: "I am not the user.". So don't make statements what "makes no difference". B/c it is not you deciding this. Unless you don't care about your users, this is as it is.

We expect our users to be understanding of the unpaid / volunteer time put into keeping this project maintained. We're not going to get things right all the time like the release notes quality, but we absolutely covered this change prominently, it's not our fault if the users lack the technical aptitude to read the first few lines of release notes for a major version, especially if they choose to dismiss them because there is no "breaking changes" heading present.

That behaviour is definitely not our choice, it's the users. Maintaining these projects are not easy, there's a fair amount of niche knowledge, I don't even deploy a mail server myself, nor regularly use any shell scripting (especially for a test suite), nor many of the other skillsets I've put to use for this project, for the benefit of others.

As a maintainer yourself, perhaps you can relate, but have more overlap with the skills required for the project elsewhere?

---

Anyway, it's 2am here, I need to rest.

There is limited time for the project, which while I'd love to see it flourish and be more polished with our processes, I'd rather the time is spent on addressing actual maintenance concerns which if not addressed stands to harm the project health far more.

By all means, contributions are welcomed (we'd deeply appreciate it), but it's rare to see here beyond talk. I'd rather not continue to debate the topic of our release process, if you'd like to see better, please help the project along with that with action 🙏 

---

As for the Postfix default for 20 years, the default has been disabled (`=no`) since at least 2013 ([Postfix 2.2](https://github.com/vdukhovni/postfix/blame/49e676c661379cbb6235fc63fcc21aec3cf369d8/postfix/src/smtpd/smtpd.c#L317)).

We now follow upstream Postfix default, and as stated previously, we clearly communicated this change was introduced (_even if it wasn't to the semantic standard you expected_).

**Comment by polarathene** [comment]
Closing as issue has been identified.

If you insist on enabling auth on port 25 (which is not default/common elsewhere for a good reason), then you can change this via our [Postfix override config `postfix-main.cf`](https://docker-mailserver.github.io/docker-mailserver/v12.1/config/advanced/override-defaults/postfix/):

```
smtpd_sasl_auth_enable = yes
```
