### ISSUE TITLE
other: Dovecot logs "unknown user" with inbound aliases containing more than one recipient

### ISSUE THREAD

**Issue by Codelica** [docker-mailserver/docker-mailserver#3444]
### Subject

Dovecot logs "unknown user" with inbound aliases containing more than one recipient

### Description

I didn't make this a bug report as the mail gets delivered properly in the end.  Still it seem a little curious.  

Basically if you configure a new email alias with more than one recipient (doesn't matter if they are local or remote) like:

```bash
docker exec mailserver setup alias add example@domain.com user1@domain.com
docker exec mailserver setup alias add example@domain.com user2@domain.com
```

And then send an email in to example@domain.com, the following will get logged as part of delivery:

`Jul 26 11:14:39 mail dovecot: auth: passwd-file(example@domain.com): unknown user`

However the email gets delivered to user1 + user2.  If the alias is just to a single user (local or remote),  there is no log entry for unknown user.  In looking at `/etc/dovecot/userdb` it seems as though aliases (with single recipients) are included rather than just email accounts and Postfix mapping the alias out before the handoff, so maybe this is by design?

**Comment by polarathene** [comment]
> If the alias is just to a single user (local or remote), there is no log entry for unknown user.
> In looking at `/etc/dovecot/userdb` it seems as though aliases (with single recipients) are included rather than just email accounts and Postfix mapping the alias out before the handoff, so maybe this is by design?

This is due to a workaround which creates dummy accounts in Dovecot to avoid an issue with Dovecot Quotas support (enabled by default). A proper fix would be better but requires more time/effort than any maintainer on DMS is likely to have available in the foreseeable future :(

If you don't need quotas, you could disable the feature and IIRC it shouldn't create the dummy accounts in Dovecot.

Unfortunately it doesn't seem like it was documented publicly, and ~~with all the refactoring of scripts since it was implemented, it may be a bit problematic to track the original PR via `git blame`~~ 😅 (_**EDIT:** Nevermind, we were smart enough to include a relevent link comment beside the script logic for this_)

References:
- Nov 2021 - [v10.3 Original PR for Dovecot Quota workaround with dummy Dovecot accounts created for simple Postfix virtual aliases](https://github.com/docker-mailserver/docker-mailserver/pull/2248#issuecomment-955088677) (_with comment linked giving overview/summary_)
- Nov 2021 - [Third-party contribution attempting to slightly improve docs on this](https://github.com/docker-mailserver/docker-mailserver/pull/2282#discussion_r740550501) (_linked review comment again describes issue_)
- June 2022 - [v11.1 Bugfix that affected users with Dovecot Quotas disabled](https://github.com/docker-mailserver/docker-mailserver/pull/2640#issuecomment-1155808553) (_links to a comment citing the usual concerns, notes wildcard/catchall and multiple recipients aren't well supported_)

Relevant logic for this workaround:

https://github.com/docker-mailserver/docker-mailserver/blob/59f483f1575c4062098af3d2ecd0686f1dc205cb/target/scripts/helpers/accounts.sh#L92-L99

---

This is one of a few long-standing issues in the project I'm aware of. I could resolve it if I could afford the time, but I cannot... I'm not that optimistic about anyone else stepping up to contribute a proper fix :(

There were plans to switch this feature off by default and make it opt-in instead. I haven't read over the linked references, but I recall us holding off on that for some reason.

**Comment by Codelica** [comment]
That is an interesting (and sort of surprising) situation for Postfix's `check_policy_service`. One would hope (expect?) it would supply both the original recipient(s) and the final recipient(s) after expansion -- but in looking at the docs that's definitely not the case. :/

Seems like some sort of `check_policy_service` "proxy" to do alias expansion to the true (local) recipients before hitting against the Dovecot quota check would be needed.  That seems a little dirty off-hand, but it doesn't seem like there are many other options as its not really Dovecot's problem (which should just be checking against its true users in the end). 

Anyway, thanks for the explanation and your work on this project. 👍
