### ISSUE TITLE
other: 

### ISSUE THREAD

**Issue by OverClockd** [docker-mailserver/docker-mailserver#3479]
### Subject

Other

### Description

The docs have changed quite a bit since I have last been here. But long story short, I cant retrieve my DKIM keys from the host anymore, I have to enter the container in a bash shell.

How do I "relink" the docker container storage to the host storage directory "docker-data/dms/config....?

Also, any ideas how this would have come undone? I used to be able to get my keys from the host directory as per the documentation states.

This isn't really a project issue, but a personal issue mostly, but I am so scared to F up my mailserver that I had to come straight to the devs to ask. Docker documentation is already a little tricky to read (I am not giantly familiar with docker beyond the mailserver).

Any help would be appreciated. If it already talks about linking the container storage to host directory, please share that link (I am having trouble finding it in the docs)

Thanks for the great product and the help!

**Comment by OverClockd** [comment]
Found a solution - though I am curious how to relink the volume. But in the meantime, I just "cat" the file to terminal rather than using vi or vim, and then I can highlight and copy from the terminal.

Thanks again for such an awesome mail server!

**Comment by polarathene** [comment]
When you bind mount a host directory into the container it will substitute the content of the container at the location you mapped it into the container.

You can use `cp` command to copy the file from the container to a different container location which you have a working volume bind mount, and that should then appear in the host location. Alternative the `cat` command as you've been using, you could just save the content as a file on the host.

That said, if the data is not stored on the host, you should not trust it to stay around. Anything in the container that is not persisted can disappear when the container is recreated. We don't advise restarting the container, as this can keep state (file changes) from the previous usage of the container, and the DMS scripts are not fully compatible with that, they tend to expect a predictable state of files we manage that are intended as internal only (no volume mounts).

You will have a better choice of support if you raise a proper bug report, at the very least sharing your `compose.yaml`. Our docs have been around for over 2 years though, we migrated away from the Github wiki, our docs are versioned. Your bigger issue would be the major versions with breaking changes since then. We publish release notes on Github Releases page, and also provide a `CHANGELOG.md`.
