### ISSUE TITLE
other: 

### ISSUE THREAD

**Issue by vahidalvandi** [docker-mailserver/docker-mailserver#3487]
### Subject

Other

### Description

i want to use one dms in two domain in one host name https://github.com/docker-mailserver/docker-mailserver/blob/master/compose.yaml#L6C5-L6C31  
I have no problem creating dkim for the second domain and creating ssl for the second domain and creating an account for the second domain

But it seems that it doesn't work
How to create two domains on one dms

**Comment by polarathene** [comment]
- `hostname: mail.dms.com`
- `setup email add hello@example.com`
- `setup email add hello@another-example.com`
- Setup your DNS to use `mail.dms.com`. TLS cert for `mail.dms.com`, the mail accounts you add don't need cert only DNS.

What issue are you facing, what errors?

**Comment by vahidalvandi** [comment]
So I don't need to create an ssl cert for the second domain

Only `mail.dms.com` have ssl 

`mail.seconddoman.com`   a record 

How should I put the a mail record in the second domain?

**Comment by vahidalvandi** [comment]
Thank you . 
Is it necessary to create a dkim for the second domain and if necessary, what should I put in the txt title of the record in the second domain

**Comment by polarathene** [comment]
I am not sure about this one as I haven't deployed DMS myself.

https://docker-mailserver.github.io/docker-mailserver/latest/config/best-practices/dkim_dmarc_spf/#dkim-dns

I think you only need one DKIM key, and for your DNS records of each domain to be updated for it. Should be fine to create another DKIM key for the other domain instead of sharing one. That may provide more confidence in DKIM being configured for each domain within DMS.

Either way, run some tests to verify: https://docker-mailserver.github.io/docker-mailserver/latest/config/best-practices/dkim_dmarc_spf/#dkim-debug

**Comment by vahidalvandi** [comment]
i this have issue in selector name
