### ISSUE TITLE
other: Cannot set DNS record to point to SMTP server withcooudflare proxy

### ISSUE THREAD

**Issue by jpsanchezl10** [docker-mailserver/docker-mailserver#3493]
### Subject

Other

### Description

Setting the DNS A record to point to my server's ip works fine .
But If i enable the proxy setting in Cloudflare, I can't connect to my server anymore. 
so my IP is exposed to the net.
how can I solve this ?

**Comment by polarathene** [comment]
> But If i enable the proxy setting in Cloudflare, I can't connect to my server anymore.

This is a cloudflare issue not DMS.

Last I knew Cloudflare proxy setting doesn't support mail servers, consult their docs to find this information if it's still the case, otherwise they should explain how to make it work if it's been resolved since.

Try contacting one of their communities, or searching DMS issues (_I believe it's been discussed in the past and I commented with some links_). This isn't something we can really provide support on, so I'll be closing this.
