### ISSUE TITLE
other: My Server rejected email from my icloud email

### ISSUE THREAD

**Issue by jpsanchezl10** [docker-mailserver/docker-mailserver#3497]
### Subject

Other

### Description

I was testing and haven't have issues with the server, I can send email and receive emails .
I tried sending an email from my iCloud account and I can see in the logs of my server that the email reached my server, but it was rejected by my docker mail server.
'Recipient address rejected: Delayed by Postgrey;'

Here are the full logs:
```
Aug 22 19:57:31 smtp policyd-spf[7115]: prepend Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=17.58.38.56; helo=ms11p00im-qufo17281901.me.com; envelope-from=mypersonal@icloud.com; receiver=<UNKNOWN> 

action=greylist, reason=early-retry (173s missing), client_name=ms11p00im-qufo17281901.me.com, client_address=17.58.38.56/32, sender=mypersonal@icloud.com, recipient=email@mydomain.com

action=greylist, reason=early-retry (173s missing), client_name=ms11p00im-qufo17281901.me.com, client_address=17.58.38.56/32, sender=mypersonal@icloud.com, recipient=email@mydomain.com

action=greylist, reason=early-retry (173s missing), client_name=ms11p00im-qufo17281901.me.com, client_address=17.58.38.56/32, sender=mypersonal@icloud.com, recipient=email@mydomain.com

action=greylist, reason=early-retry (173s missing), client_name=ms11p00im-qufo17281901.me.com, client_address=17.58.38.56/32, sender=mypersonal@icloud.com, recipient=email@mydomain.com

Aug 22 19:57:31 smtp postfix/smtpd[7104]: NOQUEUE: reject: RCPT from ms11p00im-qufo17281901.me.com[17.58.38.56]: 450 4.2.0 <email@mydomain.com>: Recipient address rejected: Delayed by Postgrey; from=<mypersonal@icloud.com> to=<email@mydomain.com> proto=ESMTP helo=<ms11p00im-qufo17281901.me.com>
```

The email was received correctly after 20 mins

**Comment by polarathene** [comment]
This is expected:

https://github.com/docker-mailserver/docker-mailserver/blob/39ae101266af7511d85fbb5e9e4b19324390f5ce/test/tests/parallel/set1/spam_virus/postgrey_enabled.bats#L9

https://github.com/docker-mailserver/docker-mailserver/blob/39ae101266af7511d85fbb5e9e4b19324390f5ce/test/tests/parallel/set1/spam_virus/postgrey_enabled.bats#L56-L64

https://github.com/docker-mailserver/docker-mailserver/blob/39ae101266af7511d85fbb5e9e4b19324390f5ce/test/tests/parallel/set1/spam_virus/postgrey_enabled.bats#L68-L78

---

The [Postgrey feature is disabled by default](https://docker-mailserver.github.io/docker-mailserver/v12.1/config/environment/#enable_postgrey). If you enable it you should have an understanding why and what it does.

What happens is the [default delay is 5 minutes (_300 seconds_)](https://docker-mailserver.github.io/docker-mailserver/v12.1/config/environment/#postgrey_delay). But this increases I think when receiving mail again before that delay time expires, up to a certain limit. After the delay is done, it will get delivered, and the client trusted. It should only be because it was new and Postgrey did not recognize it, so it became greylisted.

---

You'll find some information (_[like this](https://github.com/docker-mailserver/docker-mailserver/issues/3362#issuecomment-1560595183)_) if you search our issue history.

Please respect our [Debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice. If you were approaching this properly with an actual bug report (_instead of skipping the form_), you'd see the following at the top of our bug report form:

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/c682e667-3b62-4ec7-bbd3-c2daa2af12e6)

Your logs gave you information that you were able to identify with keywords such as "Postgrey" and "Delay". Searching our issues here, or using a search engine should provide some helpful advice to explain the issue. Then you might look through our docs (which also has a search field), and try "Postgrey" which first result is about some ENV for this feature:

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/905665e1-f138-428d-bbc4-0be51dd7d441)

If you continue to report issues like this without putting in the effort we request., you'll likely not receive further support. Maintainers are limited with time and it's far better for us to deal with actual bugs related to DMS.

If you want to ask questions, it's better to [use our DIscussions page](https://github.com/orgs/docker-mailserver/discussions), which is more appropriate.
