### ISSUE TITLE
other: Question about file permissions in rootless podman/docker

### ISSUE THREAD

**Issue by Tokariew** [docker-mailserver/docker-mailserver#3499]
### Subject

Other

### Description

Hi i using rootless podman to run container, it run quite well from my point of view. But when i want to make backup of volumes i get several file permissions errors.
This is how i have volume mounted
```
	-v /data/containers/data/mailserver/config:/tmp/docker-mailserver:Z \
	-v /data/containers/data/mailserver/data:/var/mail:Z \
	-v /data/containers/data/mailserver/logs:/var/log/mail:Z \
	-v /data/containers/data/mailserver/state:/var/mail-state:Z \
```
I was thinking about using `--userns keep-id` but i get errors `Error: Can't drop privilege as nonroot user` and container don't start, i was thinking about using gidmap/uidmap, but i don't  think it possible to map several user from container to single host one.
Are there other option except adding my host user to groups which container create?

Files and directories on which rsync fail 
```
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/lib-spamassassin/.spamassassin" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/lib-spamassassin/sa-update-keys" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/spool-postfix/active" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/spool-postfix/bounce" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/spool-postfix/corrupt" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/spool-postfix/defer" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/spool-postfix/deferred" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/spool-postfix/flush" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/spool-postfix/hold" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/spool-postfix/incoming" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/spool-postfix/maildrop" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/spool-postfix/private" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/spool-postfix/public" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/spool-postfix/saved" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] opendir "/data/containers/data/mailserver/state/spool-postfix/trace" failed: Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] send_files failed to open "/data/containers/data/mailserver/logs/clamav.log": Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] send_files failed to open "/data/containers/data/mailserver/logs/freshclam.log": Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] send_files failed to open "/data/containers/data/mailserver/state/lib-postfix/master.lock": Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] send_files failed to open "/data/containers/data/mailserver/state/lib-postfix/postscreen_cache.db": Permission denied (13)
2023/08/23 11:09:48 [2580954] rsync: [sender] send_files failed to open "/data/containers/data/mailserver/state/lib-postfix/prng_exch": Permission denied (13)
```
other fails from container i can sync without problem

**Comment by polarathene** [comment]
> Are there other option except adding my host user to groups which container create?

There is a feature called ID mapped mount. I believe Podman got support for it, while Docker has not had a release with any easy integration added.

I'm not sure if it supports rootless though, but the feature does allow writing container UID/GID to different on on the host like your non-root user.

Multiple container ID to single ID on host though, I'm not sure if that's workable as that information would be lost to map back into container ID?

You can choose to use named data volume instead of bind mount volume, no mapping necessary then, but you'll not have direct access on the host? In docker it is possible to use `docker cp` but you'd want to preserve the ID info for backup. There might be a way you can take the volume as a backup/export though (_assuming you don't need easy/direct access to these files most of the time, data volume may suit you better?_).

Our docs have a [FAQ about doing a backup with `tar`](https://docker-mailserver.github.io/docker-mailserver/latest/faq/#what-about-backups). That may work better than rsync by bundling the metadata like ID into the archive file?

---

> Files and directories on which rsync fail

- `/data/containers/data/mailserver/state/spool-postfix/`
- `/data/containers/data/mailserver/state/lib-spamassassin/`
- `/data/containers/data/mailserver/state/lib-postfix/`
- /data/containers/data/mailserver/logs/`

The `state/` dir is handled here: https://github.com/docker-mailserver/docker-mailserver/blob/39ae101266af7511d85fbb5e9e4b19324390f5ce/target/scripts/startup/setup.d/mail_state.sh
- Files: https://github.com/docker-mailserver/docker-mailserver/blob/39ae101266af7511d85fbb5e9e4b19324390f5ce/target/scripts/startup/setup.d/mail_state.sh#L37-L55
- Folders: https://github.com/docker-mailserver/docker-mailserver/blob/39ae101266af7511d85fbb5e9e4b19324390f5ce/target/scripts/startup/setup.d/mail_state.sh#L57-L76

These are symlinks made from internal data, which might be affecting your `rsync` command?

---

The ownership is not too important to keep for these files as that same part of our startup scripts specifically corrects permissions (_Postfix is a bit more complicated than the others_): https://github.com/docker-mailserver/docker-mailserver/blob/39ae101266af7511d85fbb5e9e4b19324390f5ce/target/scripts/startup/setup.d/mail_state.sh#L83-L111

They're not your core data, so not as important. Some of it may also not backup well or be useful (`.lock` and `.db`).

I believe the Postfix queue gets stored here, mail that is for example having trouble delivering outbound, so waits to try again later. If that is lost then, it'd no longer know about it and that mail never gets sent, nor a failure to send after N tries sent back your way. For archive backups, that's probably not as important since the queue is more time sensitive.

---

ClamAV `clamav.log` + `freshclam.log` are configured here: https://github.com/docker-mailserver/docker-mailserver/blob/39ae101266af7511d85fbb5e9e4b19324390f5ce/target/scripts/startup/setup.d/security/misc.sh#L161-L165

Not sure why the logs would be an issue beyond the different user/group, which I guess is also affecting your other files 😅 

---

Still I think for backup purposes, you can probably not worry about this volume. It's useful for keeping that internal state across container restarts, especially if your system crashes and you had mail in the queue, or need to access the logs for troubleshooting.
