### ISSUE TITLE
feature request: UID variable

### ISSUE THREAD

**Issue by vincentDcmps** [docker-mailserver/docker-mailserver#3548]
### Context

I try to use docker mail server with my /var/mail volume on a nfs share but when container start 
he can't take ownership on folder because user 5000 not exist on my NAS

```
chown: changing ownership of '/var/mail': Invalid argument
[  ERROR  ]  Failed to fix /var/mail permissions
[  ERROR  ]  Shutting down
```

### Description

I have an LDAP service on my synology but UID are always greaterr thant 10000
so I need to create several local user on my synology and all my nomad cluster to get uid 5000 on everyone

we could put container docker user  UID 5000 in a variable to custom this one if needed

### Alternatives

store mail on filesytem without nas

### Applicable Users

people using NFS

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute?

I could try to perform modification or test

**Comment by polarathene** [comment]
You're using LDAP, you can actually override this IIRC. I am revising the LDAP support while I have time to, and recall Dovecot documents how you can map to your preferred UID.

DMS expects UID and GID of 5000, and will apply that at container startup as a fix when that's not the case. I think it's required for non-LDAP setup, and may not be necessary for LDAP, however we need proper tests in place to confirm that.

- Related issue: https://github.com/docker-mailserver/docker-mailserver/issues/2238
- Related PR: https://github.com/docker-mailserver/docker-mailserver/pull/2256

Although those are about each LDAP user having their own UID/GID values, not a common shared one.

> `/var/mail` volume on a nfs share

You can look up Dovecot documentation regarding NFS, I don't think we support that so you may experience other issues.

**Comment by vincentDcmps** [comment]
Thanks for your answer, I use LDAP but for I don't configure LDAP on DMS.
I think my issue is more from NFS side because I will get same if Not using LDAP.

I don't understand why we can't use another uid than 5000, it is just for internal use no?


So recommended storage for /var/mail is only local?

**Comment by polarathene** [comment]
> I don't understand why we can't use another uid/gid than 5000, it is just for internal use no?

- A user and group is created with `5000` in the `Dockerfile`.
- There is two times we specifically `chown -R`, startup script and `check-for-changes.sh`.
- AFAIK this is configured for Dovecot and IIRC the other value was ensuring `/var/mail` was given correct ownership for Dovecot to have permission to write content there.
- Per-user UID/GID I think may require another change. Been a while since I looked at Dovecots docs, just requires Dovecot to run as root so that it can create the user directories with the UID/GID from UserDB.

---

> So recommended storage for `/var/mail` is only local?

Plenty of LDAP users are fine with it. It's only an issue for them when they aren't ok with the `5000:5000` ownership which is where the problems come.

LDAP support has not been supported that well in DMS and I've been trying to address bugs there, but I lack the available time to spare :(

---

You may propose a PR to support an ENV to change the static `5000:5000`. The test suite must pass (_ideally also with the ENV change applied to confirm it should work_).

The linked LDAP tests had issues with the tests that were not resolved (_they were trying to avoid the `chown -R`_).

Presently (_and for some time now_), there is little bandwidth available from project maintainers. We'd love some more contributors, but it's been years since a new maintainer or regular contributed joined the project.

**Comment by polarathene** [comment]
Just noticed a similar request from June as well (_also NAS related concern_): https://github.com/orgs/docker-mailserver/discussions/3407#discussioncomment-6299183
