### ISSUE TITLE
other: Suspend Mailbox

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#3551]
### Subject

I would like to configure a not documented mail server use case

### Description

Hey

I don't seem to be able to find anywhere in the docs (sorry if I missed something obvious there!)

Is there a way to Suspend a mailbox?
So that it no longer receives emails (and doesn't need to send either).

In other words, I want to keep the contents of the mailbox,
preferentially be able to login too,
but emails no longer arrive to that mailbox.

If I remove the account from `postfix-accounts.cf`, I assume that would do what I want, and keep the files? Is there any risk that the files might be deleted in the future, if I don't have an entry in this file?

And if in the future I want to re-enable it, by adding the account in that file again, with a new password, it will keep the files as they are - is that correct?

Thank you!

**Comment by georglauterbach** [comment]
There isn't in terms of scripts that we provide. I have not yet heard about this before :) I'd suggest you to backup the mail data of the to be suspended account, then just remove the line (as you suggested) in `postfix-accounts.cf`.

**Comment by ghnp5** [comment]
Thank you @georglauterbach
No problem.

Back when I was in cPanel, they used `exim`, and they had the Suspend functionality.

When I moved away from cPanel, years ago, I found this container, which is great, but I noticed there wasn't this functionality, but I also didn't chase much for it. It's not a crucial feature. Just a nice to have :-)

Thank you again. I'll likely just go ahead and backup the data, and then remove the entry from `postfix-accounts.cf`.

Cheers!

**Comment by polarathene** [comment]
> In other words, I want to keep the contents of the mailbox,
> preferentially be able to login too,
> but emails no longer arrive to that mailbox.

This could be done with LDAP account provisioner.

The LDAP filter queries for receiving mail and account lookup for sending mail I think can add a constraint to an attribute like `mailEnabled=TRUE`. Disabling/suspending an account would just require disabling that attribute for the account.

---

> If I remove the account from `postfix-accounts.cf`, I assume that would do what I want, and keep the files? Is there any risk that the files might be deleted in the future, if I don't have an entry in this file?

That should work too. At container startup and change events, that file is processed to configure the Dovecot mailboxes, which Postfix relies on for authentication. No mail would be accepted for delivery, but you'd lose the ability to login too as a result. However the mailbox should still exist and not be lost (_best to keep a backup though_).

> And if in the future I want to re-enable it, by adding the account in that file again, with a new password, it will keep the files as they are - is that correct?

Yeah that sounds about right. The mailbox gets created if it doesn't exist and `chown -R` applied currently. Password is whatever is in `postfix-accounts.cf` stored password hash. Should be easy enough to test.

We do have a `setup email del` command that will delete a user, and I believe it has a `-y` option to also delete their mail storage content too, but otherwise only deletes the account from `postfix-accounts.cf`, then this change event is detected, and Dovecot recreates the entire UserDB and is restarted.

LDAP account provisioning would be less naive of an approach without the extra minimal downtime from that (no change event).

**Comment by ncovercash** [comment]
If you only want to prevent incoming mail from reaching the box (I do this for my no-reply addresses), you can do something like this:

1. Add the following to `config/postfix-main.cf` (per https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/override-defaults/postfix/):

```
smtpd_recipient_restrictions = check_recipient_access hash:/etc/postfix/recipient_access, permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain
```

This is the default `smtpd_recipient_restrictions`, with the addition of `hash:/etc/postfix/recipient_access`.

2. Create a file `recipient_access` (or whatever you want to call it):

You can use the following format, where 550/450 are the [SMTP status codes](https://en.wikipedia.org/wiki/List_of_SMTP_server_return_codes#%E2%80%94_4yz_Transient_negative_completion):

```
foo@domain.com    550 This mailbox does not accept incoming mail.
bar@domain.com    450 This mailbox can't accept mail right now (but the sender can retry later)
```

3. Create a script to run when the container starts, `user-patches.sh`

```bash
#!/bin/bash

echo "Compiling no-reply account list"
# I had to do this, you might not need to
chown root:root /etc/postfix/recipient_access
postmap /etc/postfix/recipient_access
```

4. Shove these into the container (via volumes/etc):
  - the `recipient_access` should be mapped directly into `/etc/postfix` (or you can change the path in the above files)
  - `postfix-main.cf` can go in your config directory, or be mapped directly in
  - `user-patches.sh` can go in your config directory, or be mapped directly in

5. Restart the server
