### ISSUE TITLE
other: Multiple DKIM signatures

### ISSUE THREAD

**Issue by jessec** [docker-mailserver/docker-mailserver#3559]
### Subject

I would like some feedback concerning a use case

### Description

Maybe nothing but I'm having multiple DKIM signatures on outgoing emails. The emails still validate as valid DKIM emails, can this hurt my deliverability?

**Comment by allddd** [comment]
An email signed with multiple DKIM headers will pass the check as long as at least one of them is the correct one for the sending domain.  
This is something that often happens when using forwarding services, as each server it passes through adds a signature.  

I assume you are referring to the situation where a single DKIM key is signed multiple times in the same email.  
If this is the case, identifying the problem depends on what exactly you are using.

I have experienced similar behaviour after the container was improperly stopped and unfortunately did not have time to investigate further as to what exactly caused the problem.  
Fortunately, `docker compose down && docker compose up -d` was able to fix the problem and the emails were signed correctly again.

If there have been no unexpected shutdowns (or restarts of the `docker.service`), you should take a closer look at the logs.  
I don't have much experience with OpenDKIM, but I can help you get Rspamd to actually log what happens, if that's what you're using.

**Comment by jessec** [comment]
Thanks good to hear things are still OK. I will dig in deeper as soon as I have some time for now I just put it on my TODO. Thanks.

**Comment by georglauterbach** [comment]
This does not hurt :) I have another use case: I am using elliptic-curve keys (ed25519 keys) _and_ RSA keys. This is because many mail servers are not capable of checking elliptic-curve keys yet. So all is good.
