### ISSUE TITLE
bug report: `Permission denied` - Unix socket files on QNAP NAS (`/var/mail-state`)

### ISSUE THREAD

**Issue by Jobsays** [docker-mailserver/docker-mailserver#3577]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

After starting the container for the first time and adding the first user, I get the Permission denied errors in the Relevant Log Files section below.

### 👟 Reproduction Steps

Created a new app on Qnap Container Station using the yaml below with the default mailserver.env from Git.  Once the container starts, I create the first user with docker exec -ti dockermailserver setup email add someone@somewhere.com.  The logs then begin spewing out the permissions errors below every second. 

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

Qnap QTS 5.1.1.2491

### ⚙️ Container configuration files

```yml
version: '3'

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: dockermailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.somedomain.com
    env_file: /share/Container/dockermailserver/mailserver.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /share/Container/dockermailserver/mail-data/:/var/mail/
      - /share/Container/dockermailserver//mail-state/:/var/mail-state/
      - /share/Container/dockermailserver/mail-logs/:/var/log/mail/
      - /share/Container/dockermailserver/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text
mail.err
Oct 11 15:18:51 mail postfix/master[677]: fatal: open lock file /var/lib/postfix/master.lock: cannot open file: Permission denied

mail.info
Oct 11 15:12:14 mail postfix/postfix-script[627]: starting the Postfix mail system
Oct 11 15:12:14 mail postfix/master[628]: fatal: open lock file /var/lib/postfix/master.lock: cannot open file: Permission denied
Oct 11 15:12:15 mail amavis[574]: starting. /usr/sbin/amavisd-new at mail.somedomain.com amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"
Oct 11 15:12:15 mail amavis[574]: perl=5.032001, user=, EUID: 109 (109);  group=, EGID: 111 111 (111 111)
Oct 11 15:12:15 mail amavis[574]: (!)Net::Server: 2023/10/11-15:12:15 Can't connect to UNIX socket at file /var/lib/amavis/amavisd.sock [Permission denied]\n  at line 66 in file /usr/share/perl5/Net/Server/Proto/UNIX.pm

mail.warn
Oct 11 15:12:15 mail amavis[574]: (!)Net::Server: 2023/10/11-15:12:15 Can't connect to UNIX socket at file /var/lib/amavis/amavisd.sock [Permission denied]\n  at line 66 in file /usr/share/perl5/Net/Server/Proto/UNIX.pm
```

**Comment by polarathene** [comment]
You're using a NAS for deployment, this seems to often run into compatibility issues that you'll need to identify.

Compatibility checks:
- [Check your product to see which kernel version is in use](https://www.qnap.com/en-us/release-notes/kernel), if it's the 4.2.x kernel  that would not be good.
- Next up is the Docker host filesystem in use. If this is via SMB/NFS, expect compatibility issues.
- Check what user Docker is run with on the host, it may influence the permission issues. Typical deployment expects root, IIRC this usually isn't the case with the NAS offerings?

Storage:
- You may also want to check if SELinux or similar security is active, it may be restricting access and require you to adapt your configuration for it (_with bind volume mounts our docs should mention a `:Z` option for SELinux_).
- Similar issues happen on macOS, but I think this is more to do with it's volume storage driver and VM used for running the docker host in (_as it doesn't run natively on macOS_). For macOS it does not properly persist permissions / ownership which causes problems with unix sockets IIRC.
- You could try with named data volumes instead of bind volume mounts, it might at least help you narrow down the problem.


---

This isn't a bug within DMS, it's an issue with your host system preventing the container from writing to these locations you're mounting as volumes. You'll need to troubleshoot that yourself or through QNAP customer support.

It'd be appreciated if you share any solution you encounter, or confirmation of what is causing the problem for any other QNAP / NAS users that run into the same issue and find your issue here.

**Comment by Jobsays** [comment]
Hey, thanks for the help!

1. I have the TVS-1282 model with the 5.10.60 kernel. 
2. The host filesystem is Ext4. 
3. Docker runs as the 'docker' user: docker:x:1002:100:Linux User,,,:/share/homes/docker:/bin/sh
4. Tried bind volume mounts with :Z but still go the errors
5. Haven't tried named data volumes yet but will keep that in my back pocket

Other things tried that didn't make a difference:

- adding privileged: true to the yaml
- adding cap_add: - DAC_READ_SEARCH to the yaml
- editing this environment.env file section:
# Support for deployment where these defaults are not compatible (eg: some NAS appliances):
# /var/mail vmail User ID (default: 5000)
DMS_VMAIL_UID=1002
# /var/mail vmail Group ID (default: 5000)
DMS_VMAIL_GID=100

I finally got it working (I think) by simply removing this line from the yaml, since all of the permissions errors were for files in /mail-state/:
volumes:
      - /share/Container/dockermailserver//mail-state/:/var/mail-state/:Z
Now the logs on startup show:
[   INF   ]  Welcome to docker-mailserver 12.1.0
[   INF   ]  Checking configuration
[   INF   ]  Configuring mail server
[ WARNING ]  !! INSECURE !! SSL configured with plain text access - DO NOT USE FOR PRODUCTION DEPLOYMENT
[ WARNING ]  'ONE_DIR=1' but no volume was mounted to '/var/mail-state'
[   INF   ]  Starting daemons
[   INF   ]  mail.somedomain.com is up and running
Oct 12 12:49:34 mail amavis[434]: starting. /usr/sbin/amavisd-new at mail.somedomain.com amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"
Oct 12 12:49:34 mail amavis[434]: perl=5.032001, user=, EUID: 109 (109);  group=, EGID: 111 111 (111 111)
Oct 12 12:49:34 mail amavis[434]: Net::Server: Group Not Defined.  Defaulting to EGID '111 111'
Oct 12 12:49:34 mail amavis[434]: Net::Server: User Not Defined.  Defaulting to EUID '109'
Oct 12 12:49:34 mail amavis[434]: No ext program for   .zoo, tried: zoo
Oct 12 12:49:34 mail amavis[434]: No ext program for   .doc, tried: ripole
Oct 12 12:49:34 mail amavis[434]: No decoder for       .F   
Oct 12 12:49:34 mail amavis[434]: No decoder for       .doc 
Oct 12 12:49:34 mail amavis[434]: No decoder for       .zoo 
Oct 12 12:49:35 mail postfix/postfix-script[556]: starting the Postfix mail system
Oct 12 12:49:35 mail postfix/master[557]: daemon started -- version 3.5.18, configuration /etc/postfix

**Comment by polarathene** [comment]
> I finally got it working (I think) by simply removing this line from the yaml, since all of the permissions errors were for files in `/var/mail-state/`:

That's interesting, I guess it's something to do with the unix socket files. Not sure why that'd differ from other files created in these volume mounts. I know that we run some ownership / permission changes to try prevent this issue:

https://github.com/docker-mailserver/docker-mailserver/blob/82c38f242648290ab109de8e3994ea7564120deb/target/scripts/startup/setup.d/mail_state.sh#L83-L93

Perhaps that fails due to your environment 🤷‍♂️ (_perhaps due to the `docker` user not being root on the Docker host_)

---

This location is important for persisting any state related to these services. One of those is the Redis database for rspamd I think if using that feature. Another is the mail queue with Postfix which would be lost / forgotten if something brings down the container.

You can probably use a named data volume successfully. You only need bind volume mounts when you want the contents to be stored on disk in an easy to access manner. If you don't need that named data volumes should work and can be exported / backed up if necessary.

**Comment by Jobsays** [comment]
Okay, we got it fixed!  I added the /var/mail-state/ back to the bind volume mounts after your advice since I definitely want to persist that data.  Before creating the container this time, I ran these commands on the host filesystem where the container data lives from the last deployment: 
sudo chown -R docker:everyone  /share/Container/dockermailserver
sudo setfacl -Rb /share/Container/dockermailserver
sudo chmod -R 777 /share/Container/dockermailserver

And for good measure added these variables to the mailserver.env file:
PUID=1002
PGID=100

And this to the yaml:
privileged: true

(credit to this forum post for providing the answer: [https://forum.qnap.com/viewtopic.php?t=164018](https://forum.qnap.com/viewtopic.php?t=164018 ))

Container startup logs looking more normal now:
```
[   INF   ]  Welcome to docker-mailserver 12.1.0
[   INF   ]  Checking configuration
[   INF   ]  Configuring mail server
[   INF   ]  Starting daemons
[   INF   ]  mail.somedomain.com is up and running
Oct 13 14:45:13 mail amavis[645]: starting. /usr/sbin/amavisd-new at mail.somedomain.com amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"
Oct 13 14:45:13 mail amavis[645]: perl=5.032001, user=, EUID: 109 (109);  group=, EGID: 111 111 (111 111)
Oct 13 14:45:14 mail amavis[645]: Net::Server: Group Not Defined.  Defaulting to EGID '111 111'
Oct 13 14:45:14 mail amavis[645]: Net::Server: User Not Defined.  Defaulting to EUID '109'
Oct 13 14:45:14 mail amavis[645]: No ext program for   .zoo, tried: zoo
Oct 13 14:45:14 mail amavis[645]: No ext program for   .doc, tried: ripole
Oct 13 14:45:14 mail amavis[645]: No decoder for       .F   
Oct 13 14:45:14 mail amavis[645]: No decoder for       .doc 
Oct 13 14:45:14 mail amavis[645]: No decoder for       .zoo 
Oct 13 14:45:14 mail amavis[645]: Using primary internal av scanner code for ClamAV-clamd
Oct 13 14:45:14 mail amavis[645]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
```

Thanks for all the help, @polarathene !

**Comment by casperklein** [comment]
> And for good measure added these variables to the mailserver.env file:
> PUID=1002
> PGID=100

fyi: These ENVs are not supported by DMS.

**Comment by polarathene** [comment]
Just a heads-up to your solution and anyone else that lands here, if you're security conscious copy/paste solutions should be understood better before you apply them.

---

I hope you understand that `privileged: true` is not ideal for security of your Docker host system. Avoid this if you don't need it. If you do you probably need a `cap_add` for something.

Likewise, do you understand what `chmod -R 777` is doing? You are granting anyone read, write and execute permissions. The first number is for the user/owner that created the file(s), the next for groups associated to them, and the third is for anyone else. It is a hammer approach that disregards any security.

`setfacl -Rb` is removing any extended ACL attributes. Again probably not something you should strip away without knowing what these were first (_if there was any applied in the first place_).

`chown -R docker:everyone`:
- The Docker host `docker` user can write/create data for the location and was likely the main concern. Presumably your Docker instance is running as rootless and mapping the root user `0` to the UID of the `docker` user on your host.
- `everyone` sounds very broad, shouldn't be necessary I think as our startup scripts in the container should fix any internal permission issues and just requires our container `root` user to have permissions to do such.
- Due to your `chmod -R 777` the `user:group` change here doesn't really accomplish much AFAIK.

**Comment by Jobsays** [comment]
I did some more experimenting to try and get closer to the exact problem without opening too many security vulnerabilities and confirmed everything still works after removing `privileged: true` and `PUID=1002 & PGID=100` from the setup.  The `chmod -R 777` command is what fixes it, so digging a bit further, I discovered that if I reset ownership of /var/mail-state/ on the host back to default with `sudo chown -R docker:everyone /mail-state` I get the expected result:
```
[mail-state]$ ls -la
total 52
drwxrwx--- 11 docker everyone 4096 2023-10-14 12:48 ./
drwxrwx---  7 docker everyone 4096 2023-10-14 12:46 ../
drwxr-x---  6 docker everyone 4096 2023-05-03 00:32 lib-amavis/
drwxr-xr-x  2 docker everyone 4096 2023-05-01 14:46 lib-clamav/
drwxr-xr-x  2 docker everyone 4096 2023-10-14 12:48 lib-dovecot/
drwxr-xr-x  2 docker everyone 4096 2023-10-14 12:41 lib-fail2ban/
drwx------  2 docker everyone 4096 2023-05-03 00:32 lib-fetchmail/
drwxr-xr-x  2 docker everyone 4096 2022-01-30 09:29 lib-logrotate/
drwxr-xr-x  2 docker everyone 4096 2023-01-21 18:17 lib-postfix/
drwxr-xr-x  3 docker everyone 4096 2023-05-03 00:32 lib-spamassassin/
drwxr-xr-x 16 docker everyone 4096 2023-10-14 12:48 spool-postfix/
```
But as soon as the container is restarted, `ls -la` shows this:
```
drwxrwx--- 11 docker everyone       4096 2023-10-14 12:48 ./
drwxrwx---  7 docker everyone       4096 2023-10-14 12:46 ../
drwxr-x---  6    109            111 4096 2023-05-03 00:32 lib-amavis/
drwxr-xr-x  2    200            200 4096 2023-05-01 14:46 lib-clamav/
drwxr-xr-x  2 docker everyone       4096 2023-10-14 12:56 lib-dovecot/
drwxr-xr-x  2 docker everyone       4096 2023-10-14 12:41 lib-fail2ban/
drwx------  2    102 guest          4096 2023-05-03 00:32 lib-fetchmail/
drwxr-xr-x  2 admin  administrators 4096 2022-01-30 09:29 lib-logrotate/
drwxr-xr-x  2    101            102 4096 2023-01-21 18:17 lib-postfix/
drwxr-xr-x  3    108            110 4096 2023-05-03 00:32 lib-spamassassin/
drwxr-xr-x 16 admin  administrators 4096 2023-10-14 12:56 spool-postfix/
```
Since those numerical UID & GID don't exist on the host, they have no permissions on the file system, and that is why `chmod -R 777` fixes the problem, since it grants those unknown users write access to these directories.

**Comment by polarathene** [comment]
> The `chmod -R 777` command is what fixes it

Shouldn't be required, `770` at the very least should still work.

> Since those numerical UID & GID don't exist on the host, they have no permissions on the file system

Not true. Human friendly name mappings instead of numerical UID / GID is not required for permissions to work. Under the hood it's always the ID value. What is required is for the Docker container user `root` that internally is UID + GID of `0:0` to properly have access.

Since your Docker host does not run Docker as root, you needed to remedy that, as the containers `root` user is mapping to the host `docker` user. Whatever name mappings are on the host for any of the UID / GID values is irrelevant to the functionality, just misleading to the reader as they are not aligned to what the container associates them to.
