### ISSUE TITLE
change port 25 to 2525

### ISSUE THREAD

**Issue by michaelmartinnz** [docker-mailserver/docker-mailserver#3620]
### Subject

I would like some feedback concerning a use case

### Description

Hi,

how to change postfix smtp 25 to port 2525?

I did:

`config/postfix-master.cf`:
```
smtp       inet n       -       n       -       1       postscreen
2525       inet n       –       n       –       –       smtpd
tlsproxy   unix -       -       n       -       0       tlsproxy
dnsblog    unix -       -       n       -       0       dnsblog
submission inet n       -       n       -       -       smtpd
```

`ufw allow 2525` and in `docker-compose.yml` change `25:25` to `2525:2525`

```bash
docker compose down
docker system prune
docker compose up --build
```

but it doesn't work.

Thanks, Michael

**Comment by polarathene** [comment]
Can you provide more context to why you want to do this?

- Is your intent to not receive mail from public third-parties? That needs to be port 25, other mail servers will not know otherwise.
- Did you instead want to send mail out on port 2525? This change you're attempting does not support that.
  - If you want this you want to [configure a relayhost](https://docker-mailserver.github.io/docker-mailserver/v12.1/config/advanced/mail-forwarding/relay-hosts/).
  - Port 2525 is a common port for submitting to relay host services like SendGrid, when you configure for that all outbound mail from DMS can be sent via the relayhost.

It's not clear what other reason you would have for this. It's usually for outbound mail to these services when your server / network prevents you from sending mail out on port 25, so instead the third-party service supports other ports for you to send to, and they will send the mail out on port 25 on their servers instead to the recipient.

If you really want port 2525 for inbound mail, then compose lets you map a host port like 2525 to an internal container port like 25. You don't need to try anything else for that?

**Comment by michaelmartinnz** [comment]
digital ocean droplet is blocking port smtp 25 to sent emails.

**Comment by polarathene** [comment]
> digital ocean droplet is blocking port smtp 25 to sent emails.

Yes, then your attempt to address it would never work.

Delivering outbound mail will require port 25, unless you relay through a service like SendGrid.

Unauthenticated mail is always delivered to a mail server over port 25.

**Comment by polarathene** [comment]
Next time please pay attention to our docs: https://docker-mailserver.github.io/docker-mailserver/v12.1/config/debugging/#mail-sent-from-dms-does-not-arrive-at-destination

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/58b78049-c5dd-4d97-8eb6-4149adfedf71)

---

If you tried to raise a bug report, you would get a link very early on to direct you there:

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/0e71cf81-a6b6-468f-a9f4-816170de64e1)

**Comment by michaelmartinnz** [comment]
Ok, thank you.
