### ISSUE TITLE
bug report: can't limit to receive via TLS 1.3 only

### ISSUE THREAD

**Issue by ww7** [docker-mailserver/docker-mailserver#3685]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I created user-patches.sh file that patches '/etc/postfix/main.cf'
to
```
smtpd_tls_mandatory_protocols= !SSLv2,!SSLv3,!TLSv1,!TLSv1.1,!TLSv1.2,TLSv1.3
smtpd_tls_protocols= !SSLv2,!SSLv3,!TLSv1,!TLSv1.1,!TLSv1.2,TLSv1.3
smtp_tls_mandatory_protocols= !SSLv2,!SSLv3,!TLSv1,!TLSv1.1,!TLSv1.2,TLSv1.3
smtp_tls_protocols= !SSLv2,!SSLv3,!TLSv1,!TLSv1.1,!TLSv1.2,TLSv1.3
```
and extended `tls_high_cipherlist` with `TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256`

TLS 1.3 working fine, but still receiving from Outlook servers via TLS 1.2

After setting
```
smtpd_tls_security_level = encrypt
smtp_tls_security_level = encrypt
```
SMTP stops receiving emails and can't send

At docker log
```
amavis Negative SMTP resp. to DATA: 530 5.7.0 Must issue a STARTTLS command first
```

At Mail Delivery Error
```
127.0.0.1[127.0.0.1] said: 530
    5.7.0 id=01082-01 - Rejected by next-hop MTA on relaying, from
    MTA(smtp:[127.0.0.1]:10025): 530 5.7.0 Must issue a STARTTLS command first
    (in reply to end of DATA command)
```

### 🐋 DMS Version

v13.0.1

### 💻 Operating System and Architecture

Ubuntu 22.04

**Comment by georglauterbach** [comment]
> ```
> smtpd_tls_security_level = encrypt
> smtp_tls_security_level = encrypt
> ```

Probably not what you want: "[...] require that clients use TLS encryption" ([source](https://www.postfix.org/postconf.5.html#smtpd_tls_security_level))

Please post what your `user-patches.sh` looks like and show us your patched `main.cf`.

---

On a different note: when using `TLS_LEVEL=modern`, you get >=TLSv1.2. This is desirable. Do you have a special use-case that warrants using only TLSv1.3? You will lose a lot of e-mails by rejecting TLSv1.2 and in case you want to "simply" (1) run a mail server.

---

(1)

![image](https://github.com/docker-mailserver/docker-mailserver/assets/44545919/75d98f82-f213-4464-b468-b2436fab015d)

**Comment by polarathene** [comment]
> Do you have a special use-case that warrants using only TLSv1.3?

I would like an answer to this as well.

I audited the config here a while back (_not a professional but quite confident in my assessment and changes contributed_), if you use `TLS_LEVEL=modern` you'll have best practice ciphers with TLS 1.2 and above.

Last I knew you cannot configure TLS 1.3 ciphers like earlier cipher suites, so you'd get no improvement from trying to restrict to those AFAIK.

**Comment by georglauterbach** [comment]
> There are no benefits in security terms, but request from the client.

I don't understand; can you elaborate?

> `-o smtpd_tls_protocols=!SSLv2,!SSLv3,ITLSv1,ITLSv1.1,ITLSv1.2,TLSv1.3`
> Any suggestions or corrections can be? 

Shouldn't it be more like:

```diff
--o smtpd_tls_protocols=!SSLv2,!SSLv3,ITLSv1,ITLSv1.1,ITLSv1.2,TLSv1.3
+-o smtpd_tls_protocols=!SSLv2,!SSLv3,!TLSv1,!TLSv1.1,!TLSv1.2,TLSv1.3
```

in your case? It's not `ITLSx.x` but `!TLSx.x`.

**Comment by polarathene** [comment]
> but request from the client.

Is the client informed? They may not understand the impact of their request?

It's not uncommon when someone tries to add such constraints that they lack much expertise with security (_similar to those that think RSA 4096-bit certs should be used instead of RSA 2048-bit_).

TLS 1.3 will be used when clients support it, and any concerns they have with TLS 1.2 should be alleviated with `TLS_LEVEL=modern`, since we have limited the selection only to those that are secure.

As mentioned previously, I don't think you're gaining anything from adding TLS 1.3 ciphers to the cipher list, AFAIK this does nothing TLS 1.3 is treated differently, last I knew its supported ciphers were not configurable by server-side.

---

https://www.postfix.org/postconf.5.html#smtpd_tls_mandatory_protocols

Note that the next major release of DMS will upgrade the base image, which will bring a newer Postfix and you'll be able to simplify that to just `smtpd_tls_mandatory_protocols = >=TLSv1.3`.

You potentially have a typo in the syntax, as has been mentioned with `ITLS` instead of `!TLS`, hopefully you're testing your changes are effective? Try running `testssl.sh` or similar to verify your TLS support and cipher suite is what you expect.

You're also setting protocol constraints on inbound (`smtpd`), but while you override `smtp` (outbound) to also force `encrypt`, you're not adjusting the protocols there? (`smtp_tls_protocols`)

Unless you're still using `main.cf`, in which case some of these changes you've added to `master.cf` may be redundant, they should by default be what `main.cf` configures, with `master.cf` allowing you to override them with `-o`. We provide support via `postfix-main.cf` and `postfix-master.cf` files to add your own overrides to either file without needing to do it via `user-patches.sh`

---

https://www.postfix.org/postconf.5.html#smtpd_tls_security_level

As already mentioned `smtpd_tls_security_level = encrypt` depends on context.
- As the linked docs mention, it's technically mandated that you allow mail to be delivered to Postfix unencrypted (_just because it arrives over a secure connection does not mean it was through any additional hops prior btw_)
- If this deployment is for internal use only it's a non-issue.

> `smtpd_tls_exclude_ciphers=aNULL,MD5,DES,ADH,RC4,RIPEM`

You've modified our default, but was there a need to?:

https://github.com/docker-mailserver/docker-mailserver/blob/908d38047ce4be6dd1e8ca5021d0bce86625a3c3/target/postfix/main.cf#L44

The one we provide should work well with our cipher suite selection:

https://github.com/docker-mailserver/docker-mailserver/blob/908d38047ce4be6dd1e8ca5021d0bce86625a3c3/target/scripts/helpers/ssl.sh#L133-L143

When you limit yourself to TLS 1.3 IIRC none of these will have any relevance. Use `testssl.sh` to verify that, but you're probably adding additional configuration that isn't beneficial.

> `smtpd_tls_ciphers=medium`

You're enforcing `encrypt` which uses the `smtpd_tls_mandatory_ciphers` which you've set to `high`, so this addition does nothing for you? You'll also find we already configure to `high` in the same way by default via `main.cf`:

https://github.com/docker-mailserver/docker-mailserver/blob/908d38047ce4be6dd1e8ca5021d0bce86625a3c3/target/postfix/main.cf#L42

We do this to have a separate cipher suite on submission(s) ports, while port 25 is more relaxed due to the requirement for public exposure making security less relevant/reliable.

**Comment by polarathene** [comment]
> > There are no benefits in security terms, but request from the client.
> 
> I don't understand; can you elaborate?

Client as in someone is paying them to provide a service of setting up DMS. Not client-side software like Thunderbird 😅 

It's not unusual for such requests, and sometimes all you can do is advise the client, but in the end they're paying for a service and if they disregard any advice that is their choice/risk 🤷‍♂️
