### ISSUE TITLE
Possibility to add the dynamic html footer (businness card/signature) to all outgoing emails.

### ISSUE THREAD

**Issue by wwk-github** [docker-mailserver/docker-mailserver#3689]
### Context

To make all outgoing mails company branded it is required to add standard looking footer to all outgoing mail sent by authorised users.

### Description

Add html footer (businness card/signature) to all outgoing emails. The footer would be dynamic for every user (for the simpicyty lets assume ith would need to have: name, surname, company branch address, logo (picture attached/embeded to every mail payload to avoid linking),  email address, mobile phone number.

### Alternatives

None yet.

### Applicable Users

All users.

### Are you going to implement it?

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

### What are you going to contribute?

I would need some guidance where to hook this feature.

**Comment by reneploetz** [comment]
Generally speaking: While this is indeed possible it's highly discouraged as it can easily break and adding footers should usually be done by the user himself. Using this within the mail-server also would put additional burden on whoever is maintaining the server as the templates would need to be updated regularly.

It's a also bit tricky to do this dynamically, but I can give you some guidance how you can implement this.
You can read this for inspiration: https://www.howtoforge.com/how-to-automatically-add-a-disclaimer-to-outgoing-emails-with-altermime-postfix-on-debian-squeeze

Note that I did not specifically test this, but I merely provide you a possible way to implement this.

You will need to build a custom docker image with "altermime" as additional package: https://packages.debian.org/bookworm/altermime

Addtionally you need to create a postfix filter that will add the header to all outgoing emails.

1. Create a shell script that will get all incoming mails and return a modified version.
The idea here is that we obtain the from-address from the user that was sending the message. As difference from the original script we are lowercasing the result of this so that we can create a consistent lowercase email address. Note that this is a rather simplistic approach, but it should work for most addresses. You can try to get a better regex/extraction method.
The version of the howto mentioned is using an exclusion list because your shell script will receive both incoming and outgoing emails. You really do not want to modify incoming files. I have removed that feature for simplicity because we can simply use the file path and add it if it exists.

For each user you would create a two files in the `/tmp/docker-mailserver/postfix/disclaimers/<mail address> folder. One is for the txt part of the mail, one is for html. If you only want the business card on html mails you can remove that part of the modification.
You can also opt for a general approach and create the templates using whatever template language you want to use and a static file with all the user data so that you do not need a file per user.

Create a file named `postfix_disclaimer` and put it into a directory where you would build the custom image.

```
#!/bin/sh
INSPECT_DIR=/var/spool/disclaimer
SENDMAIL=/usr/sbin/sendmail

# Exit codes from <sysexits.h>
EX_TEMPFAIL=75
EX_UNAVAILABLE=69

# Clean up when done or when aborting.
trap "rm -f in.$$" 0 1 2 3 15

# Start processing.
cd $INSPECT_DIR || { echo $INSPECT_DIR does not exist; exit
$EX_TEMPFAIL; }

cat >in.$$ || { echo Cannot save mail to file; exit $EX_TEMPFAIL; }

# obtain From address
from_address=`grep -m 1 "From:" in.$$ | cut -d "<" -f 2 | cut -d ">" -f 1 | tr '[:upper:]' '[:lower:]'`
disclaimer_userdir="/tmp/docker-mailserver/postfix/disclaimers/$from_address"

if [ -d "$disclaimer_userdir" ]; then
    /usr/bin/altermime --input=in.$$ \
                   --disclaimer="$disclaimer_userdir/disclaimer.txt" \
                   --disclaimer-html="$disclaimer_userdir/disclaimer.txt" || \
                    { echo Message content rejected; exit $EX_UNAVAILABLE; }
fi

$SENDMAIL "$@" <in.$$

exit $?
```


2. Create a `Dockerfile` to add altermine and postfix filters to it
I'm using the "edge" version of the mailserver, but you can select a stable release version for this as well. We install altermime and the script and will let it run under a non-root user. You can opt for the postfix user too, but keeping this separately does not hurt.

```
FROM mailserver/docker-mailserver:edge
ADD postfix_disclaimer /usr/bin/postfix_disclaimer
RUN apt-get update && \
    apt-get -y --no-install-recommends install altermime && \
    useradd -r -c "Postfix Disclaimer" -d /var/spool/disclaimer disclaimer && \
    mkdir /var/spool/disclaimer && \
    chown disclaimer:disclaimer /var/spool/disclaimer && \
    chmod 750 /var/spool/disclaimer && \
    chgrp disclaimer /usr/bin/postfix_disclaimer && \
    chmod 750 /usr/bin/postfix_disclaimer && \
    sed -i -E 's|^  -o syslog_name=postfix/submission|  -o syslog_name=postfix/submission\n  -o content_filter = disclaimer:|g' /etc/postfix/master.cf && \
    cat >>/etc/postfix/master.cf <<EOF
disclaimer     unix    -       n       n       -       -       pipe
    flags=Rq user=disclaimer argv=/usr/bin/postfix_disclaimer -f ${sender} -- ${recipient}
EOF
```

Note that using sed to add the content_filter will clash with ENABLE_AMAVIS=1 as both are adding content filters to postfix. If you do use this, you need to use `user-patches.sh` to add your filter within the amavis filter on runtime. The file content that will used is here with the line referenced: https://github.com/docker-mailserver/docker-mailserver/blob/master/target/amavis/postfix-amavis.cf#L17

**Comment by wwk-github** [comment]
Tnx. I will give it a try.
