### ISSUE TITLE
bug report: ENABLE_QUOTA=0 produces `sed` error.

### ISSUE THREAD

**Issue by casperklein** [docker-mailserver/docker-mailserver#3706]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

In #3703, I've replaced `sed` statements with our `sedfile` wrapper. This revealed a not working `sed` statement:

```
[  DEBUG  ]  Setting up Dovecot quota
[  ERROR  ]  No difference after call to 'sed' in 'sedfile' (sed -i s|check_policy_service inet:localhost:65265||g /etc/postfix/main.cf)
```

### 👟 Reproduction Steps

Start DMS with `ENABLE_QUOTA=0`:

```
docker run --rm --interactive --tty --name dms-test_example \
                --env OVERRIDE_HOSTNAME=mail.example.test \
                --env POSTFIX_INET_PROTOCOLS=ipv4 \
                --env DOVECOT_INET_PROTOCOLS=ipv4 \
                --env ENABLE_CLAMAV=0 \
                --env ENABLE_AMAVIS=0 \
                --env ENABLE_RSPAMD=0 \
                --env ENABLE_OPENDKIM=0 \
                --env ENABLE_OPENDMARC=0 \
                --env ENABLE_POLICYD_SPF=0 \
                --env ENABLE_SPAMASSASSIN=0 \
                --env LOG_LEVEL=trace \
                --env ENABLE_QUOTAS=0 \
                mailserver-testing:ci
```

Related script: https://github.com/docker-mailserver/docker-mailserver/blob/bbed3f66081a838275c54ac32de5d3ceac4f49b1/target/scripts/startup/setup.d/dovecot.sh#L100-L101

### 🐋 DMS Version

Branch from #3703 not merged yet

### 💻 Operating System and Architecture

Debian

**Comment by georglauterbach** [comment]
Can you provide the fix?:)

**Comment by casperklein** [comment]
Yes, but I wasn't 100% sure how to fix it, that's why I opened this issue.

1. What have changed for this regression to happen / What is the root cause
2. Why the quota tests didn't catch this problem

**Comment by casperklein** [comment]
As far I can tell, `check_policy_service inet:localhost:65265` was never part of `main.cf`.

So removing it, in case of `ENABLE_QUOTAS=0` makes no sense and did never work?

My proposed fix therefor is, to remove this line completely.

**Comment by polarathene** [comment]
> My proposed fix therefor is, to remove this line completely.

👍 

---

<details>
<summary>Original response</summary>

> So removing it, in case of `ENABLE_QUOTAS=0` makes no sense and did never work?

I recall you modified the Quotas tests to run with ENV change on an existing container, probably for a `setup` command. Instead of trying with a separate container instance (_due to the test being stuck in the larger `tests.bats` file at the time_).

Looking over at the `sed` line for the logic here, I would guess that it was for handling container restarts with the state change being kept? Changing ENV between runs of `docker run` or `docker compose up` recreates the container AFAIK, so no internal files should persist...

It may just have been naively added as an undo/revert? 🤷‍♂️ 

---

> 2\. Why the quota tests didn't catch this problem

They had issues IIRC, I have a PR that's probably getting stale at this point to refactor them 😅 

---

<details>
<summary>Dovecot Quota PR (stale) - hidden as not relevant</summary>

I have quite a bit going on, so it's been low priority for me to circle back to completing that PR as much as I'd like to, I recall it being almost done but some changes on a local copy being relevant. However those exist on another disk that's a bit tricky for me to locate and access atm 😬 

It may be best to look over it's current state and get the PR merged with a TODO issue for my backlog to compare the PR branch with my local for any improvements/fixes that were intended to go forward.

It wouldn't have been an issue if my PC at the time didn't die on me earlier in the year 💀 (_presently on a laptop with a few GB storage spare, unable to run my VMs until I disable WSL2 or replace windows for Linux, Dovecot Quota PR will be on one of my SATA SSDs, potentially in a VM, just more difficult to find as that'd be a 4TB disk while a separate disk had software that kept track of projects_)

</details>

**EDIT:** The ENV for toggling the feature has a separate test from the quota tests, it only checks if the feature is disabled by the omission of the config:

https://github.com/docker-mailserver/docker-mailserver/blob/b9f7ff86dea6709f785be0bf900c2845f9e321ea/test/tests/parallel/set1/dovecot/quotas_disabled.bats#L29-L33

</details>
