### ISSUE TITLE
security: postfix SMTP smuggling

### ISSUE THREAD

**Issue by becker-s** [docker-mailserver/docker-mailserver#3719]
### Subject

Something else that requires developers attention

### Description

A vulnerability affecting several mail server implementations, including postfix, has been disclosed recently.
See the related postfix documentation page for more details: https://www.postfix.org/smtp-smuggling.html

While a short-term workaround exists, it is only partial:
>  NOTE: This will stop only the published form of the attack. Other forms exist that will not be stopped in this manner.

Postfix should be updated to a version in which the vulnerability is fixed (3.8.4, 3.7.9, 3.6.13 or 3.5.23) and the new optional feature [`smtpd_forbid_bare_newline`](https://www.postfix.org/postconf.5.html#smtpd_forbid_bare_newline) be set to `yes`. The feature will be enabled by default for postfix >= 3.9.

If the `smtpd_forbid_bare_newline` feature cannot be enabled for backward-compatibility reasons, you could release a patch version of DMS with one of the patched postfix versions and let users decide whether they want to enable the feature [via their local configuration](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/override-defaults/postfix/).

**Comment by georglauterbach** [comment]
Current state of DMS' Postfix packaging (see <https://packages.debian.org/de/postfix>):

- `:edge` currently packs Debian 11, hence the version of Postfix is `3.5.18-0+deb11u1` and the vulnerability exists
- the new 13.1.0 release does not pack #3403 and hence contains the same version (`3.5.18-0+deb11u1`) as the current `:edge`
- when #3403 is merged, we will release v14.0.0, and Postfix will be updated to `3.7.6-0+deb12u2` where the vulnerability can be fixed

Due to the way we organize releases, we cannot (or rather, it'd be immensely complicated to) backport such fixes. I do not know how we could provide users of DMS with versions <v14.0.0 with fixes.

CC @casperklein @polarathene

**Comment by georglauterbach** [comment]
Small note: @becker-s thank you very much for reporting this! :)

Next time, please use the dedicated security vulnerability reporting feature that we have enabled (<https://github.com/docker-mailserver/docker-mailserver/security/advisories/new>).

**Comment by casperklein** [comment]
Quick summary:

- Mitigation for **all postfix versions** for the **published attack**: `smtpd_data_restrictions = reject_unauth_pipelining`
  - Postfix 3.8.1, 3.7.6, 3.6.10 and 3.5.20 have a dedicated config option for that: [`smtpd_forbid_unauth_pipelining`](https://www.postfix.org/postconf.5.html#smtpd_forbid_unauth_pipelining)
- Postfix 3.8.4, 3.7.9, 3.6.13 and 3.5.23 provides additional mitigation for all attacks (including those not published yet) with the config option: [`smtpd_forbid_bare_newline`](https://www.postfix.org/postconf.5.html#smtpd_forbid_bare_newline)`

For now, `smtpd_data_restrictions = reject_unauth_pipelining` should be set. But:

> this may break legitimate SMTP clients that mis-implement SMTP, but such clients are exceedingly rare, especially when email is sent across the Internet.

I could imagine, Debian will release postfix updates for Debian 11/12 shortly.

**Comment by polarathene** [comment]
> leading me to think that that type of issue is only meant for direct vulnerabilities rather than vulnerabilities in dependencies.

That's how I see it too.

If the vulnerability is already public knowledge, I don't see any issue with opening an issue here. At best you'd be minimizing awareness? 🤷‍♂️ I'd expect any capable malicious actor would have no issue finding the same public disclosure.

> I do not know how we could provide users of DMS with versions <v14.0.0 with fixes.

Technically the scheduled build workflow could be adapted with manual dispatch with tag as an input. I think that would allow for building from the git tagged commit and publishing that tag to DockerHub and GHCR.

That should build with the package install process updating to the latest packages available, since we don't introduce any actual change beyond that it should only be packages with updated point releases (bug / security fixes). ClamAV database would be updated too.

Probably need to build without any cache used, which I don't think we presently support 🤔

**Comment by casperklein** [comment]
fyi: There will be a talk at [37C3](https://fahrplan.events.ccc.de/congress/2023/fahrplan/events/11782.html)

**Comment by bjoerns1983** [comment]
Could you please give me an info how to properly insert the short term fix into postfix main.cf?
Can is simply post:
smtpd_data_restrictions = reject_unauth_pipelining
smtpd_discard_ehlo_keywords = chunking
into the mailserver.env, restart the container and it will be picked up by the postfix running inside the container?

**Comment by georglauterbach** [comment]
You need <https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/override-defaults/postfix/> and add the lines there.

**Comment by bjoerns1983** [comment]
Really thanks for that hint.

Okay if i see this correct smtp_data_restrictions is already set to reject_unauth_pipelining in master.cf, so i only hat to changte smtpd_discard_ehlo_keywords from silent-discard, dsn to chunking to implement the workaround. Is taht correct?

**Comment by georglauterbach** [comment]
> Really thanks for that hint.
> 
> Okay if i see this correct smtp_data_restrictions is already set to reject_unauth_pipelining in master.cf, so i only hat to changte smtpd_discard_ehlo_keywords from silent-discard, dsn to chunking to implement the workaround. Is taht correct?

`smtp_data_restrictions` only seems to be set for Amavis; setting it in `main.cf` should be done. I think that `smtpd_discard_ehlo_keywords` does not have to do with this problem. Once Postfix has an appropriate version, we can enable `smtpd_forbid_bare_newline`.

**Comment by bjoerns1983** [comment]
smtpd_discard_ehlo_keywords is at east mentioned in the postfix blogpost regarding the short term workaround.
Of course having a patched postfix version is the better way.

**Comment by polarathene** [comment]
> `smtpd_discard_ehlo_keywords` is at east mentioned in the postfix blogpost regarding the short term workaround.

Just for reference, since this issue was opened the [Postfix announcement link ](https://www.postfix.org/smtp-smuggling.html) has since updated it's content, and includes a new "all versions" fix:

```
smtpd_data_restrictions = reject_unauth_pipelining
smtpd_discard_ehlo_keywords = chunking
```

`smtpd_discard_ehlo_keywords = chunking` was also added to the [original short-term fix](https://github.com/docker-mailserver/docker-mailserver/issues/3719#issuecomment-1868287208).

Previously neither the short-term or long-term fixes were viable for DMS as the short-term fix `smtpd_forbid_unauth_pipelining = reject_unauth_pipelining` requires a newer [Postfix version than Debian packages provide](https://packages.debian.org/search?searchon=sourcenames&keywords=postfix) (_Bookworm provides the necessary `3.7.6` which DMS v14 will have, but Bullseye still has `3.5.18`_).

**Comment by woeisme** [comment]
> > `smtpd_discard_ehlo_keywords` is at east mentioned in the postfix blogpost regarding the short term workaround.
> 
> Just for reference, since this issue was opened the [Postfix announcement link ](https://www.postfix.org/smtp-smuggling.html) has since updated it's content, and includes a new "all versions" fix:
> 
> ```
> smtpd_data_restrictions = reject_unauth_pipelining
> smtpd_discard_ehlo_keywords = chunking
> ```
> 
> `smtpd_discard_ehlo_keywords = chunking` was also added to the [original short-term fix](https://github.com/docker-mailserver/docker-mailserver/issues/3719#issuecomment-1868287208).
> 
> Previously neither the short-term or long-term fixes were viable for DMS as the short-term fix `smtpd_forbid_unauth_pipelining = reject_unauth_pipelining` requires a newer [Postfix version than Debian packages provide](https://packages.debian.org/search?searchon=sourcenames&keywords=postfix) (_Bookworm provides the necessary `3.7.6` which DMS v14 will have, but Bullseye still has `3.5.18`_).

For those of us coming here after the talk at 37c3, is the correct procedure to 'fix' this problem to:

`sudo nano docker-data/dms/config/postfix-main.cf`

then pasting the lines:

`smtpd_data_restrictions = reject_unauth_pipelining
smtpd_discard_ehlo_keywords = chunking
`
and finally restarting the docker instance (in my case):

`docker-compose stop`
followed by 
`docker-compose start` 

(btw the documenation update instructions incorrectly say 'docker compose' instead of 'docker-compose')

**Comment by georglauterbach** [comment]
> `docker-compose stop` followed by `docker-compose start`

**Please don't!** (see <https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/#preliminary-checks>)

> (btw the documenation update instructions incorrectly say 'docker compose' instead of 'docker-compose')

The docs are correct; you seem to be using an older version of Docker Compose. The latest versions are a plugin to the `docker` command, hence `docker compose` is correct (and up to date) (ref: <https://docs.docker.com/compose/reference/>). 

> It would be nice to get a followup comment from someone else here confirming this is the accepted procedure for patching this bug.

CC @polarathene | What do we do with `smtpd_discard_ehlo_keywords` where `silent-discard, dsn` seem to be set.

**Comment by polarathene** [comment]
> What do we do with `smtpd_discard_ehlo_keywords` where `silent-discard, dsn` seem to be set?

This was provided via PR review feedback. `chunking` can be prepended/appended, but this is only necessary for the short-term fixes. Unless there is a good reason to keep that addition, it'll be reverted once the long-term fix can be configured.

---

> It would be nice to get a followup comment from someone else here confirming this is the accepted procedure for patching this bug.

- [Add a `postfix-main.cf` config override](https://docker-mailserver.github.io/docker-mailserver/v13.0/config/advanced/override-defaults/postfix/) if one doesn't yet exist.
- Add the following to `postfix-main.cf`:
   
   ```
   # SMTP smuggling short-term fix (DMS v14 will make these two lines redundant):
   smtpd_data_restrictions = reject_unauth_pipelining
   smtpd_discard_ehlo_keywords = chunking
   ```
   
   **NOTE:** That will remove a recent addition to drop support for DSNs on inbound port 25 (_while submission ports 465 + 587 allow DSNs for authenticated users_). If you want to keep that, you want to modify that line to `smtpd_discard_ehlo_keywords = chunking, silent-discard, dsn`
- `docker compose down && docker compose up` (_or similar to [correctly restart DMS](https://docker-mailserver.github.io/docker-mailserver/v13.0/config/debugging/#preliminary-checks)_).
- When DMS v14 is out, remove those lines 👍 
- Future release after v14 will switch to the long-term fix once Debian makes the updated packages available.

**Comment by bjoerns1983** [comment]
Debians Bullseye Updated Repo has been updated to Postfix 3.5.23 which should contain the longterm fix.
https://packages.debian.org/search?suite=bullseye-updates&searchon=names&keywords=postfix

**Comment by georglauterbach** [comment]
I will trigger a build so `:edge` has the appropriate version. A built-in fix in DMS should be around in the next few days I think.

**Comment by georglauterbach** [comment]
I will re-open; because we should update when merged Debian 12 (right?).

**Comment by polarathene** [comment]
> I will re-open; because we should update when merged Debian 12 (right?).

Do we have an actual blocker related to that reason? I think we resolved this with the v13.2 release right? (_which you released a day after the above comment_)

https://github.com/docker-mailserver/docker-mailserver/blob/2bf52342500726e86362ee1ea5954b7d96533d32/CHANGELOG.md?plain=1#L45-L51

**Comment by georglauterbach** [comment]
I thought there was a change we could only implement with Debian 12; but I guess I was wrong. I'll close this then.

**Comment by polarathene** [comment]
> I thought there was a change we could only implement with Debian 12

The newer Bullseye Postfix patch release backported the long-term fix IIRC.
