### ISSUE TITLE
question: Implications of adding accounts to `postfix-accounts.cf` in a multi-tenant environment?

### ISSUE THREAD

**Issue by Okdesk** [docker-mailserver/docker-mailserver#3737]
### Subject

I would like some feedback concerning a use case

### Description

I plan to use DMS in a production SaaS with multi-tenancy. Each time a user signs up, we add a new line to postfix-accounts.cf so that they can receive incoming messages.

The behavior of DMS that I am seeing is that each time postfix-accounts.cf is updated, postfix reloads to pick up the change. Though this is not a restart, I'd still like to understand the implications of this behavior, like what if a new message comes in in that interval - will it get lost?

And is such a multi-tenant environment a supported use scenario by DMS?

Thanks.
GC

**Comment by polarathene** [comment]
> I plan to use DMS in a production SaaS with multi-tenancy. Each time a user signs up, we add a new line to postfix-accounts.cf so that they can receive incoming messages.

The `ACCOUNT_PROVISIONER=FILE` (default) isn't really well suited for large scale users, at least when that updates frequently enough as any change there triggers the `check-for-changes.sh` service that has naive implementation for rebuilding the user "database" for Dovecot (_which Postfix in turn uses too_).

This will introduce a small downtime (_5-10 secs for example_), and some services like Postfix may receive mail while up and try to deliver that to Dovecot which is temporarily unavailable. That's affected some users in the past, such as when their TLS certificates renewed.

An alternative is LDAP, and soon we should also have OAUTH2 (for authentication, but presently still requires one of the existing `ACCOUNT_PROVISIONER`s to be used_). We additionally have a community contributed Lua auth guide which may be another alternative.

Note that presently the change detection service is disabled when LDAP is used, so even renewing certificates won't be handled which may require you to restart the services / container yourself.

---

> The behavior of DMS that I am seeing is that each time postfix-accounts.cf is updated, postfix reloads to pick up the change. Though this is not a restart, I'd still like to understand the implications of this behavior, like what if a new message comes in in that interval - will it get lost?

There are probably other issues like this one: https://github.com/docker-mailserver/docker-mailserver/issues/3679#issuecomment-1847877960

We have a `mail-state` volume which should persist state like a mail queue. The issue that I linked to however is the scenario where mail has arrived for delivery, it checks with Dovecot for the user account to know that it's valid to accept for delivery, but since Dovecot was down Postfix could not get that information and rejects the mail.

It's a small window if changes to monitored files is minimal, but for what you want it may be a problem.

---

> And is such a multi-tenant environment a supported use scenario by DMS?

Not that I'm aware of. I know there are some providing a hosted mail services that deploys DMS, presumably an instance per customer.

You may want to consider an alternative to DMS, one of the competitors I recall has monetized support allowing them to develop for more commercial scale needs :)

**Comment by Okdesk** [comment]
Thanks for the helpful info. Am considering switching back to iRedmail, which I've been using for a long time. Love so much how well the DMS approach works though. Clean and easily upgradable.
