### ISSUE TITLE
question: Default enabled services

### ISSUE THREAD

**Issue by robbertkl** [docker-mailserver/docker-mailserver#3857]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Hi, looking into DMS as a replacement for my current mail setup. I noticed in the documentation `ENABLE_AMAVIS` is on by default, and its description says "used for ClamAV & SpamAssassin". However, both ClamAV (`ENABLE_CLAMAV`) and SpamAssassin (`ENABLE_SPAMASSASSIN`) are turned off by default. Does Amavis then still need to be active or could/should it be disabled too?

This also begs the general question how to deal with combination of services, as I could not find this in the documentation. E.g. I've read to disable policyd when enabling rspamd, but what about the other things rspamd can do? Edit: I do see in the DMS rspamd documentation the "very basic configuration" where a bunch of other services are disabled. However, greylisting for example is not being disabled, but something rspamd can do as well (through `RSPAMD_GREYLISTING`).

Finally, is it correct (read it in 1 of the issues) DMS is moving fully to rspamd (enabled by default) in the future? Is rspamd the safest choice for a new setup, to be compatible with future releases?

### 🐋 DMS Version

v13.3.1

### 💻 Operating System and Architecture

FedoraCoreOS 39 x86_64

**Comment by georglauterbach** [comment]
> Hi, looking into DMS as a replacement for my current mail setup. I noticed in the documentation `ENABLE_AMAVIS` is on by default, and its description says "used for ClamAV & SpamAssassin". However, both ClamAV (`ENABLE_CLAMAV`) and SpamAssassin (`ENABLE_SPAMASSASSIN`) are turned off by default. Does Amavis then still need to be active or could/should it be disabled too?

If you do not use SA/ClamAV, Amavis is probably less effective. You can do that, though. Other maintainers have better insights on SA/Amavis + Clam than I have.

> This also begs the general question how to deal with combination of services, as I could not find this in the documentation. E.g. I've read to disable policyd when enabling rspamd, but what about the other things rspamd can do? Edit: I do see in the DMS rspamd documentation the "very basic configuration" where a bunch of other services are disabled. However, greylisting for example is not being disabled, but something rspamd can do as well (through `RSPAMD_GREYLISTING`).

The example is indeed missing `ENABLE_POSTGREY=0`, good catch! I will also add a section on this topic to the Rspamd documentation.

In general, I can guarantee you that a service combination that will probably not play well with Rspamd is logged as a warning. As a rule of thumb, you can enable Rspamd and disable all other anti-spam-related services except for Postscreen (which you cannot modify currently via ENVs anyway).

> Finally, is it correct (read it in 1 of the issues) DMS is moving fully to rspamd (enabled by default) in the future? Is rspamd the safest choice for a new setup, to be compatible with future releases?

With future releases, we intend to make Rspamd the default. We have decided not to drop the other services for now, though. You should not face any issues by not using Rspamd in the near and mid future.

**Comment by robbertkl** [comment]
Thanks @georglauterbach, great answer, just what I was looking for! PR looks good too, much clearer 🚀

**Comment by polarathene** [comment]
We're being a bit careful / slow with the transition to rspamd. We get more users trying it out and reporting any issues or inconsistencies and in time rspamd will be switched over to the default as we consider it a superior solution.

The current services it will replace will still be available for a while in the event the switch to default doesn't go as smoothly, and can remain as an alternative so long as they don't carry maintenance burden.

---

Regarding Amavis, I'm only familiar with it being used with SpamAssassin / ClamAV integration.

I'm not sure what value it brings without that, I came into the project when it was the only option available so it's possible that it doesn't have value enabled by default if SpamAssassin is not (_this previously was configured to bounce spam, but that was changed to always deliver to junk a year or so ago, thus it may have been disabled by default as a precaution_).

I know that ClamAV is disabled by default due to resource requirements being much higher when enabled.

---

Overall docs get slowly revised as time permits.
- Some pages have been effectively untouched for years and need some love.
- The ENV page is planned for a tidy up to be better organized / overview for example, while the current `:edge` (soon to be v14) docs now better document the DMS volumes seen in our repo example `compose.yaml`.
- I'm currently tackling rewrites for relay host support, authentication pages (LDAP, OAuth2, Accounts).
