### ISSUE TITLE
Feature request: Ability to restrict access to given IP range(s)

### ISSUE THREAD

**Issue by chascode** [docker-mailserver/docker-mailserver#3863]
### Context

All services where the user can authenticate with their email/password (IMAP, SMTP, Sieve, etc.).

### Description

I would like an environment variable where i can give a space separated list of IP ranges to allow users to authenticate from.  For example: ALLOW_FROM = "123.123.0.0/16" would allow users with an IP 123.123.1.2 to authenticate but drop all other connections.

### Alternatives

I have tried configuring docker compose but cannot publish ports 587 and 993 as desired.

### Applicable Users

Those who want to restrict access to their mail.

### Are you going to implement it?

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

### What are you going to contribute?

I do not understand dovecot/postfix enough to contribute, sorry.

**Comment by polarathene** [comment]
[`PERMIT_DOCKER` is planned to allow a list of IPs](https://github.com/docker-mailserver/docker-mailserver/issues/3478#issuecomment-1916529351), but this is for trusted clients (_bypassing restrictions/checks_), which is a separate concern to your request.

What you're asking for is generic and out of scope for DMS AFAIK. You should use an ingress / reverse-proxy service when you want to restrict port access by IP entirely.

For example [this setting in Caddy](https://caddyserver.com/docs/caddyfile/matchers#client-ip) would be what you're after...if it supported generic TCP rather than only HTTP(S), which AFAIK is not supported out of the box yet. Alternatives like Traefik do, and for StartTLS connections you need to handle a passthrough, just use Traefik for routing / restricting access.

If you really want to avoid that, you may configure Postfix or Dovecot manually via `user-patches.sh` or our supported override configs. AFAIK they both support configuring this, just not as convenient as a list via a single ENV.

We try to avoid adding too much to DMS unless there's enough user interest to justify it.

---

I'd still advise the approach with something like Traefik, since that would be a solution that is software agnostic. There are some extra caveats to keep in mind from that indirection, see our docs on the `PROXY_PROTOCOL` to ensure the real client IP is preserved.

One other option available to you is to instead use a VPN. You can then avoid publishing ports publicly that require authentication to use, and instead only publish to the VPN network interface for systems connected to that trusted network to access them.

This should work well depending on why you need this, assuming all systems can be configured to use the VPN 👍

**Comment by chascode** [comment]
Thanks for the reply.

I've decided not to publish 587 and 993 ports by default but configure iptables on the host accordingly.  The only port that is open to the whole world is 25 so as long as you can't authenticate over that port then all is good.  :)

Thanks again.

**Comment by polarathene** [comment]
> I've decided not to publish 587 and 993 ports by default but configure iptables on the host accordingly.

That works, so long as you're comfortable doing that.

I know that Docker manipulates the iptables rules itself, and that it has priority over UFW / Firewalld IIRC, such that even if those firewalls don't allow the port, if it was published by Docker it bypasses the firewall rules completely 😅 



> The only port that is open to the whole world is 25 so as long as you can't authenticate over that port then all is good. :)

We disable auth over port 25 👍 

---

BTW you don't need to worry too much about someone brute-forcing your password, if you can [ensure high enough entropy](https://security.stackexchange.com/a/244151). That is kind of difficult when the passwords are decided by your users instead though :(

DMS uses `SHA512-CRYPT` for `postfix-accounts.cf` (_password examples generated by [`getapassphrase.com`](https://getapassphrase.com/generate/)_):
- `detailed snail summons slim lab coat` (48-bit):
  - Would [take on average over 6 years](https://github.com/FusionAuth/fusionauth-issues/issues/85#issuecomment-1493371525) (`((2^48 / 700e3) / (60*60*24*365)) / 2 == ~6 years`).
  - 48-bit entropy attacked at [approx 700 KH/sec for `SHA512-CRYPT` via a single Nvidia RTX 4080](https://gist.github.com/bigpick/cfa22947c884f7a3fc1431475e345427) (_`sha512crypt`, not `sha512` which is considerably weaker_).
- `clever jay juggles moonlit honeybee in Kenya` (52-bit):
  - (`((2^52 / 70e6) / (60*60*24*365)) / 2`) => 1 year with 100x the attack power of that RTX 4080.
  - Quite expensive for a single attack, there are cheaper ways to gain access.
