### ISSUE TITLE
other: 

### ISSUE THREAD

**Issue by szguoxz** [docker-mailserver/docker-mailserver#3874]
### Subject

I would like some feedback concerning a use case

### Description

Not sure if it's a bug.

I run:

```bash
setup alias add @example.com xx@example.com
```

Then if I send email to `email1@example.com`, it will be forwarded to `xx@example.com`, which is good.

The I run:

```bash
setup email add email1@example.com
```

Now if I send email to `email1@example.com`, it will be forwarded, but `email1@example.com` will be empty. Because it's forwarded?

Then I try to keep emails in `email1@example.com`, I run:

```bash
setup alias add email1@example.com email1@example.com
```

I got error:  `email1@example.com` is already defined as an account

If this can not be done, then how can I do an email forwarding while still keep a copy of the email?

Thanks

**Comment by polarathene** [comment]
Two issues exist, see:

- https://github.com/docker-mailserver/docker-mailserver/issues/3022
- https://github.com/docker-mailserver/docker-mailserver/issues/3528

---

A catch-all alias has some compatibility issues in DMS presently. Likewise aliases and accounts are not permitted to use the same address because that is conflicting in usage.

See the issues for manual workarounds, no one has contributed a proper fix so far.
