### ISSUE TITLE
other: X-Spam-Last-External-rDNS sent directly from dynamic IP address

### ISSUE THREAD

**Issue by aario** [docker-mailserver/docker-mailserver#3889]
### Subject

I would like to contribute to the project

### Description

Hi Folks,
I have set up an aws ec2 instance which simply sits there and forwards request to my actual server. The actual server uses dynamic IP address and works through the ec2 instance.
Everything works properly. I can receive emails and send them.
The problem is emails end up in spam folder.
The mail-tester.com shows:
```
-0.001	RCVD_IN_SORBS_DUL	SORBS: sent directly from dynamic IP address
-0.363	RDNS_DYNAMIC	Delivered to internal network by host with dynamic-looking rDNS
```
Looking at SOURCE shows that:
```
X-Spam-Last-External-IP: <dynamic ip  of the actual mail server>
X-Spam-Last-External-HELO: <domain name of the aws ec2 isntance that is used for mails>
X-Spam-Last-External-rDNS: <dynamic domain name of the actual mail server>
```
As I researched it, people say there is no way to hide rDNS unless you run your own mail server. Since I'm running my own mail server, please tell me what should I do to hide my rDNS. I have already done an extensive search but could not find any tutorial/forum post/issue. 

Thanks in advance.

**Comment by aario** [comment]
@reneploetz thanks for the reply. 

> EC2 instance somewhat of an IP network proxy?
It is an IP network proxy. The mailserver is on a computer connected to dynamic ip. The remote server, the ec2 instance has static ip. The mailserver makes tunnels on all email ports (25, 143, 465, 587, 995, 993) to the ec2 instance. So incoming requests to these ports will be redirected to the mailserver which has the dynamic IP. 
Now I think the opposite direction of connection has not been passed through  the tunnel as you said. Which is to say, the mailserver directly sends email from its dynamic IP :thinking: 

Can you please guide me to a link to describe how to do rDNS configuration of the domain? I have found some but they were about cloudflare and MS Exchange. In our case this is AWS and mailserver.
Also can an  OpenVPN connection from the container running the mailserver to the EC2 fix the problem of outgoing connections having wrong IP?

**Comment by reneploetz** [comment]
You need to pass all traffic to external port 25 though your EC2 proxy too. External mail-servers will then only see the EC2 IP address and perform the rDNS query for that.
What you essentially do is to configure the DNS entries for your mail domain (MX/SPF,rDNS,...) on the DNS of the EC2 instance. Your dynamic-ip-address mail-server does not need any DNS configuration as it will never been visible to external parties.

Note that you need to setup the rDNS to the hostname you configured in postfix. You probably want to or already use (Amazon) Elastic IP addresses - otherwise your EC2 instance would get a new IP address once you restart the instance. 
To configure rDNS see here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html#Using_Elastic_Addressing_Reverse_DNS

Note that setting the rDNS by itself will not make your mails deliverable. You need to actually send them through the EC2 instance.
Postfix does not support SOCKS directly, you would need another software as intermediary.
But you can use OpenVPN to tunnel outgoing mail connections from your dynamic ip address server to EC2.

Note that I would advise against such a setup for any kind of critical mail infrastructure.
