### ISSUE TITLE
bug report: log: command not found

### ISSUE THREAD

**Issue by williamdes** [docker-mailserver/docker-mailserver#3896]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

The command should not output an error and print me the help
Present since a bunch of versions of DMS.

```sh
/usr/local/bin/open-dkim: line 8: log: command not found
```

### 👟 Reproduction Steps

```sh
docker exec -it mailserver-1 bash
root@emails:/# setup config dkim
/usr/local/bin/open-dkim: line 8: log: command not found
```

### 🐋 DMS Version

13.3.1

### 💻 Operating System and Architecture

Debian 12

**Comment by williamdes** [comment]
It is funny because `setup config dkim --help` works by printing the help and saying the option does not exist

**Comment by williamdes** [comment]
Okay, patch:
In `/usr/local/bin/open-dkim`
Diff:
```diff
-     log
+    _log
```

**Comment by williamdes** [comment]
Can some do something about this error ?
```
You enabled Rspamd and OpenDKIM - OpenDKIM will be implicitly used for DKIM keys
```

I have to comment the entire If block to have the script run.
My reaction to `OpenDKIM will be implicitly used for DKIM keys` was: and so what ?
Should we advise another command ?
Commenting the block got me to the result I wanted, my key.

**Comment by polarathene** [comment]
Thanks for the bug report. Was this encountered due to skimming the docs/instructions or enabling Rspamd without consideration for the default OpenDKIM feature the docs mention?

https://docker-mailserver.github.io/docker-mailserver/latest/config/best-practices/dkim_dmarc_spf/#generating-keys

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/888a976d-4d79-4496-9b56-7f0a013a30e3)

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/17b3e19c-b970-4e07-8b49-03b2f1974bb4)
![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/adc355a7-bcc0-4dfa-bbea-db657ab48e1f)

The logic presently only brings up the error you got because you enabled rspamd and didn't opt-out of OpenDKIM:

https://github.com/docker-mailserver/docker-mailserver/blob/a815bf5ab44388baecb597a0b83f71872a2d34bc/target/bin/open-dkim#L6-L13

---

> My reaction to `OpenDKIM will be implicitly used for DKIM keys` was: and so what ?

If you don't care for OpenDKIM, then perhaps you should acknowledge the log error you discovered, which communicates the concern like the docs also advise. Only have one of those features enabled.

> Should we advise another command ?

There are plans to revise the DKIM helper commands to a single command agnostic to rspamd or opendkim. Limited time from maintainers however to tackle that, I've got most of it ready to implement AFAIK for v15, but I want to tackle the LDAP rework first.

**Comment by williamdes** [comment]
Thank you for this reply
> Was this encountered due to skimming the docs/instructions or enabling Rspamd without consideration for the default OpenDKIM feature the docs mention?

One day I switched to rspamd from spamassasin as soon as it was available, patched the config for it to find the dkim keys. And that was it. But this script since I migrated got angry each time so I monkey patch it and get my key and life continues.
I am at a point where I have no idea what is the next thing that will break if I change an option 😄
Should I disable opendkim, maybe but what are the consequences: unknown

**Comment by Drugoy** [comment]
@polarathene please explain (or better yet add this docs) the choice between rspamd and opendkim: which one is better? Is one or the other legacy? Why support 2 things instead of 1? Sometimes having choice is ~bad, as it leads to confusion about what option would be better.
