### ISSUE TITLE
bug report: docs for certificate over caddy with json might be wrong or dont work with latest caddy

### ISSUE THREAD

**Issue by chrismaster** [docker-mailserver/docker-mailserver#3931]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

reading through the docs and found something didn't work here with latest caddy 2.7.6 and latest docker-mailserver 13.3.1

### 🐋 DMS Version

v13.3.1

### 💻 Operating System and Architecture

fedora 39

### ⚙️ Container configuration files

```yml
in the docs
https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#caddy
under 
Caddy v2 JSON example snippet
this part is wrong:

"tls": {
      "automation": {
        "policies": [
          {
            "subjects": [
              "mail.example.com",
            ],
            "key_type": "rsa2048",
            "issuer": {
              "email": "admin@example.com",
              "module": "acme"
            }
          },
          {
            "issuer": {
              "email": "admin@example.com",
              "module": "acme"
            }
          }
        ]
      }

https://caddyserver.com/docs/json/apps/tls/
says no issuer field
there is only a issuers field under policies, so it shoud be

,
    "tls": {
      "automation": {
        "policies": [
          {
            "subjects": [
              "mail.example.com"
            ],
            "key_type": "rsa2048"
          }
        ]
      }
    }
```

**Comment by polarathene** [comment]
> https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#caddy

Looks like these were contributed in May 2020, about a week after the official Caddy v2.0 release:
- https://github.com/docker-mailserver/docker-mailserver/commit/087a4ae7508945f11fbcb4dff83e89672a6e3d4f
- https://github.com/caddyserver/caddy/releases/tag/v2.0.0

Caddy doesn't have versioned docs, so it may have been something that changed since, or even from pre-release given the timing of the contribution (_back then it was Github Wiki, there was no PR review process_)

---

> https://caddyserver.com/docs/json/apps/tls/

Yeah thanks for that so it's an array of issuers, and the example is an array of automation policy objects where the 2nd object is just an issuer(s) key for some reason 🤷‍♂️ 

So this would be a more accurate snippet:

```json
    "tls": {
      "automation": {
        "policies": [
          {
            "subjects": [
              "mail.example.com",
            ],
            "key_type": "rsa2048",
            "issuers": [{
              "email": "admin@example.com",
              "module": "acme"
            }]
          }
        ]
      }
    }
```

---

I was actually considering dropping that entire JSON example from the docs, do you think it provides any value? Usually I think the reader is only interested in the `Caddyfile` example, whereas those interested in JSON are less likely to need to the additional guidance?

**Comment by polarathene** [comment]
> if you want to do copy the cert from caddy to docker-mailserver.

I don't follow? What does the JSON config help with better vs the Caddyfile approach?

**Comment by chrismaster** [comment]
With the JSON config you are able to bind an event handler to cp the cert to DMS, when a new cert for mail.myserver.com is obtained.

**Comment by polarathene** [comment]
> cp the cert to DMS, when a new cert for mail.myserver.com is obtained.

Oh ok, so that would be better resolved by improving DMS support for cert management as discussed here: https://github.com/docker-mailserver/docker-mailserver/issues/3486

Once that happens the importance of the JSON config via Caddy would be irrelevant?

That said we don't mention or document how to use Caddy in that way currently, so I'm not sure how the existing JSON example is useful as-is?
