### ISSUE TITLE
fetchmail SMTP error "Sender address rejected: Domain not found"

### ISSUE THREAD

**Issue by GuillaumeHullin** [docker-mailserver/docker-mailserver#3961]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I use Fetchmail to automatically pull my emails into my Docker Mail Server.

What I've observed is that, since the last update of DMS, some emails are left in the remote mailbox.

In the mail.err, I can see the error "Sender address rejected: Domain not found," which is legitimate because it's almost exclusively spam. However, I would like to receive that spam in my DMS mailboxes (and have it filtered by DMS)... yeah, I never thought I would write this sentence.

The main point is that I want to keep the remote box at zero. Is there a way to skip this domain verification for Fetchmail?

### 🐋 DMS Version

13.3.1

### 💻 Operating System and Architecture

Debian 12 x86_64 GNU/Linux

**Comment by GuillaumeHullin** [comment]
I was thinking of modifying Postfix settings... but I would love if I don't reduce Postfix security (which apply for send mail).

**Comment by polarathene** [comment]
https://github.com/docker-mailserver/docker-mailserver/issues/3962#issuecomment-2024034080

> What I've observed is that, since the last update of DMS, some emails are left in the remote mailbox.

- Provide configuration when raising a bug report. Do not omit env if you use a separate ENV file, but do not add the entire ENV file either, we're only interested in non-default config.
- Please be more specific about what your previous version of DMS was, it's not always clear if it was the previous minor release, or multiple releases prior.

It would be good if you could [identify the relevant change from our Changelog](https://github.com/docker-mailserver/docker-mailserver/blob/master/CHANGELOG.md) that helps identify what the exact change is that affected you from the upgrade. At a glance nothing stands out, but as I don't know what your configuration is it is difficult to tell.

---

> I was thinking of modifying Postfix settings...

If this is actually due to a change we made between releases, you can experiment with modifying postfix settings, then checking what related changes we did between the version you were on before and the upgraded one, and then check why we made that change.

It's possible that we overlooked something, or it could be done in a better way. We just need to identify why that was changed since, as there should be a good reason behind the change. The likely outcome would then be to override your config if it's not a bug in DMS.

## Alternative solutions

It should be possible to trust mail sent to DMS from fetchmail which runs within the container, `PERMIT_DOCKER=container` may do the trick I think 🤔 that should relax the security for anything able to send mail from within the container itself (eg: `0.0.0.0` / `127.0.0.1` / `localhost`).

Alternatively fetchmail can be configured to submit mail to DMS via authentication through a DMS account like `fetchmail@example.com` (_it can be any account credentials you want to use_), that would be a more secure approach since you restrict the scope to only software that has those credentials to submit mail. This is what you'd usually do for any other service wanting to send mail through DMS.

We are lacking documentation on configuring fetchmail however, I've not looked into that but it should be possible to mount a config file and perhaps use `user-patches.sh` if necessary. Or we might need to adjust how the `fetchmail` service is started. If you look into that and we can add support to make custom configuration easier 👍

**Comment by GuillaumeHullin** [comment]
Alright so I found the solution: removing `reject_unknown_sender_domain ` from `dms_smtpd_sender_restrictions`

Into `/dms/config/postfix-main.cf`
```sh
# Allow fetchmail to route emails which would normally be blocked by Postfix
mynetworks = 127.0.0.0/8
dms_smtpd_sender_restrictions = permit_sasl_authenticated, permit_mynetworks
```

See: 
https://github.com/docker-mailserver/docker-mailserver/blob/082e076377b48378761890a6a39acfda2a0db68d/target/postfix/main.cf#L72

and https://github.com/docker-mailserver/docker-mailserver/issues/3716#issuecomment-1868033234


> It should be possible to trust mail sent to DMS from fetchmail which runs within the container, `PERMIT_DOCKER=container` may do the trick I think 🤔 that should relax the security for anything able to send mail from within the container itself (eg: `0.0.0.0` / `127.0.0.1` / `localhost`).

Yes that's why I had the settings `mynetworks = 127.0.0.0/8` already before.

For your info (or maybe somebody else), here are some of my env variables:

```yaml
        environment:
            - ENABLE_FAIL2BAN=0 # Disabled in order to use Docker host Fail2Ban and ban system-wide 
            - ENABLE_CLAMAV=0 # Disabled until fully setup
            - ENABLE_POSTGREY=0 # Disabled because SMTP server is not reachable via Internet (it just delay fetchmail for nothing)
            - ENABLE_MANAGESIEVE=1

            - ENABLE_SPAMASSASSIN=1
            - SPAMASSASSIN_SPAM_TO_INBOX=1
            - "SA_SPAM_SUBJECT=[SPAM SCORE (_SCORE_)] "
            - MOVE_SPAM_TO_JUNK=1

            - ENABLE_SASLAUTHD=0
            - POSTFIX_MESSAGE_SIZE_LIMIT=0 # Email size will be unlimited (it can be however limited on email provider SMTP)
            - ONE_DIR=1
            
            - SSL_TYPE=manual
            - SSL_CERT_PATH=/tmp/dms/custom-certs/letsencrypt.fullchain
            - SSL_KEY_PATH=/tmp/dms/custom-certs/letsencrypt.key
            
            - ENABLE_FETCHMAIL=1
            - FETCHMAIL_PARALLEL=1
            - FETCHMAIL_POLL=60
```

> We are lacking documentation on configuring fetchmail however, I've not looked into that but it should be possible to mount a config file and perhaps use `user-patches.sh` if necessary. Or we might need to adjust how the `fetchmail` service is started. If you look into that and we can add support to make custom configuration easier 👍

Fetchmail is quite a big part of my setup. Basically I use DMS as my IMAP server but not as my SMTP. Fetchmail pull all the mails from my provider and put them on my DMS. This setup makes it that I have all my mail data in my own server which has backup and more than few GB of space ;). And I don't have to deal with SMTP challenges.

 `/dms/config/fetchmail.cf` have all the mail account which are setup in DMS to be pulled from remote provider. Hope that make sense?

**Comment by polarathene** [comment]
> Yes that's why I had the settings `mynetworks = 127.0.0.0/8` already before.

You shouldn't have the issue like the referenced one you linked. This setting has two permit rules that if valid should skip any rejection rules that follow:

`dms_smtpd_sender_restrictions = permit_sasl_authenticated, permit_mynetworks`

- The first one is for any authenticated user (ports 587 and 465, using credentials for DMS account).
- The other is for `mynetworks` setting you configure, that is what `PERMIT_DOCKER` ENV also controls. By default it will clear `mynetworks` to no trust.

Are you sure you needed to remove `reject_unknown_sender_domain` via `postfix-main.cf` override? I would have expected only the `mynetworks` line to be necessary, provided it matched the source IP of fetchmail 🤔 

---

> `/dms/config/fetchmail.cf` have all the mail account which are setup in DMS to be pulled from remote provider. Hope that make sense?

Credentials for fetchmail to connect to the local DMS / postfix and deliver, instead of the default (_might be `0.0.0.0:25`, `localhost:25`, `127.0.0.1:25`_) without authentication.

You'd connect to port 587 or 465 and additionally configure the username + password of a DMS account to authenticate fetchmail with for permission to submit the mail this way instead.

If fetchmail was configured that way, you would hit the `permit_sasl_authenticated` rule and the `permit_mynetworks` rule would not need to be considered, thus no `postfix-main.cf` and better security (_in the sense of reduced trust, not allowing any process in the container to bypass security when sending mail to local postfix_).

**Comment by GuillaumeHullin** [comment]
Thank you for your ideas. Let's find out if we can put back `reject_unknown_sender_domain`.

> Are you sure you needed to remove `reject_unknown_sender_domain` via `postfix-main.cf` override? I would have expected only the `mynetworks` line to be necessary, provided it matched the source IP of fetchmail 🤔

`mynetworks` line was already present specifically for the purpose of allowing Fetchmail. That worked for the last year and in several install.
I was not aware of `PERMIT_DOCKER` env... I'll look more into that.

> Credentials for fetchmail to connect to the local DMS / postfix and deliver, instead of the default (_might be `0.0.0.0:25`, `localhost:25`, `127.0.0.1:25`_) without authentication.
> 
> You'd connect to port 587 or 465 and additionally configure the username + password of a DMS account to authenticate fetchmail with for permission to submit the mail this way instead.
> 
> If fetchmail was configured that way, you would hit the `permit_sasl_authenticated` rule and the `permit_mynetworks` rule would not need to be considered, thus no `postfix-main.cf` and better security (_in the sense of reduced trust, not allowing any process in the container to bypass security when sending mail to local postfix_).

Here is an exemple of my `fetchmail.cf`
```
    poll 'remote.host.net' 
        proto imap 
        port 993
        user 'email@host.net'
        pass 'password'
        fetchall
        limit 0
        ssl
        sslproto 'auto'
        idle
        is 'email@host.net'
```

I'm not exactly sure how you want to add SMTP credential... maybe I missed something in the docs of fetchmail.
Using an MTA (as I saw that in the docs) would effectively create a loop because the mail would actually go back to the remote host.

**Comment by polarathene** [comment]
> I'm not exactly sure how you want to add SMTP credential

I found my [recent fetchmail config comment](https://github.com/orgs/docker-mailserver/discussions/3949#discussioncomment-8846367) where I suggested similar.

> _It may require some configuration on the fetchmail side perhaps (_see [Delivery Control Options](https://www.fetchmail.info/fetchmail-man.html#toc-entry-12)_). While I don't think DMS provides an easy way to modify the supervisor config for the fetchmail command options, the [fetchmail config seems to support the equivalent options as keywords](https://www.fetchmail.info/fetchmail-man.html#toc-entry-37)._

For the option `-S <hosts> | --smtphost <hosts>`:

> _If this option is not specified, 'localhost' is used as the default. Each host name may have a port number following the host name._

That lets you set the IP/host and port to connect to. While `-u` / `--user` can set the username, [according to this](https://www.fetchmail.info/fetchmail-man.html#toc-entry-17) the password can only be provided via the fetchmail config file 🤔 

So config file wise it [looks like the options](https://www.fetchmail.info/fetchmail-man.html#keyword-option-summary) you'd want are: `esmtpname` + `esmtppassword` and maybe `smtphost`?

https://www.fetchmail.info/fetchmail-man.html#toc-entry-23

> ESMTP AUTH
> _fetchmail also supports authentication to the ESMTP server on the client side according to [RFC 2554](http://tools.ietf.org/html/rfc2554.html). You can specify a name/password pair to be used with the keywords 'esmtpname' and 'esmtppassword'; the former defaults to the username of the calling user._

https://www.fetchmail.info/fetchmail-man.html#toc-entry-6

> _As each message is retrieved, fetchmail normally delivers it via SMTP to port 25 on the machine it is running on (localhost), just as though it were being passed in over a normal TCP/IP link._

I see configuration for the remote user and local user, but I may have misunderstood these docs for being able to do authenticated submission on port 587 locally 🤔 

---

Perhaps you'll have to rely on the `PERMIT_DOCKER` / `mynetworks` approach then.

We have a similar service called [`getmail6`](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/mail-getmail/) that likewise [doesn't seem to support auth for local delivery](https://getmail6.org/configuration.html#conf-destination), it doesn't seem to be capable of delivering to Postfix SMTP either, instead it would store mail at the storage location Dovecot is configured for (_DMS uses Maildir format by default IIRC_).

Our docs for `getmail` do show an example of configuring the delivery destination as an MDA, so that it skips Postfix and gets handed over directly to Dovecot to store on disk, that might work well for you?
