### ISSUE TITLE
Your DKIM signature is not valid - opendkim

### ISSUE THREAD

**Issue by janowi** [docker-mailserver/docker-mailserver#3963]
### Subject

Something else that requires developers attention

### Description

0

I'm running postfix server with few "features" like spf, dmarc and DKIM. SPF and DMARC works fine and when I sent an email to my gmail account I see they PASS, however DKIM shows "FAIL" and I'm not sure why. I used some online-dns checks and they claim that my DKIM DNS record is ok but mail-checks like mail-tester fails:

```
The DKIM signature of your message is:

v=1;
a=rsa-sha256;
c=relaxed/simple;
d=mydomain.com;
s=email;
t=1711628971;
bh=Rv2fKWBlNI8YfmXfYIWLRt8FRQfzmecyWP3jcdyv3KQ=;
h=Subject:From:To;


b=Euf/WOxr4EcUxl3MgvTfpod7gkhQ8MPsxm8qULS2lD83fx1PWPeVaB+JTQJk27bQNzXPZcufpB0ANcA3hG34WDzKCefabN/Y97OdyRoI6nAH4JfeXqG3AeloDDc6i6o1961TLNVZr8qjPBe2quQSb+LPY/EpGu1RSRxgQO9ws/Yv92IHV6Lx8tzcQjDKQ3CAkTV+v9FGxp3l/VJDbbUbCU9P/8WuQ1JjluP4zJSJPV9zd6EWRiJgiLomXSlaSI5ekvbJRip1uLFfq8Qr7sXcmlW3mCts3bkS95LU8kFJ8/27TXzJY32sVw2tkX0h9Hx/6YUVOjlbGI590JJ/IsCoIg==
Your public key is:

"v=DKIM1;
k=rsa;
p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA24F81SHRpZJ/EA3NAfWRYEwKi6XHx1o/RIGVDuEMvxefDDOtbRQsh4hG7er/Ll3f4ID4aTa99IHWHx/Zik0PBnXwDLbGqDqqU0dgtURYGfRXwuxtvvQfuOaWLa9DwVKiIUOcPtXIdh6a5sM73jQcatCaPwoVZadVb9klQubN+NU3A7JI1FtIk0Lovm7gOr/7VSuibcV6Ni8ZZ/5jM4xo67LpT3rbJpDsmKWRFoe1HmU3pe2+AmG/hFnOvLHkGYt6j0gdHJbIUdjr/ObBzQJ8VSFQJY55ortYMFxR1LO79f5G1CT3bMlLMauH2odzPTSGBeP7ihlP3zFblFd6MOKmrwIDAQAB"
Key length: 2048bits

Your DKIM signature is not valid
```
**File: opendkim.conf:**

```
root@email:/# cat /etc/opendkim.conf 
AutoRestart             Yes
AutoRestartRate         10/1h
UMask                   002
Syslog                  yes
SyslogSuccess           Yes
LogWhy                  Yes
RemoveOldSignatures     Yes

Canonicalization        relaxed/simple

ExternalIgnoreList      refile:/etc/opendkim/truhost
InternalHosts           refile:/etc/opendkim/truhost
KeyTable                /etc/opendkim/keyt
SigningTable            refile:/etc/opendkim/sign

Mode                    sv
PidFile                 /var/run/opendkim/opendkim.pid
SignatureAlgorithm      rsa-sha256

UserID                  opendkim:opendkim

Socket                  inet:8891@localhost
OmitHeaders             Message-ID, Date, Return-Path, Bounces-To, Received, Comments, 

Keywords, Bcc, Resent-Bcc, List-ID, List-Unsubscribe, DKIM-Signature<Paste>
    Nameservers 127.0.0.11
```
**File keyt:**

`email._domainkey.mydomain.com mydomain.com:email:/etc/opendkim/keys/mydomain.com/email.private`
**File: sign:**

`*@mydomain.com email._domainkey.mydomain.com`

One website mentioned: 
Validating Signature
result = fail Details: bad RSA signature

I took my DKIM record from email.txt as opendkim generates it automatically and it looks like this:

```
"v=DKIM1; h=sha256; k=rsa; "
"p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1MjR9CMslFUjbjDA7XWVFCcVOS6nVruC9iILNrSAMoozGgqOxp0vCBOFtCmdpVl/AK66wzo6WiCDyO1MqL0r+EKZbHSoSGurQRuq1FTcSDB110gfuyB/EwoAmW1z8YiK5dU7ae/rrpZH5IHr18F/cnMSX6UvjhO52qOkru06YkxXVnunZQ3zsOntpLJgLZ6f3bSbkv1R72/n+A"
    "ObOYzx3ZB0j7pUPc4b3NzPycQKd/gIN72GPWixy5RkaKBqc89MR71MfefzmLA2cyedORp0xayMAZRJxD6BA1hLjXJ1DDdufL5rJIIU/R5s2jCWawAXK4Sw+wepsQRfYQra0605EwIDAQAB"
```
It was failing when I was trying to add it in dns and I had to remove "" after n+A and replace it with / then it worked 
I'm running out of ideas why it doesn't work :/

**Comment by polarathene** [comment]
I don't have time to help troubleshoot here, especially since you've skipped filing a proper bug report and this is very likely a misconfiguration issue, thus personal support request.

- I have a opendkim/rspamd agnostic guide to generating DKIM keys and formatting them properly here: https://github.com/docker-mailserver/docker-mailserver/issues/3630#issuecomment-1903401956
- Please make sure you read our related [DNS docs for DKIM](https://docker-mailserver.github.io/docker-mailserver/latest/config/best-practices/dkim_dmarc_spf/), there is a guide for formatting the key for DNS input which was an issue you experienced in your report and attempted fix:
   ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/e27e957a-9ea7-4a9a-991e-a86107921aab)

Alternatively consider trying the Rspamd equivalent support. If you run into any trouble with the docs, let us know as rspamd will eventually replace opendkim. Presently rspamd is more involved in reading our docs for setup, so sharing your feedback helps identify where improvements need to be made.

**Comment by janowi** [comment]
>  especially since you've skipped filing a proper bug report and this is very likely a misconfiguration issue, thus personal support request.

Lol, I didn't select it as a bug simply because I believe the issue is on my side and I did some misconfiguration which you even tagged like it, so since when misconfiguration on the user side is a software bug? Anyway, I tried mailcow which works thanks

**Comment by polarathene** [comment]
> I didn't select it as a bug simply because I believe the issue is on my side and I did some misconfiguration

When submitting an issue like you did, it should have directed you to raise a discussion instead. You chose to ignore that.

> which you even tagged like it

Yes, part of triage since we still have users open support requests that don't read.

---

> since when misconfiguration on the user side is a software bug

It is assumed misconfiguration as no other users are raising issues for common setup functionality.

If you disregard our request for support queries to be handled via discussions, then the only way I can invest time helping you further is if you provide the information requested (_which is what our bug report template is well catered for_). I'd just be asking for the same information otherwise, it'd just be more inconvenient for both of us.

So while it's unlikely a bug, I'm not sure why you're concerned about that difference when you had no problem with the approach you chose instead?:

> ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/a0e66ee2-71c1-425c-8db5-f4c444d33cf9)

> ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/040c342e-1e3d-48d2-8ef8-a03431a8781c)

This issue wasn't something that required our attention to prioritize.

We maintainers volunteer our time unpaid. Many times I'll chime in trying to be helpful and never get a response back 🤷‍♂️ 

---

> Anyway, I tried mailcow which works thanks

Ok awesome! They use rspamd which I suggested earlier that you give a go, was that something you considered trying? If so, was there too much friction in applying that change with our current docs?

Mailcow docs [DNS advice doesn't seem any better](https://docs.mailcow.email/getstarted/prerequisite-dns/#dkim-spf-and-dmarc), you'd still have run into that earlier formatting issue? I'm curious what you did differently from other users that this setup step broke for you in DMS but worked fine in mailcow 🤔
