### ISSUE TITLE
Sender dependent relay should NOT require RELAY_HOST env

### ISSUE THREAD

**Issue by szguoxz** [docker-mailserver/docker-mailserver#3970]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I hosted a multiple-domain email server.  One of the domain: A needs to use AWS relay ses.
So I use setup relay add, to add relay host for domain A, and modify postfix-sasl-password.cf to include the uername password.

Then I try to send out emails, it does not work. Email is not sent.
Then I added the ENV setting for RELAY_HOST,  try again it works.

But I don't need relay for other domains. setting RELAY_HOST just seem weird. Right, it seems like just a flag, has value, relay works. no value, relay stopped.
Besides, just don't see the difference between: DEFAULT_RELATY_HOST and RELAY_HOST, the doc is simply not clear.

### 🐋 DMS Version

V13.3.1

### 💻 Operating System and Architecture

ubuntu

**Comment by polarathene** [comment]
> Besides, just don't see the difference between: `DEFAULT_RELAY_HOST` and `RELAY_HOST`, the doc is simply not clear.

It was a legacy issue as these features were contributed by different users in the past AFAIK for their specific needs. We didn't have the same level of quality for reviews back then.

I have refactored it twice since and with `edge` (_should be released as v14 this month sometime_), there my 2nd refactor fixes the concern you've raised here with the inconsistency / bugs. I also rewrote the docs (_see [here](https://github.com/docker-mailserver/docker-mailserver/issues/3962#issuecomment-2024358955) for direct links_).

On the new doc pages I mentioned, at the bottom of the [relay host page](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/mail-forwarding/relay-hosts/#technical-details) is a technical details admonition. This shows relevant Postfix config you could use via `postfix-main.cf` instead of the existing ENV var feature support.

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/78f47e07-0d46-4c63-a22c-3c14f1d77949)

For reference, the page also better documents the two config files that the `setup` command helps manage:

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/49043540-2dfc-46d7-a91a-af1f62bff0be)

If you're comfortable trying `:edge` image out to let me know if that is working much better now, I'd appreciate that as I'd like to know if I've missed anything (_see the [rewritten ENV docs section](https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#relay-host) for additional insights_). I also [rewrote the AWS SES page](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/mail-forwarding/aws-ses/) which may be relevant to you?

---

There is still some larger refactoring work planned for this feature in future, if you'd like to subscribe to the tracking issue it is here: https://github.com/docker-mailserver/docker-mailserver/issues/3607

**Comment by szguoxz** [comment]
Cool!
While you are at it, did you fix another issue that has been a pain in ass for a while with setup Alias? Right now, I can’t forward a copy of my email to another account, as setup Alia’s add does not allow me to add a forward for a real email account!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by polarathene** [comment]
> Did you fix another issue that has been a pain in ass for a while with setup Alias?
> Right now, I can’t forward a copy of my email to another account, as setup Alia’s add does not allow me to add a forward for a real email account!

No, the command has logic to prevent having an alias and actual account with the same address. This was due to various issues in the past where users misused the feature IIRC. You can find details and workarounds on a relevant issue here: https://github.com/docker-mailserver/docker-mailserver/issues/3022#issuecomment-1807816689

Wanting to accept mail for a legit account and send a copy to another address is a use-case that several users have wanted since that is valid. I'm not familiar with other solutions instead of using an alias that points to an account of the same name to achieve that same functionality.

For now you can use the workaround with a manual edit of `postfix-virtual.cf`, or you can wait until someone contributes a PR that maintainers approve. I don't think any of the active maintainers are going to fix one problem to introduce the previous problem though, but they'd probably be open to an option like `--force` for the setup command to ignore the guard.

Feel free to open a new issue as a feature request for that if you're not comfortable contributing it, someone may come along and tackle it 👍
