### ISSUE TITLE
question: Why does `SMTP_ONLY=1` still allow to receive mail locally?

### ISSUE THREAD

**Issue by MateuszBeru** [docker-mailserver/docker-mailserver#3974]
### Subject

I would like to configure a not documented mail server use case

### Description

Hello,
While setting up a standard setup of docker-mailserver with intention to use this as an email sending only I found a problem.
After the setup accordingly to the documentation It worked but there was an issue that the email that was set to be sending only was saving copy on local mailbox. After trying to turn server into send only mode with help of issue [#3477](https://github.com/docker-mailserver/docker-mailserver/issues/3477) that didn't helped I had decided to turn off local account with help of resolved issue [#3472](https://github.com/orgs/docker-mailserver/discussions/3472#discussioncomment-6711584). Unfortunately solution proposed as solution in [#3472](https://github.com/orgs/docker-mailserver/discussions/3472#discussioncomment-6711584) that was mentioned in FAQ section of documentation did not resolve the problem.

Otherwise server is working fine, configuration was done accordingly to the documentation and score on mail-tester.com was 9.5/10.

As went through the thread of connected related issues I had noticed that most of them are occurring between 2019 and 2023 so I tried with different releases (:13.x, :latest. :edge) hoping that this problem was patched unfortunately with the same result. 

I'm not sure if this is a bug or not documented well option, as I had noticed few issues were filed around similar problem.

Please see logs and yaml below
```
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:edge
    container_name: main
    hostname: mail.hostname.com
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/dms/sasl-data/sasl:/etc/postfix/sasl
      - /etc/localtime:/etc/localtime:ro
      - /ymls/nginx/docker-data/acme-companion/certs/:/etc/letsencrypt/live/:ro
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    environment:
      - SSL_TYPE=letsencrypt
      - LETSENCRYPT_HOST=mail.hostname.com
      - SMTP_ONLY=1
      - SMTP_USERNAME=info
      - SMTP_DOMAIN=mail.hostname.com
      - SMTP_PASSWORD=yvj0ufb@avy3MCP8hze
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_MECHANISMS=
```

```
2024-04-09T16:36:20.193026+02:00 direct postfix/submission/smtpd[652]: connect from static.111.111.111.111.clients.your-server.de[222.222.222.222]
2024-04-09T16:36:20.438185+02:00 direct postfix/submission/smtpd[652]: Anonymous TLS connection established from static.111.111.111.111.clients.your-server.de[222.222.222.222]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
2024-04-09T16:36:20.609177+02:00 direct postfix/submission/smtpd[652]: NOQUEUE: reject: RCPT from static.111.111.111.111.clients.your-server.de[222.222.222.222]: 554 5.7.1 <static.111.111.111.111.clients.your-server.de[222.222.222.222]>: Client host rejected: Access denied; from=<info@mail.hostname.com> to=<test@testmail.anotherhost.com> proto=ESMTP helo=<DESKTOP-OSIMTIL>
2024-04-09T16:36:20.668553+02:00 direct postfix/submission/smtpd[652]: lost connection after RCPT from static.111.111.111.111.clients.your-server.de[222.222.222.222]
2024-04-09T16:36:20.668660+02:00 direct postfix/submission/smtpd[652]: disconnect from static.111.111.111.111.clients.your-server.de[222.222.222.222] ehlo=2 starttls=1 mail=1 rcpt=0/1 commands=4/5
```

```
2024-04-09T17:21:22.383897+02:00 direct postfix/submission/smtpd[638]: >>> START Client host RESTRICTIONS <<<
2024-04-09T17:21:22.383901+02:00 direct postfix/submission/smtpd[638]: generic_checks: name=permit_sasl_authenticated
2024-04-09T17:21:22.383909+02:00 direct postfix/submission/smtpd[638]: generic_checks: name=permit_sasl_authenticated status=0
2024-04-09T17:21:22.383912+02:00 direct postfix/submission/smtpd[638]: generic_checks: name=reject
2024-04-09T17:21:22.383926+02:00 direct postfix/submission/smtpd[638]: NOQUEUE: reject: RCPT from static.111.111.111.111.clients.your-server.de[222.222.222.222]: 554 5.7.1 <static.111.111.111.111.clients.your-server.de[222.222.222.222]>: Client host rejected: Access denied; from=<info@mail.hostname.com> to=<test@testmail.anotherhost.com> proto=ESMTP helo=<DESKTOP-OSIMTIL>
```

**Comment by georglauterbach** [comment]
Just to understand exactly what you are referring to: you want a send-only mail server, but your instance is receiving and saving e-mail, right?

**Comment by polarathene** [comment]
> While setting up a standard setup of docker-mailserver with intention to use this as an email sending only I found a problem.
> After the setup accordingly to the documentation It worked but there was an issue that the email that was set to be sending only was saving copy on local mailbox.

This is not clear enough. The DMS account that is sending mail is storing a copy locally in the container/volume? Or you have sent mail to DMS for this account and it received it?

To prevent receiving mail, just don't expose the port 25 for the container. No MX DNS record should resolve to that host anyway since you don't want mail delivered there. You should still have a mail server somewhere that receives mail for that domain however, and DNS TXT records like for SPF that authorize your DMS server to send mail for that domain.

## `SMTP_ONLY=1` disables Dovecot service (_mail can still be received by Postfix on port 25 if you allow it_)

`SMTP_ONLY=1` is effectively `ENABLE_DOVECOT=0` for the most part. There's no official support yet for an alternative account provider, so you configure Postfix with mail accounts manually like you've done through referenced links providing guidance.

https://github.com/docker-mailserver/docker-mailserver/blob/ad5d1011f82401415421b0738209d855bcb12443/target/scripts/start-mailserver.sh#L46-L54

https://github.com/docker-mailserver/docker-mailserver/blob/ad5d1011f82401415421b0738209d855bcb12443/target/scripts/startup/setup.d/postfix.sh#L71-L83

SASL auth on Postfix could be disabled (_but in your case it's not and you'd probably want to keep it that way_):

https://github.com/docker-mailserver/docker-mailserver/blob/ad5d1011f82401415421b0738209d855bcb12443/target/scripts/startup/setup.d/postfix.sh#L22-L42

---

## Managed domains (_should not apply to you unless using virtual aliases_)

This part of our setup script will inform Postfix that it manages the mail domains (_via lookup at  `virtual_mailbox_domains` config setting_) in `postfix-accounts.cf` and `postfix-virtual.cf` config files if they exist.

https://github.com/docker-mailserver/docker-mailserver/blob/ad5d1011f82401415421b0738209d855bcb12443/target/postfix/main.cf#L102-L106

https://github.com/docker-mailserver/docker-mailserver/blob/ad5d1011f82401415421b0738209d855bcb12443/target/scripts/startup/setup.d/postfix.sh#L48-L50

https://github.com/docker-mailserver/docker-mailserver/blob/ad5d1011f82401415421b0738209d855bcb12443/target/scripts/helpers/postfix.sh#L40-L82

---

## Internal addresses and deliveries

Internally Postfix recognizes the DMS FQDN (_from the `hostname` container config_) as what it should present for HELO/EHLO greeting (_the FQDN of the mail server, not the sender address domain_) to use when sending mail.

https://github.com/docker-mailserver/docker-mailserver/blob/ad5d1011f82401415421b0738209d855bcb12443/target/postfix/main.cf#L15-L18

https://github.com/docker-mailserver/docker-mailserver/blob/ad5d1011f82401415421b0738209d855bcb12443/target/scripts/startup/setup.d/postfix.sh#L13-L15

When you have configured this to be separate from the actual mail domains your accounts used (_not a "bare domain" as per our docs FAQ entry_), this `mail.example.com` hostname is better distinguished as for internal system mail.

We implicitly create `/etc/aliases` with an alias for the system `root` user to your `POSTMASTER` ENV address:

https://github.com/docker-mailserver/docker-mailserver/blob/ad5d1011f82401415421b0738209d855bcb12443/target/scripts/helpers/aliases.sh#L33-L50

Our startup process runs this [DNS helper script](https://github.com/docker-mailserver/docker-mailserver/blob/ad5d1011f82401415421b0738209d855bcb12443/target/scripts/helpers/dns.sh) that derives the `HOSTNAME` (overrides) and `DOMAINNAME` (_if not a bare domain, truncates the 1st left-side DNS label from the FQDN, `mail.example.com` => `example.com`_). If the `POSTMASTER` ENV is not configured, it implicitly infers one for that `/etc/aliases` entry above to use:

https://github.com/docker-mailserver/docker-mailserver/blob/ad5d1011f82401415421b0738209d855bcb12443/target/scripts/startup/variables-stack.sh#L52-L54

There are some recurring tasks internally that will send mail to that address, or send mail as the `root` user at your `mail.example.com` hostname address, which should deliver locally. As you can see above there is also some inferred default addresses for reports. This should all be internal.

If mail fails to deliver, Postfix may attempt to notify you by sending a mail to your account locally, which may be what you're seeing. You did not share the contents of the mail stored, are you sure it's a copy, or was there extra information included about delivery faliure?
