### ISSUE TITLE
bug report: setup script alway fail with "setup email list" related on the user name

### ISSUE THREAD

**Issue by mattn** [docker-mailserver/docker-mailserver#4011]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I don't make sure this is really related on the username but:

j5 is ok

```
setup email add j5@example.com x
setup email list
```

```
* j5@example.com ( 0 / ~ ) [0%]
```

but j5v is not ok
```
setup email add j5v@example.com x
setup email list
```

```
[  ERROR  ]  Supplied non-number argument '' to '_bytes_to_human_readable_size()'
[  ERROR  ]  Aborting
[  ERROR  ]  Supplied non-number argument '' to '_bytes_to_human_readable_size()'
[  ERROR  ]  Aborting
* j5v@example.com (  /  ) [%]
```

### 🐋 DMS Version

v13.3.1

### 💻 Operating System and Architecture

Linux docker-mailserver-7b4bd5cdf9-n5vk9 5.15.0-205.149.5.1.el8uek.x86_64 #2 SMP Fri Apr 5 12:44:45 PDT 2024 x86_64 GNU/Linux

### ⚙️ Container configuration files

```yml
I guess this is not a bug related on configuration file but if you want, I'll put my configuretion file here.
```

### 📜 Relevant log output

```Text
This is not an error of e-mail server.
```

**Comment by mattn** [comment]
Something wrong.

```
$ setup dovecot-master add j5v@example.com x
$ doveadm quota get -u j5v@example.com
doveadm(j5v@example.com): Error: User doesn't exist
Quota name Type Value Limit                               
```

**Comment by polarathene** [comment]
```console
$ docker run --rm -itd --hostname mail.example.test --name dms mailserver/docker-mailserver

# You have 120 sec to provision `/tmp/docker-mailserver/postfix-accounts.cf` with a user:
$ docker exec -it dms bash
$ setup email add j5@example.com x
$ setup email add j5v@example.com x

$ setup email list
* j5@example.com ( 0 / ~ ) [0%]

* j5v@example.com ( 0 / ~ ) [0%]
```

No problem it's working fine 👍 

---

```
Error: User doesn't exist
[  ERROR  ]  Supplied non-number argument '' to '_bytes_to_human_readable_size()'
[  ERROR  ]  Aborting
[  ERROR  ]  Supplied non-number argument '' to '_bytes_to_human_readable_size()'
[  ERROR  ]  Aborting
```

This error though when running `setup email list` is due to running it too quickly, I was able to reproduce it.

Basically `setup email add ...` will update `postfix-accounts.cf` file with the new account. Then we have a check every 2 seconds if the file is updated, and if it is then create the new accounts in Dovecot. This can take a little bit longer, but it should all be done within about 10 seconds tops? This is just a disadvantage of using text file for accounts instead of an actual database unfortunately.

**Comment by mattn** [comment]
Thanks. I still have problem. Please do not close. I'm thinking I got this problem.

https://serverfault.com/questions/260488/dovecot-user-lookup-fails-when-using-usernamedomain-format

**Comment by mattn** [comment]
At least I can reproduce this problem even after 2 seconds have passed.

**Comment by polarathene** [comment]
> even after 2 seconds have passed.

You misread. Every 2 seconds the file is checked for new accounts, if there is any it will trigger the Dovecot update which takes longer.

If you add an account, and this check happens, then you add another account after the check, while Dovecot is being updated, this process will start again to update Dovecot. You need adequate time to pass but it should work once Dovecot UserDB is updated.

---

> Thanks. I still have problem. Please do not close. I'm thinking I got this problem.

```console
$ doveadm user j5v@example.com

field   value
uid     5000
gid     5000
home    /var/mail/example.com/j5v/home
mail    maildir:/var/mail/example.com/j5v
```

I cannot reproduce with the basic instructions I provided. Likely your problem is you did not wait long enough before running the command.

**Comment by mattn** [comment]
@polarathene At least, half of days are passed after my "setup email add" command. I have hidden my domain name for security reasons, but it seems that this problem related on the domain name or hash value of userdb.
Could you please try some usernames randomly?

**Comment by mattn** [comment]
I could reproduce this with

```
$ setup email add j5F@example.com x
$ sleep 10
$ setup email list
[  ERROR  ]  Supplied non-number argument '' to '_bytes_to_human_readable_size()'
[  ERROR  ]  Aborting
[  ERROR  ]  Supplied non-number argument '' to '_bytes_to_human_readable_size()'
[  ERROR  ]  Aborting
* j5F@example.com (  /  ) [%]
```

**Comment by polarathene** [comment]
> I have hidden my domain name for security reasons, but it seems that this problem related on the domain name or hash value of userdb.
> Could you please try some usernames randomly?

Just look at the commands I gave you please. Run them yourself with any adjustments.

You can change the hostname to whatever you're using, and create accounts for whatever mail address you like. This runs perfectly fine locally to test and prove you can reproduce the problem.

If you are concerned about privacy, try reproduce with some domain that is not yours, like I have done with `example.com`.

---

**UPDATE:**

> I could reproduce this with

Reproduced, thank you.

```console
$ docker run --rm -it --hostname mail.example.test --name dms mailserver/docker-mailserver
$ docker exec -it dms bash -c 'setup email add j5F@example.com x && sleep 10 && setup email list'

doveadm(j5F@example.com): Error: User doesn't exist
[  ERROR  ]  Supplied non-number argument '' to '_bytes_to_human_readable_size()'
[  ERROR  ]  Aborting
[  ERROR  ]  Supplied non-number argument '' to '_bytes_to_human_readable_size()'
[  ERROR  ]  Aborting
* j5F@example.com (  /  ) [%]
```

This is due to uppercase usage in the email address, which AFAIK is being normalized to lowercase somewhere in DMS, but configuration in both `postfix-accounts.cf` and `/etc/dovecot/userdb` including the created mailbox at `/var/mail` is using the original uppercase input.

**EDIT:** Here we go, the default is using the [`%L` modifier](https://doc.dovecot.org/configuration_manual/config_file/config_variables/#modifiers) to lowercase the user (_`%u` variable that is the full username and domain_):

https://github.com/docker-mailserver/docker-mailserver/blob/016d6b5255be6945b08616a79f92f496a583b775/target/dovecot/10-auth.conf#L51

Interestingly no one has reported this thus far, so not many have been attempting to use upper-case letters in their email addresses.

Personally it should remain lowercased like this which avoids any deployments that automate user account creation where allowing mixed casing would allow a fake account to exist with any uppercase letter to get mail instead (_and various other UX issues_). We already prevent creating another account like this via `setup email add ...` by checking for case-insensitive existing account:

https://github.com/docker-mailserver/docker-mailserver/blob/016d6b5255be6945b08616a79f92f496a583b775/target/scripts/helpers/database/manage/postfix-accounts.sh#L19-L20

https://github.com/docker-mailserver/docker-mailserver/blob/016d6b5255be6945b08616a79f92f496a583b775/target/scripts/helpers/database/manage/postfix-accounts.sh#L72-L77

https://github.com/docker-mailserver/docker-mailserver/blob/016d6b5255be6945b08616a79f92f496a583b775/target/scripts/helpers/database/db.sh#L126-L135

But we don't normalize to lowercase, which affects the files and mailbox location mentioned. We probably should resolve this by normalizing to lowercase on account creation instead, especially since we know that there's already this issue with Dovecot not acknowledging such accounts it would be less invasive.

---

Do you have a specific need for uppercase mail addresses? Or is normalizing to lowercase acceptable?

**Comment by mattn** [comment]
There is no strong need for me. I was experimenting with the WordPress email post-submission feature. In doing so, WordPress recommends including a random string of characters as part of the email address so that it cannot be submitted by anyone else.
That is what caused this problem.

**Comment by polarathene** [comment]
> There is no strong need for me.

👍 

> WordPress recommends including a random string of characters as part of the email address so that it cannot be submitted by anyone else.

I'm not familiar with the advice there, but I do want to point out that by default `setup email add user@example.com` is not specifically an email address. It's the DMS account with an email address as the username, but by default DMS will allow anyone who authenticates with these credentials to send email with any sender address they like.

I can only imagine that the advice from WP is to prevent guessing common usernames easily to try various passwords with 🤷‍♂️
- If this is a concern from an attacker with access to the container already, they can easily find the DMS accounts to use for credentials though, but they'll still need to guess the password.
- If DMS can be reached publicly on ports 587 or 465, authentication can be attempted by guessing the username, so you might have some added benefit there if that's a concern. However you may be better to just add the security improvement to the password if this is only personal accounts, high entropy there will work just as well if not better.

For high entropy password, [look at this site](https://getapassphrase.com/generate/), by selecting 48-bit, here is a passphrase example generated _"detailed snail summons slim lab coat"_ (yes that's a very secure password!). This would at a minimum [take 6 years to attack](https://github.com/docker-mailserver/docker-mailserver/issues/3863#issuecomment-1922733241) due to the hashing involved for someone with a fairly decent GPU. They can speed that up with more compute but that's still quite expensive (_and as a remote login attack there is notable latency involved to the point it's irrelevant_), plus with Fail2Ban active any remote login attack should quickly be blocked.

**Comment by mattn** [comment]
The WordPress email post-submission feature does not authenticate. Just simple. Everything is published once the email arrives at that email address. So the email address must be strongly secret.
I don't plan to use this feature, but at least the docker-mailserver's setup script should display some kind of friendly error message like "Do not use upper case letters in mail addresses". :+1:

**Comment by polarathene** [comment]
> The WordPress email post-submission feature does not authenticate. Just simple. Everything is published once the email arrives at that email address. So the email address must be strongly secret.

DMS won't allow that?

- You cannot relay mail through DMS without authentication / trust.
- Port 25 doesn't support authentication. It is only for receiving mail inbound, or sending mail already submitted outbound.
- Ports 587 and 465 are required to submit mail you want to send outbound. These enforce authentication.

You can relax this of course with `PERMIT_DOCKER`, but that is discouraged for security reasons mentioned in my previous comment.

Or I've misunderstood, this isn't about WP sending mail through DMS, just reading mail DMS has already received via IMAP/POP3, in which case I understand now 👍 

---

> I don't plan to use this feature, but at least the docker-mailserver's setup script should display some kind of friendly error message like "Do not use upper case letters in mail addresses". 👍

The issue was re-opened, with plans to instead normalize to lowercase on account creation for the next release. That should remove any UX issues, thus no warning needed :)

**Comment by mattn** [comment]
The write of the article write and submit the text of the article to a specific (veriy secret) e-mail address.
Apart from that, WordPress checks for new emails triggered by cron and publishes the body text as an article. So DMS is used for just e-mail spooler.

**Comment by mattn** [comment]
![image](https://github.com/docker-mailserver/docker-mailserver/assets/10111/ac7e29cd-68c6-4770-98b5-232b0f2ba328)

**Comment by polarathene** [comment]
> So the email address must be strongly secret.

For this then, keep in mind that you'll have only lowercase letters (_due to planned normalization with DMS_) and numbers, 36 values (aka base 36).

To avoid malicious abuse from guessing this by sending mail to many addresses, you would want this suffix to have plenty of entropy. The same advice for the passphrase would work here (_eg: `wordpress.detailed-snail-summons-slim-lab-coat@example.com`, but obviously don't use the same value as a password_).

The equivalent with base 36 is roughly 47-bit (`log2(36^9) = 46.53`) and would look like `wordpress.zqy2cs5c5`. If my math is right, that would require sending over 250k email addresses every second 24/7 to reach halfway of the possible email addresses (`((36^9 / 250e3) / (60*60*24*365)) / 2`_) within the same 6 years target (_this assumes they already know the `wordpress.` part_). There's over 100 trillion possible values in `36^9`.

`log2(52^8)` (upper + lowercase letters) as shown in the image example from WP is 45.6 bits of entropy, so this is roughly equivalent of what they're suggesting. For another point of context `log2(36^7) = 36`, just dropping down to 7 characters from 9 is now 36-bit, and if the attacker could only send at a rate of 5k mails per second constantly, that 50% point (average rate of guessing successfully) is now 90 days (`((36^7 / 5e3) / (60*60*24)) / 2`).

Hope that helps translate the WP advice to adjust for security equivalence in DMS 👍

**Comment by georglauterbach** [comment]
FYI: This is now a blocker for v14.0.0 - I thought it'd be good to resolve this before we release v14.0.0.

**Comment by georglauterbach** [comment]
I will have a look later today at this, just FYI.

**Comment by vahidalvandi** [comment]
i have this bug in ver 15.0.2

**Comment by polarathene** [comment]
Be more specific:
- Initial report was [identified as a timing issue](https://github.com/docker-mailserver/docker-mailserver/issues/4011#issuecomment-2105406439) (commands run too soon)
- Then later specific to [their address having uppercase letters](https://github.com/docker-mailserver/docker-mailserver/issues/4011#issuecomment-2105462076), which DMS v14 fixed by ensuring lowercase](https://github.com/docker-mailserver/docker-mailserver/pull/4033) when creating an account.

You are doing something differently than reported if you still experience this issue. We need more context to know where that problem is though.

**Comment by lreardon** [comment]
I have this issue as well, using `ghcr.io/docker-mailserver/docker-mailserver:latest`. I add an email with `setup email add example@mysite.ext password`

<img width="867" alt="Image" src="https://github.com/user-attachments/assets/21086528-6dad-475c-be4a-ca12035d9436" />

**Comment by polarathene** [comment]
Provide more context please, cannot reproduce:

```console
$ docker run --rm -itd --name dms --hostname mail.example.test ghcr.io/docker-mailserver/docker-mailserver:latest
$ docker exec -it dms bash -c 'setup email add test@cholect.co password && sleep 10 && setup email list'
* test@cholect.co ( 0 / ~ ) [0%]

# DMS v15 with the original email address works fine too, now with warning about normalization:
$ docker run --rm -itd --name dms --hostname mail.example.test mailserver/docker-mailserver:15
$ docker exec -it dms bash -c 'setup email add j5F@example.com x && sleep 10 && setup email list'
2025-04-26 05:01:06+00:00 WARN  addmailuser: Mail account 'j5F@example.com' has uppercase letters and will be normalized to 'j5f@example.com'
* j5f@example.com ( 0 / ~ ) [0%]
```

I can lower that `sleep` value down to `1` on a single core VPS (Vultr) that works perfectly fine. At `sleep 0` (_or without chaining `sleep` at all_) it will produce the error.

> I can repeatedly run `setup email list` and get the same errors a few minutes after I ran the `setup email add ...` command.

Chances are if you still get an error after some delay, there is something wrong with your config. Is Dovecot actually running?

Check our docs troubleshooting page (_when you open a new bug report we link you to the page_), run DMS with debug/trace logs, inspect the logs and log directory for any errors related to Dovecot not running etc.

If you identify the problem, please share for other users landing here that might have made the same mistake.
