### ISSUE TITLE
question: How can I verify that the integration with iptables is actually working?

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#4109]
### Subject

Something else that requires developers attention

### Description

Hello!

I was now reading this page: https://docker-mailserver.github.io/docker-mailserver/edge/config/security/fail2ban/

And I see that it says that the default is to work with NFTables, and not IPTables.

So I changed the jail.cf (reusing the default from the repo) to put:

```
banaction = iptables-multiport
banaction_allports = iptables-multiport
```

Then I recreated the container (down/up).

I tested running `setup fail2ban ban <ip>`, inside the container, and I verify that fail2ban says that IP is blocked.

I also have `NET_ADMIN` added to the `docker-compose.yml` file.

However, when I look at the host's iptables, the only fail2ban set I see is `f2b-sshd` from the host's fail2ban service running.

I'm not sure how this is supposed to work, but wouldn't this container create a set in the host's iptables, e.g. `f2b-postfix` or something?

Many thanks!

**Comment by casperklein** [comment]
>However, when I look at the host's iptables, the only fail2ban set I see is f2b-sshd from the host's fail2ban service running.

Afaik, you shouldn't have to adjust this and it should work out of the box.

> I'm not sure how this is supposed to work, but wouldn't this container create a set in the host's iptables, e.g. f2b-postfix or something?

No. The rules are only applied within the container. Try `nft list ruleset` to verify.

**Comment by ghnp5** [comment]
Thank you very much for your reply!

Ok - so I'm confused, then!

1) am I supposed to keep "nftables" in the fail2ban config, even if the Host uses "iptables" ?

2) why is `NET_ADMIN` needed then, if the rules are only added within the container? (not saying that it's not needed - I'm just not understanding, as I thought `NET_ADMIN` was needed so the container could add rules to the Host's filewall)

3) if we use "nftables-allports" instead of "nftables-multiport", is the IP still going to be blocked from all ports? it's strange to me, because if we're blocking IPs on the container's firewall, how can it affect all other ports of the host?

Many thanks again!

**Comment by polarathene** [comment]
> even if the Host uses `iptables` ?

Docker doesn't use `nftables` on the host AFAIK, it lacks native support at least I think.

> why is `NET_ADMIN` needed

I thought the same thing recently and was surprised to know that the ban is only within the container, as it makes more sense at the host level to me. I assume if this capability is actually required, the container still requires access to it to interact with the kernel syscalls to apply the ban within the container, even though it should be capable of messing with the host.

---

I can't provide feedback on the 3rd question, Fail2Ban isn't my area of expertise in the project 😅

**Comment by ghnp5** [comment]
> Docker doesn't use nftables on the host AFAIK, it lacks native support at least I think.

yeah, and that's mostly why I still have `iptables` on the host.

But my question is whether I should keep `nftables` in the fail2ban config of DMS, instead of `iptables`. I changed to `iptables` because I was assuming DMS wasn't blocking any IPs, since the host doesn't use `nftables`.
But seems it *was* indeed blocking, if DMS uses `nftables`, then ??

**Comment by polarathene** [comment]
I would need to be corrected, but I think DMS uses `nftables` with Fail2Ban in the container:

https://github.com/docker-mailserver/docker-mailserver/blob/4778f15fdaf5e94aee364396166fdc2821066c46/target/scripts/build/packages.sh#L93

`NET_ADMIN` is required to then interact with this functionality, and I had assumed it also interacted with the host because of [stuff like this](https://docker-mailserver.github.io/docker-mailserver/v14.0/config/security/fail2ban/) and [this](https://docker-mailserver.github.io/docker-mailserver/v14.0/config/debugging/#network):

> ![image](https://github.com/user-attachments/assets/5138a447-9a87-4918-9666-00437bebb16b)

> ![image](https://github.com/user-attachments/assets/4a9a47a4-6fc9-45bf-8533-a9c97eb27b76)

I know there is some old discussions about this switch in DMS a while back. And that some distros have packages for `iptables` that actually provide the legacy `iptables` interface and indirectly call `nftables` under the hood. I'm not too familiar with how these two interact and work, but I have observed that while Docker uses `iptables`, when I checked the rules via `nftables` they were presented there too.

I do know that Docker manages networking and ports with `iptables` in a way that it conflicts with any firewalls. Your firewall can block a port, but if Docker publishes the port, it has priority over the firewall rule and can be accessed anyway. This wouldn't be an issue with `nftables` I think IIRC, if Docker eventually supports that.

**Comment by ghnp5** [comment]
Thank you.

Yep - I understood that DMS uses `nftables`.

However, what confuses me is this, in that red warning above:

> You will need to configure F2B to use legacy IPTables again, for example with the fail2ban-jail.cf

This is what made me think I indeed had to change `fail2ban-jail.cf` to set `iptables`, as per my initial post in this thread.

But if DMS internally uses `nftables`, and IPs are only blocked internally, I don't understand why the host has to support `nftables`, then.

I use AlmaLinux 8 (RHEL/CentOS family), and it's my understanding that the `iptables` package is a wrapper to `nftables`. But, the `nftables` service is disabled and masked, so only `iptables` runs. If I run `nft list ruleset` on the host, I see all the entries that are also in `iptables-save`. (I actually never run that before - but this proves that `iptables` is indeed a wrapped to `nftables` !)

--

Now, back to the container.

`setup fail2ban` shows 2 IPs blocked, but `nft list ruleset` doesn't.

I updated the fail2ban config to put `nftables-multiport`, and then recreated the container.

Banned an IP, and now I see `table inet f2b-table` in the ruleset of the container.
But I don't see the same IP blocked on the host's `nft list ruleset`.
No idea if the IP is really blocked, unless I test with my own IP :-)

**Comment by casperklein** [comment]
Checkout https://www.puzzle.ch/blog/2021/07/05/containers-netfilter-iptables-nftables-teil-1. If you scroll a bit down, there is a nice chart explaining how iptables, iptables-nft and nft interact. Not best practice, but you can use them all at the same time.

> But I don't see the same IP blocked on the host's nft list ruleset.

That's the point of a container, not polluting the host settings. Unless other rights granted, all stuff done in a container should only apply in the container. If you don't like that behaviour, you can specify [`network_mode: "host"`](https://docs.docker.com/compose/compose-file/05-services/#network_mode) in your `compose.yml` file. Then you'll see the f2b ruleset on the host, because it's directly applied there. However, you mentioned, that you run another instance of f2b directly on the host. I wouldn't be surprised, if you run both at the same time, that the could mess up each other.

**Comment by polarathene** [comment]
> But if DMS internally uses `nftables`, and IPs are only blocked internally, I don't understand why the host has to support `nftables`, then.

I think it's regarding kernel support, which is what the `NET_ADMIN` capability helps with.

I trust @casperklein knows this area well enough, but if you do identify something in our docs is outdated / incorrect or could be communicated more clearly, please do contribute a PR :)

**Comment by ghnp5** [comment]
Thanks @casperklein 

> That's the point of a container, not polluting the host settings.

Sure, and I'm well aware of that (hence I've been dockerizing pretty much everything!!).

But it's the `NET_ADMIN` requirement, and the docs saying about changing the config to `iptables` depending on the host, that is confusing me a lot :-)

Also, this:

[# nftables-multiport: block IP only on affected port
# nftables-allports:  block IP on all ports](https://github.com/docker-mailserver/docker-mailserver/blob/4778f15fdaf5e94aee364396166fdc2821066c46/config-examples/fail2ban-jail.cf#L19C1-L20C44)

Can the container's nftables block an IP on "all ports", or not ??
If it's a container, I guess it can only block the ports that the container can access?

**Comment by polarathene** [comment]
> If it's a container, I guess it can only block the ports that the container can access?

I assume it is blocking for interfaces available only with the container.

With the default docker bridge network, this will be the container IP AFAIK, so any source IP (_the external IP, or separate container IP like via RoundCube webmail for example which loses the real client IP_) that connects to the DMS container IP is matched and blocked.

On the host side, Docker has `iptables` rules to route external connections to a public IP and port to a container IP and port. So if you did your host F2B monitor the DMS logs volume to apply bans instead, I guess it would need to have it's rules with more priority over the Docker routing ones, since I think the Docker rules or container services (reverse proxy) can replace the original source IP/port otherwise.

---

## References

`NET_ADMIN` capability requirement was discussed in the PR that introduced F2B into DMS: https://github.com/docker-mailserver/docker-mailserver/pull/78#discussion_r52808062

Here is an example where it fails due to the host environment (kernel I think): https://github.com/docker-mailserver/docker-mailserver/issues/3897#issuecomment-1953423571

And there was a [recent discussion regarding a reverse proxy (Traefik) breaking the F2B support](https://github.com/orgs/docker-mailserver/discussions/4063#discussioncomment-9781114) (_which is where I became aware of the F2B in the container not being host wide_), note the `daddr` and `saddr` in the NFT rules for scope of IPs / interfaces in addition to ports.

**Comment by casperklein** [comment]
```
# nftables-multiport: block IP only on affected port
# nftables-allports:  block IP on all ports
```

>Can the container's nftables block an IP on "all ports", or not ??

No, only if you explicitly use network_mode host for the container.

>If it's a container, I guess it can only block the ports that the container can access?

Correct.

Normally, F2B only blocks an IP address on the service/port it detects failures. For example, if you fail to authenticate multiple times via IMAP, your IP will be blocked for IMAP only. You will still be able to connect via POP3, SMTP etc.
All ports means, that regardless on which service an failure was recognized, the IP is blocked for all services. IMO that makes sense when blocking a malicious actor.
All ports only apply to exposed services within the container and will not effect the host system.

**Comment by ghnp5** [comment]
Thank you, folks!

I've just tested banning my own IP, and I confirm it only bans within the container, even if I use `allports` instead of `multiport`.

Perfect - I confirm it's working!!

Have a great day!
