### ISSUE TITLE
question: How to add a service to Postfix `master.cf` with a different `maxproc` value?

### ISSUE THREAD

**Issue by pitilux** [docker-mailserver/docker-mailserver#4218]
### Subject

I would like some feedback concerning a use case

### Description

Hello DMS team,

I'd like to configure a service with a specific process limit and I'm wondering if this could be done with `postconf -P <service_name>/<type>/<parameter>`?
Consider the following service:
```
# ==========================================================================
# service      type  private unpriv  chroot  wakeup  maxproc command + args
#                    (yes)   (yes)   (no)    (never) (100)
# ==========================================================================
slow           unix    -       -       -       -       1     smtp -o syslog_name=postfix-slow
```

Out of curiosity, what is the rationale behind the fact that the `docker-data/dms/config/postfix-master.cf` content is not appended to `master.cf` but rely on using `postconf -P`?

**Comment by polarathene** [comment]
> I'd like to configure a service with a specific process limit and I'm wondering if this could be done with `postconf -P <service_name>/<type>/<parameter>`?

I wasn't sure if this could be done from reading over the [`postconf` command docs](https://www.postfix.org/postconf.1.html), so I had to hit up search engine with keywords _"postfix postconf maxproc master"_, and [found this helpful answer](https://unix.stackexchange.com/questions/691166/how-do-you-use-the-postconf-me-option/691222#691222) fairly easily:

```bash
# Add the new service like you showed above in full to `/etc/postfix/master.cf`:
postconf -M 'submission/inet=slow unix - - - - 1 smtp -o syslog_name=postfix-slow'
```

The `-e` (_as per the `postconf` command docs_) is optional, so just `-M` is fine due to the `=` which implicitly treats it as `-Me`. This was also [originally discussed by the Postfix developers here](https://narkive.com/hC5RVN8r.10).

**EDIT:** It seems that if you use `-F` it will allow you to target specific service fields such as `maxproc`, however that is not the actual field name. When you use `-F` without any assignment, it'll list the fields for the service and you can get the proper field names this way:

```console
# With the `slow` service we just created above:
$ postconf -F slow/unix

slow/unix/service = slow
slow/unix/type = unix
slow/unix/private = -
slow/unix/unprivileged = -
slow/unix/chroot = -
slow/unix/wakeup = -
slow/unix/process_limit = 1
slow/unix/command = smtp -o syslog_name=postfix-slow
```

With that you can now easily update just a specific field if the service already exists:

```console
# Set maxproc to 42:
$ postconf -F slow/unix/process_limit=42

# Query the field (`-h` to only output value, instead of `key = value`):
$ postconf -Fh slow/unix/process_limit
42
```

As suggested below, whichever command above meets your needs you can [handle that via our `user-patches.sh` support](https://docker-mailserver.github.io/docker-mailserver/v14.0/config/advanced/override-defaults/user-patches/) (_just a regular shell script at `/tmp/docker-mailserver/user-patches.sh` inside the container_).

---

> Out of curiosity, what is the rationale behind the fact that the `docker-data/dms/config/postfix-master.cf` content is not appended to `master.cf` but rely on using `postconf -P`?

That was a decision made before any active maintainer was involved in the project, back in June 2017 ([PR](https://github.com/docker-mailserver/docker-mailserver/pull/595) and [feature request](https://github.com/docker-mailserver/docker-mailserver/issues/594)).

The more generic `user-patches.sh` solution didn't get contributed later until Oct 2019 ([PR](https://github.com/docker-mailserver/docker-mailserver/pull/1284) and [associated issue](https://github.com/docker-mailserver/docker-mailserver/issues/1281#issuecomment-538860483)).

---

One advantage of `postconf -P` I think is it overrides/updates an existing entry? Which you can see a use-case for in our docs here:

https://github.com/docker-mailserver/docker-mailserver/blob/26a44995a9bba825b1348dbf3551687c2100f7a3/docs/content/examples/tutorials/mailserver-behind-proxy.md?plain=1#L174-L186

IIRC if you just append such a change (_as a full service line_) it would not be compatible, or would replace the earlier definition losing any other configuration. Whereas with `postfix-main.cf` we do append, as that config file will use the last instance of a setting in the file, and during startup we also filter any earlier occurrences out (_to minimize warnings logged about repeated settings_) via `postconf -n`:

https://github.com/docker-mailserver/docker-mailserver/blob/26a44995a9bba825b1348dbf3551687c2100f7a3/target/scripts/startup/setup.d/postfix.sh#L124-L142

---

**EDIT:** Ah, after completing my response here, I can see that `postconf -P` is specifically focused on overriding `main.cf` settings per service in `master.cf`, so our `postfix-master.cf` is specifically focused on catering to that kind of overriding. More niche requirements should be handled via `user-patches.sh` with either `postconf` commands or appending to `/etc/postfix/master.cf` directly.

In the same DMS docs example I showed for `postfix-master.cf`, we have a `user-patches.sh` snippet for duplicating a service where we make a small change to support alternate ports for PROXY protocol usage:

https://github.com/docker-mailserver/docker-mailserver/blob/26a44995a9bba825b1348dbf3551687c2100f7a3/docs/content/examples/tutorials/mailserver-behind-proxy.md?plain=1#L248-L262

**Comment by pitilux** [comment]
Awesome! Thanks for this very detailed answer!

**Comment by polarathene** [comment]
> In fact the postconf command to add a new service is slightly different (otherwise it would replace the `submission/inet` service):

Oops, missed that while adapting to your service, sorry about that! I've updated my comment to correct it 😅
