### ISSUE TITLE
feature request: IPTABLES_MODE

### ISSUE THREAD

**Issue by vhedges** [docker-mailserver/docker-mailserver#4220]
### Context

An option to select between iptables or nftables to be used in Fail2ban

### Description

Please can you implement an Environment variable called 'IPTABLES_MODE',
which selects between iptables or nftables to be used in fail2ban.

### Alternatives

I have had to deploy Docker-mailserver 10.5.0 which uses iptables, because the latest
version (14.0.0) uses nftables which do not work on my NAS. Because the NAS employs
a legacy kernel.

### Applicable Users

All NAS users and those on legacy kernels.
Docker-mailserver is absolutely fabulicious. Compact, easy to use, and powerful. It would be a shame if the latest versions did not work on legacy kernels.

### Are you going to implement it?

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

### What are you going to contribute?

I have worked on main-frames for the past 40years. Mainly C, C++

**Comment by polarathene** [comment]
DMS does not maintain support for legacy devices. I would suggest you host DMS on a different device which shouldn't cost you all that much vs the cost of support and maintenance burden it can place on DMS 😅 

The switch occurred at this PR: https://github.com/docker-mailserver/docker-mailserver/pull/2505

You should be able to patch this on your end if you insist on staying with the legacy product for DMS. Alternatively you could have Fail2Ban disabled in DMS and manage it externally I think if that's easier for you?

**EDIT:** Seems there was a PR for this feature request back in June 2022 that didn't reach completion (_deferred to docs, and I don't recall much demand for this support since_): https://github.com/docker-mailserver/docker-mailserver/pull/2662#pullrequestreview-1020896368

---

You'll need to [install the `iptables` package and add back the two updates](https://github.com/docker-mailserver/docker-mailserver/commit/a9305a073f90f3bea59864552db0aab7ea05bd96#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R61):

```bash
# switch iptables and ip6tables to legacy for Fail2Ban
update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
```

[`jail.local` change](https://github.com/docker-mailserver/docker-mailserver/commit/a9305a073f90f3bea59864552db0aab7ea05bd96#diff-69dbfc355c116d7abb4e683d9de30ed0559b95322c1cd54fdd97c11916fceaabR21), replace this line with `banaction = iptables-allports`, the default config we bundle into the container is placed at `/etc/fail2ban/jail.local`:

https://github.com/docker-mailserver/docker-mailserver/blob/26a44995a9bba825b1348dbf3551687c2100f7a3/target/fail2ban/jail.local#L21

https://github.com/docker-mailserver/docker-mailserver/blob/26a44995a9bba825b1348dbf3551687c2100f7a3/Dockerfile#L184

I don't maintain the Fail2Ban support, so I'm not sure if you can override that as the config volume support seems to be copied to different internal locations (@casperklein would know this answer better):

https://github.com/docker-mailserver/docker-mailserver/blob/26a44995a9bba825b1348dbf3551687c2100f7a3/target/scripts/startup/setup.d/security/misc.sh#L196-L204

[This change](https://github.com/docker-mailserver/docker-mailserver/commit/a9305a073f90f3bea59864552db0aab7ea05bd96#diff-141cf3167e0d3e34aa4f5242772a4e7519a0abb8a7cd2ba4493e8ea0ed607a61R1147) now lives here:

https://github.com/docker-mailserver/docker-mailserver/blob/26a44995a9bba825b1348dbf3551687c2100f7a3/target/scripts/startup/setup.d/security/misc.sh#L206-L209

Replace the inner `echo` line with:

```bash
echo -e '[Init]\nblocktype = DROP' >/etc/fail2ban/action.d/iptables-common.local
```

I won't go into changes related to the `setup` related support but that related [file is here](https://github.com/docker-mailserver/docker-mailserver/blob/26a44995a9bba825b1348dbf3551687c2100f7a3/target/bin/fail2ban) should you want to apply changes there too.

---

## Workaround

Try this [`user-patches.sh`](https://docker-mailserver.github.io/docker-mailserver/v14.0/config/advanced/override-defaults/user-patches/) example, just add it to your [config volume](https://docker-mailserver.github.io/docker-mailserver/v14.0/config/advanced/optional-config/#volumes) which should place it at `/tmp/docker-mailserver/user-patches.sh`:

```bash
#!/bin/bash

apt-get update && apt-get install -y iptables
# switch iptables and ip6tables to legacy for Fail2Ban
update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

if [[ ${FAIL2BAN_BLOCKTYPE} != 'reject' ]]; then 
  echo -e '[Init]\nblocktype = DROP' >/etc/fail2ban/action.d/iptables-common.local
fi

sed -i 's/banaction = nftables-allports/banaction = iptables-allports/' /etc/fail2ban/jail.local
```

That should be sufficient to give you iptables equivalent support instead of nftables 👍

**Comment by georglauterbach** [comment]
I agree with @polarathene here; you will need to patch this, which is viable. We do not provide support for legacy configuration in modern versions of DMS as the maintenance overhead is too big.
