### ISSUE TITLE
question: How do I use SASL for SMTP authentication to send mail? (with `SPOOF_PROTECTION=1`)

### ISSUE THREAD

**Issue by a1exus** [docker-mailserver/docker-mailserver#4228]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

hello, world!

I'm trying to configure SMTP authentication so I can send out emails from Mail client on macOS.
I was reading [Postfix SASL docs](https://www.postfix.org/SASL_README.html#server_sasl_authc) and then per [DMS docs for `ENABLE_SASLAUTHD`](https://docker-mailserver.github.io/docker-mailserver/v14.0/config/environment/#enable_saslauthd) I set the variable to `1`, and then checked postfix via `postconf`, yet still not seeing `smtpd_sasl_auth_enable` enabled:

```console
$ grep ENABLE_SASLAUTHD mailserver.env
ENABLE_SASLAUTHD=1

$ docker exec -it mailserver postconf smtpd_sasl_auth_enable
smtpd_sasl_auth_enable = no
$ 
```

Please advise.

### 👟 Reproduction Steps

none / out of the box behavior

### 🐋 DMS Version

latest (v14.0)

### 💻 Operating System and Architecture

```
$ cat /etc/debian_version
12.7
$ uname -a
Linux X 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux
$
```

### ⚙️ Container configuration files

```
$ cat docker-compose.override.yaml
services:
  mailserver:
    cap_add:
      - NET_ADMIN
    networks:
      - default
    volumes:
      - /path/certbot/etc/letsencrypt:/etc/letsencrypt:rw
```

### 📜 Relevant log output

```
mailserver  | 2024-10-15T12:58:39.702433-07:00 mail postfix/submission/smtpd[1251]: NOQUEUE: reject: RCPT from d-X-X-X-X.X.cpe.atlanticbb.net[X.X.X.X]: 554 5.7.1 <d-X-X-X-X.X.cpe.atlanticbb.net[X.X.X.X]>: Client host rejected: Access denied; from=<X@X.X> to=<X@X.X> proto=ESMTP helo=<smtpclient.apple>
```

**Comment by polarathene** [comment]
Why do you think you need that setting? We have SASL setup by default via Dovecot, that ENV is for an alternative to Dovecot, you very much aren't likely to need that.

- `setup email add my-user@example.com` and enter a password to create a DMS account for that email address.
- Connect to the DMS FQDN (hostname, which should not be `example.com`, but instead something like `mail.example.com`) on port 587 or 465 from your mail client (_make sure it's configured correctly, plain-text auth mechanism over STARTTLS (587) or TLS (465)_).

You should be good to go then, assuming your DNS and LetsEncrypt certificate are all setup correctly.

**Comment by a1exus** [comment]
set ENABLE_SASLAUTHD back to 0 and restarted it, and now getting following error instead:

```
mailserver  | 2024-10-15T13:27:19.133948-07:00 mail postfix/submission/smtpd[1242]: NOQUEUE: reject: RCPT from d-X-X-X-X.X.cpe.atlanticbb.net[X.X.X.X]: 553 5.7.1 <alexus@example.com>: Sender address rejected: not owned by user postmaster@example.com; from=<alexus@example.com> to=<X@gmail.com> proto=ESMTP helo=<smtpclient.apple>
```

**Comment by polarathene** [comment]
Aliases are not meant for login. They are for mail to be received on port 25 and then delivered to a target recipient address.

`setup email add user@example.com` is your DMS account, you create the login credentials with that (_along with a mailbox_). You may send mail from any sender address you like (_assuming `SPOOF_PROTECTION` is not `1`_) from that authenticated login.

For more information, until v15 is released, you can see the updated accounts/aliases docs on `:edge` here:
- https://docker-mailserver.github.io/docker-mailserver/edge/config/account-management/overview/#aliases
- https://docker-mailserver.github.io/docker-mailserver/edge/config/account-management/provisioner/file/#aliases

> `553 5.7.1 <alexus@example.com>: Sender address rejected: not owned by user postmaster@example.com`

Suggests that you may have `SPOOF_PROTECTION=1`?

**Comment by a1exus** [comment]
> Aliases are not meant for login. They are for mail to be received on port 25 and then delivered to a target recipient address.

i'm _not_ using alias to login, instead i use _postmaster_ account to authenticate and alias is set in _from_ field

> `setup email add user@example.com` is your DMS account, you create the login credentials with that (_along with a mailbox_). You may send mail from any sender address you like (_assuming `SPOOF_PROTECTION` is not `1`_) from that authenticated login.
> 
> For more information, until v15 is released, you can see the updated accounts/aliases docs on `:edge` here:

i just update the _image_ in the test (production) environment ;p

```
$ grep image docker-compose.override.yaml
    image: ghcr.io/docker-mailserver/docker-mailserver:edge
$
```

> * https://docker-mailserver.github.io/docker-mailserver/edge/config/account-management/overview/#aliases
> * https://docker-mailserver.github.io/docker-mailserver/edge/config/account-management/provisioner/file/#aliases
> 
> > `553 5.7.1 <alexus@example.com>: Sender address rejected: not owned by user postmaster@example.com`
> 
> Suggests that you may have `SPOOF_PROTECTION=1`?

per recommendation spoof protection _IS_ enabled:

```
$ grep -B4 SPOOF_PROTECTION mailserver.env
# Configures the handling of creating mails with forged sender addresses.
#
# **0** => (not recommended) Mail address spoofing allowed. Any logged in user may create email messages with a forged sender address (see also https://en.wikipedia.org/wiki/Email_spoofing).
# 1 => Mail spoofing denied. Each user may only send with his own or his alias addresses. Addresses with extension delimiters(http://www.postfix.org/postconf.5.html#recipient_delimiter) are not able to send messages.
SPOOF_PROTECTION=1
$
```

**Comment by polarathene** [comment]
> > Suggests that you may have `SPOOF_PROTECTION=1`?
> 
> per recommendation spoof protection _IS_ enabled

https://github.com/docker-mailserver/docker-mailserver/blob/34eb54ac398c4c3846645cf79404d8528869891b/target/scripts/startup/setup.d/security/spoofing.sh#L18

`postconf smtpd_sender_login_maps` should output that line with `unionmap` then? It will check the login address I think for permission to use other sender addresses.

The referenced config IIRC was implemented wrong, so although it looks in the virtual alias table, I believe it is checking `postmaster` on the left-side for an alias to match, not for sender addresses that match an alias to `postmaster`.

---

The `SPOOF_PROTECTION=1` feature is [not in the greatest shape](https://github.com/docker-mailserver/docker-mailserver/issues/2819).

We have https://github.com/docker-mailserver/docker-mailserver/pull/4044 for improving this, I just need to get back to reviewing it for the v15 release. In the meantime there is the existing `postfix-regexp.cf` config support [which has some caveats](https://github.com/docker-mailserver/docker-mailserver/pull/4044#discussion_r1623695525), you can add that to your Config volume with a line like this:

https://github.com/docker-mailserver/docker-mailserver/blob/34eb54ac398c4c3846645cf79404d8528869891b/test/config/postfix-regexp.cf#L5

This isn't really what you'd want though, as any mail arriving for `postmaster` will be sent to that alias target recipient instead. Hence the PR I linked which properly adds a config that is only for relaxing the `SPOOF_PROTECTION=1` restriction with no affect on mail routing elsewhere.

If this is only a personal instance of DMS you may want to disable the feature. It's only to restrict the authenticated user from what sender address they can use, since on a multi-user deployment of DMS, the janitor could login to their own e-mail account but also send out mail using the CEO's email address.

---

Another option for you is to manually override `smtpd_sender_login_maps` via `postfix-main.cf`, instead of using that `SPOOF_PROTECTION=1` setting.

```
# postfix-main.cf
smtpd_sender_login_maps = unionmap:{ pcre:/etc/postfix/maps/sender_login_maps.pcre, texthash:/tmp/docker-mailserver/sender-login-map.cf }
```

`unionmap` will query both configs and merge the results of any valid sender addresses (_for regex maps you still only get the result returned per config of the first match found_). The `pcre` one is the regex used for `SPOOF_PROTECTION=1` to restrict the sender address to the login address:

https://github.com/docker-mailserver/docker-mailserver/blob/34eb54ac398c4c3846645cf79404d8528869891b/target/postfix/sender_login_maps.pcre#L1

The `texthash` one is a filepath to your custom config, just add direct mapping of login address to one or more additional sender addresses you'd like to support:

```
# /tmp/docker-mailserver/sender-login-map.cf
postmaster@example.com myalias@example.com,user@example.com,user@another-domain.com

# Another user account, that is also permitted to send as the `user@example.com` account address
user@another-domain.com user@example.com
```
