### ISSUE TITLE
Feature request: Add documentation for creating custom rspamd rules

### ISSUE THREAD

**Issue by chascode** [docker-mailserver/docker-mailserver#4232]
### Context

My request is related to rspamd rules.

### Description

I'm trying to add 10.00 to the score of all emails where any of the received headers matches *.instillerhq.com.

I've tried many things in my patch script, but, no matter what I append to "/etc/rspamd/rspamd.conf", nothing works.

### Alternatives

A global sieves rule for all users instead of setting sieve rules for each and every user.

### Applicable Users

Anyone who doesn't want spam from spammers who successfully score negatively.

### Are you going to implement it?

No, and I understand that it is highly likely no one will implement it. Furthermore, I understand that this issue will likely become stale and will be closed.

### What are you going to contribute?

Sorry, ChatGPT and I give up with trying to add custom rules to rspamd.

**Comment by polarathene** [comment]
> ### Alternatives
> A global sieves rule for all users instead of setting sieve rules for each and every user.

Our [docs on sieve support](https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/mail-sieve/) do mention global rule support (before/after). So you should be able to do that.

I've assigned to @georglauterbach as they're most experienced with rspamd, but as they're quite busy they may not have time to add such an example to the docs, especially without other users expressing interest since you raised this it will likely stay stale as the demand for it is too low.

If that's a deal breaker, you may want to consider an alternative to DMS such as stalwart, mailcow, or mailu.

**Comment by chascode** [comment]
I configured `sieve before` to my liking but it'll be nice to set my own scoring rules, too.

**Comment by georglauterbach** [comment]
Please first tell us what you already tried, so I have an idea :)

I don't think `/etc/rspamd/rspamd.conf` is the correct location.
