### ISSUE TITLE
bug report: Server cannot receive mail 

### ISSUE THREAD

**Issue by Softbox44** [docker-mailserver/docker-mailserver#4236]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I am encountering some strange behaviour between two DMS's that I am running on two separate IPs and Domains.
One of the servers (DSM-X) cannot receive mail from the other (DMS-T). Both run in separate locations on completely separate infrastructure.

DMS-X --> DMS-T [works fine]
Gmail --> DMS-X [works fine]
Gmail --> DMS-T [works fine]
**DMS-T --> DMS-X [no emails arrive]**

What I have checked:

- For both domains the SPF, DMARC and DKIM records are correctly setup in Cloudflare DNS.
- non of the IPs are banned in fail2ban 

When I send the emails, the DMS-T (sender) logs show the following:
```
2024-10-23T23:15:04.918123+01:00 mail postfix/submissions/smtpd[9482]: E014377243: client=mail.DSM-X[DSM-X-IP], sasl_method=LOGIN, sasl_username=user@DSM-T
2024-10-23T23:15:04.944166+01:00 mail postfix/sender-cleanup/cleanup[9645]: E014377243: message-id=<003601db2599$031eb650$095c22f0$@DSM-T-Domain>
2024-10-23T23:15:04.944212+01:00 mail postfix/sender-cleanup/cleanup[9645]: E014377243: replace: header MIME-Version: 1.0 from mail.DSM-X[DSM-X-IP]; from=<user@DSM-T> to=<nmax3@DSM-X> proto=ESMTP helo=<DESKTOPNEII4G1>: MIME-Version: 1.0
2024-10-23T23:15:04.981200+01:00 mail opendkim[1187]: E014377243: DKIM-Signature field added (s=mail, d=DSM-T-Domain)
2024-10-23T23:15:05.053214+01:00 mail postfix/qmgr[1305]: E014377243: from=<user@DSM-T>, size=2271, nrcpt=1 (queue active)
2024-10-23T23:15:06.218612+01:00 mail dovecot: imap-login: Login: user=<user@DSM-T>, method=PLAIN, rip=DSM-X-IP, lip=172.30.0.2, mpid=9796, TLS, session=<Jb3bNywlet1ZJELH>
2024-10-23T23:15:06.433904+01:00 mail postfix/smtpd-amavis/smtpd[9653]: connect from localhost[127.0.0.1]
2024-10-23T23:15:06.436299+01:00 mail postfix/smtpd-amavis/smtpd[9653]: 6A7A477250: client=localhost[127.0.0.1]
2024-10-23T23:15:06.437881+01:00 mail postfix/cleanup[9654]: 6A7A477250: message-id=<003601db2599$031eb650$095c22f0$@DSM-T-Domain>
2024-10-23T23:15:06.441025+01:00 mail postfix/smtpd-amavis/smtpd[9653]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
2024-10-23T23:15:06.441147+01:00 mail postfix/qmgr[1305]: 6A7A477250: from=<user@DSM-T>, size=3280, nrcpt=1 (queue active)
2024-10-23T23:15:06.448285+01:00 mail amavis[1747]: (01747-10) Passed CLEAN {RelayedInbound}, [DSM-X-IP]:56697 [DSM-X-IP] <user@DSM-T> -> <nmax3@DSM-X>, Queue-ID: E014377243, Message-ID: <003601db2599$031eb650$095c22f0$@DSM-T-Domain>, mail_id: ykv3-K1dkRbc, Hits: 2.643, size: 2768, queued_as: 6A7A477250, 1393 ms
2024-10-23T23:15:06.450147+01:00 mail postfix/smtp-amavis/smtp[9485]: E014377243: to=<nmax3@DSM-X>, relay=127.0.0.1[127.0.0.1]:10024, delay=1.5, delays=0.14/0/0/1.4, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 6A7A477250)
2024-10-23T23:15:06.451022+01:00 mail postfix/qmgr[1305]: E014377243: removed
2024-10-23T23:15:06.466542+01:00 mail dovecot: lmtp(9797): Connect from local
2024-10-23T23:15:06.531558+01:00 mail dovecot: lmtp(nmax3@DSM-X)<9797><DvHLG2p1GWdFJgAAEnssuw>: sieve: msgid=<003601db2599$031eb650$095c22f0$@DSM-T-Domain>: stored mail into mailbox 'INBOX'
2024-10-23T23:15:06.532365+01:00 mail postfix/lmtp[9655]: 6A7A477250: to=<nmax3@DSM-X>, relay=mail.omvmail24.org[/var/run/dovecot/lmtp], delay=0.1, delays=0.01/0/0.02/0.07, dsn=2.0.0, status=sent (250 2.0.0 <nmax3@DSM-X> DvHLG2p1GWdFJgAAEnssuw Saved)
2024-10-23T23:15:06.532645+01:00 mail postfix/qmgr[1305]: 6A7A477250: removed
2024-10-23T23:15:06.532699+01:00 mail dovecot: lmtp(9797): Disconnect from local: Logged out (state=READY)
2024-10-23T23:15:07.588921+01:00 mail postfix/submissions/smtpd[9482]: disconnect from mail.DSM-X[DSM-X-IP] ehlo=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=6
```

When I send the emails, the DMS-X (receiver) logs show **no** entry.
Any ideas what I am missing?

### 🐋 DMS Version

v14.0.0.

### 💻 Operating System and Architecture

Debian

### ⚙️ Container configuration files

```yml
:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: mailserver2
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    # added one vol for import aj
    hostname: mail.[DMS-X_domain]
    ports:
      - "28:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "465:465"
      - "4190:4190"
    volumes:
    - /srv/dev-disk-by-uuid-c8781cb8-41f2-42a6-9ee0-acd14b06524f/Dockerapps240/ajmail2/mail-data/:/var/mail/
    - /srv/dev-disk-by-uuid-c8781cb8-41f2-42a6-9ee0-acd14b06524f/Dockerapps240/ajmail2/mail-state/:/var/mail-state/
    - /srv/dev-disk-by-uuid-c8781cb8-41f2-42a6-9ee0-acd14b06524f/Dockerapps240/ajmail2/mail-logs/:/var/log/mail/
    - /srv/dev-disk-by-uuid-c8781cb8-41f2-42a6-9ee0-acd14b06524f/Dockerapps240/ajmail2/config/:/tmp/docker-mailserver/
    - /etc/localtime/:/etc/localtime:ro
    # - /srv/dev-disk-by-uuid-c8781cb8-41f2-42a6-9ee0-acd14b06524f/Dockerapps240/letsencrypt/fromDSM_T17/xmail44.win/:/tmp/dms/custom-certs/
    # new location for manually created certificates on T630
    - /srv/DockerDrive/Dockerapps240/letsencrypt/630created/certbot/certs/:/etc/letsencrypt
    #- /srv/DockerDrive/Dockerapps240/letsencrypt/630created/certbot/certs/live/mail.xmail44.win:/tmp/dms/custom-certs/
    #- /srv/dev-disk-by-uuid-c8781cb8-41f2-42a6-9ee0-acd14b06524f/Dockerapps240/ajmail2/import/:/tmp/import/
    environment:
      - TZ=Europe/London # added 01-03-24
      - LOG_LEVEL=debug #by AJ
      - PFLOGSUMM_TRIGGER=daily_cron # by AJ
      - POSTFIX_MESSAGE_SIZE_LIMIT=10240000 # by AJ
     # - PFLOGSUMM_RECIPIENT=nmax3@mail # by AJ, switched from 22-02-24
     # 01-03-24 leave empty so email go to postmaster (and that is typically redirected via alias to nmax3)
      - LOGWATCH_INTERVAL=daily # by AJ, can be weekly
 #    - ENABLE_SPAMASSASSIN=1
      - ENABLE_SPAMASSASSIN_KAM=0 #added by AJ 25-04-24 and changed to 0 01-06-24
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=0 # by AJ
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - ENABLE_MANAGESIEVE=1 # enables sthe server on port 4190
      - POSTFIX_MESSAGE_SIZE_LIMIT=10240000 # added aj 13-07-24 to allow kindle attachments to be sent
# SSL type was also changed 11-07-24 when certbot command was used to create certificate directly on T630 
      - SSL_TYPE=letsencrypt
# setting was changed 11-07-24 when certbot command was used to create certificate directly on T630
#      - SSL_CERT_PATH=/tmp/dms/custom-certs/fullchain.pem
#      - SSL_KEY_PATH=/tmp/dms/custom-certs/privkey.pem
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
```

**Comment by polarathene** [comment]
> When I send the emails, the DMS-X (receiver) logs show **no** entry.
> Any ideas what I am missing?

```
dovecot: lmtp(9797): Connect from local
dovecot: lmtp(nmax3@DSM-X)<9797><DvHLG2p1GWdFJgAAEnssuw>: sieve: msgid=<003601db2599$031eb650$095c22f0$@DSM-T-Domain>: stored mail into mailbox 'INBOX'
postfix/lmtp[9655]: 6A7A477250: to=<nmax3@DSM-X>, relay=mail.omvmail24.org[/var/run/dovecot/lmtp], delay=0.1, delays=0.01/0/0.02/0.07, dsn=2.0.0, status=sent (250 2.0.0 <nmax3@DSM-X> DvHLG2p1GWdFJgAAEnssuw Saved)
```

It looks like mail sent to `@DSM-X` is being stored in Dovecot mailbox managed by DSM-T. We can see that a relay was referenced too.

Perhaps something in your config makes DMS-T believe it manages mail for DMS-X? It did happily store mail in Dovecot which Postfix sent via LMTP (should only be when DMS thinks it's local mail).

Perhaps you've created an alias incorrectly?

**Comment by Softbox44** [comment]
> Perhaps you've created an alias incorrectly? Check `/etc/postfix/vhosts` on `DMS-T` and see if your `DMS-X` domain is listed there.

Brilliant. Well spotted. Thank you. 
You are right. Inside DMS-T's vhosts file I have DMS-X listed. This was not by mistake but I had in the past setup DMS-T as a failover mailserver for DMS-X. So I copied the mailbox over. Since both servers are in different physical locations and with different IPs, this made sense to me at the time. I had the relevent MX records seup, too. I never assumed this could cause a conflict for emails that are actually sent live from DMS-T to DMS-X.

How could I rectify this please? And is there a way to run a failover server without causing conflicts?

**Comment by polarathene** [comment]
> I think this is a routing problem. DMS-T wants to send the email to DMS-X but recognises that DMS-X mailbox is also available inhouse
> DMS-T then decides it will **not** consult the external DNS record for DMS-X
> Instead DMS-T delivers the mail to the internal mailbox.

Correct 👍 

> So somehow I must force DMS-T to consult the external DNS server for IP resolution. How can this be achieved?

I recall Postfix has some guidance on their official docs somewhere about backup MX servers and how to properly configure those, you'd need to look into that.

I believe that advice is different, but in this case you could probably relay the mail where DMS-T connects to DMS-X over port 587 / 465 and authenticates to have DMX-X send the mail, which it should then itself recognize as having the local mailbox and store at DMS-X.

If the forwarding alias you have gets in the way of that due to `/etc/postfix/vhosts`, whatever Postfix suggests to do instead may be more appropriate. There's also a `relay_domains` setting which DMS doesn't have any official support/docs on, where inbound mail for specific domains is allowed to arrive on port 25 and be relayed outbound without authenticated submission.

---

Just know that DMS is generating `/etc/postfix/vhosts`, and it does so by taking the DMS accounts (`postfix-accounts.cf``) and virtual aliases (`postfix-virtual.cf`) configs for mail domains, and Postfix will then use that `vhosts` file to know what mail domains it manages, and thus accepts delivery for.

Aliases are resolved to the actual recipient address during that step where Postfix accepts the mail, it'll resolve the alias before some other rules would get applied IIRC. I _think_ that's also the case when sending mail outbound (_but it's been a while since I tried, perhaps I have that mixed up with something else in the config_). It may be possible to alter the configuration so that aliases only apply to inbound and don't get resolved for outbound mail sent by DMS, but that `vhosts` file is probably still an issue as we can see with the logs the alias was still present in the recipient.

---

[This relay example `compose.yaml`](https://github.com/docker-mailserver/docker-mailserver/blob/34eb54ac398c4c3846645cf79404d8528869891b/demo-setups/relay-compose.yaml) may be of interest to you if you want to experiment. It's 3 DMS instances configured to show `client (swaks) => sender (DMS origin) => DMS relay (authenticated) => recipient (DMS destination)`.

That will work completely locally offline, so it can be quite convenient to adapt to adjust and experiment with config.

**Comment by polarathene** [comment]
There was also a recent discussion started up that is roughly similar to this issue. Rather than their own managed domain on a separate DMS instance, they had likewise created aliases with mail domains that DMS does not manage, this isn't too uncommon to see, in this case it was for external mail services like `@gmail.com` which prevented mail being sent out to the real mail servers, so same issue faced here.

Rather than your use-case for aliases, they were wrongly using them for `SPOOF_PROTECTION=1` to allow as additional sender addresses.

They have stated their fix was to leverage our [`user-patches.sh` feature to replace the `/etc/postfix/vhosts` file](https://github.com/orgs/docker-mailserver/discussions/4234#discussioncomment-11045243). In their case that works since these aliases were never used to accept mail, or anything else really beyond a `SPOOF_PROTECTION=1` workaround. Might not work for you 🤔 

Do let us know if you find a suitable solution so that other users in your situation can benefit. Or perhaps there is something in DMS that could be improved if we're not doing something quite right (_some of the config decisions were made many years ago and don't always turn out to be the right approach_).
