### ISSUE TITLE
bug report: `Error: queue file write error` / `dovecot.index.cache: No such file or directory`

### ISSUE THREAD

**Issue by hikmethankolay** [docker-mailserver/docker-mailserver#4266]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I encountered an issue where sending an email to an outgoing source fails with the error:  
`Error: queue file write error.` 

### 👟 Reproduction Steps

1. Set up the mail server using Docker Mailserver.  
2. Attempt to send an email.  

### 🐋 DMS Version

14.0.0

### 💻 Operating System and Architecture

Windows server 22

### ⚙️ Container configuration files

```yml
services:
  db:
    image: mysql:latest
    container_name: ################-backend-db
    environment:
      MYSQL_ROOT_PASSWORD: ################
      MYSQL_DATABASE: ################
      MYSQL_USER: ################
      MYSQL_PASSWORD: ################
    ports:
      - "3306:3306"
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    command: ["--wait_timeout=3660"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p################"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: ################-backend-mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.################.com
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./ssl:/var/ssl/
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

  app:
    build:
      context: .
      dockerfile: Dockerfile-backendapp
    container_name: ################-backend-app
    env_file:
      - .env
    ports:
      - "8443:8443"
    volumes:
      - ./assets:/usr/src/backend/assets
    depends_on:
      db:
        condition: service_healthy
      mailserver:
        condition: service_healthy
```

### 📜 Relevant log output

```Text
2024-11-18T17:39:52.747345+03:00 mail postfix/submission/smtpd[1366]: connect from unknown[172.18.0.1]
2024-11-18T17:39:52.873248+03:00 mail postfix/submission/smtpd[1366]: Anonymous TLS connection established from unknown[172.18.0.1]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (3072 bits) server-digest SHA256
2024-11-18T17:39:53.029385+03:00 mail postfix/submission/smtpd[1366]: 06927E00000000C4C4: client=unknown[172.18.0.1], sasl_method=PLAIN, sasl_username=support@################.com
2024-11-18T17:39:53.088440+03:00 mail postfix/sender-cleanup/cleanup[1375]: 06927E00000000C4C4: message-id=<fb5c93eb-c7b9-4443-a6ff-922674536395@################.com>
2024-11-18T17:39:53.088503+03:00 mail postfix/sender-cleanup/cleanup[1375]: 06927E00000000C4C4: replace: header MIME-Version: 1.0 from unknown[172.18.0.1]; from=<support@################.com> to=<##########@gmail.com> proto=ESMTP helo=<[192.168.0.102]>: MIME-Version: 1.0
2024-11-18T17:39:53.116049+03:00 mail opendkim[1133]: 06927E00000000C4C4: DKIM-Signature field added (s=mail, d=################.com)
2024-11-18T17:39:53.199229+03:00 mail postfix/sender-cleanup/cleanup[1375]: 2FF32F00000000C4C4: message-id=<20241118143953.2FF32F00000000C4C4@mail.################.com>
2024-11-18T17:39:53.202194+03:00 mail postfix/submission/smtpd[1366]: disconnect from unknown[172.18.0.1] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=0/1 commands=6/7

Edit:

2024-11-18T18:31:38.396861+03:00 mail dovecot: imap(support@##########.com)<6388><eYjHijEnvNKsEgAB>: Error: Mailbox Drafts: mmap(size=0) failed with file /var/mail/##########.com/support/.Drafts/dovecot.index.cache: No such file or directory
```

**Comment by polarathene** [comment]
Likely this volume:

```yaml
- ./docker-data/dms/mail-state/:/var/mail-state/
```

The volume is typically disposable, but may store statistics for SPAM with Redis (only with rspamd) IIRC, and temporary information like the mail queue with Postfix.

The Postfix mail queue is for mail not yet sent out, so a volume is used to persist that in the event of some failure like power loss or kernel panic, then when you start DMS again it should be able to resume from there instead of those mails being lost and never sent.

---

First did you actually follow the troubleshooting advice to run `docker compose up --force-recreate`?

For resolution:
- If you know there isn't anything important in this volume, you can delete it and you shouldn't have the problem.
- You could also use a named volume instead of a bind mount volume if there is potential for incompatibility with your host filesystem as it's not a Linux FS?

---

**EDIT:** I may be mistaken. Your error is from the mail client, but the log actually mentions Dovecot with:

```
failed with file /var/mail/##########.com/support/.Drafts/dovecot.index.cache: No such file or directory
```

Do you have a `support@example.com` address there? (`/var/mail/example.com/support`) With the `.Drafts` directory?

You have various config that you're clearly not sharing in the report. It's not possible to reproduce. Why is a MySQL DB service there? We do not have any support for DB integration, can you reproduce this with a minimal DMS config that does not rely on the DB or `env_file`? What custom configurations have you applied?

Better to try with a minimal DMS setup that should work, and work your way back towards your real config where something you've done has likely broken it. If it's not something we document in DMS, we are not able to provide much assistance.

**Comment by hikmethankolay** [comment]
I haven’t configured DMS itself beyond the basic setup. MySQL is used for my own site and has nothing to do with DMS. 
I just thought including everything related to my backend in a single `docker-compose.yml` file would be fine.

Yes, there’s a `support@example.com` address, and the `/var/mail/example.com/support/.Drafts` directory exists.

I haven’t yet tried `docker compose up --force-recreate`, but I’ll do that next.

**Comment by hikmethankolay** [comment]
I just tried `docker compose up --force-recreate`, but unfortunately it didn't solve my problem.

**Comment by hikmethankolay** [comment]
>How is Docker installed? Is this running through WSL? Or Docker for Windows?
Docker for Windows
>It is often more helpful in these situations to try reproduce the problem with minimal reproduction where possible.
I ran DMS without anything that running on side and run the test as you instructioned, This is the result of swaks test:

`=== Trying mail.example.com:587...
=== Connected to mail.example.com.
<-  220 mail.example.com ESMTP
 -> EHLO mail.example.com
<-  250-mail.example.com
<-  250-PIPELINING
<-  250-SIZE 10240000
<-  250-ETRN
<-  250-STARTTLS
<-  250-ENHANCEDSTATUSCODES
<-  250-8BITMIME
<-  250-DSN
<-  250 CHUNKING
 -> STARTTLS
<-  220 2.0.0 Ready to start TLS
=== TLS started with cipher TLSv1.3:TLS_AES_256_GCM_SHA384:256
=== TLS client certificate not requested and not sent
=== TLS no client certificate set
=== TLS peer[0]   subject=[/CN=example.com]
===               commonName=[example.com], subjectAltName=[DNS:example.com] notAfter=[2025-01-10T15:05:01Z]
=== TLS peer certificate failed CA verification (unable to get local issuer certificate), failed host verification (using host mail.example.com to verify)
 ~> EHLO mail.example.com
<~  250-mail.example.com
<~  250-PIPELINING
<~  250-SIZE 10240000
<~  250-ETRN
<~  250-AUTH PLAIN LOGIN
<~  250-AUTH=PLAIN LOGIN
<~  250-ENHANCEDSTATUSCODES
<~  250-8BITMIME
<~  250-DSN
<~  250 CHUNKING
 ~> AUTH PLAIN AHN1cHBvcnRAaW5raWxhcG1lY211YXNpLmNvbQBJbmtpbGFwbWVjbXVhc2lfNTM0IQ==
<~  235 2.7.0 Authentication successful
 ~> MAIL FROM:<support@example.com>
<~  250 2.1.0 Ok
 ~> RCPT TO:<jane.doe@gmail.com>
<~  250 2.1.5 Ok
 ~> DATA
<~  354 End data with <CR><LF>.<CR><LF>
 ~> Date: Tue, 19 Nov 2024 00:19:00 +0300
 ~> To: jane.doe@gmail.com
 ~> From: support@example.com
 ~> Subject: test Tue, 19 Nov 2024 00:19:00 +0300
 ~> Message-Id: <20241119001900.001623@mail.example.com>
 ~> X-Mailer: swaks v20240103.0 jetmore.org/john/code/swaks/
 ~>
 ~> This is a test mailing
 ~>
 ~>
 ~> .
<~* 451 4.3.0 Error: queue file write error
 ~> QUIT
<~  221 2.0.0 Bye
=== Connection closed with remote host.`

**Comment by polarathene** [comment]
> Docker for Windows

We do not support this. It may be contributing to your issue.

I'm not sure if that is a product from Docker that is actively maintained anymore?:

> https://docs.docker.com/desktop/setup/install/windows-install/
>
> Docker only supports Docker Desktop on Windows for those versions of Windows that are still within [Microsoft’s servicing timeline](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet).
> Docker Desktop is not supported on server versions of Windows, such as Windows Server 2019 or Windows Server 2022.
> For more information on how to run containers on Windows Server, see [Microsoft's official documentation](https://learn.microsoft.com/virtualization/windowscontainers/quick-start/set-up-environment)

> This is the result of swaks test:

> ```
> TLS peer certificate failed CA verification (unable to get local issuer certificate), failed host verification (using host mail.example.com to verify)
> ```

You are not using a public CA? That should have been successful otherwise.

> ```
> <~* 451 4.3.0 Error: queue file write error
> ```

- Have you tried with the mentioned bind mount volumes disabled?
- What version of Docker Engine is running? (`docker info`)
- Are you using the old Docker Compose or 2.x release?

---

I get the impression that the issue may be specific to your deployment environment unfortunately. DMS might not be compatible there, but you could try an alternative like [Stalwart](https://stalw.art/) instead.

**Comment by hikmethankolay** [comment]
I think it would be easier to migrate to Ubuntu rather than try to make it work on windows. It was a mistake to use windows at first. Thank you for help, I'm sorry for taking up your time.
